### ISSUE TITLE
FR: filter to sort emails by unread

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1000]
Idea of a filter to sort emails by unread first.
or
When you click on the read e-mail, it is automatically moved to the "Read" folder.

Thanks.

**Comment by derjoachim** [comment]
You can already toggle between read and unread status:

![image](https://github.com/Intermesh/groupoffice/assets/1264970/55903434-54ea-44e4-82bc-584cfcd713f9)

![image](https://github.com/Intermesh/groupoffice/assets/1264970/e67bc9af-79ca-4e4d-93d5-2b60571a5f8c)

**Comment by flaviozluca** [comment]
Thanks!
