### ISSUE TITLE
CardDAV: REV is given as timestamp, leads to exceptions

### ISSUE THREAD

**Issue by silicht** [Intermesh/groupoffice#1001]
Sometimes (not always) the REV field is filled with a timestamp instead of a datetime string.

## Example:

```
REV;VALUE=DATE:16855717
```

This leads to an exception e.g. on the DAVx⁵ Android CardDAV client, as it tries to parse this number as a datetime string:

```
j$.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 57
```

## Suggestion

I suggest always providing REV as datetime sring, as this seems to be more compatible with commonly used CardDAV clients.

## Versions

- Group Office: v6.7.31
- DAVx⁵: 4.3.2

**Comment by mschering** [comment]
Thanks, I changed it to a correct value of REV:19951031T222710Z

**Comment by silicht** [comment]
I updated today to 6.7.32, but I still have the same issue. Do you know if the wrong values are somewhere cached? (SabreDAV?)

**Comment by mschering** [comment]
Yes sorry, they are indeed. You can rebuild the cards by running this query:

update addressbook_contact set vcardBlobId = null;

**Comment by silicht** [comment]
Thank you!
