### ISSUE TITLE
Core module unique index

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#1003]
@mschering Shouldnt be core_module unique index changed from name to name + package? Currently you are unable to install module that has same name as lets say community module but it is in different package. The module has own unique name so there are no troubles to run it however I am currently unable to install module like that. I guess I already mentioned similar thing in old version of module installer - Settings -> Modules - however it looks like the ui is probably fixed but there is problem in installer self.

**Comment by mschering** [comment]
Yes you're totally right. I think we didn't change this yet as there are more things counting on a unique module name. One thing for sure is that a main panel in the layout adds a route #MODULENAME to the router. This would be a conflict. 
I have to test what happens with duplicate names in different packages.
