### ISSUE TITLE
Error during fresh install (Debian 11 + sixseven)

### ISSUE THREAD

**Issue by manjarooo** [Intermesh/groupoffice#1004]
Hello,
I installed a minimal Debian 11 (bullseye) into a VirtualBox VM through NetInstall-ISO (no GUI, just Terminal/SSH), and installed Group-Office on it as described on this official site:
https://groupoffice.readthedocs.io/en/latest/install/debian.html

After entering this:
`apt install php-apcu groupoffice groupoffice-mailserver`
the installation process runs fine, until it comes to a specific point, where I get this error message (the last few lines)

`Installing postfixadmin module in Group-Office`
`Uncaught exception: PDOException in /usr/share/groupoffice/go/core/db/Connection.php at line 174: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.core_module' doesn't exist at 2023-05-31T03:39:37+00:00`

Then the installation stops.
I tried it a second time (deleted the whole Debian system, and installed it new), but got the same error at the same process state.

I'm not sure if it is because of the aborted installation process, but I also had to correct some folder permissions after installation, so I had to run:
`chown www-data:www-data -R /usr/share/groupoffice/go/modules /var/lib/groupoffice`

And I had to download and install the ioncube-loader for PHP manually (which is mentioned on the install tutorial site to be neccessary for "purchased" versions only, but turns out that it is neccessary for Group-Office to run at all).
https://www.ioncube.com/loaders.php

At this point, it seems that the main Group-Office app is working, I can run the installer website, and after that, I can login into Group-Office. But because I am new on Group-Office, I'm not sure if everything is working as expected (with the above installation errors in mind).
I also was able to install some additional modules, and installed these without any obvious problems: PostfixClient, PostfixManagement, LDAP authenticator, IMAP authenticator
But I think that the automatic user-mailbox-creation with postfix is not working correct: when I create a new user, there is no new mailbox added for that user, and I have to create it manually... maybe because of the "failed" installation process?

Btw., and beside my installation problems: This is really a great piece of software! :-)
I've worked with Nextcloud a lot, but was searching for a good (better) replacement for MS Exchange for one specific project... and I think I've found it. I'm experimenting with Group-Office since about a day now, and it makes a lot of fun to use it, everything seems to fit together, and it's fast and user friendly. Thank you guys, and keep on going! ;-)

EDIT:
Oops, I did overlook on the tutorial page that for "user/postfix auto creation" I also have to copy/modify the example configuration from the page into /etc/groupoffice/globalconfig.inc.php. So this had nothing to do with the PDOException. My fault, sorry... ;-)
But I am still not sure if the PDOException during install affects my current Group-Office installation, even if it seems to work.

**Comment by mschering** [comment]
Hi,

I will look into the install error. It looks like it falsely tries to add the postfixadmin module when the Group-Office database hasn't been installed yet.

Ioncube should only be needed for the pro add-on modules. I will check this too.

Finally, it's normal that there's no maildir on disk yet until you connect via IMAP or a message is delivered. GO does not have the permissions to create the maildir.

Best regards,
Merijn

**Comment by mschering** [comment]
The postfixadmin error can be safely ignored. I fixed the ioncube problem for the next release.

**Comment by manjarooo** [comment]
Great... :-D Thank you!
