### ISSUE TITLE
version 6.7.32   error  JsonStore load 

### ISSUE THREAD

**Issue by maquinate2** [Intermesh/groupoffice#1005]
when scrolling pages quickly forward or backward the error appears, thanks
![group office](https://github.com/Intermesh/groupoffice/assets/100289638/ada5db7d-5cb8-4ee7-92ab-e571e522b091)

**Comment by mschering** [comment]
Can you check the webserver error log for errors and post it here?

**Comment by maquinate2** [comment]
log the apache?

**Comment by mschering** [comment]
This error has been fixed in the most recent version.
