### ISSUE TITLE
Disabling email warnings

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#1007]
Where to disable the warning that this email might be harmful?
Searched the docs, hasn't been in 6.6...

**Comment by mschering** [comment]
It's not possible. Can you share the source with me if it's a false positive?

It detects some kind of javascript or style that could harm GO somehow.

**Comment by koekie71** [comment]
I have this too since an update to 6.7.32. I have sent you two examples by mail.

It happens to me with almost all emails from mailing lists.

**Comment by lonesomewalker** [comment]
I have this for literally EVERY email.

**Comment by mschering** [comment]
Thanks, I fixed the issue.
