### ISSUE TITLE
6.7.33 - Error when importing email in support module

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1012]
Got the following error when I tried to insert an email in the support module

go\modules\business\support\cron\ImapImport output:
go\core\orm\exception\SaveException in /usr/share/groupoffice/go/modules/business/support/model/EmailAccount.php at line 160: Could not save 'Comment'. Validation failed: "text": You're not allowed to use scripts in the content
---

The ticket is created with the subject as ticket name, like in the 6.6.X ticket module, but no content (message) or attachments.

**Comment by mschering** [comment]
Thanks, this one is fixed. We will release an update today.
