### ISSUE TITLE
6.7.33 Uncaught ErrorException: sem_remove()

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1013]
Got this error 1-2 times a day.
Cannot really tell on what action this occurs. 
If necessary I can run a debug log.

PHP Fatal error:  Uncaught ErrorException: sem_remove(): Failed for SysV semaphore for key 0x51e9f600: Operation not permitted in /usr/share/groupoffice/go/core/util/Lock.php:205
Stack trace:
#0 [internal function]: go\core\ErrorHandler::errorHandler()
#1 /usr/share/groupoffice/go/core/util/Lock.php(205): sem_remove()
#2 /usr/share/groupoffice/go/core/util/Lock.php(230): go\core\util\Lock->unlock()
#3 [internal function]: go\core\util\Lock->__destruct()
#4 {main}
  thrown in /usr/share/groupoffice/go/core/util/Lock.php on line 205

**Comment by thomasgg23** [comment]
Also got this with 6.8.10

PHP Fatal error:  Uncaught ErrorException: sem_remove(): Failed for SysV semaphore for key 0x51e9f600: Operation not permitted in /usr/share/groupoffice/go/core/util/Lock.php:207
Stack trace:
#0 [internal function]: go\core\ErrorHandler::errorHandler()
#1 /usr/share/groupoffice/go/core/util/Lock.php(207): sem_remove()
#2 /usr/share/groupoffice/go/core/util/Lock.php(232): go\core\util\Lock->unlock()
#3 [internal function]: go\core\util\Lock->__destruct()
#4 {main}
  thrown in /usr/share/groupoffice/go/core/util/Lock.php on line 207

**Comment by mschering** [comment]
Sorry, I have no idea what's happening here. Please contact us directly if you need support.
