### ISSUE TITLE
Interpret email

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1028]
Friends,

Pls check if you can view this email?

I can't in GO, but we're not in the latest version. It reads fine in TB, the last reply is blank in my GO.

Thanks!
[Re Confusão em logins empresa - 10-07-2023 1237.zip](https://github.com/Intermesh/groupoffice/files/12014414/Re.Confusao.em.logins.empresa.-.10-07-2023.1237.zip)

![image](https://github.com/Interm
![go blank](https://github.com/Intermesh/groupoffice/assets/44004645/def79e39-a63a-4502-963e-6df3de622165)
esh/groupoffice/assets/44004645/7460d0f2-c1a7-4e13-b951-226f2beaafde)

**Comment by mschering** [comment]
Works in 6.8.
