### ISSUE TITLE
 v6.7.39 , Error: inline attachment missing on server   

### ISSUE THREAD

**Issue by maquinate2** [Intermesh/groupoffice#1029]
groupoffice v6.7.39

After upgrading to the latest version, when I try to send an email with an attachment, it gives this error, how can I fix it? thank you

Error: inline attachment missing on server: /var/lib/groupoffice/data/b1/e8/b1e84c15c67c4b0981be58f725e31ea2ab577c0c.<br /><br />The temporary files folder is cleared on each login. Did you relogin?

**Comment by maquinate2** [comment]
I updated to 6.7.40 and the error continues, is there a solution? thank you

**Comment by maquinate2** [comment]
![error safari](https://github.com/Intermesh/groupoffice/assets/100289638/591b2136-acca-4226-9798-b6fbe1560c87)

**Comment by maquinate2** [comment]
![error safari](https://github.com/Intermesh/groupoffice/assets/100289638/a9232b2b-33de-4366-afdb-fd6e4627e320)

**Comment by maquinate2** [comment]
a new error from safari when sending email with attachments

**Comment by maquinate2** [comment]
a new error from safari when sending email with attachments
![error safari](https://github.com/Intermesh/groupoffice/assets/100289638/c2635a7c-3dc9-44d0-946d-3dd53c6e894b)

**Comment by mschering** [comment]
I can't replicate this but I made some changes that should fix this in the next 6.7.41 release.
