### ISSUE TITLE
6.7.41 create PDF generating new warning in console

### ISSUE THREAD

**Issue by ijuliusz** [Intermesh/groupoffice#1031]
Hi,

From 6.7.41 I see in console new warning message with base64 code
(screenshot is only a part of it)
![image](https://github.com/Intermesh/groupoffice/assets/33216868/868bdb63-9c74-4b86-83ca-d4a4d57c1127)
and on the end of code is note
`was loaded over an insecure connection. This file should be served over HTTPS.`

Our Dev server is set on HTTP, and we won't change
How to turn off this kind of warning?

**Comment by mschering** [comment]
Where does that uri come from? What are you doing when it happens.

**Comment by ijuliusz** [comment]
When I create PDF
`        public function exportPdf(array $params) {
            $pdfDok = new FakturaExportPDF($params);
            return array("base64"=>$pdfDok->outputBase64());
        }`
Our Dev server is local 

I have checked again, and only Chrome 115.0.5790.99 shows that warning

Firefox 115.0.2, Firefox Dev 116.0b7 and Edge 114.0.1823.86 have no warnings in the console

**Comment by mschering** [comment]
This your own code right? Not part of Group-Office?

**Comment by ijuliusz** [comment]
Yes, it's my code
Function exportPDF using GO build in TCPDF library for PDFs
I have that function in .../faktury/controller/Faktura.php
That function working propertly, but warning comes after update from 6.7.40 to 6.7.41

**Comment by mschering** [comment]
I have no idea. It's a browser error and not coming from Group-Office.

**Comment by ijuliusz** [comment]
Thank you for help anyway :)

I leave a comment when I find a reason
