### ISSUE TITLE
v6.7.42 error module help

### ISSUE THREAD

**Issue by maquinate2** [Intermesh/groupoffice#1033]
help module does not show the lists created in the support module, the permissions do not work well in support and help, thanks
![help](https://github.com/Intermesh/groupoffice/assets/100289638/7546dfa0-5415-4ab4-9b2a-35761c207880)
![soporte](https://github.com/Intermesh/groupoffice/assets/100289638/92970197-9e3b-41f5-90a0-40d845c606e0)

**Comment by mschering** [comment]
Did you set the customer permissions in the list? There are two permission tabs, one for agents and one for customers.

**Comment by maquinate2** [comment]
Hello, I have generated a new list and I cannot see them, could you tell me where the permits you mention are, both for agents and for clients? thank you so much

**Comment by maquinate2** [comment]
Hello, I have generated a new list and I cannot see them, could you tell me where the permits you mention are, both for agents and for clients? thank you so much

**Comment by derjoachim** [comment]
Would this screen shot help?

![image](https://github.com/Intermesh/groupoffice/assets/1264970/36cad59d-8278-4a7e-bcf5-54811cb69e1f)

**Comment by maquinate2** [comment]
thank you very much, i will try it
