### ISSUE TITLE
Mailsync - Active Sync does not work for big mailboxes

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#1036]
I have updated to GO 6.7.42

Mailsync via Active sync is not working anymore. 

Device is an iphone XR with iOS 16.6

On one iphone with large mailboxes on small mailboxes it seams to work. (if i see the log correctly it depends on attachmentsize).

Iphone throws "server not reachable" and serverlogfile shows

"POST /Microsoft-Server-ActiveSync?User=USERNAME&DeviceId=ID&DeviceType=iPhone&Cmd=Provision HTTP/2.0" 500 3612 "-" "Apple-iPhone11C8/2007.75"

28/07/2023 15:35:05 [31708] [DEBUG] -------- Start
28/07/2023 15:35:05 [31708] [DEBUG] cmd='Provision' devType='iPhone' devId='XXX' getUser='XXX' from='IP' version='2.6.1' method='POST'
28/07/2023 15:35:05 [31708] [DEBUG] Used timezone 'Europe/Amsterdam'
28/07/2023 15:35:05 [31708] [DEBUG] Request::ProcessHeaders() headers: array (
  'host' => 'HOSTNAME',
  'accept-encoding' => 'gzip, deflate, br',
  'user-agent' => 'Apple-iPhone11C8/2007.75',
  'accept-language' => 'de-DE,de;q=0.9',
  'ms-asprotocolversion' => '14.0',
  'content-length' => '41',
  'content-type' => 'application/vnd.ms-sync.wbxml',
  'accept' => '*/*',
  'authorization' => 'Basic bS5sYW5nZUByZW0tbWVkaWEuZGU6MDkwNWxpc2E=',
)
28/07/2023 15:35:05 [31708] [DEBUG] Request::ProcessHeaders() ASVersion: 14.0
28/07/2023 15:35:05 [31708] [DEBUG] ZPush::CommandNeedsProvisioning(20): false
28/07/2023 15:35:05 [31708] [DEBUG] ZPush::CommandNeedsAuthentication(20): false
28/07/2023 15:35:05 [31708] [DEBUG] FileStateMachine->GetState() read '4177' bytes from file: '/PATHTO/files/zpush21state/g/p/XXX-devicedata'
28/07/2023 15:35:05 [31708] [DEBUG] ASDevice data loaded for user: 'USERNAME'
28/07/2023 15:35:05 [31708] [DEBUG] InterProcessData:__construct type: 'XXX'
28/07/2023 15:35:05 [31708] [DEBUG] TopCollector initialised with IPC provider 'IpcSharedMemoryProvider' with type '20'
28/07/2023 15:35:05 [31708] [DEBUG] InterProcessData:__construct type: 'XXX'
28/07/2023 15:35:05 [31708] [DEBUG] LoopDetection initialised with IPC provider 'IpcSharedMemoryProvider' with type '1337'
28/07/2023 15:35:05 [31708] [DEBUG] ZPush::HierarchyCommand(20): false
28/07/2023 15:35:05 [31708] [DEBUG] ZPush::CommandNeedsPlainInput(20): false
28/07/2023 15:35:05 [31708] [DEBUG] RequestProcessor::HandleProvision(): Forcing delayed Authentication
28/07/2023 15:35:05 [31708] [ INFO] ZPUSH2::Logon(GO version: 6.7.42, backend version: 407, user: USERNAME, domain: )
28/07/2023 15:35:05 [31708] [ INFO] The zpushadmin module is installed, checking access for device.
28/07/2023 15:35:05 [31708] [WBXML] I  <Provision:Provision>
28/07/2023 15:35:05 [31708] [WBXML] I   <Provision:Policies>
28/07/2023 15:35:05 [31708] [WBXML] I    <Provision:Policy>
28/07/2023 15:35:05 [31708] [WBXML] I     <Provision:PolicyType>
28/07/2023 15:35:05 [31708] [WBXML] I      MS-EAS-Provisioning-WBXML
28/07/2023 15:35:05 [31708] [WBXML] I     </Provision:PolicyType>
28/07/2023 15:35:05 [31708] [WBXML] I    </Provision:Policy>
28/07/2023 15:35:05 [31708] [WBXML] I   </Provision:Policies>
28/07/2023 15:35:05 [31708] [WBXML] I  </Provision:Provision>
28/07/2023 15:35:05 [31708] [DEBUG] WBXMLEncoder->startWBXML() type: vnd.ms-sync.wbxml
28/07/2023 15:35:05 [31708] [WBXML] O  <Provision:Provision>
28/07/2023 15:35:05 [31708] [WBXML] O   <Provision:Status>
28/07/2023 15:35:05 [31708] [WBXML] O   1
28/07/2023 15:35:05 [31708] [WBXML] O   </Provision:Status>
28/07/2023 15:35:05 [31708] [WBXML] O   <Provision:Policies>
28/07/2023 15:35:05 [31708] [WBXML] O    <Provision:Policy>
28/07/2023 15:35:05 [31708] [WBXML] O     <Provision:PolicyType>
28/07/2023 15:35:05 [31708] [WBXML] O     MS-EAS-Provisioning-WBXML
28/07/2023 15:35:05 [31708] [WBXML] O     </Provision:PolicyType>
28/07/2023 15:35:05 [31708] [WBXML] O     <Provision:Status>
28/07/2023 15:35:05 [31708] [WBXML] O     1
28/07/2023 15:35:05 [31708] [WBXML] O     </Provision:Status>
28/07/2023 15:35:05 [31708] [WBXML] O     <Provision:PolicyKey>
28/07/2023 15:35:05 [31708] [WBXML] O     912196122
28/07/2023 15:35:05 [31708] [WBXML] O     </Provision:PolicyKey>
28/07/2023 15:35:05 [31708] [DEBUG] DeviceManager->getPolicyName(): determined policy name: 'default'
28/07/2023 15:35:05 [31708] [DEBUG] DeviceManager->getProvisioningPolicies(): loaded 'default' policy.
28/07/2023 15:35:05 [31708] [WBXML] Policy 'devpwenabled' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'alphanumpwreq' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'devencenabled' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'docbrowseenabled' enforced with: empty (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'attenabled' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'mindevpwlenngth' enforced with: 4 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxinacttimedevlock' enforced with: 900 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxdevpwfailedattempts' enforced with: 8 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxattsize' enforced with: empty (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowsimpledevpw' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'devpwexpiration' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'devpwhistory' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowstoragecard' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowcam' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqdevenc' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowunsignedapps' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'mindevcomplexchars' enforced with: 3 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowwifi' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowtextmessaging' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowpopimapemail' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowbluetooth' enforced with: 2 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowirda' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqmansyncroam' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxcalagefilter' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowhtmlemail' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxemailagefilter' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxemailbodytruncsize' enforced with: -1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'maxemailhtmlbodytruncsize' enforced with: -1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqsignedsmimemessages' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqencsmimemessages' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqsignedsmimealgorithm' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'reqencsmimealgorithm' enforced with: 0 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowsmimeencalgneg' enforced with: 2 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowsmimesoftcerts' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowbrowser' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowconsumeremail' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WBXML] Policy 'allowinternetsharing' enforced with: 1 (string)
28/07/2023 15:35:05 [31708] [WARN] SyncObject->Check(): Unmet condition in object from type SyncProvisioning: parameter 'maxattsize' is LOWER than '-1'. Check failed!
28/07/2023 15:35:05 [31708] [FATAL] FatalException: Invalid policies! - code: 0 - file: /PATHTO/modules/z-push/vendor/z-push/lib/request/provisioning.php:220
28/07/2023 15:35:05 [31708] [FATAL] WBXML 10K debug data: AwFqAAAORUZHSANNUy1FQVMtUHJvdmlzaW9uaW5nLVdCWE1MAAEBAQE=
28/07/2023 15:35:05 [31708] [ INFO] User-agent: 'Apple-iPhone11C8/2007.75'
28/07/2023 15:35:05 [31708] [FATAL] Exception: (FatalException) - Invalid policies!
28/07/2023 15:35:05 [31708] [DEBUG] ZPush::PrintZPushLegal()
28/07/2023 15:35:05 [31708] [DEBUG] LoopDetection->ProcessLoopDetectionTerminate()
28/07/2023 15:35:05 [31708] [ INFO] cmd='Provision' memory='2.47 MiB/4.00 MiB' time='0.23s' devType='iPhone' devId='XXX' getUser='USERNAME' from='XXX' idle='0s' version='2.6.1' method='POST' httpcode='500'
28/07/2023 15:35:05 [31708] [DEBUG] -------- End
28/07/2023 15:35:06 [31590] [DEBUG] -------- Start
28/07/2023 15:35:06 [31590] [DEBUG] cmd='Provision' devType='iPhone' devId='XXX' getUser='USERNAME' from='IP' version='2.6.1' method='POST'
28/07/2023 15:35:06 [31590] [DEBUG] Used timezone 'Europe/Amsterdam'
28/07/2023 15:35:06 [31590] [DEBUG] Request::ProcessHeaders() headers: array (
  'host' => 'DOMAINNAME',
  'accept-encoding' => 'gzip, deflate, br',
  'user-agent' => 'Apple-iPhone11C8/2007.75',
  'accept-language' => 'de-DE,de;q=0.9',
  'ms-asprotocolversion' => '14.0',
  'content-length' => '41',
  'content-type' => 'application/vnd.ms-sync.wbxml',
  'accept' => '*/*',
  'authorization' => 'Basic XXXXXXXXZW0tbWVkaWEuZGU6MDkwNWxpc2E=',
)

**Comment by remmedia** [comment]
Uncommenting

/PATHTO/modules/z-push/vendor/z-push/lib/request/provisioning.php

Line 119 and 220 fixes that error.

**Comment by mschering** [comment]
Sorry, but I have no comments on those lines.
