### ISSUE TITLE
Postfix module delete mailbox function

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1038]
Just a question to understand.

With the module "postfix" we can manage to create or delete mailboxes.
But the delete command doesn't actually delete the mailbox (and everything in the mailbox) on the dovecot server.

So the delete button deletes only the information in the mysql database for the postfix server, but doesn't delete any user/files/folders on the dovecot server, right?

![image](https://github.com/Intermesh/groupoffice/assets/2633051/ac669013-58ff-41f8-87e4-a813c3013105)

To delete the folders on the dovecot server we have to do this manually or with a script.
Perhaps there is a status somewhere in the user database from groupoffice when the postfix module deletes the mailbox.

**Comment by mschering** [comment]
There's actually an undocumented command for this:

php groupofficecli.php -r=postfixadmin/maildir/cleanup --dryRyn=1

**Comment by mschering** [comment]
Added docs here:

https://groupoffice.readthedocs.io/en/latest/install/debian.html#mailserver
