### ISSUE TITLE
Feature request: arrow in forwarded msgs

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1041]
Some webmails have a neat feature, not at all necessary, but imho nice to have, they add a small arrow icon next to emails that you have forwarded... It helps to remember you forwarded them...

Thanks.

**Comment by mschering** [comment]
It's already there!?

<img width="366" alt="image" src="https://github.com/Intermesh/groupoffice/assets/1314447/ef159866-e749-4c37-9a8e-1278a8d73848">

**Comment by flaviozluca** [comment]
Cool, imho the arrow slanted is better, but great.

gives more of an impression of forwarded.

![Untitled](https://github.com/Intermesh/groupoffice/assets/44004645/acab826d-2214-476a-a12b-eeea3e1f8862)
