### ISSUE TITLE
Email Labels problems

### ISSUE THREAD

**Issue by pavelstianko** [Intermesh/groupoffice#1043]
If I have more labels for an email and remove the last label everything works fine, but if I remove another than last one it will delete all labels from end to selected label.

In video:
delete Label 5 - ok
delete Label 4 - ok
delete Label 1 - delete label 1+2+3

GO 6.7.42

https://github.com/Intermesh/groupoffice/assets/13132639/7b66ec9c-245a-4d5f-a6fc-6085e40a9d87

**Comment by derjoachim** [comment]
We are currently at 6.7.61 . Does the problem still occur on your side? I am unable to reproduce this locally.
