### ISSUE TITLE
6.7.143 GarbageCollection SQL-table missing

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#1045]
The  GarbageCollection activated I get every time this issue:

> PDOException in /home/web/go7/go/core/db/Connection.php at line 174: SQLSTATE[42S02]: Base table or view not found: 1146 Table '**go7.test_a**' does not exist

This table manually added same error changes to:

> PDOException in /home/web/go7/go/core/db/Connection.php at line 174: SQLSTATE[42S02]: Base table or view not found: 1146 Table '**go7.test_b**' does not exist

The name of may GO-DB is go7.
Greetings robw

**Comment by mschering** [comment]
Can you check if the community/dev module is installed? Please uninstall that.

**Comment by robshnup** [comment]
Hello, - now with dev module removed same issue as described. Ever wants a table_a | table_b | table_c and so on...

**Comment by mschering** [comment]
Can you try to clear the cache by running /install

**Comment by robshnup** [comment]
OK - done - but .... no chance!

**Comment by robshnup** [comment]
Hej, since GO 6.8.5 this issue has gone!
Thanks - Greetings robw
