### ISSUE TITLE
6.7.43 Whispering of recipient that is in addressbook does not work unless you are in admin group

### ISSUE THREAD

**Issue by Gsxr11** [Intermesh/groupoffice#1046]
After writing couple letters into Recipient while creating New email the whispering of names from addressbook works normal once loged in as a member of admin group. Once loged in as normal user this function is not working. It only says Please wait instead.

Using version 6.7.43

**Comment by mschering** [comment]
I think you mean suggestions / autocomplete in the e-mail composeer by "whispering" right?
I can't replicate this issue. Can you check if there are errors in the apache log when doing a search?

**Comment by Gsxr11** [comment]
Hi, unfortunately no errors anywhere in the log. As I wrote this is happening only when loged in as non admin user.
![obrazek](https://github.com/Intermesh/groupoffice/assets/108576866/97f5b985-676c-4c6d-b9ed-69b6afb40655)

**Comment by derjoachim** [comment]
I think that I fixed this one earlier this month. Can you try to replicate the issue with any version from 6.7.44 please?

**Comment by Gsxr11** [comment]
I confirm that this issue has already been fixed. Thank you!
