### ISSUE TITLE
Sourceguardian install script fails

### ISSUE THREAD

**Issue by creissig** [Intermesh/groupoffice#1047]
The install script under https://raw.githubusercontent.com/Intermesh/groupoffice/sourceguardian/scripts/sg_install.sh is missing the part where the architecture amd64 is found. Should be like in the ioncube install script:

DPKG_ARCH=$(dpkg --print-architecture)
if [[ "$DPKG_ARCH" = "i386" ]]; then
  ARCH="x86"
elif [[ "$DPKG_ARCH" = "amd64" ]]; then
  ARCH="x86-64"
elif [[ "$DPKG_ARCH" = "arm64" ]]; then
  ARCH="aarch64"

For now i've manually changed the script. Please have a look. Thanks.

**Comment by mschering** [comment]
Thanks, I applied the fix.
