### ISSUE TITLE
Request Read Notification / doesn't work

### ISSUE THREAD

**Issue by spysz** [Intermesh/groupoffice#1052]
Hello All,

After upgraded to version 6.8.5 option "Request Read Notification" doesn't work. 
When I press "Send" I get error:

`_Call to undefined method GO\Base\Mail\SmimeMessage::setReadReceiptTo()_`

OS: Debian 12
PHP: 8.2
MariaDB: 10.11.3

Regards,
Szymon

**Comment by mschering** [comment]
Thanks, This bug will be fixed in 6.8.6.
