### ISSUE TITLE
by addming multi_instance on Debian 12 Undefined array key 0

### ISSUE THREAD

**Issue by nfos** [Intermesh/groupoffice#1054]
Hi together,
first time for me in groupoffice i installed 
(2 times) a fresh groupoffice (community) Debian 12 (fresh).
Everything works!
But if i want to save the first Multi_instance i get the error:

Undefined array key 0

while in the apache error log:
XXX [Wed Oct 04 11:21:42 2023] [notice] [pid 1606] [client 109.85.75.XX:13109] ./sapi/apache2handler/sapi_apache2.c(358): ErrorException in /usr/share/groupoffice/go/core/db/Utils.php at line 101: Undefined array key 0

Can someone point me to the right direction please?

Thank you all and have a nice Day.

Michael

**Comment by derjoachim** [comment]
I think I fixed this issue a few weeks ago. You may want to update to the latest 6.8 version, which currently is at 6.8.11.
