### ISSUE TITLE
Go Is using FROM header date, showing a message in the future

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1055]
Dear Merijn and team.

I will send you a video I made via email, as it has private info of the user.

Basically, in the INBOX of a customer, GO shows messages in order... Today, yesterday, saturday and then suddenly it shows a message labelled as "tomorrow", in the future
[Soluçao - 10-10-2023 1148.zip](https://github.com/Intermesh/groupoffice/files/12871387/Solucao.-.10-10-2023.1148.zip)
.

When you see my video, you will see that the times are different, 11:43, which is the received by time, but there it shows 7 october, so it shouldnt say tomorrow... GO got the date from from header... the time from received line.

GO should use, I believe, the DATE from the RECEIVED BY not the header, as that can have a data in the future, past, anything.

Thanks.

**Comment by mschering** [comment]
GO uses the date from the date header or the internal date received. You can switch the columns if you like.

**Comment by flaviozluca** [comment]
Friend,

But what is the default? Seems to be HEADER FROM which is strange. Imagine, showing an email as "tomorrrow". That doesnt happen with other systems.

Can I change the default? Isnt it better GO change the default to received TIME? More trusthworthy.

You wont see GMail label an email as tomorrow.

Tks.

**Comment by mschering** [comment]
I think we changed this because when you migrate mail it all has the internal date of migration.

**Comment by mschering** [comment]
You're right. I made this change in 6.8 now.

**Comment by flaviozluca** [comment]
Awsome, thanks!!!
