### ISSUE TITLE
6.8.10 - ErrorException in GarbageCollection permission denied

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1057]
After an update to 6.8.10 i'm getting this error:

Cron php /usr/share/groupoffice/cron.php /etc/groupoffice/config.php
go\core\cron\GarbageCollection output:
ErrorException in /usr/share/groupoffice/go/core/fs/File.php at line 648: touch(): Unable to create file /tmp/groupoffice/cache/disk/dbColumns_mysql:host=localhost;port=3306;dbname=groupoffice;charset=utf8mb4_core_blob because Permission denied

I deleted the whole /tmp/groupoffice folder but the error stays.

**Comment by thomasgg23** [comment]
This one too

EXCEPTION: touch(): Unable to create file /tmp/groupoffice/cache/disk/modelColumns_pr2_income because Permission denied

**Comment by derjoachim** [comment]
Is the cronjob run by the Apache user?

**Comment by mschering** [comment]
In addtion to that, make sure cronjobs and manual cli.php or groupofficecli.php calls are always executed by the apache user "www-data" on debian systems.

**Comment by thomasgg23** [comment]
Sorry my fault, saw that I had two cronjobs running one as root and one as www-data.
