### ISSUE TITLE
loop update

### ISSUE THREAD

**Issue by gaetano118** [Intermesh/groupoffice#1058]
Good morning
I have been using Group-Office for some time, I must say that it is very nice and has been very useful to me, it is hosted on an Aruba Linux server and up until version 6.7 I had no update problems, but now with version 6.8 I have managed to update only at 6.8.1, all subsequent versions the update goes in Loop, practically when the update finishes it practically always repeats it to me.
I'm sure I'm doing the update procedure wrong.
How do I proceed with the update:
I delete all folders and files except config.php and the Temp and Data folders.
I also noticed that if I change the PHP version there are several problems, I'm currently using 8.2.

**Comment by derjoachim** [comment]
Hi,

I am not entirely sure what you mean by a 'loop'. An update either works or it does not. Also, we are currently at 6.8.11 with .12 coming very soon. What install method are you using, manual, Docker or .deb file? I am assuming manual, because the other upgrade methods are more or less automatic.

You may want to refer to the documentation page below: https://groupoffice.readthedocs.io/en/latest/upgrade/tarball.html

**Comment by gaetano118** [comment]
Thanks for the reply, yes, Do you mean that it tries to run the upgrade script time and time again? sorry but it is translated with Google translate,
in reality it doesn't give any error, but a message
"Upgrade output will be logged into: log/upgrade/20231102_091152.log"
it's a problem for me because I can't find the log file to try to understand what the problem could be.
The links you suggested are perhaps useful for my problem, I will do some more tests and if I solve it I will post how I did it, if you can see my link to understand the problem, thank you.
[](https://www.nursind-sicilia.it/privata/)

**Comment by mschering** [comment]
Maybe there are errors in your webserver log?

**Comment by gaetano118** [comment]
Sorry if I'm only replying now, here's the error I get

> WARNING: [pool www.nursind-sicilia.it] child 3529 said into stderr: "[09-Nov-2023 11:16:38 Europe/Amsterdam] Error in /web/htdocs/www.nursind-sicilia.it/home/privata/go/core/model/Settings.php at line 198: Call to undefined function go\core\model\exec()"

**Comment by gaetano118** [comment]
No idea?

**Comment by mschering** [comment]
GO needs the "exec" function. I think it's disabled on your system.

**Comment by mschering** [comment]
Next release will check if the function is there and skip this check. But it's better if you have the functionality on your host.

**Comment by gaetano118** [comment]
Thanks, I'll try it as soon as possible and post the result

**Comment by gaetano118** [comment]
Here's the answer
It is not possible to activate this function in a Shared Server, therefore you will be able to independently activate the PHP Shell_exec function only in a Dedicated Server and in an SSD VPS.

**Comment by gaetano118** [comment]
I confirm that with the new version 6.8.19 the problem has been resolved, thank you
