### ISSUE TITLE
Problem parsing header

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1073]
Dear friends,

We have a strange issue in GO we're on older 6.6.123, but it probably happens in newer versions too.

It seems GO cannot show an email address in the CC due to quotes/apostrophes in excess...

I will send the email and details to info at groupoffice, seem it has sensitive info.

**Comment by flaviozluca** [comment]
Friends, any news?

**Comment by flaviozluca** [comment]
Told customer if the sender can fix it in his contacts, see what he said:

The problem is that it becomes a snowball, several people receive it and these contacts are saved in other programs.

Here with us it interferes with both outlook and webmail, which I personally use.

**Comment by mschering** [comment]
This one will be fixed in the next release.

**Comment by flaviozluca** [comment]
Appreciate it, Merijn!

**Comment by flaviozluca** [comment]
Friend,

When, more or less, will you guys release this next version?

Thanks.

**Comment by flaviozluca** [comment]
Solved. Can close. Thanks!
