### ISSUE TITLE
Module email: date/time in encrypted mails shows current date/time instead sending (recieving) date/time

### ISSUE THREAD

**Issue by Kieltux** [Intermesh/groupoffice#1076]
Hello,
since at least GroupOffice 6.7.54 (maybe before) encrypted mails (SMIME) show after entering the SMIME password in the main mail window the current system date/time instead sending (recieving) date/time.

The mail "[GroupOffice]: GroupOffice Update 6.7.55 (6.7.54)" was send 22.11.23 at 22:02.
The mail tree shows the correct date/time, but the mail window show the current time: 28.11.23 18:44 (screenshot time).

![grafik](https://github.com/Intermesh/groupoffice/assets/6629537/3229258f-2f03-446a-b593-6577bd32107c)

This occurs only with encrypted mails, e.g. not with signed mails.

Thank you very much for taking your time to look into this.

Bye

**Comment by mschering** [comment]
Please retest in 6.8. I can't replicate it there.
