### ISSUE TITLE
Not working with macOS Contacts or Calendar apps

### ISSUE THREAD

**Issue by zine999** [Intermesh/groupoffice#1091]
Version: 6.8.26

![broken](https://github.com/Intermesh/groupoffice/assets/155118056/ff9f5efe-8eb9-4b90-8762-7940e6cb7026)

What do I do?

**Comment by zine999** [comment]
So, I got it to work with Calendar by using the *Server Path* `/caldav/principals/<YOURUSERNAME>/` as mentioned [here](https://groupoffice.readthedocs.io/en/latest/using/connect-a-device/macos.html), but the docs don't mention what *Server Path* to use for Contacts.

I tried `/carddav/principals/<USERNAME>/` but that didn't work.

What to do?

Seems like the docs missed this case.

**Comment by zine999** [comment]
And same issue on iOS, except on iOS I can't even figure out a way to let it let me specify the *Server Path* at all. It just fails.

**Comment by mschering** [comment]
You probably missing these redirects in your webserver config:

#DAV Service discovery. At least required for iOS7 support
Redirect 301 /.well-known/carddav /carddav
Redirect 301 /.well-known/caldav /caldav

See point 3 in the installation manual here:

https://groupoffice.readthedocs.io/en/latest/install/tarball.html#instructions

**Comment by zine999** [comment]
@mschering Hi, sorry I forgot to mention that I'm using the [official docker build](https://github.com/Intermesh/docker-groupoffice), which should come with those redirects built-in, right?

**Comment by mschering** [comment]
Yes they are. Maybe something is off with the proxy? You can test if it works by going to:

/.well-known/carddav

and

/.well-known/caldav

It should simply redirect to /caldav

**Comment by mschering** [comment]
Sorry for the late reply but it looks like you just need to install the carddav module.
