### ISSUE TITLE
6.8.27 Country added in formatted field

### ISSUE THREAD

**Issue by ijuliusz** [Intermesh/groupoffice#1094]
The contact address does not have a country specified when it is located in Poland. 
However, when I generate the full contact in PDF format, 'Netherlands' (Holandia) is added as the default in the 'formatted' field.
Should be no country there
```
address: "Zuzanny 20"
city: "Sosnowiec"
country: null
countryCode: null
formatted: "Zuzanny 20\n41-200 Sosnowiec\nHolandia"
latitude: null
longitude: null
state: ""
type: "work"
zipCode: "41-200"
```

**Comment by derjoachim** [comment]
The logged in user and/or the admin user should set their time zone to Europe/Warsaw . It looks as if either of them has set their time zone to Europe/Amsterdam. By default, a formatted address is formatted with a country. In your use case (printing labels), this makes sense.  If a country is not entered for a postal address, it tries to find a default which is either the country associated with the user's timezone or failing that, the admin's time zone. My guess is that either of these is set to Europe/Amsterdam.

**Comment by mschering** [comment]
This is fixed now.
