### ISSUE TITLE
Feature Request : Disable /install/ after installation for any one to access and clear cache

### ISSUE THREAD

**Issue by deependhulla** [Intermesh/groupoffice#1098]
Feature Request : Disable /install/ after installation for any one to access and clear cache.
it should be from Admin or via Config.php option.

As one has to temporary have to move the folder after every update.

**Comment by michalcharvat** [comment]
You can easily disable it in vhost configuration, or even better allow access from defined IPs. Sometimes you still need to go and run /install/upgrade.php script :-)

**Comment by deependhulla** [comment]
But if that is locked with some password by default, or as you said, disabled by default in apacheconf, for example, in the Debian package, that would be great.

**Comment by mschering** [comment]
That's not possible as new users will not be able to install.

**Comment by deependhulla** [comment]
I mean if its not from localhost or cli ..then default lock ... i recently found DDOS attack as hacker knows its install folder and was open online, and was keeping on clearing my cache.
