### ISSUE TITLE
6.8.x - problem editing email template

### ISSUE THREAD

**Issue by mitakjakub** [Intermesh/groupoffice#1099]
After upgrade version from 6.7 to 6.8 we encourded a bug. 
We working while with groupoffice 6.8, realy don't know, from which version problem persists.
Archieved version 6.7.x still works perfectly.

When someone wants to edit, create or delete email template always ends with:

Error
Invalid address: (From): 

Corresponding error in apache log:

[Thu Jan 18 07:11:59.611850 2024] [proxy_fcgi:error] [pid 756121] [client xxxxxxxxx:53132] AH01071: Got error 'PHP message: PHPMailer\\PHPMailer\\Exception in /usr/share/groupoffice/vendor/phpmailer/phpmailer/src/PHPMailer.php at line 1331: Invalid address:  (From): ', referer: https://xxxxxxxxxxxxxx

**Comment by mitakjakub** [comment]
6.8.29
Problem solved - notification section was empty.

**Comment by mschering** [comment]
Thanks, that should be a required field. I'll change that.
