### ISSUE TITLE
Upgrade 6.8.22 -> 6.8.29

### ISSUE THREAD

**Issue by mitakjakub** [Intermesh/groupoffice#1100]
Hello.
Tried to upgrade groupoffice from 6.8.22 to 6.8.29 ends with database problem - cannot upgrade because table business_business_category not exists.

After adding this into db schema:
```
create table business_business_category
(
    id         int unsigned NOT null auto_increment,
    businessId int unsigned not null,
    name       varchar(40)  not null,
    isHours boolean not null default false,
        constraint business_business_category_pk
        primary key (id),
    constraint business_business_category_business_business_id_fk
        foreign key (businessId) references business_business (id)
            on delete cascade
);

```
upgrade runs perfectly without problems.

**Comment by mschering** [comment]
Strange, as that query is present in the upgrade scripts. Did you get an error while upgrading? You can also check the upgrade logs in the log/upgrade folder.

**Comment by mitakjakub** [comment]
Below is the first one, before adding table into dbscheme:

`Skipping module chat because it's not available.
[business/business] Excuting query: CREATE TABLE if not exists `business_business_vat_rate` (
`id` int(10) UNSIGNED NOT NULL,
  `businessId` int(10) UNSIGNED NOT NULL,
  `name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate` decimal(19,4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
business/business updated from 32 to 33
[business/business] Excuting query: INSERT INTO `business_business_vat_rate` (`id`, `businessId`, `name`, `rate`) VALUES
(3, 1, 'Standard', '21.0000'),
(4, 1, 'Reduced', '9.0000'),
(5, 1, 'Zero', '0.0000');
business/business updated from 33 to 34
[business/business] Excuting query: ALTER TABLE `business_business_vat_rate`
  ADD PRIMARY KEY (`id`),
  ADD KEY `businessId` (`businessId`);
business/business updated from 34 to 35
[business/business] Excuting query: ALTER TABLE `business_business_vat_rate`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
business/business updated from 35 to 36
[business/business] Excuting query: ALTER TABLE `business_business_vat_rate`
  ADD CONSTRAINT `business_business_vat_rate_ibfk_1` FOREIGN KEY (`businessId`) REFERENCES `business_business` (`id`) ON DELETE CASCADE;
business/business updated from 36 to 37
[business/business] Excuting query: ALTER TABLE `business_business` ADD `defaultVatRateId` INT UNSIGNED NULL DEFAULT NULL AFTER `contactId`;
business/business updated from 37 to 38
[business/business] Excuting query: ALTER TABLE `business_business` ADD FOREIGN KEY (`defaultVatRateId`) REFERENCES `business_business_vat_rate`(`id`) ON DELETE SET NULL ON UPDATE RESTRICT;
business/business updated from 38 to 39
[business/business] Excuting query: alter table business_business
        add aclId int default null;
business/business updated from 39 to 40
[business/business] Excuting query: alter table business_business
        add constraint business_business_core_acl_id_fk
                foreign key (aclId) references core_acl (id);
business/business updated from 40 to 41
[business/business] Running callable function
Uncaught exception: PDOException in /usr/share/groupoffice/go/core/db/Connection.php at line 182: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.business_business_category' doesn't exist at 2024-01-17T16:12:32+00:00
`

**Comment by mschering** [comment]
Thanks, I can't reproduce it here but I did made a workaround so it will continue with the upgrade if such an error occuirs.
