### ISSUE TITLE
Changing user passwords in system settings changes imap/smtp password in users with the same name before @

### ISSUE THREAD

**Issue by Inforytel** [Intermesh/groupoffice#1103]
As stated in the title, I was having this weird issue, when changing user passwords as administrator in system settings, when i change the password for the user marketing@somedomain.com it syncs the password of the imap and smtp service but it does it for that user and other users with the same name but different domain marketing@otherdomain.com.

The web login is correct for both users, but the imap/smtp is what gets mixed up.

I've updated to the latest version last night, I have not tried to replicate the issue yet, but i'll try and update on it I was using 6.7

**Comment by Inforytel** [comment]
Confirmed, the issue remains after the update

**Comment by mschering** [comment]
Sorry for the late reply. But I fixed this issue.
