### ISSUE TITLE
Export multiple calendar entries to an ICS file 

### ISSUE THREAD

**Issue by dbuehl** [Intermesh/groupoffice#1104]
Hi,

I am looking for a possibility to export multiple or all events from one calendar to one ICS file from within Group Office or via the Sabre/DAV functionality.

I did find the possibility to export single events from a calendar to ICS. I am aware of the possibility to export complete calendards to ICS from connected clients but this is not what I am looking for. 

I have looked through previous issues here but found nothing similar. Should I have overlooked a respective entry here that covers my inquiry, I am grateful to be pointed into the right direction.

Haartelijk bedankt
Daniel

**Comment by michalcharvat** [comment]
That one can be easily implemented by adding https://sabre.io/dav/ics-export-plugin/. Of course it depends how it should work in general however basic functionality is available by adding plugin to CalDAV server

**Comment by dbuehl** [comment]
Thanks Michael, 

good to know. So far, I’ve been „using“ group office only, never looked under the hood.  Would you please point me to the respective sabre/DAV config file and location where to add this — thank you!

Daniel

**Comment by michalcharvat** [comment]
Open modules/caldav/calendar.php and insert those lines
```
$icsPlugin = new \Sabre\CalDAV\ICSExportPlugin();
$server->addPlugin($icsPlugin);
```
lets say to the line 100 but basically anywhere beween the server initialization and server->start(

Maybe there could be necessary some caching etc but for now it could help you until that functionality will be implemented.
