### ISSUE TITLE
Upgrading from v.6.6 to 6.7 

### ISSUE THREAD

**Issue by razerrazer** [Intermesh/groupoffice#1105]
Hi,

I working on an upgrade from version 6.6 to 6.7 and i get this message:

Uncaught exception: PDOException in /home/xxxx/domains/xxxxx/public_html/crm/go/core/db/Connection.php at line 182: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxx_xxx.core_client' doesn't exist at 2024-01-25T14:57:58+00:00

So i then tested another version of 6.7 but with the same result, is this a known bug or is it because of 6.7 isn't' finished yet?

**Comment by michalcharvat** [comment]
Did you try run upgrade once again? I have mentioned that bug too when I had to upgrade one instance. It looks like there is problem in migrations. You can try create core_client table manually however in the end all migrations were processed well. If I am not wrong there is one more bug to register tasklist entity but you will see.

**Comment by mschering** [comment]
It sometimes happens when you are logged in. Please try with a private browser screen or on the command line.

**Comment by razerrazer** [comment]
Thank you so much to both of you, it worked like a charm doing it via the private browser!
