### ISSUE TITLE
6.8.34 bad translation german

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1119]
if user 1 creates an appointment with user 2 as participant and a weekly repetition user 1 get a mail with for example:
`Wiederhole alle Woche am Freitag`

this should be:
`Wiederhole jede Woche am Freitag`
or
`Wiederholung jede Woche am Freitag`

**Comment by mschering** [comment]
Fixed for the next release.

**Comment by Nachtlichtermeer** [comment]
i checked your change and as i notice german is triggy :-/

there is a difference between 1 and many days or weeks; for example:
- Wiederhole jede Woche am Freitag
- Wiederhole aller 5 Wochen am Freitag
- Wiederhole jeden Tag
- Wiederhole aller 5 Tage

**Comment by mschering** [comment]
Maybe my last commit improves it?
