### ISSUE TITLE
6.8.35 smime error signed attachment

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#1120]
With the latest 6.8.35 there is an error in the smime signing when sending an email with attachment.

Mail sent to myself without an attachment and signed with an smime certificate shows an valid certificate.
![image](https://github.com/Intermesh/groupoffice/assets/2633051/45478a62-9a1a-429e-a295-1b6c8ceb53ba)

Same mail with an pdf attachment only shows an multipart-signed attachment and no check for an certificate 
![image](https://github.com/Intermesh/groupoffice/assets/2633051/e4d3301a-dcf7-48c2-ae12-15239ef6d0dd)

**Comment by mschering** [comment]
I can't replicate it here. Can you send me a sample?

**Comment by thomasgg23** [comment]
Sure.
I have send you two messages signed. One with attachment the other without.

**Comment by mschering** [comment]
Both arrived fine at my end!

**Comment by mschering** [comment]
I looked more closely and see there's a problem in other mail clients than Group-Office. Working on a fix.

**Comment by mschering** [comment]
Will be fixed in the next release.
