### ISSUE TITLE
Terminology attaching files

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1123]
Friend,

The usability here could be better. Most webmails, we tested several, you click on the clips, it attaches right away (Gmail, Afterlogic, Mailenable, etc...) or they separate it, icewarp for example has written Attach (which attaches right away when u click on top) and an arrow next to it where you choose "from webmail files".

![image](https://github.com/Intermesh/groupoffice/assets/44004645/47e395cd-3e07-4122-be56-672489329592)

We will probably change ENVIAR (SEND) on the right side to PROCURAR (search), since GO has an extra step. 

It's not wrong the way GO does it, just a bit more confusing than usual. Usually UPLOAD/SEND is a final action... So some users can get confused... I dont wanna change GO, it has its method, but it would be nice also to change the arrow icon next to send to a computer... Search, then you send...

Can you consider this? 

Example of other webmails

Gmail attach goes directly to choosing files
![image](https://github.com/Intermesh/groupoffice/assets/44004645/a2ab6b17-b48a-4e30-a03f-d500c5ea91f0)

Afterlogic, separates Attach, which goes direct (clips) from attach from webmail files
![image](https://github.com/Intermesh/groupoffice/assets/44004645/2709d030-3dc9-4087-8ed7-423dfef125bf)

icewarp, also separates. if you click on attach text, it attaches directly
![image](https://github.com/Intermesh/groupoffice/assets/44004645/6bb6a307-dd36-4e42-a184-c61d61af8938)

For GO, so you keep it's style, we suggest simply:

- Change UPLOAD on right side to SEARCH  or Attach
- Change UP ARROW ICON to COMPUTER ICON

Thanks.

**Comment by flaviozluca** [comment]
Even better:

I think it's best if indeed when clicking on the attach icon the attach window pops up right away, no ?

** but it would, perhaps, change GO's philosophy, no?

 we think it's not GO's style, understand what I mean?

So we tried to respect it and find a way out that doesnt change it so much, since GO uses these icons for everything...

So it's multi-step... Clips icon, then upload, then choose... Most systems are like Gmail, ATTACH right away or they separate attach (right away) and attach from files.

Afterlogic does this

![pasted-image](https://github.com/Intermesh/groupoffice/assets/44004645/268bcb03-6785-4d0c-9adf-125b301806ca)


IceWarp too but icewarp has it written ATTACH

![pasted-image](https://github.com/Intermesh/groupoffice/assets/44004645/93454de0-5530-4244-abfd-c29bfc19bb44)


If GO simply puts the attach directly in the clips without text, it can become confusing. Understand what I mean?

**Comment by mschering** [comment]
Looks like a translation issue. The original phrase is "Upload" and not "Send".

**Comment by flaviozluca** [comment]
Even in english, The 1st text is UPLOAD.

![image](https://github.com/Intermesh/groupoffice/assets/44004645/859b59d7-96e9-4733-bc2c-8c55ab1dba55)

Suggestion:


    Change UPLOAD on right side to SEARCH or Attach
    Change UP ARROW ICON to COMPUTER ICON

**Comment by mschering** [comment]
I've changed the icon but I personally think "Upload" is the correct text. You are already inside the "Attach" button menu.

**Comment by flaviozluca** [comment]
Thanks. I think its send or select first, you upload afterwords. I compared other webmails, its that way.

But great, thanks. 

Even here in github. Attach file.

PS - to make it even stranger, the win dialog that appears afterwords is "open" ;)) when u select a file.

**Comment by mschering** [comment]
You are of course attaching files. You are in the "Attach file" menu. The difficulty is that there are 3 ways to attach files in Group-Office. I agree it's confusing but I don;'t think renaming it to "Search" or "Attach" makes it better. 

There should be only 2 options. "Upload" and "From Group-Office". But the from the file browser you can't reach all the files. So we have to take care of that when we refactor the files module. But for the short term we will have to stick with 3 options. I'll try to clarify it with a group header.

**Comment by flaviozluca** [comment]
Thanks, friend.



 
 luca.gif
 		 
 		traco_roxo.png
 Atenciosamente/Regards,

Flávio Zarur Lucarelli
Sócio-Diretor
LucaNet Sistemas [1]
55-21-3005-9310 / 55-11-2122-4256
Celular / WhatsApp: 21-99542-4180 
 

 
 

Em Quinta-feira, 17/04/2025 no 4:07 Merijn Schering escreveu:



 

You are of course attaching files. You are in the "Attach file" menu.
The difficulty is that there are 3 ways to attach files in
Group-Office. I agree it's confusing but I don;'t think renaming it to
"Search" or "Attach" makes it better.



There should be only 2 options. "Upload" and "From Group-Office". But
the from the file browser you can't reach all the files. So we have to
take care of that when we refactor the files module. But for the short
term we will have to stick with 3 options. I'll try to clarify it with
a group header.



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 

 
mschering left a comment (Intermesh/groupoffice#1123) [2] 

You are of course attaching files. You are in the "Attach file" menu.
The difficulty is that there are 3 ways to attach files in
Group-Office. I agree it's confusing but I don;'t think renaming it to
"Search" or "Attach" makes it better.



There should be only 2 options. "Upload" and "From Group-Office". But
the from the file browser you can't reach all the files. So we have to
take care of that when we refactor the files module. But for the short
term we will have to stick with 3 options. I'll try to clarify it with
a group header.



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1] http://www.lucanet.com.br
[2]
https://github.com/Intermesh/groupoffice/issues/1123#issuecomment-2811999168
[3]
