### ISSUE TITLE
CardDAV only work with permissions to module CardDAV server

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1126]
version: 6.8.36
as in https://github.com/Intermesh/groupoffice/issues/691
CardDav won't work until i add the group 'Internal' manually

**Comment by mschering** [comment]
This is not really a bug but a feature :) You can control webdav access with permissions.

**Comment by Nachtlichtermeer** [comment]
ahhh :-D
OK, after i found #691 i thought it have to be a bug

the default permissions are sometimes a little bit strange for me.
for example all calendars are visible for all, but not the addressbooks.
or the page ActiveSync is visible for all users with delete-button, but for CardDAV i have to give the permissions manually.

it's good the manage everything, but the default is, in my opinion, not best

**Comment by mschering** [comment]
Yes perhaps we should give internal permissions by default.

But I do like that address books are not shared by default. A common shared address book is often used and then you can put your personal stuff in your personal address book.

**Comment by Nachtlichtermeer** [comment]
you're absolutely right
sharing personal addressbooks as default could be a privacy break
but this could be the same with calendars i think.

ok, to find a good default isn't easy ...

and why all users can see activesync devices and can delete them also default?
activesync seems to work if only 'admin' (group) is listed

**Comment by mschering** [comment]
the activesync is only for management by an admin. All users can sync if they have access to the "sync" module.

**Comment by Nachtlichtermeer** [comment]
that's make sense
sorry for annoy but when i install GO, add a ldap server and then login as normal user
i can see the activesync page and the delete-button works
after deleting the permissions for 'internal' and add 'admin' and so on only the admin can see this page
is this really the desired default?

**Comment by mschering** [comment]
No you're right. It should be for admins only. I will fix this.

**Comment by Nachtlichtermeer** [comment]
Then this ticket was useful after all, great
and thanks for support - our test phase looks good ;-)
