### ISSUE TITLE
Development of Email Drafting Feature Using Ollama API (latter OpenAI API) for GroupOffice Integration

### ISSUE THREAD

**Issue by deependhulla** [Intermesh/groupoffice#1127]
Dear Merijn Schering,

I have been utilizing ChatGPT for some time and am now using Ollama on an offline server with the tinyllama module for generating email replies, which I plan to  incorporate into GroupOffice mail. I am considering developing a feature akin to Gmail's "Smart Compose/help write" which drafts emails based on a few inputs, by leveraging the Ollama API. I intend to contribute the code to your project.

I have begun reviewing your developer documentation available at https://groupoffice.readthedocs.io/en/latest/developer/index.html. However, I believe I might benefit from your guidance to expedite the exploration of this concept. Your advice would be invaluable in enabling me to start development and create a module for this purpose.

Here are my specific inquiries:

I aim to familiarize myself with the structure and development process of modules in GroupOffice and understand how modules can extend its functionality.
I plan to review the GroupOffice developer documentation in detail, focusing on guidelines for module creation, hooks, and email functionality interaction.
For example, identifying the appropriate location to integrate an "Email Responder" button within the email module. Upon clicking, a dialog box should appear, offering various reply options, including a textbox for custom responses.
After selecting "generate," the complete EML of the opened email should be sent to the backend for processing by my code API with security measures in place. My PHP code would then interact with the Ollama API to generate two or three response options. Upon the user's selection, the chosen response would be inserted into the email body at the cursor's location.

Your insights could significantly accelerate my development process. I am inclined to develop this as a module rather than modifying the original code. I look forward to hearing your thoughts on this approach.

-Deepen Dhulla

**Comment by lonesomewalker** [comment]
Maybe it is better to not scramble this with GO.
If you REALLY need help with writing emails or email drafts, you can do that externally and then do it vice versa (or even send it directly from Ollama).

And sooner or later you will also realize: machine learning was a waste of time/energy. Wait for it :-)

**Comment by deependhulla** [comment]
Hi,

I do not wish to struggle with integrating GO, which is why I am seeking your advice for tips and tricks. Additionally, I've been using Ollama manually for personal purposes and am considering offering the same functionality within GO for others. Despite a nornmal view that machine learning often represents a significant investment of time and energy without substantial benefits, in this case of Ollama with the TinyLlama, Llama2, Phi-2 model, the major machine learning development work has already been completed. It's now a matter of integration with chat-api. I would appreciate any insights you can provide on these points, I raised earlier.

By the way, thank you for the wonderful Group-Office. Although I am not a paying customer, I have been using your community edition for years and recommending it to others as part of an open-source email solution deployment.

**Comment by mschering** [comment]
Hi,

lonesomewalker does not speak for Intermesh. It's not up to us to decide what is useful functionality for you. It's perfectly fine to ask for guidance on how to write a plugin module for the e-mail module here.

What I would do is write a module that overrides the GO.email.EmailComposer. You can find a perfect example in the smime module here:

https://github.com/Intermesh/groupoffice/blob/15c55886ef5ff6efcaf05391175e2f57d87c0bd5/www/modules/smime/PluginEmailComposer.js

Good luck,
Merijn

**Comment by deependhulla** [comment]
Thank you, Merijn. I will surely check it out, hoping for the best.

**Comment by derjoachim** [comment]
Obligatory link to our [documentation page](https://groupoffice.readthedocs.io/en/latest/developer/override-an-existing-module.html) on overriding existing modules. :-)

**Comment by deependhulla** [comment]
Hello Everyone,

I attempted to override existing modules but encountered some challenges in identifying the right approach. As a result, I opted to patch various files to incorporate additional code, enabling support for OpenAI-based APIs, Groq API, and Ollama for local use.

I have documented my work and shared both notes and a video in my repository. If anyone is interested in using it, referencing it to develop a module, or integrating it into the core project, you are welcome to explore it. While the implementation is in a raw format, it has been running successfully in production for quite some time and may serve as a helpful resource.

You can find the repository here:
https://github.com/deependhulla/genai-update-for-email-in-groupoffice

A big thanks to the community for your continued contributions!

Best regards,
Deepen Dhulla

**Comment by michalcharvat** [comment]
Well, to achieve your purpose, you don't need to overwrite the backend; you simply need to write a new module with a controller and reuse the existing libraries for handling emails. On the frontend, just use Ext.override to modify the parts you need. In the end, you'll have a clean module without the need to modify any other modules. That module will also remain independent until any changes are made to the main libraries or the email module.

**Comment by deependhulla** [comment]
Hi @michalcharvat ,

You're absolutely right. I did receive similar suggestions from other key team members, but unfortunately, those didn't help me achieve the desired outcome (I failed somewhere).  Therefore, I explored a patching solution, which ultimately proved successful.

Since I was able to achieve the results I needed, I wanted to share this solution with the community.  Hopefully, it can serve as a stepping stone for others who might want to integrate this functionality into the core or develop it as a module.

**Comment by michalcharvat** [comment]
@deependhulla Perhaps I can offer you some advice, but patching anything in GO is a one-way ticket to hell. Sometimes, problems arise in your own module if you don't keep up with all the changes in the core, forcing you to modify parts of your module. However, in general—until there are any major changes—using a module is a much better option if you update Go periodically.

The first piece of advice is to create an AI module with providers because customers have different requirements and you need to configure AI in a single place. In fact, in some cases, you may need more than one provider or AI model. What's also useful are system prompt settings.

For your summarizer, you just need one controller endpoint that will find the email by ID and process it using the selected provider. For the writer, I envision another endpoint where the input is the original email(s) and the output is a new message. That's the PHP part.

The JavaScript part will simply involve overrides and calling your endpoints to paste or replace HTML. You can also create a simple override that adds a button with AI commands, and instead of replacing the HTML on the message panel, you can display the output in a small popup.

![Image](https://github.com/user-attachments/assets/479a8d38-49ac-4766-8d60-af90b03038e1)

**Comment by deependhulla** [comment]
@michalcharvat  Yes, I did take a more complex approach, but I believe it has been beneficial, which is why I shared my implementation. The modular approach did not yield effective results in this case.

I do understand that a modular approach is generally preferred, and I did attempt it as suggested.

Implementation Details : 

**"Writer AI" Option in Email Compose :** 
I checked the model creation part in GroupOffice, and as you suggested, the button was initially placed at the top. However, based on UI feedback, users preferred having it inside the HTML editor, next to the bold font button.

Upon exploring the code, I found that many other plugins for the HTML editor were created as JS files and called within form/HtmlEditor.js as plugins rather than models—likely due to the EXTJS architecture.

To align with this structure, I:
Created HTMLEditorWriterAI.js and called it in form/HtmlEditor.js (updating the existing file).
Added the necessary modifications in /usr/share/groupoffice/controller/CoreController.php. (I believe this part can be further refined, but I followed a similar approach to how the spell-check module was integrated via JS and CoreController.php.)
Additional Benefit: This approach extended the "Writer AI" option to all modules using the HTML editor, such as "**Notes**" and "**Comments**."

![Image](https://github.com/user-attachments/assets/a94ede53-e133-4da8-b370-c8fd87091dbe)

**"Summarize Email with AI" Feature :** 
Users wanted the summary link placed above "Click here if you think this message is spam."

Upon checking the code, I found that this functionality was provided through MessagePanel.js, a core component of the Email module. Instead of rewriting the entire module, I:

Added the necessary code in MessagePanel.js.
Integrated the required JS function in EmailClient.js. (I believe this could be modularized further by placing it in a separate file and calling it via scripts.txt, but for now, it’s implemented as a patch to the core code.)
This approach allows the feature to be added without losing future updates from the original GroupOffice core or Email modules.

![Image](https://github.com/user-attachments/assets/8787fed1-8475-47c5-a0de-5233b531f40f)

Output.

![Image](https://github.com/user-attachments/assets/0c768806-a51d-4540-a6f2-660280dcb198)



**AI Module Approach for Support  other providers :** 
The AI module follows OpenAI compatibility and is configurable via config.php. In addition to Groq API, I also tested it with the Ollama API endpoint for a fully local setup using IBM’s granite3.1-moe model, which worked well.

via config.php:

$config['ai_url'] = 'https://api.groq.com/openai/v1/chat/completions';
$config['ai_api_key'] = 'your_api_key_from_console';
$config['ai_model'] = "llama-3.3-70b-versatile";

you can check **Demo video** to get idea.

For a demonstration, visit: https://youtu.be/IkS6pNHPj8c
This demo showcases the new GenAI-powered features added to GroupOffice Community using the Groq API. 
Watch how AI summarizes emails for quick insights and assists in generating well-crafted email responses—enhancing productivity within GroupOffice.

I do believe my practical, tried-and-tested, and live implementation could be helpful for someone who wants to enable these features immediately. It might also serve as a foundation for building more feature-rich AI modules. While we have already started implementing this in our custom PHP CRM for our company, I believe it will also be beneficial within GroupOffice. This is a simple way to say thank you to the GroupOffice team and community.
