### ISSUE TITLE
GO 6.8.36 CardDav  via DAVx5 complains about "Invalid Mimedir file"

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#1129]
GO is strictly installed on Debian according to the manual at "https://groupoffice.readthedocs.io/en/latest/install/tarball.html" including alle aliases and FastCGI authentications. CalDAV works like a charm but for CardDAV i can only recall all the addresses via Sabre UI in browser with full success - **not via DAVx5**. The according users have all rights on their addressbooks with "Manage" too. (My Davx5-Sabre connection to Nextcloud works in contrast with both protocols)

**DAVx5-GOCardDAV spits out this message:**

`HTTP RESPONSE Response{protocol=h2, code=500, message=, url=https://groupoffice/carddav/addressbooks/rob/35/}
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>4.5.1</s:sabredav-version>
<s:exception>Sabre\VObject\ParseException</s:exception>
<s:message>Invalid Mimedir file. Line starting at 28 did not follow iCalendar/vCard conventions</s:message>
</d:error>`

**Debug.log is a bit more detailed:**

[log][go\core\dav\auth\BasicBackend:41] Authenticating rob
[log][Sabre\DAV\Auth\Backend\AbstractBasic:103] Authentication success: rob
[log][Sabre\DAVACL\AbstractPrincipalCollection:114] getPrincipalByPath(principals/rob)
[log][Sabre\DAVACL\AbstractPrincipalCollection:114] getPrincipalByPath(principals/rob)
[error] Sabre\VObject\ParseException in /go/vendor/sabre/vobject/lib/Parser/MimeDir.php at line 431: Invalid Mimedir file. Line starting >[error] #0 /go/vendor/sabre/vobject/lib/Parser/MimeDir.php(227): Sabre\VObject\Parser\MimeDir->readProperty()
[error] #1 /go/vendor/sabre/vobject/lib/Parser/MimeDir.php(178): Sabre\VObject\Parser\MimeDir->parseLine()
[error] #2 /go/vendor/sabre/vobject/lib/Parser/MimeDir.php(90): Sabre\VObject\Parser\MimeDir->parseDocument()
[error] #3 /go/vendor/sabre/vobject/lib/Reader.php(47): Sabre\VObject\Parser\MimeDir->parse()
[error] #4 /go/vendor/sabre/dav/lib/CardDAV/Plugin.php(808): Sabre\VObject\Reader::read()
[error] #5 /go/vendor/sabre/dav/lib/CardDAV/Plugin.php(243): Sabre\CardDAV\Plugin->convertVCard()
[error] #6 /go/vendor/sabre/dav/lib/CardDAV/Plugin.php(189): Sabre\CardDAV\Plugin->addressbookMultiGetReport()
[error] #7 /go/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\CardDAV\Plugin->report()
[error] #8 /go/vendor/sabre/dav/lib/DAV/CorePlugin.php(690): Sabre\DAV\Server->emit()
[error] #9 /go/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpReport()
[error] #10 /go/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
[error] #11 /go/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
[error] #12 /go/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
[error] #13 /go/go/modules/community/carddav/index.php(86): Sabre\DAV\Server->exec()
[error] #14 /go/modules/carddav/addressbook.php(2): require('...')

Killing all addresses and reimporting it as fresh vcf's also didn't solve the problem at all - since I thought that there could be an improper entry there. Don't know what can be done next.
Thanks for any support. Robw

**Comment by robshnup** [comment]
It's obsolete, becaus it has turned out that there were multiple addressantries faulty.
With mint condition new vcf-Import everything works! Sorry!
Robw

**Comment by mschering** [comment]
Still interesting to know what was faulty and if we could work around this issue.
