### ISSUE TITLE
6.8.36 ActiveSync doesn't work with Outlook

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1130]
mobile phones with android an iOS are working
with outlook 2019 pro plus i only can send mails but don't see my calendars, mails and folders

maybe it is a bug with Outlook see https://kopano.com/de/featured-de/updates-fuer-microsoft-office-beeintraechtigen-activesync-verbindung-von-outlook/

after clicking on syncing folders in outlook  i get high load on server and many many entries in z-push.log with debug=true

interesting is maybe:
```
28/02/2024 14:25:02 [3514527] [DEBUG] [foo] ChangesMemoryWrapper->ImportFolderChange(): Change for folder 'foo' will not be sent as parent folder is not set or not known on mobile.
```
which comes for every folder of that user

**Comment by mschering** [comment]
Unfortunately Outlook does not work with third party activesync. I can't even configure an account anymore.
You can use caldavsynchronizer and imap:

https://caldavsynchronizer.org
