### ISSUE TITLE
Start module selection doesn't work

### ISSUE THREAD

**Issue by Yaaaxx** [Intermesh/groupoffice#1131]
When I want to change the module where to start in my profile edition. The dropdown is empty.

![image](https://github.com/Intermesh/groupoffice/assets/48021864/c45f31d7-b2d0-45ab-84b9-d15158e21dea)

I think the problem come from 6.8.32.

**Comment by derjoachim** [comment]
I fixed this today. Will release 6.8.37 tomorrow  with the bug fix.

**Comment by Yaaaxx** [comment]
Thanks ! Now updated, it works.

**Comment by derjoachim** [comment]
Excellent! I'm closing this ticket :-)
