### ISSUE TITLE
CalDAV-Event creates duplicate events in web-GUI

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1132]
version: 6.8.36

When i create an event through CalDAV and invite other internal users of groupoffice
they see that event in their calendar 2 times in the web-GUI. With CalDav they see this event only once.
After using the button 'doppelte Einträge entfernen' (remove duplicate entries) in the web-GUI it's all as expected
but we cannot use this multiple times over a day.

**Comment by mschering** [comment]
I believe this has been caused by a recent sabredav upgrade. I have fixed the issue now.

**Comment by Nachtlichtermeer** [comment]
First test with version 6.8.37 looks good
i wait for response of other users
