### ISSUE TITLE
CalDAV-Event send mail with english subject

### ISSUE THREAD

**Issue by Nachtlichtermeer** [Intermesh/groupoffice#1133]
version: 6.8.36

When a user with language=german creates an event using CalDAV (thunderbird) a mail is triggered
with subject 'Invitation: ...' instead of 'Einladung: ...'

**Comment by mschering** [comment]
Will be fixed in today's 6.8 release

**Comment by Nachtlichtermeer** [comment]
ACK, tested succesfully with v6.8.37
