### ISSUE TITLE
inability to change customer 

### ISSUE THREAD

**Issue by tindows** [Intermesh/groupoffice#1135]
Hi,

following the commit 'Disallow modification of modifiedAt, createdAt, modifiedBy and createdBy via API', I have encountered an issue with assigning or modifying the customer associated with a ticket. Newly created or modified support ticket is assigned to the user who created it, rather than the chosen customer.

Could the property 'createdBy' be excluded from readonly properties, or can I modify which properties for an entity are readonly?

Thanks.

**Comment by mschering** [comment]
Sorry, this has been fixed in the current release.
