### ISSUE TITLE
Can't edit tasks, after adding file for ex. pdf to a task

### ISSUE THREAD

**Issue by bartekbtm** [Intermesh/groupoffice#1139]
Hello,

I can't edit tasks (save button is disabled), after adding file for ex. pdf. The same problem is when im add task from phone, and trying to edit on the pc.
Can You help me please?

**Comment by mschering** [comment]
Sorry, I can't find any issue or perhaps I don't understand you correctly. Could you please try to elaborate and perhaps add a screenshot?

**Comment by bartekbtm** [comment]
Thank You for answer.

after adding a task, I can edit it. If I add a file to it, for example a PDF, editing is no longer possible and the button looks like in the screenshot (cannot be saved)

If I add a task from my phone, I cannot edit it from my computer. Same user.
Is this a privilege problem?

![screen](https://github.com/Intermesh/groupoffice/assets/164920941/1865e471-9cd2-4199-b912-840211c2272b)

**Comment by mschering** [comment]
But how do you add a file to a task in that dialog?

**Comment by bartekbtm** [comment]
I'm dropping the file here
![Uploading 1212.png…]()

**Comment by bartekbtm** [comment]
![Uploading 2222.png…]()

**Comment by mschering** [comment]
Strange, that makes no sense to me. I have tried it to be sure but I don't have this problem. If you have a support license than you can contact us so we can investigate it.
