### ISSUE TITLE
Confirm close window with changes

### ISSUE THREAD

**Issue by ijuliusz** [Intermesh/groupoffice#1140]
Hi :)

The default notification for closing a dialog window before saving appears even when changes have not been made. 
This happens in a dialog window where data is automatically populated immediately after its opening. 

There are situations in the modules I've created where data isn't fetched 'live' upon opening, 
and in those cases, such a window can be closed without notification.

Is it possible to disable this for a specific dialog window?

Juliusz

**Comment by mschering** [comment]
You can do two thing:

1. set closeWithModification = true on the window
2. call yourwin.formPanel.form.trackReset(); after populating so it will behave as it should.

Good luck!

**Comment by ijuliusz** [comment]
I applied solution number 2. 
I used it in either `onReady:` or `this.on('ready', function(){...})` just before the last closing curly brace.

It works
Thank you.
