### ISSUE TITLE
Feature: auto-refresh

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#1142]
Ive seen some webmails that always that require a reload, offer it to you "can we reload?", you click yes, it reloads. Would be nice for GO, where sometimes you make a change and need to hit f5.

**Comment by mschering** [comment]
It reloads every 2 mins already.

**Comment by flaviozluca** [comment]
I see. I mean, I saw in another webmail, when certain changes are made, that require a refresh, webmail asks "can I reload for changes to be effected?". thats what I mean. I believe some things in GO, we have to press f5 for the change to be done.

Ill try to see solid cases.

**Comment by mschering** [comment]
We are rewriting all modules for the JMAP API which supports push notifications of changes. Refresh will eventually be fully automatic.  Check our roadmap for the state:

https://www.group-office.com/blog/2025/01/2025-roadmap
