### ISSUE TITLE
/install/upgrade.php too slow

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#1145]
Any idea how to speed up /install/upgrade.php ? I have mentioned issues with performance after upgrade to 6.7.79 and although the cache was cleared a minute ago, next call takes about 1 minute sometimes more.

**Comment by mschering** [comment]
Do you run it with multi instance?

**Comment by michalcharvat** [comment]
Yes and no, the same issue is also on dev with debug. Earlier I mentioned it took some time on instances where were a lot of changes however second call was much faster. Currently every install/upgrade call with the intention to reload caches etc take too long

**Comment by mschering** [comment]
Strange, I don't see the same thing. Perhaps you can use xdebug to produce a profile?

**Comment by michalcharvat** [comment]
Fixed at least on my dev - one cron task which was managed externally by supervisor hadnt session write close in it. However it didnt help on productuion. Anyway closing because it looks like nothing related to GO self :-)

**Comment by mschering** [comment]
that's odd, I tried it here but EntityType::clearCache() is only called 87 times (for each entity I guess). Can you dive into the stack trace?

**Comment by mschering** [comment]
Or are you running this on sse.php?

**Comment by mschering** [comment]
Thanks for bringing this to my attention. There was a huge inefficiency in the SSE process which will be fixed in the next release.

**Comment by michalcharvat** [comment]
@mschering btw there is a bug if you are still using < PHP 8 - PushDispatcher.php:75
<img width="574" alt="image" src="https://github.com/Intermesh/groupoffice/assets/8058273/d778fc77-c718-4089-9168-471bf9734c8b">

**Comment by mschering** [comment]
Please retest with the next releases.

**Comment by michalcharvat** [comment]
The problem was found... one script was named with a capital letter at the start, which is automatically loaded by the class loader.
