### ISSUE TITLE
PL holidays file

### ISSUE THREAD

**Issue by ijuliusz** [Intermesh/groupoffice#1148]
Hi

I see that there is no file with Polish holidays yet. 

Please add a file with the following content to the next GO update:

`<?php
// holidays with fixed date
$input_holidays['fix']['01-01'] = 'Nowy Rok';
$input_holidays['fix']['01-06'] = 'Trzech Króli';
$input_holidays['fix']['05-01'] = 'Święto Pracy';
$input_holidays['fix']['05-03'] = 'Święto Konstytucji 3 Maja';
$input_holidays['fix']['08-15'] = 'Wniebowzięcie Najświętszej Maryi Panny';
$input_holidays['fix']['11-01'] = 'Wszystkich Świętych';
$input_holidays['fix']['11-11'] = 'Dzień Niepodległości';
$input_holidays['fix']['12-25'] = 'Boże Narodzenie (pierwszy dzień)';
$input_holidays['fix']['12-26'] = 'Boże Narodzenie (drugi dzień)';

// holidays with variable date (christian holidays computation is based on the date of easter day)
$input_holidays['var']['0'] = 'Niedziela Wielkanocna';
$input_holidays['var']['1'] = 'Poniedziałek Wielkanocny';
$input_holidays['var']['49'] = 'Zesłanie Ducha Świętego';
$input_holidays['var']['60'] = 'Boże Ciało';`

Regards
Juliusz

**Comment by mschering** [comment]
Thanks! I've added them.
