### ISSUE TITLE
Most of the config.php params does not work

### ISSUE THREAD

**Issue by kemeris2000** [Intermesh/groupoffice#1149]
I am trying to automate group-office deployment with docker compose. Most of the config.php params does not work for me:

```
$config['title'] = 'Office';
$config['default_timezone'] = 'Europe/Vilnius';
$config['default_date_format'] = 'Ymd';
$config['password_min_length'] = '8';

```
Only couple of them does work, for example:

`$config['product_name'] = 'Office';`

Am I missing something? Is this [documentation](https://www.group-office.com/wiki/Configuration_file#Config_file_settings_lists) is up to date?

**Comment by michalcharvat** [comment]
I assume you didnt check the first line on wiki page:

```This manual is deprecated. Please visit https://groupoffice.readthedocs.io for the latest documentation.```

Also some configuration options were migrated from underscore to camelcase, some of them are stored in database - table core_setting.

**Comment by kemeris2000** [comment]
I missed that line indeed, sorry. Already studied [latest documentation ](https://groupoffice.readthedocs.io/en/latest/install/config.html) but couldn't find settings I need. Any options to modify  core_setting without modifying database table directly, is cli.php capable of this?

**Comment by kemeris2000** [comment]
I am appreciate for your help @michalcharvat
