### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#115]
1. Do we need to show “ Root folder” or could that be hidden?
2. When there are no sub project would it be possible not to see this area as it just takes up space.
3. The Add button for links doesn’t have any context so you don’t know that this one is for like etc, maybe it would be better to continue calling it the “ New” button? 
4. Could the Add and browser buttons be beside their corresponding names so that even when minimised you can use them?
5. When you are looking at the sub projects in the list would it be possible to have a small line colour variation to show that they are different lines
6. When on the project edit under income the add button doesn’t work.
7. When in UK could the finance button be £

![projects](https://user-images.githubusercontent.com/37214605/39623804-bbca4292-4f8e-11e8-84ed-cecb9cf415ed.JPG)
![projects 2](https://user-images.githubusercontent.com/37214605/39623803-bbb16b78-4f8e-11e8-9a24-b98e86150584.JPG)

**Comment by mschering** [comment]
1. The root folder is needed for moving projects to the root.
2. Will be changed in the next release.
3. The new button has been restored :)
4. They have been added to the "More" menu now too for easy access.
5. They have now
6. Fixed
