### ISSUE TITLE
Proxy headers (X-FORWARDED-FOR) are ignored for "Authorized clients"

### ISSUE THREAD

**Issue by bkury** [Intermesh/groupoffice#1150]
Hi,

Group-office is installed behind a NGINX proxy with all necessary proxy headers set correctly.

It seems like that X-FORWARD-FOR headers are not taken into account for "authorized clients". It's working fine in other modules like history (e.g. login/logout IP) 

Any ideas? Thanks!

OT: Is there a way to change the order of the navigation menu ?

![headers](https://github.com/Intermesh/groupoffice/assets/1777146/cb2c5ecf-1e8c-4730-a015-3c45e12922e0)

**Comment by michalcharvat** [comment]
Regarding the menu, earlier you could change the order by drag-and-drop (DnD) within modules. However, with the new UI, DnD is no longer available. You can now change the order by modifying the sort_order column in the core_module table - without warranty :) It’s been a while since I last worked on this

**Comment by bkury** [comment]
Thanks for the reply!

Something else I noticed:
After updating to 6.8.53 I can no longer edit the "Default permissions" in "System Settings". Nothing happens when clicking on a entity or "Manage default permssions".

**Comment by bkury** [comment]
I think i found another issue:

- Installed Trial License to test the additional modules
- I noticed that installing the license disabled access from my other domains pointing to group-office (which is pretty annoying when trying to test stuff out but ok)
- Removed the license

Now I can no longer login with my admin account (normal user accounts are still working fine), error after login:
**Cannot read properties of undefined (reading 'primaryColor')**

Any idea? Thanks!

Also, when buying a "professional license", is it also bound to one specific (sub)domain?

**Comment by michalcharvat** [comment]
> Thanks for the reply!
> 
> Something else I noticed: After updating to 6.8.53 I can no longer edit the "Default permissions" in "System Settings". Nothing happens when clicking on an entity or "Manage default permssions".

It looks like there is a bug @mschering 

go.defaultpermissions.ShareWindow - returns panel instead of array in initFormItems method

**Comment by michalcharvat** [comment]
> I think i found another issue:
> 
> * Installed Trial License to test the additional modules
> * I noticed that installing the license disabled access from my other domains pointing to group-office (which is pretty annoying when trying to test stuff out but ok)
> * Removed the license
> 
> Now I can no longer login with my admin account (normal user accounts are still working fine), error after login: **Cannot read properties of undefined (reading 'primaryColor')**
> 
> Any idea? Thanks!
> 

It would be nice to see output in console. Based on your descrition there is an error

> Also, when buying a "professional license", is it also bound to one specific (sub)domain?
Yes professional license is bound to the specific domain @mschering will tell your more about licensing.

**Comment by mschering** [comment]
Thanks, I fixed both issues (SharePanel and remote IP). 

The professional license is for one installation and therefore bound to one hostname. If you need more we can discuss the options. Please contact us via info@intermesh.nl if you like that.

Best regards,
Merijn

**Comment by bkury** [comment]
> It would be nice to see output in console. Based on your descrition there is an error

/views/Extjs3/script.php?v=1717952384
![error](https://github.com/Intermesh/groupoffice/assets/1777146/2e73a9be-c0aa-4099-8c7f-2e6f3b564882)

Thanks!

**Comment by bkury** [comment]
Found the issue:

If no license is installed and module "projects2" is installed and enabled you get the login error above.
Manually disabling the module in the database fixed the issue:

```
mysql> update core_module set enabled = 0 where id = 30;
Query OK, 1 row affected (0.16 sec)
Rows matched: 1  Changed: 1  Warnings: 0

| 30 | projects2         | NULL      |     414 |        185 |          0 |       1 | 2024-06-09 16:58:31 |   NULL | NULL      |         126 |
```

**Comment by bkury** [comment]
> The professional license is for one installation and therefore bound to one hostname. If you need more we can discuss the options. Please contact us via [info@intermesh.nl](mailto:info@intermesh.nl) if you like that.

Thanks!

I get that a license is for one (server) installation, but why would you also bind the license to a specific hostname? It's pretty common to have multiple (sub)domains pointing to one groupware installation.

- e.g. I'm hosting 5 small open source projects (2-5 user each) with 5 different domains on the same group-office server. Without a license I can access group-office from all domains (e.g. webmail.domain1.com, mail.domain2.com, domain3.com) but if I would buy a "professional license" I'm suddenly restricted to access group-office only from one specific sub(domain) ? That doesn't make any sense ...
- Also, it's pretty easy to bypass this restriction with a reverse proxy and some small code changes, but I'm still wondering why this limitation is there in the first place?

Anyway, thank you for this project. It's really refreshing to see a groupware solution with that many features and a fair license pricing model.

**Comment by mschering** [comment]
PS: You can change the order of the modules in 6.8.54 now when going to System settings -> Modules and click the Sort icon from the toolbar.

**Comment by bkury** [comment]
Why would that be confusing? It's actually the opposite, for example:

If you are a user/developer working on project2 you are using the services of the project2.com domain (e.g. gitlab.project2.com, support.project2.com, ...) Now, if you want to access group-office I assume you expect something like "mail.project2.com" or "office.project2.com, right ?

Well, that's not possible with a license because it's already bound to e.g. mail.project1.com, so basically all users from project2.com, project3.com, project4.com have to use mail.project1.com to be able to access group-office although they are all on the same server/installation.

So, my options to solve this problem are:
- Use a different/neutral (sub)domain for a licensed group-office installation that everybody have to use.
- Bypass this pointless restriction with a reverse proxy and some code changes
- Don't buy a license for this server/installation and use the community edition instead which doesn't have this restriction.

Again, I don't understand the point of this limitation when using a license.

>PS: You can change the order of the modules in 6.8.54 now when going to System settings -> Modules and click the Sort icon from the toolbar.

Yes, I've already seen the commit, thank you very much!
I've already changed the sort order directly in the database as you suggested but this is much more user friendly.

**Comment by mschering** [comment]
I'm sorry, but the license is for one installation / hostname only. The only way we can prevent users from installing it for multiple clients is by restricting the hostname. I hope you understand.
Sure, you can hack the code or use proxies to bypass this technical measure. But then you are in breach with our terms of use and you use it illegally.

**Comment by michalcharvat** [comment]
I see only one reason why to do that -> have all data in single instance because you have to supervise data and you would like to create unique UI for each group. Truth is you cant do that. Although you have each GO installation on own domain, the database is the same. If you have enabled PRO modules you will get an error on instance without valid license. 
The only way how to implement supervisors instance is create custom reports above all those instances (so you do not need license) and sync data from each to the parent. 
Actually reason why you would like to have own instance per group could be simple - you do not want create mess in database because if group or lets say project ended you can easily delete whole instance. It is a specific edge case but I was also facing similar problem. 
It is difficult to say why @bkury needs anything like that because he didnt descibe the reason.

**Comment by bkury** [comment]
> I'm sorry, but the license is for one installation / hostname only. The only way we can prevent users from installing it for multiple clients is by restricting the hostname. I hope you understand.

So, the hostname requirement is about preventing users from using the same license on multiple installations/servers, right? Honestly, I assumed that there is some other online license check in place, because only matching x-forwarded-for header against the license hostname isn't preventing anybody from anything because it can easily set manually on the reverse proxy side.

At this point I really don't know how to further explain to you why it's not ideal to bind an installation to a specific hostname/domain. 

But I guess if you don't have an alternative/online way of checking the validity of a license the hostname is probably your best bet.

> It is difficult to say why @bkury needs anything like that because he didnt descibe the reason.

It's much more simple, I'll try again:

- The reason is that users with multiple domains (e.g. business, private, family) on a single group-office installation want to access group-office from all their domains.
- This is even more important if you use group-office to host multiple collaboration projects with multiple domains (as explained 3 posts above) on a single server.
- This way you can have separate logfiles, analytics, configs for each domain although you are using one group-office installation.

There are more things to consider but these are more of an edge case.

Anyway, I don't think we find a common ground on this problem but thank you for the quick fixes. 
"Authorized Clients" and "Default permissions" are now working and the new GUI feature to change the sort order of modules is fantastic.

Thanks!

**Comment by michalcharvat** [comment]
Although you are trying to describe it I still dont see real reason to use single instance for all. Count with scenarios when you have to run maintenance tools on that database - count with days to rebuild indexes on big database. So until there isnt real reason to put everything into one database I recommend you use as many instances as you can. It will help you with maintenance. 
Maybe the reason is AB sharing? I dont know. However from description above I dont see any reason why I have to use single instance. Just setup one GO for family, one for business etc. The mailbox could be added to all instances and I dont see any reason mixup business data with your personal. Also question is which pro modules you need for personal use :)

@mschering Truth is if you want to use GO as document editor you have to buy PRO license which is pretty expensive compared to Office 365 for Family or Nextcloud. Maybe this is the reason why he is trying share single instance but who knows...

**Comment by bkury** [comment]
Well, using multiple instances is not an option in this case because it's a family business and they want to share their work calendars, files, photos, etc with each other. They have a business domain but also private (surname) domains which they also want to access group-office from. (which isn't possible with a license because it's bound to the business domain)

And yes, having the ability to use the professional modules (without paying for a second license for 2-3 users) is also a reason for using one instance only. Especially the onlyoffice module you mentioned is really nice to have but there are also other paid modules like the time tracking which are handy to have even if it's not for work/business use-case.

**Comment by bkury** [comment]
I just noticed that ActiveSync devices still show up with the proxy IP instead of the real (x-forwarded-for) IP. This is true for "Authorized Clients" and for "ActiveSync Management" module.

Thanks!

**Comment by mschering** [comment]
The client is looked up with the wrong IP right now. Next release should fix that.

About ActiveSync. We use a third party lib. Please report it there: https://github.com/Z-Hub/Z-Push

**Comment by bkury** [comment]
> The client is looked up with the wrong IP right now. Next release should fix that.

Thank you!

> About ActiveSync. We use a third party lib. Please report it there: https://github.com/Z-Hub/Z-Push

Z-Push already has support for that, fixed it by enabling "USE_CUSTOM_REMOTE_IP_HEADER" in config.php :

/usr/share/groupoffice/modules/z-push/config.php
```
// Use a custom header to determinate the remote IP of a client.
// By default, the server provided REMOTE_ADDR is used. If the header here set
// is available, the provided value will be used, else REMOTE_ADDR is maintained.
// set to false to disable this behaviour.
// common values: 'HTTP_X_FORWARDED_FOR', 'HTTP_X_REAL_IP' (casing is ignored)
// const USE_CUSTOM_REMOTE_IP_HEADER = false;
define('USE_CUSTOM_REMOTE_IP_HEADER', 'X_FORWARDED_FOR');
```

**Comment by michalcharvat** [comment]
> Sorry for bothering you again ...
> 
> Is there a reason why you haven't adopted my z-push config change above which fixes z-push reporting the wrong IP when using a reverse proxy?

Maybe because it does change whole logic? Think about it. The best would be create configuration in GO and forward it to zpush config instead of overwriting configuration for all.

**Comment by bkury** [comment]
Why would it change the whole logic? 

If X-FORWARDED-FOR is set (which is only true if you have a proxy in front of GO) it will use that, if it's not set (no proxy) it will use the default REMOTE_ADDR

So, this should actually work for anybody with or without proxy.

**Comment by michalcharvat** [comment]
If you dont now want use X-FORWARDER-FOR for some reason how do you want to switch it back to the default? If it is set and you would like to use itm then you have an option to do that. With your modification you basically dont give any other option - just use it if it is set. There simply should be the option enable/disable it in GO settings. Thats it.

**Comment by bkury** [comment]
> If you dont now want use X-FORWARDER-FOR for some reason how do you want to switch it back to the default?

Honestly, there is no "for some reason" in this case, either you have X-FORWARDED-FOR set which should then always be used or not. If you have a proxy in front of GO and don't want GO to use FORWARDED-FOR you would simply remove the proxy config that adds the FORWARD-FOR header in the first place ...

Well, anyway, thanks for your reply!
