### ISSUE TITLE
[6.8.53] Email styles read / unread message 

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#1151]
I dont think it is a good idea to make subject bold although the message is read
<img width="792" alt="image" src="https://github.com/Intermesh/groupoffice/assets/8058273/b18760bc-ddbc-4b16-ba48-7a5a54a6a7b6">

Comparison to unread message:

<img width="802" alt="image" src="https://github.com/Intermesh/groupoffice/assets/8058273/7b8056b6-1486-413f-acd9-0348212c9f22">

**Comment by mschering** [comment]
It doesn't look like that on my environment. Which theme is this? Did you perhaps add custom style?

**Comment by michalcharvat** [comment]
It's gone after I cleared browsers caches. The similar problems was with tertiary and accent colors. I cant replicate it now so I will close this issue.
