### ISSUE TITLE
Multi Instance list dissappeared on update to 6.8.56

### ISSUE THREAD

**Issue by oxdrove** [Intermesh/groupoffice#1157]
**Problem**
After update to 6.8.56 the Multi-Instance list in the master instance is empty.
Some of the multi instance options produce a busy/waiting pop-up but no action.

**Severity**
Minor as far as I can tell. There appears to be no problem with the sub instances although I have not comprehensively checked.

**To reproduce**
Update Groupoffice. Pre-update "apt list --upgradeable" output line: 
`groupoffice/unknown 6.8.56-sixeight all [upgradable from: 6.8.55-sixeight]`

The update logs say update was successful.
```
# cat var/log/upgrade/20240625_143839.log
Rebuilding cache
Registering all entities

Upgrading all instances
-------------------------------

Upgrading instance: go.xxxxxx.co.uk: ok
Upgrading instance: go.yyyyyy.co.uk: ok
Upgrading instance: go.zzzzzz.uk: ok
All OK!
Done!
```

**Workaround**
I have rolled back the machine to its pre-update update state and the Multi-Instance list is back.

**Notes**
OS is virtualised Debian 12 using the package stream:
`deb http://repo.group-office.com/ sixeight main`

**Comment by mschering** [comment]
Do you find any errors in the log? I can't find any issues here.

**Comment by oxdrove** [comment]
As per the report, the update log is shown.  The terminal output looked normal.

**Comment by oxdrove** [comment]
I have just repeated and get the same result.

**Comment by oxdrove** [comment]
![go](https://github.com/Intermesh/groupoffice/assets/92857152/4c7e0706-39b1-42cd-8768-50c1f275f495)

**Comment by michalcharvat** [comment]
I see just the picture - did you check the console, network tab, server logs? It looks like there is problem load data as you can see on that picture where you are stuck on loading mask.

**Comment by oxdrove** [comment]
Yes, as per my initial report the log is shown.
Yes, it is stuck and no listing, that is what I am reporting.

**Comment by oxdrove** [comment]
Please let us not not get over existed but the update is log is in my original report.
The "error" is that the multi-instance listing has disappeared, again in my original report.  What we do not know is what is the cause.

Thank you for suggesting things to reveal the cause. I will switch on debug and do the update again.

I did not understand the phrase "Please open console in browser" so do not know what to do there.

**Comment by mschering** [comment]
The update log shows only messages during the upgrade. runtime errors can also be found in /var/log/apache2/error.log.

**Comment by oxdrove** [comment]
There was none but see for yourself.  Also I provide the debug output during update and page view.
[apache_error.log](https://github.com/user-attachments/files/16033297/apache_error.log)
[debug.log](https://github.com/user-attachments/files/16033299/debug.log)

**Comment by oxdrove** [comment]
I will add that there is no output when clicking on a header which hangs - which is why I have not included it.

**Comment by oxdrove** [comment]
"Please open console in browser"  == "Please open the browser console" (sorry I was looking for a GO console to open in the browser).  Try this:

```
SyntaxError: Unexpected token '<', "<html><bod"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.success (script.php?v=1719597970:1745:167)
    at Ext.data.Connection.handleResponse (ext-all-debug.js?mtime=1719235266:4641:33)
    at handleTransactionResponse (ext-base-debug.js?mtime=1719235266:2312:38)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js?mtime=1719235266:2418:15)
```

**Comment by oxdrove** [comment]
Update to 2.5.58 and the list is back.  Red bits in the browser's log have gone too.
