### ISSUE TITLE
Address Book

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#116]
1. Not able to do an export when you search for something.
2. Do ticket groups allow people to see all the companies tickets.
3. Could there be a way of having an area the ticket users show in the address book, not in "Users" address book?
4. When adding a contact or company the grid does not reload.

**Comment by michalcharvat** [comment]
4. still exists in 6.3.12

**Comment by mschering** [comment]
These have all been fixed I believe.
