### ISSUE TITLE
GroupOffice 6.8 Studio module search name filed not working

### ISSUE THREAD

**Issue by komunalinfo** [Intermesh/groupoffice#1166]
![Képernyőkép_2024-07-16_13-36-39](https://github.com/user-attachments/assets/5c9de60f-713d-461f-8c27-c64b8b890017)
![Képernyőkép_2024-07-16_13-27-01](https://github.com/user-attachments/assets/aa6873df-5979-4112-b116-1933e676dd58)

**Comment by derjoachim** [comment]
The search name was fixed and will be rolled out in 6.8.63 . You should regenerate your studio module though and possible regenerate your entire search cache.
