### ISSUE TITLE
Is labeling emails an IMAP feature which has to be available by server?

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#1174]
Strange behaviour: GO latest, labels deleted, new created
When trying to add them to an email, there is an error message, saying "No error message given", also no entry in server logfile.

**Comment by mschering** [comment]
Labels is an IMAP feature which not all IMAP servers support indeed.

**Comment by lonesomewalker** [comment]
Then this can be closed :-) 👍
