### ISSUE TITLE
CalDAV shared calendars are not shown in Thunderbird

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#1178]
Adding new client by Thunderbird with IMAP, CalDAV and CardDAV.
Shared calendars are not offered at initial setup.

Missing permissions?

**Comment by lonesomewalker** [comment]
When logging in by direct webinterface to sabredav, and then checking the calendars, i get:
User did not have the required privileges ({DAV:}read) for path "calendars/username"', referer: https://go.domain.tld/caldav/calendars/

User is in the internal group, and group permission is read.

**Comment by mschering** [comment]
Are there calendars present in the users' account settings -> Synchronisation? Those should be available for caldav.

**Comment by lonesomewalker** [comment]
Yes, they have been.
Just for being 100% sure, i removed them, logged out, logged in, added them.

Now, they are offered to synchronize, but without limitations.

Means: private appointments show full details instead like GO does. :-|

**Comment by mschering** [comment]
I can't replicate this. Private events are not synchronized to caldav at all if you're not the owner.

**Comment by lonesomewalker** [comment]
Okay... maybe a permission thing.
When the user has writing rights, already too much? Only read and add?

**Comment by mschering** [comment]
I don't understand this. So you say:

1. User A has a private event in a calendar owned by User A.  The ownership of the calendar is important here.
2. User A shares this calendar with User B
3. User B sees the private event via caldav?

**Comment by lonesomewalker** [comment]
Check :-)

Totally weird. Makes no sense.
I already replicated this with the official docker image, so it has nothing to do with the setup.

If there would be an official demo of GO, i am sure to replicate this.

**Comment by lonesomewalker** [comment]
Closed, tested thoroughly, working.

Thanks.
