### ISSUE TITLE
PHP 8.3 loader problem

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#1180]
Latest version of loader v13.3.1 supports PHP 8.3 however it looks like business modules are still encoded with old version of loader.

```PHP Fatal error:  The file /usr/share/groupoffice/go/modules/business/support/model/SupportTasklist.php encoded as type [1/81] cannot be decoded by this version of the ionCube Loader```

@mschering Can you release new version where will be all modules encoded with SourceGuardian or shall I downgrade to 8.2 which does mean I have to upgrade the system once again when you support 8.3? 

```PHP 8.3.6 (cli) (built: Jun 13 2024 15:23:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.3.1, Copyright (c) 2002-2024, by ionCube Ltd.
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
    with SourceGuardian v15.0.2, Copyright (c) 2000-2024, by SourceGuardian Ltd.
```

**Comment by mschering** [comment]
Which version are you using? The 6.8 releases should already work on php 8.3.

**Comment by michalcharvat** [comment]
The latest version ![image](https://github.com/user-attachments/assets/bcf807d4-f4d7-487b-aa2b-3124d57e1ef1)

**Comment by mschering** [comment]
Are you sure you're not mixing some files here? I just built a 8.3 docker image to verify but all runs fine with it.

**Comment by michalcharvat** [comment]
> PS: You can remove the ioncube loader.

Yes thats what I thought however I get an error in business module so I installed it again. Package is from sixeight repository installed on Ubuntu 24 LTS but let me check it again.

**Comment by michalcharvat** [comment]
Strange.. after install --reinstall was SupportTasklist.php removed and of course there is no error. It was upgrade from 6.7 where 6.7 was installed from sourceforge and 6.8 from repository.
