### ISSUE TITLE
Undefined constant "GO\Email\Controller\mailer"

### ISSUE THREAD

**Issue by APachLv** [Intermesh/groupoffice#1181]
Dear.

Fresh install, first user ok, second "Undefined constant "GO\Email\Controller\mailer"

How to sort out this?

![2024-09-09_14-32-01](https://github.com/user-attachments/assets/6bb52773-2eb2-4635-95e2-b801c11e6245)

**Comment by mschering** [comment]
It happens when mail sending fails. The previous version shows this uninformative error. This is fixed in the latest release but you should still correct your smtp settings.
