### ISSUE TITLE
Sync with multiple Mailboxes in Outlook Cause App Crash (Z-Push/ActiveSync)

### ISSUE THREAD

**Issue by gmcpaul** [Intermesh/groupoffice#1190]
Dear all,
i recently migrated a mailsystem of a friend of mine which worked as a charm.

Now we currently face an interesting problem.
When syncing multiple Mailboxes (4-6) to Outlook (tried 2013,2016,2024) the Outlook App keeps Crashing after Sync has been done.

I tried following things:

- Completely removed the Office Install (Office Scub) and reinstall
- Renewed the Outlook Profiles
- Cleared the Cache Directories
- Set Sync Time to a minimum

Outlook starts and crashes after a few seconds 
the err reports mentions pstprx32.dll in correlation with that.
So i tried different Versions of the Outlook App since i found that M$ has had some issues with that dll in the past. Sadly without success.
Now that im out of ideas, i wanted to check here, if ther are some known issues in connection with z-push?
Maybe im missing some tweaks or something, i checked and adjusted the php.ini as mentioned and all that but it did not solve the issue.

Thanks and all the best,
Paul

**Comment by mschering** [comment]
Sounds like an outlook problem but it might be worth checking the server logs to see if there are any errors server side:

https://groupoffice.readthedocs.io/en/latest/troubleshooting/logging.html

**Comment by gmcpaul** [comment]
@mschering turns out you where right... zpush was not able to write to the cache dir ... my fault... 
thank you für putting me on the right track ;)

**Comment by gmcpaul** [comment]
well seems the problem is not solved... still hassling with outlook crashes
os is a ubuntu 24.04 with the current group-office release


some errors i can find within the zpush error log:

/usr/share/groupoffice/go/core/util/StringUtil.php:483 iconv(): Wrong encoding, conversion from &quot;pdfiso-8859-1&quot; to &quot;UTF-8//TRANSLIT//IGNORE&quot; is not allowed (2)

15/10/2024 22:57:34 [138121] [ERROR] [mailadress] ImportChangesCombined->Config() icc not configured
15/10/2024 22:57:34 [138121] [WARN] [mailadress] /usr/share/groupoffice/go/modules/community/activesync/Z-Push/src/lib/default/diffbackend/importchangesdiff.php:221 Trying to access array offset on false (2)
15/10/2024 22:57:34 [138121] [WARN] [mailadress] StatusException: DiffState->GetState(): Error, state not available - code: 12 - file: /usr/share/groupoffice/go/modules/community/activesync/Z-Push/src/lib/default/diffbackend/diffstate.php:100
15/10/2024 22:57:34 [138121] [FATAL] [mailadress] WBXML 10K debug data: AwFqAAAHU1IDe2RlZDExNWFlLWJjZmMtNGNlNy1hMjg2LWNmNGVkZDVmMmEwOH0xAAFJAzAAAUcDQXJjaGl2AAFKAzEyAAEB
15/10/2024 22:57:34 [138121] [FATAL] [mailadress] Exception: (StatusException) - DiffState->GetState(): Error, state not available

15/10/2024 23:00:34 [86406] [ERROR] mailadress] Failed to recreate mime source. Falling back to original mime. Subject: [your-subject] Exception: Invalid address:  (From): bla


FROM `addressbook_contact` `c`
LEFT JOIN `addressbook_contact_star` `s` ON 
 c.id = s.contactId AND s.userId = 13
WHERE 
 addressBookId = :addressBookId -> SQLSTATE[HY000] [2002] No such file or directory
18/10/2024 13:32:44 [2514987] [FATAL] [mailadress] WBXML 10K debug data: AwFqAAANRUgDNDgwAAFJSksDYy8xMwABTANDb250YWN0cwABAUpLA2EvMTIAAUwDQ2FsZW5kYXIAAQFKSwNtL0lOQk9YAAFMA0VtYWlsAAEBSksDbS9XRUJDQU0AAUwDRW1haWwAAQFKSwNtL1N5Y2hyb25pc2llcnVuZ3Nwcm9ibGVtZQABTANFbWFpbAABAUpLA20vU3BhbQABTANFbWFpbAABAUpLA20vU2VudCBJdGVtcwABTANFbWFpbAABAUpLA20vU2VudAABTANFbWFpbAABAUpLA20vUHJpdmF0AAFMA0VtYWlsAAEBSksDbS9MaW5lNAABTANFbWFpbAABAUpLA20vTGFyYW5qYQABTANFbWFpbAABAUpLA20vX0JBVQABTANFbWFpbAABAUpLA20vTGluZTQuVEhJTkshAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5TVEVVRVJCRVJBVEVSLCBGSVJNQSwgQkFOSwABTANFbWFpbAABAUpLA20vTGluZTQuU1BFRElUSU9OLCBMSUVGRVJVTkdFTiwgVkVSUEFDS1VORwABTANFbWFpbAABAUpLA20vTGluZTQuU0hPUAABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBSRVNTRQABTANFbWFpbAABAUpLA20vTGluZTQuT25saW5lLVBvcnRhbGUAAUwDRW1haWwAAQFKSwNtL0xpbmU0LktVTkRFTgABTANFbWFpbAABAUpLA20vTGluZTQuSE9NRVBBR0UgLSBJVAABTANFbWFpbAABAUpLA20vTGluZTQuRUJBWQABTANFbWFpbAABAUpLA20vTGluZTQuRE9NSVpJTAABTANFbWFpbAABAUpLA20vTGluZTQuREVTSUdOLCBEUlVDSywgV0VSQlVORywgw5xCRVJTRVRaVU5HAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5BTkdFQk9URQABTANFbWFpbAABAUpLA20vTGluZTQuQU1BWk9OAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5BTExHRU1FSU5FUwABTANFbWFpbAABAUpLA20vX0JBVS7Dlk1BRy1TVFJPTQABTANFbWFpbAABAUpLA20vX0JBVS5XYXNzZXIgU2VtcmlhY2gAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlNIT1AuYWRtaW4AAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlpFTFRFLCBNQVRURU4sIFNDSExBRlNBQ0sAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlRFRERZAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5TS0kAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSE5FRVNDSFVIRSwgRUlTRU4sIFBST1RFS1RPUkVOLCBHQU1BU0NIRU4AAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSExJVFRFTgABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuUlVDS1PDhENLRQABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuS0xFSURVTkcAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkhFTE1FAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5HT0xGAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5FbGVrdHJvbmlrAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5CUklMTEVOAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVAABTANFbWFpbAABAUpLA20vTGluZTQuS1VOREVOLlNDSEzDnFNTRUxSRUdJU1RSSUVSVU5HAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5LVU5ERU4uMTMwNzA0IE1haQABTANFbWFpbAABAUpLA20vTGluZTQuS1VOREVOLjExMTAxOCBJbmRpZ286AAFMA0VtYWlsAAEBSksDbS9MaW5lNC5LVU5ERU4uMDIxMDE2IEJlcmdiYWhuZW4gV2VzdGVuZG9yZgABTANFbWFpbAABAUpLA20vTGluZTQuS1VOREVOLjAyMTAxMiBzcG9ydDIwMDAAAUwDRW1haWwAAQFKSwNtL0xpbmU0LktVTkRFTi4wMjEwMTIgSW50ZXJzcG9ydAABTANFbWFpbAABAUpLA20vTGluZTQuSE9NRVBBR0UgLSBJVC5YRU8AAUwDRW1haWwAAQFKSwNtL0xpbmU0LkhPTUVQQUdFIC0gSVQuVVBDLVdPUkxENFlPVQABTANFbWFpbAABAUpLA20vTGluZTQuSE9NRVBBR0UgLSBJVC5TSE9QU1lTVEVNICwgUEVDSE1BTk4AAUwDRW1haWwAAQFKSwNtL0xpbmU0LkhPTUVQQUdFIC0gSVQuUFJPRFVLVEJJTERFUgABTANFbWFpbAABAUpLA20vTGluZTQuRUJBWS5YLUFLVEVOLUVCQVkAAUwDRW1haWwAAQFKSwNtL0xpbmU0LkVCQVkuUGF5cGFsAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5FQkFZLkZpeGNoYW5nZQABTANFbWFpbAABAUpLA20vTGluZTQuRUJBWS5BZnRlcmJ1eQABTANFbWFpbAABAUpLA20vTGluZTQuRUJBWS5BZG1pbgABTANFbWFpbAABAUpLA20vTGluZTQuQU1BWk9OLlgtQUtURU4tQU1BWk9OAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5BTUFaT04uQWRtaW5pc3RyYXRpb24AAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlpFTFRFLCBNQVRURU4sIFNDSExBRlNBQ0suVGhyaXZlICwgTHVmZnkAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlpFTFRFLCBNQVRURU4sIFNDSExBRlNBQ0suU09MTwABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuWkVMVEUsIE1BVFRFTiwgU0NITEFGU0FDSy5TSU5PQ0hFTQABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuWkVMVEUsIE1BVFRFTiwgU0NITEFGU0FDSy5ReWllbGQAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlpFTFRFLCBNQVRURU4sIFNDSExBRlNBQ0suRmlyc3QAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlpFTFRFLCBNQVRURU4sIFNDSExBRlNBQ0suRmVuZyBZaQABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuWkVMVEUsIE1BVFRFTiwgU0NITEFGU0FDSy5DaGluYWxpZ2h0AAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZQABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuVEVERFkuQW5mcmFnZW4AAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSE5FRVNDSFVIRSwgRUlTRU4sIFBST1RFS1RPUkVOLCBHQU1BU0NIRU4uTWluT25lIC0gSGFuZCBMaWdodCBMdGQAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSE5FRVNDSFVIRSwgRUlTRU4sIFBST1RFS1RPUkVOLCBHQU1BU0NIRU4uSmlhbkZlbmcAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSE5FRVNDSFVIRSwgRUlTRU4sIFBST1RFS1RPUkVOLCBHQU1BU0NIRU4uSEsgR09MREVOAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5TQ0hORUVTQ0hVSEUsIEVJU0VOLCBQUk9URUtUT1JFTiwgR0FNQVNDSEVOLkdlbm4gU2hhbmcAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlNDSE5FRVNDSFVIRSwgRUlTRU4sIFBST1RFS1RPUkVOLCBHQU1BU0NIRU4uRXZlciBCdWlsZC1VcAABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuU0NITkVFU0NIVUhFLCBFSVNFTiwgUFJPVEVLVE9SRU4sIEdBTUFTQ0hFTi5EYW4tTWF0dAABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuUlVDS1PDhENLRS5UcmF2ZWx3ZWxsAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5SVUNLU8OEQ0tFLnNwb3RsaWdodAABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuUlVDS1PDhENLRS5IaW5nIFdhaAABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuS0xFSURVTkcuU09OU1RJR0UAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLktMRUlEVU5HLkpvaG5zb24gLSBMZXNsaWUAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkhFTE1FLlNPTlNUSUdFAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5IRUxNRS5KVU1CTyBIRUxNRVRTAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5IRUxNRS5IRUxNQkFHAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5IRUxNRS5DQVBPAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5HT0xGLlRyZXN0b24AAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkdPTEYuTWF5b3IAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkJSSUxMRU4uV09PU1VORwABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuQlJJTExFTi5WUwABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuQUdFTlQud2lua2F5AAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVC5IRVJTVEVMTEVSAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZS5SaWNoYXJkIE5nAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZS5SaWNoIEdhcmRlbiBUb3lzAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZS5yZWJlY2NhAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZS5KYXNvbgABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuVEVERFkuQW5nZWJvdGUuSGVpZGkAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlRFRERZLkFuZ2Vib3RlLkZvbmcgU2ltAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5URUREWS5BbmdlYm90ZS5FdXJvcGEAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlRFRERZLkFuZ2Vib3RlLkNpbmR5IFdhbmcAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLlRFRERZLkFuZ2Vib3RlLkNhbmlmaW5lAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVC5IRVJTVEVMTEVSLnZpdmVrAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVC5IRVJTVEVMTEVSLnNvbnN0aWdlIGhlcnN0ZWxsZXIAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIuc2lub3gAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIuc2lub2hiY2UAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIucmlnaHR3YXkAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIucGlvbmVlcgABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuQUdFTlQuSEVSU1RFTExFUi5sb25nZmVuZwABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuQUdFTlQuSEVSU1RFTExFUi5rYW1laWNvaGsoc2ltb24pIC0gSG9mZXIhAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVC5IRVJTVEVMTEVSLkJ1cmctV8OkY2h0ZXIAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIuYnJ1Y2VlZQABTANFbWFpbAABAUpLA20vTGluZTQuUFJPRFVLVEUuQUdFTlQuSEVSU1RFTExFUi5heGEAAUwDRW1haWwAAQFKSwNtL0xpbmU0LlBST0RVS1RFLkFHRU5ULkhFUlNURUxMRVIuYWJhAAFMA0VtYWlsAAEBSksDbS9MaW5lNC5QUk9EVUtURS5BR0VOVC5IRVJTVEVMTEVSLmFiYS5wcml2AAFMA0VtYWlsAAEBAQE=
18/10/2024 13:32:44 [2514987] [FATAL] [mailadress] Exception: (go\core\db\DbException) - Database exception, DEBUG: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away, Full SQL: SELECT COALESCE(count(*), 0) AS count, COALESCE(max(modifiedAt), 0) AS modifiedAt 
FROM `addressbook_contact` `c`
LEFT JOIN `addressbook_contact_star` `s` ON 
 c.id = s.contactId AND s.userId = 12
WHERE 
 addressBookId = :addressBookId -> SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by gmcpaul** [comment]
maybe someone has an idea ..

outlook profile reset, and entered the new mbxes ... it syncs after 1-2 days if fails with the errors mentioned at the beginn
 pstprx32.dll causes crash

**Comment by creissig** [comment]
Refering to the error message, something happend to the MySQL connection. Whats the size of your max_allowed_packet in my.cnf?

**Comment by gmcpaul** [comment]
@creissig  thanks for your response
in my.cf it was commented out so i queried the mysql and got following answer

mysql> SHOW VARIABLES LIKE 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 67108864 |
+--------------------+----------+

so it appears 64mb

so i up it to 128?  for testing?

**Comment by creissig** [comment]
For testing I would reccomend setting to 512MB. If it works you can try with lower values.

**Comment by gmcpaul** [comment]
@creissig 
i let it run for good 5 days and yesterday (after i updated groupoffice) it seems that it failed again
but i did not find the disconnects ... so maybe its not the only problem


in the apache error log i found: 

[Wed Oct 30 03:43:09.008206 2024] [php:error] [pid 3658665] [client 178.115.240.199:64451] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /usr/share/groupoffice/modules/z-push/backend/go/go.php on line 634
[Wed Oct 30 03:43:09.008468 2024] [php:notice] [pid 3658665] [client 178.115.240.199:64451] ErrorException in /usr/share/groupoffice/modules/z-push/backend/go/go.php at line 634: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes)
[Wed Oct 30 03:43:09.033747 2024] [php:error] [pid 3658665] [client 178.115.240.199:64451] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 720896 bytes) in /usr/share/groupoffice/go/core/Debugger.php on line 364

so i extended mem to 512mb now in apache2/php.ini and 256mb in all other php modules

**Comment by creissig** [comment]
Settings with 512MB and 256MB for the modules look fine. I always recommend to stick in first instance to the manual under https://groupoffice.readthedocs.io/en/latest/install/config.html#recommended-php-settings
Also check that your memory limit change is applied  correctly. Try to run php_info() in a script and check the output for the actual memory_limit there. For php_fpm the file is under /etc/php/x.x/fpm directory (where x.x is your version)

**Comment by gmcpaul** [comment]
regarding phpinfo
memory_limit shows 512mb, yes 👍 
also changed fpm-php.ini from 256 to 512mb now

**Comment by gmcpaul** [comment]
@creissig  btw thanks for your effort

**Comment by gmcpaul** [comment]
...im still on the hunt
had to work on another frontier in the mean time...

so outlook active sync clients keep crashing
when deleten the eas cache directory on the client side it seems to rebuilt the sync but i do not believe that this is an client issue, since were syncing the same mailboxes on 3 different systems 

eas cache i mean : %userprofile%\appdata\Local\Microsoft\Outlook\EasCache  -- > i delete the dir and then it appears to try to resync


problem is i cannot find when it crashes exactly, cause the logs fill up so fast

**Comment by gmcpaul** [comment]
@mschering maybe you can reopen the ticket... and maybe some of the groupoffice devs have some input for me <3

**Comment by gmcpaul** [comment]
also updated to the latest release of group office... just for good measure

**Comment by gmcpaul** [comment]
i mean, is it possible that activesync somehow stumbles because of some "bad" mails like wrong codepage or such?
cause i had to migrade the mailboxes via imapsync back then ..

12/11/2024 21:09:35 [ 2799] [WARN] [a.b@c.net] /usr/share/groupoffice/go/core/util/StringUtil.php:483 iconv(): Wrong encoding, conversion from &quot;pdfutf-8&quot; to &quot;UTF-8//TRANSLIT//IGNORE&quot; is not allowed (2)
12/11/2024 21:09:36 [ 2799] [ERROR] [a.b@c.net] Failed to recreate mime source. Falling back to original mime. Subject: AW:Auswertung Monitoring Materialbeschaffung, Stand 07.02.2020 Exception: Invalid address:  (to): Christina Oppelz
