### ISSUE TITLE
Aphostrophe in calendar

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#1191]
When I hover over a calendar appointment I see `&#039;` instead of an apostrophe (in my name). See attached image.

![gofoutje](https://github.com/user-attachments/assets/2fdb3033-2c16-483e-87ff-a5038489bd63)

**Comment by derjoachim** [comment]
Should look better in 6.8.81, to be released later today.

**Comment by koekie71** [comment]
Thanks!
