### ISSUE TITLE
CalDAV sync with DAVx5 error

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#1192]
When I sync my GO calender with the DAVx5 with my phone, I got an HTTP 500 internal server error. In the Apache log I see:

[Mon Oct 21 18:50:52.043528 2024] [proxy_fcgi:error] [pid 2428285:tid 2428285] [client x.x.x.x:43344] AH01071: Got error 'PHP message: ErrorException in /usr/share/groupoffice/vendor/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php at line 133: Undefined array key "calendarid"'

The calendar syncs normally from phone to GO but not from GO to phone.

GO 6.8.78 (but also 6.8.77)

**Comment by spysz** [comment]
Hi,

The same problem after upgrade to 6.8.77.  :-(

p.

**Comment by mschering** [comment]
Thanks for reporting. It has been fixed for the next release. I will create one today.
