### ISSUE TITLE
Sync in Outlook (Z-push/Activesync) problem

### ISSUE THREAD

**Issue by sixxx-b** [Intermesh/groupoffice#1193]
Hello,
I have a problem with ActiveSync and Outook.
It is fresh install of Groupoffice but Outlook doesn't sync - Apache2 error log give - TypeError in /usr/share/groupoffice/go/base/mail/Message.php at line 297: trim(): Argument #1 ($string) must be of type string, array given

Thanks in advance!

**Comment by mschering** [comment]
It seems to be related to some non standard formatting in the mail. Would you be able to share the mail source with me? You can send it to mschering@intermesh.nl.

**Comment by mschering** [comment]
In the meantime I made a change that possibly fixes this problem.

**Comment by sixxx-b** [comment]
Thanks for your fast response. Everythink seems like ok.
