### ISSUE TITLE
Invitation bug

### ISSUE THREAD

**Issue by Yaaaxx** [Intermesh/groupoffice#1197]
Hi,

I'm currently at V6.8.79.

When someone create an event and invite other person, the invitation is correctly sent. But when invited person want to accept from the email, it say that "Could not find organizer to send message to!". The event is accepted and we can fount it in the calendar but when we want to see more (clicking on the event), it say "John doe (j.doe@email.com) was not invited for this event". The organizer see that the person have accepted the invitation.

The problem comes with the update from V6.8.78 to V6.8.79.

**Comment by Yaaaxx** [comment]
I have more information :
When we delete the invitation, it disapear but after a moment the invitation goes back and it works fine.

**Comment by Yaaaxx** [comment]
Hi,
Am I the only one to have this problem ? It still here and I can't find any solution.
This error appear in the log :
[Mon Nov 04 06:13:50.748603 2024] [php:notice] [pid 61274] [client 192.168.6.197:27566] Exception in /usr/share/groupoffice/modules/calendar/controller/AttendanceController.php at line 22: Ya\xc3\xabl Perret (y.perret@exemple.com) was not invited for this event, referer: https://agenda.exemple.com:55000/

**Comment by dehart** [comment]
We were probably not the only one.
But it would only occur if the event was copied to someone else its calendar when the invitee was in the same system and the organizer has write permission to the calendar.

Thanks for providing the info.
It's fixed in the next release (probably today)

**Comment by Yaaaxx** [comment]
Thank for the fix ! It works fine now
