### ISSUE TITLE
Modules JsonStore not available

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#1198]
Since several versions I get this error while looking for modules
![modules_error](https://github.com/user-attachments/assets/5a729957-1539-4917-a4a4-6cd4ec5230a9)

Don't have a clue, where to look for...
Thanks for help robw

**Comment by derjoachim** [comment]
I am not noticing any odd behavior on my side. There's probably a server side error that prevents the module list from rendering. You can either look into your webserver logs for more information or enable debug mode in your `config.php`, click the 'refresh' icon and see in your developer console, tab 'network', the output of the request that retrieves all modules.

**Comment by robshnup** [comment]
Hi,
i use the community version and it's complaining about a faulty version of sourceguardian.

`Uncaught exception: Uncaught ErrorException: SourceGuardian Incompatible loader version. This protected script was encoded with a newer version of SourceGuardian. Please download and install the <A HREF="https://www.sourceguardian.com/loaders/">latest loaders</A>. Error code [19] in /home/web/go/go/modules/business/paypal/model/Settings.php`

I have no sourceguardian loaded.
But even if I take the appropriate newest version (15.0.2) from their website for my php8.2-fpm I get the same error message.

**Comment by robshnup** [comment]
I close this issue, because GO-staff has updated their sourceguardian version. So I had to update too and the error was gone.
