### ISSUE TITLE
Installer bug in go/core/Installer.php

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#12]
It claims the DB is not empty, even though it is empty. Fails on this line:

line 40:

                if (count($database->getTables())) {
                        throw new Exception("Database is not empty");
                }

**Comment by gtech99** [comment]
This one is actually not a bug but is caused by the following:

set db name/user/pass in config.ini , then even if you set other values in the installer, it will still use the config.ini values. That's why we were getting the error above...but you should still make it use the installer values

**Comment by mschering** [comment]
I can't replicate this issue. Please retest in next beta after I fixed your other issues. Thanks for testing so fast! Really appreciated.
