### ISSUE TITLE
php 8.3 supported?!

### ISSUE THREAD

**Issue by gmcpaul** [Intermesh/groupoffice#1209]
hi, since im still struggling with another issue (https://github.com/Intermesh/groupoffice/issues/1205) i came up with one thing i noticed.

ubuntu 24.04 lts is equipped with php 8.3 by default, regarding to the install man its 8.1 or 8.2 
so could this be a problem with my issues.?

is php 8.3 covered or still not supported

thanks

**Comment by mschering** [comment]
Yes, 8.3 is supported by v6.8.

**Comment by gmcpaul** [comment]
thanks for the info...
well maybe the docu needs an update :D
