### ISSUE TITLE
Show BCC by default option

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#138]
When selecting this option ( Show BCC by default ) in the user settings and saving it, it has no effect when composing a new message

**Comment by pvdvendjc** [comment]
I think E-mail settings won't be saved. When testing this I get the error:
"Exception in /usr/local/share/groupoffice/go/core/data/Model.php at line 235: Can't set not existing property 'emailSettings' in 'go\core\auth\model\User'"
Also other settings on this tab will result in an error. Other tabs are working fine.

**Comment by mschering** [comment]
This is fixed now
