### ISSUE TITLE
HelpDesk

### ISSUE THREAD

**Issue by nuwohg** [Intermesh/groupoffice#148]
HelpDesk in group-office.com doesn't work anymore ->

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.due_date' in 'field list'
FeaturesCasesRoadmapNewsContactPartnersBlogAccount ▼ GET ITSUPPORT
Oops!
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.due_date' in 'field list' in /home/govhosts/intermesh.group-office.com/git/groupoffice/www/go/base/db/ActiveRecord.php:1705
Stack trace:
#0 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/go/base/data/DbStore.php(267): GO\Base\Db\ActiveRecord->find(Array)
#1 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/go/base/data/DbStore.php(487): GO\Base\Data\DbStore->createStatement()
#2 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/widget/Pager.php(89): GO\Base\Data\DbStore->getTotal()
#3 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/go/base/Model.php(65): GO\Site\Widget\Pager->getPageCount()
#4 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/widget/Pager.php(111): GO\Base\Model->__get('pageCount')
#5 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/promodules/groupofficecom/views/site/tickets/ticketlist.php(77): GO\Site\Widget\Pager->render()
#6 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Controller.php(148): require('/home/govhosts/...')
#7 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Controller.php(122): GO\Site\Components\Controller->renderFile('/home/govhosts/...', Array, true)
#8 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Controller.php(104): GO\Site\Components\Controller->renderPartial('/tickets/ticket...', Array)
#9 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/promodules/groupofficecom/controller/TicketController.php(66): GO\Site\Components\Controller->render('/tickets/ticket...', Array)
#10 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/go/base/controller/AbstractController.php(487): GO\Groupofficecom\Controller\TicketController->actionIndex(Array)
#11 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Controller.php(291): GO\Base\Controller\AbstractController->callActionMethod('actionindex', Array)
#12 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Router.php(50): GO\Site\Components\Controller->run('index', Array)
#13 /home/govhosts/intermesh.group-office.com/git/groupoffice/www/modules/site/components/Site.php(176): GO\Site\Components\Router->runController()
#14 /var/www/group-office.com/html/index.php(39): Site::launch()
#15 {main}
Error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.due_date' in 'field list'

**Comment by mschering** [comment]
This was during an upgrade I suppose. Works fine now!
