### ISSUE TITLE
7.2 and Object use

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#15]
Fatal error: Cannot use go\core\data\Object as Object because 'Object' is a special class name in /usr/share/groupoffice/go/core/data/Store.php on line 7

**Comment by mschering** [comment]
Object has been removed a while ago. Please test with the latest beta.

**Comment by gtech99** [comment]
This is from the 29-03-2018 6.3.2.tar.gz tarball

**Comment by mschering** [comment]
Yes, sorry. It only happened on php 7.2. I fixed this issue now.

If you know your way with docker you can try the new docker image with the latest git master of Group-Office: 

https://github.com/Intermesh/groupoffice-docker-development

**Comment by gtech99** [comment]
so that one is updated daily ? If so I can work with it to report/fix bugs and get this working faster

**Comment by mschering** [comment]
That's updated on every code push we make. So it's always the bleeding edge :)

**Comment by gtech99** [comment]
Are you sure that's the right file though ?

git clone https://github.com/Intermesh/groupoffice-docker-development.git

yield only a 1MB directory and when I run docker-compose up -d it eventually ends with this fatal error:

Creating db       ... error
Creating sass     ...
Creating composer ... done
ERROR: for db  Cannot create container for service db: invalid bind mount spec "/home/pulsar/groupoffice-docker-development/daCreating sass     ... done

ERROR: for db  Cannot create container for service db: invalid bind mount spec "/home/pulsar/groupoffice-docker-development/data/mysql:/var/lib/mysql:cached": invalid mode: cached
ERROR: Encountered errors while bringing up the project.

**Comment by gtech99** [comment]
nevermind, I just did a git clone from this repository and it installed fine. I'll continue reporting bugs to fix
