### ISSUE TITLE
File browser window cannot up preview window is not in full screen

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#170]
When using the popout file browser you are not able to click on the arrow that opens the preview bar.
![file browser](https://user-images.githubusercontent.com/37214605/42217163-11e03ad6-7ebc-11e8-948e-b8e454cceefa.JPG)

**Comment by dehart** [comment]
I have changed this.
![screen shot 2018-08-02 at 14 33 11](https://user-images.githubusercontent.com/3679323/43583929-3b58883e-9661-11e8-9e70-b815ed7efaa5.png)
