### ISSUE TITLE
Error on installing Billing module

### ISSUE THREAD

**Issue by pvdvendjc** [Intermesh/groupoffice#173]
When installing the billingmodule in version 6.3.21 this error-message will be generated:

Exception in /usr/local/share/groupoffice/go/base/db/ActiveRecord.php at line 3930: SQLSTATE[HY000]: General error: 1364 Field 'country' doesn't have a default value Full SQL Query: INSERT INTO `bs_books` (`user_id`,`name`,`acl_id`,`order_id_prefix`,`order_id_length`,`next_id`,`default_vat`,`currency`,`call_after_days`,`is_purchase_orders_book`,`backorder_status_id`,`delivered_status_id`,`reversal_status_id`,`addressbook_id`,`files_folder_id`,`allow_delete`,`import_status_id`,`auto_paid_status`,`import_not…re/groupoffice/go/base/controller/AbstractController.php(398): GO\Base\Controller\AbstractController->callActionMethod('actionupdate', Array) #10 /usr/local/share/groupoffice/go/base/controller/AbstractJsonController.php(290): GO\Base\Controller\AbstractController->run('update', Array, true, true) #11 /usr/local/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractJsonController->run('update', Array) #12 /usr/local/share/groupoffice/index.php(81): GO\Base\Router->runController() #13 {main}

**Comment by mschering** [comment]
I never was able to replicate this. Are you still unable to install the billing module?

**Comment by pvdvendjc** [comment]
I can't neither, somewhere the error is gone, it seems that the database installation script is changed for the field country in the table bs_books. Still the bug exists.
The country will not be filled at creation of the books. 
See the atteched PrtScreen.

![schermafdruk van 2019-01-18 15-33-06](https://user-images.githubusercontent.com/1845562/51392891-97c58900-1b36-11e9-89d8-84105273ae28.png)

**Comment by mschering** [comment]
Not sure if that's a bug. You can simply select the correct country.
