### ISSUE TITLE
Calendar time picker

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#174]
The current time picker in the calendar does not display properly see the picture.
![time picker](https://user-images.githubusercontent.com/37214605/42560069-c1418bf6-84ed-11e8-8efd-2e90a3c25d86.JPG)

Even if the screen is maximised it does not change.
Could it use something more like ![option1](https://www.queness.com/resources/images/bootstrapjs/7.jpg) or ![option2](https://camo.githubusercontent.com/4f773299dfbec4f228db2a6a410c7c2a24d6710d/687474703a2f2f692e696d6775722e636f6d2f486343464645532e706e67) as this doesn't require you to go down a very long list

**Comment by mschering** [comment]
I agree this component can be improved but for now i've just made it a bit wider.
