### ISSUE TITLE
Task linking

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#175]
There doesnt seem to be a way to get a task to link against to contact or company even when creating the task from the contact or company.

**Comment by mschering** [comment]
Via the "+" menu this works for me.

**Comment by Jonnybt4** [comment]
![task error](https://user-images.githubusercontent.com/37214605/43580478-874a8c42-964d-11e8-8ca0-6d1dafda107e.JPG)
I get this error when trying to create the link

**Comment by Jonnybt4** [comment]
It looks like this may not just be with tasks

**Comment by Jonnybt4** [comment]
https://s3.eu-west-2.amazonaws.com/bgsgo6.3/File-error-6.3.mp4

**Comment by mschering** [comment]
Do you still get this error in the latest version?
