### ISSUE TITLE
Selected message color

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#178]
Right now it's very difficult to see when a message is selected. I propose something more visible.

In style.css, around like 7507, change

    .x-grid3-row-selected {
      background-color: rgba(0, 0, 0, 0.04);

to
    .x-grid3-row-selected {
      background-color: hsla(213, 100%, 46%, 0.21);

**Comment by mschering** [comment]
I've played around with some colors but I liked grey the most. I made it a bit darker now. I hope you can live with it :)
