### ISSUE TITLE
Form elements render issue

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#180]
I believe there is an issue rendering form elements in GO 6.3.24 or possibly CSS.

Please see attached for messages rendered in another webmail client ( Afterlogic ) & Thunderbird/Outlook vs GO 6.3.24.  GO is the only one that doesn't render properly

Message #1: Afterlogic
![afterlogic](https://user-images.githubusercontent.com/15035337/43359418-4c131c2e-9270-11e8-94ec-50164e3e5c4d.JPG)

Message #1: Thunderbird
![thunderbird](https://user-images.githubusercontent.com/15035337/43359423-4c5a48d8-9270-11e8-8f9a-bade97ce3177.JPG)

Message #1: GO 6.3.24
![go6 3 24](https://user-images.githubusercontent.com/15035337/43359420-4c2e5e80-9270-11e8-8e09-2d18579bcecc.JPG)

Message #2: Afterlogic
![afterlogic_2](https://user-images.githubusercontent.com/15035337/43359419-4c2086f2-9270-11e8-99ef-7c36e58459ac.JPG)

Message #2: Outlook
![outlook_2](https://user-images.githubusercontent.com/15035337/43359422-4c475638-9270-11e8-94ef-b725fe0d722a.JPG)

Message #2: GO 6.3.24
![go6 3 24_2](https://user-images.githubusercontent.com/15035337/43359421-4c3b2bce-9270-11e8-90c3-84d524e9ea30.JPG)

**Comment by mschering** [comment]
Can you send a sample to test@intermesh.nl?

**Comment by gtech99** [comment]
sent

**Comment by mschering** [comment]
Fixed in next release
