### ISSUE TITLE
Request: move css for extjs3 tree view from projects module to global css.

### ISSUE THREAD

**Issue by derekdreery** [Intermesh/groupoffice#184]
I have a custom module that uses the extjs3 [`TreePanel`]. I think the project module also uses one of these, but the css to style it is in that module. If I add css for my module, it clashes with the projects css.

Could the css for the `TreePanel` be moved from the projects module to the global css file?

[`TreePanel`]: https://docs.sencha.com/extjs/3.4.0/#!/api/Ext.tree.TreePanel

**Comment by derekdreery** [comment]
I can't submit a PR for this because the projects module is private :)

**Comment by Jonnybt4** [comment]
From @dehart 

"Michael de Hart06-08-2018 17:28
I checked but there is no style for tree in the projects2 module.
All the style should indeed be in the global stylesheet.

The CSS and JS file are open source even in pro modules. 
Could you tell me which style definitions you are referring to?"

**Comment by lhmedia** [comment]
Diese Emailadresse ist aus Gründen zu vieler Spam-Nachrichten nicht mehr gültig. Bitte verwenden Sie das Kontaktformular auf unserer Webseite.

**Comment by derekdreery** [comment]
I believe that this is fixed, so I'll close. I'll reopen if the problem persists.
