### ISSUE TITLE
Upload of profile pics fails

### ISSUE THREAD

**Issue by applejuiceDE** [Intermesh/groupoffice#186]
I can not upload a profile picture or another company logo. Nothing happens. Running GroupOffice 6.3 on Debian9 (php7.0) using the deb-repository.

**Comment by mschering** [comment]
Check your URL property in system settings. It's probably incorrect.

**Comment by applejuiceDE** [comment]
The property is set correct. also in /etc/groupoffice/config.php is a value "host" set to "/"

**Comment by mschering** [comment]
Does the URL match the URL you have in the browser?

Can you see in the web inspector if the HTTP request fails?

**Comment by dymitar** [comment]
I have the same issue with company logo and profile picture.
There is javascript error, you can see it in the attached file.
The version is 6.3.38 on Ubuntu 16.04, installed from repository (upgraded from 6.2)
![go-error](https://user-images.githubusercontent.com/4599323/45976565-c97a8780-c04f-11e8-9a6c-b9b889bcba64.png)

**Comment by remmedia** [comment]
While uploading an profile image:

PHP message: Exception in /go/core/data/Model.php at line 235: Can't set not existing property 'contentType' in 'go\\core\\fs\\Blob'

**Comment by mschering** [comment]
Will be fixed in 6.3.42

**Comment by mschering** [comment]
Sorry, I mentioned the wrong version number. I'm releasing 6.3.43 now with the fix.
