### ISSUE TITLE
Multiple accounts generate SecurityTokenMismatch

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#187]
When you add a secondary mail account and want to view images in the secondary mail account, images don't display. 

Error message is:
GO\\Base\\Exception\\SecurityTokenMismatch in /usr/share/groupoffice/go/base/controller/AbstractController.php at line 203: Security token mismatch in route: core/downloadTempFile

**Comment by mschering** [comment]
I can't replicate this one. Do you still have this error?
