### ISSUE TITLE
Translation german

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#193]
in version 6.3 many texts are not translated in german

login dialog: Remember my login on this computer until I press logout, Forgot Username?
System settings: Groups, User defaults, General, Appeareance, Notifications, Authentication 
and and and

**Comment by TGueffroy** [comment]
I do agree. So this state of development is far away from being ready for the customers. Very sad...

Need help for translation?

**Comment by mschering** [comment]
Yes, we depend on community contributions for the translations so we have to release it without it.

**Comment by mschering** [comment]
In the next release translating will be easier:

https://groupoffice.readthedocs.io/en/latest/translations.html

**Comment by mschering** [comment]
Latest release as an update for German! Thanks peter!
