### ISSUE TITLE
Time on E-Mail module

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#194]
Under the Date column, the time is no longer displayed since version 6.3. It would be nicer to see the time of the email as before.

**Comment by mschering** [comment]
The time is only displayed for today to keep the list compact. You can always select the message to view details.

**Comment by stewert72** [comment]
I also think that this has been better in version 6.2. For me it's sometimes important to know the time of a email which was incoming yesterday. Some days I get more as 50 emails on one day. It's realy not usable to click email by email if you search an email which was incoming at a specific time. And in my opinion you can place the time in a second line directly under the date (an email entry has already a high of two lines).

**Comment by mschering** [comment]
I've added a new setting per user so they can choose if they want to use "short" dates in lists or not.
