### ISSUE TITLE
zpushadmin missing function

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#196]
In: www/modules/zpushadmin/controller/DeviceController.php:   

$response['zpushAdminFound'] = \GO\Zpushadmin\ZpushadminModule::zpushAdminFileExists();

error:
Call to undefined method GO\Zpushadmin\ZpushadminModule::zpushAdminFileExists()

**Comment by mschering** [comment]
This one is fixed in the current version.
