### ISSUE TITLE
6.2 to 6.3 upgrade

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#197]
When going through the upgrade, the following error appears, despite no Professional modules existing in the previous install

[2018-08-28T10:12:56+00:00] ErrorException in Unknown at line 0: 
The encoded file /usr/share/groupoffice/modules/savemailas/model/LinkedEmail.php requires a license file groupoffice-pro-6.3-license.txt.

**Comment by mschering** [comment]
Could you redo this with debug enabled and include a stack trace?

**Comment by rasos** [comment]
The [migration docs](https://groupoffice.readthedocs.io/en/latest/upgrade.html) do not say anything about professional modules when upgrading. I assume that when I add the license key in the groupoffice folder then any pro module can be activated again.

**Comment by thomasgg23** [comment]
I added the new 6.3 license file to the gpo folder and everything went fine with the update.

**Comment by mschering** [comment]
I'll add the info to the docs.

**Comment by michal-ambroziak** [comment]
I'm on the 6.1 professional version and want to upgrade to 6.5 open-source without professional modules. Don't have a valid licence for 6.2+. Does it mean that due to this issue I won't be able? Is there a workaround?
