### ISSUE TITLE
Specific task fields not showing

### ISSUE THREAD

**Issue by derekdreery** [Intermesh/groupoffice#199]
I have a single task not showing in a task list.

![task_display_missing](https://user-images.githubusercontent.com/1392222/45027722-20390680-b03a-11e8-866d-33cf401fa4fa.png)

This only applies to a single specific tasks, all other tasks display correctly.

I checked the JSON from the server and it seems to be in the right format, but I haven't checked it matches exactly.

This is probably a low priority.

**Comment by mschering** [comment]
Can you provide more info on this? Is it perhaps filtered out?

**Comment by derekdreery** [comment]
I'll try to debug it myself if it occurs again. Can you leave the issue open but mark it unreproducible, in case I find a solution?

**Comment by mschering** [comment]
I'll close it to keep the list clean. We'll reopen it if it happens again.
