### ISSUE TITLE
ErrorException while opening "batch edit" in ticket module

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#201]
GO Version: 6.3.36

While opening in the ticket module the "batch edit" view I get the following error:

ErrorException in /var/www/html/groupoffice-6.3.36-php-71/go/base/Observable.php at line 141: Parameter 1 to GO\Files\FilesModule::afterBatchEditStore() expected to be a reference, value given

**Comment by mschering** [comment]
This one is fixed in the next release
