### ISSUE TITLE
No more link-to field in e-mail compose 6.3

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#202]
After the upgrade to 6.3.36 the "link-to" field in the compse new e-mail dialog is gone.
Is this an error or changed in the 6.3 Version.

Professional license is installed.
![clipboard01a](https://user-images.githubusercontent.com/2633051/45204840-be1e1280-b280-11e8-8db1-d76eeb148035.jpg)

**Comment by mschering** [comment]
We removed the link to field everywhere because you can use the + button in the detail views. We plan to change email to a threaded view so you can also easily link the thread after sending an email.

**Comment by thomasgg23** [comment]
Okay. Looking forward to it.
