### ISSUE TITLE
Project linked emails

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#205]
When looking at linked emails there does not seem to be a way to see the sender and recipient on the email. This means that you have to open each email to check the details which is very difficult when the emails all have the same subject. See below.
![proj-email](https://user-images.githubusercontent.com/37214605/45613273-a8b59f00-ba5d-11e8-9449-b415ddde0c85.JPG)

**Comment by mschering** [comment]
This will be fixed in 6.3.42 today.

**Comment by Jonnybt4** [comment]
6.3.42 was released on the 9th which we have installed last week, I still have this issue. Will 6.3.43 be the release that sorts this?

**Comment by mschering** [comment]
Sorry i meant 43
