### ISSUE TITLE
Linked invoices in projects only open the in billing info pane not the grid

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#206]
When you click on a link to an invoice etc in the billing it takes you to the billing module and shows you the info (if you have the info pane open but does not highlight the correct book and invoice in the grid or tree.

**Comment by mschering** [comment]
Yes, this is hard to do because lists are not fully loaded. It loads when you scroll. So we could select the correct book but selecting the order in the list can be difficult.
