### ISSUE TITLE
6.3 - template setting

### ISSUE THREAD

**Issue by TGueffroy** [Intermesh/groupoffice#211]
As far as I can see it there are two templates in GO 6.3 - Groupoffice and Paper. Setting this to Paper  - nothing is changed. After restarting GO in the browser one cannot change back to template Groupoffice - the entry is gone - just Paper is there for using.

**Comment by mschering** [comment]
The setting in the database is still left at Group-Office. But the only theme available right now is Paper.

**Comment by TGueffroy** [comment]
OK - so it's not a bug. Thank you.


Ein freundlicher Gruß
Thomas


Am Dienstag, den 18.09.2018 um 20:07 schrieb Merijn Schering:




The setting in the database is still left at Group-Office. But the
only theme available right now is Paper.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2].





Links:
------
[1]
https://github.com/Intermesh/groupoffice/issues/211#issuecomment-422492505
[2]
