### ISSUE TITLE
Feature request: allow to create share link for folders

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#212]
It is very useful to share files as external links. Similar as in nextcloud, we would also to be able to share folders to non-GroupOffice users. 

Our current workaround: create an external file mount from nextcloud to the `/home/groupoffice/users/user/directory` folder. However, this is not very flexible nor does it respect the permissions as set in GroupOffice.

**Comment by derjoachim** [comment]
It has been possible to share files through email a long time, at least since 6.5.X. Closing this ticket.
