### ISSUE TITLE
6.3.38 Project icons

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#213]
After updating to 6.3.38 the Project icons look like they repeat now
![icons](https://user-images.githubusercontent.com/37214605/45748568-0fbf8900-bc01-11e8-8fbe-b62522d87c53.JPG)

**Comment by thomasgg23** [comment]
I had this problem in version <6.3.37 (blurry icons)
With 6.3.38 they are looking fine again (browser firefox and chrome)

Perhaps refreshing the cache of the web browser helps.

![clipboard01](https://user-images.githubusercontent.com/2633051/45817384-e8d78480-bcde-11e8-92c1-2cf59cdd6620.jpg)

**Comment by Jonnybt4** [comment]
I've upgraded to 6.3.39 and tested with cleared cache on Chrome, Firefox, Edge and Tor all have the same issue with Icons repeating.
Does "background-repeat: no-repeat;" need to be added?

**Comment by mschering** [comment]
I've added backfground-size: contain to scale the image to fit.

**Comment by Jonnybt4** [comment]
That's great but could you also add background-repeat: no-repeat; as I still get a small bit of repeat and I don't think there would ever be a time that you would want it to repeat.
