### ISSUE TITLE
making pdf in facturation module-->  link is missing

### ISSUE THREAD

**Issue by janderjander** [Intermesh/groupoffice#215]
After making a bill in the facturation module in groupoffice 6.3
the option to per view and saving the bill as pdf is missing
PDF link is missing

**Comment by mschering** [comment]
Fixed in 6.3.42

**Comment by janderjander** [comment]
hallo Merijn
een aantal malen bedankt !
gr
jander

Op 15 okt. 2018 om 07:59 heeft Merijn Schering <notifications@github.com> het volgende geschreven:

Closed #215.
