### ISSUE TITLE
Email size mismatch and error

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#217]
I have an issue with a mailbox on 6.3 showing full but the email server says it's only about half full. 
![mailbox on eserver](https://user-images.githubusercontent.com/37214605/46004506-0031bb80-c0ab-11e8-98d5-ac6e40c17e06.jpg)
![mailbox on portals](https://user-images.githubusercontent.com/37214605/46004507-00ca5200-c0ab-11e8-882e-2508c7332c70.jpg)

Also, the error provided when trying to send an email does not represent the full mailbox.
![failed to save](https://user-images.githubusercontent.com/37214605/46004525-0a53ba00-c0ab-11e8-9db1-953e7968038f.jpg)

**Comment by mschering** [comment]
Is the cron job running on the mail server to index usage?

**Comment by Jonnybt4** [comment]
Yes it is but I don't think it is working for all domains. As I calculated the size from the server and it is wrong on the mail server group office end as the mail server is 6.2 I will raise this as a ticket.
