### ISSUE TITLE
Email linking

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#218]
When you create an email from the email module or if you save an email created from a project as a draft there is no way to then link the email to a project or something else before you send it. Meaning that any responses would not be linked to the correct place.

Is there any way we could get the link option back for the email compose window?

**Comment by stewert72** [comment]
I miss that too! In V6.2 there was a extra text field while typing a new email. With this text field you could create links. That was very smart and very useful! Would be nice if this link text field will be back in the feature in V6.3.

**Comment by mschering** [comment]
This one will be fixed in the next release. Sneak preview here:

https://twitter.com/GroupOffice/status/1057949960619130885
