### ISSUE TITLE
Deleting Notes

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#220]
If you try to delete a note from the middle grid shown in the picture. 
![notes delete](https://user-images.githubusercontent.com/37214605/46069087-a3013d00-c172-11e8-9c67-22b59fd85a05.JPG)

This error is produced

![notes delete error](https://user-images.githubusercontent.com/37214605/46069115-b9a79400-c172-11e8-8c75-dd766cf651bd.JPG)

**Comment by wsmits** [comment]
Just fixed this
