### ISSUE TITLE
Notes from project

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#221]
When creating a note from a project there is no link created between them.
![project note](https://user-images.githubusercontent.com/37214605/46069442-74379680-c173-11e8-870f-c6da16287aa7.JPG)

Also, each note seems to have the following at the bottom with the time created
![project note 2](https://user-images.githubusercontent.com/37214605/46069547-b1038d80-c173-11e8-9dbf-417c2d85be9f.JPG)

**Comment by mschering** [comment]
This one is fixed in the current release
