### ISSUE TITLE
Calendar creation from grid click

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#224]
If you create a calendar event by selecting the date and time from the grid, where you click in relation to time is different than what time you select.

This picture you would expect the time to be 12 pm to 2.15pm 
![time grid](https://user-images.githubusercontent.com/37214605/46071469-fc1f9f80-c177-11e8-91f8-4d51c9d24a7a.JPG)

But it creates and event as follows
![calendar event](https://user-images.githubusercontent.com/37214605/46071734-97b11000-c178-11e8-8371-dff8eb5bd63b.JPG)

**Comment by thomasgg23** [comment]
Can confirm that error with version 6.3.38

**Comment by mschering** [comment]
Fixed in the next release (6.3.42)
