### ISSUE TITLE
Calendar reminders cannot be deletet and will multiplicated every day

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#226]
I have a daily appointment in my calendar (StandUp of our project). The reminder opens every day which is ok. If I delete the appointment entry in the reminder view all looks fine. But: next day the reminder dialog opens with two (or three?) reminders, the day after with four (or six or so)... Currently I have 8192 reminders! And I cannot delete the reminders. I'm afraid I have tomorrow more reminders again ... Problem is also that closing the reminder view or selecting all reminder entries and deleteing the reminders will be take many time (more as 10 minutes currently)

**Comment by stewert72** [comment]
I hav this problem since updating from V6.2 to V6.3. Also using the newest version V6.3.39
![reminders](https://user-images.githubusercontent.com/24894016/46132043-66e6de80-c23d-11e8-970a-03c14c33c2c0.png)

**Comment by stewert72** [comment]
After deleting the calendar entry and recreating it, it seems to work. May be this is an issue related to upgrading from latest 6.2 to 6.3

**Comment by mschering** [comment]
I can't replicate this. Please reopen if you are experiencing it again.
