### ISSUE TITLE
V6.3.39: wrong language of many entries of email context menu 

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#227]
I have german language settings. In V6.3.36 the email context menu was fine. All entries was in german. But after updating to V6.3.39 all entries (except "Delete"/"Löschen" and  "Save as"/"Speichern als") of the email context menu are in english.
![emailctxtmenu](https://user-images.githubusercontent.com/24894016/46132936-a8788900-c23f-11e8-87fa-17c803baa106.png)

**Comment by pvdvendjc** [comment]
This happens also in other modules. If you outcomment the lines 74 .. 76 in www/views/Extjs3/javascript/common.js then all translations seems to be correct.
