### ISSUE TITLE
Ticket view: Missing additional information about linked emails in email list

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#231]
GO Version 6.3.39

If the are emails are linked to a ticket the emails will be listet in the ticket view (see below)

![ticket_emails](https://user-images.githubusercontent.com/24894016/46157413-f27f6000-c27b-11e8-9cd3-63daba96187e.png)

But only email subject and date (without time) will be displayed. Without additional informations it's difficult to find the correct email if you searching an email. Additional information are for me:

* email address of the sender
* date with time

**Comment by mschering** [comment]
I've added this for the next release 6.3.42 tomorrow.
