### ISSUE TITLE
6.2 to 6.3 upgrade issue

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#232]
When upgrading to 6.3 I found cases where users which had been deleted still had a calendar somehow and it was causing primary key violations.

Solved it by running this query:
delete from su_visible_calendars where user_id not in ( SELECT id from core_user );

**Comment by mschering** [comment]
I don't see how this would help. No keys are added to this table.

Do you have the error message?

**Comment by gtech99** [comment]
I don't have it anymore, but it was complaining about user id I believe not matching. I have added the line to our version and it didn't seem to cause any adverse effects

**Comment by mschering** [comment]
Ok, i'll close this one. Just raise a new issue if you have something like this again.
