### ISSUE TITLE
Export tasks error

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#234]
When using the Export button and then Currently on screen in the tasks module the following error appears.

ErrorException in /usr/share/groupoffice/go/base/model/AbstractExport.php at line 67: Undefined index: tasks

**Comment by wsmits** [comment]
GroupOffice stores the latest grid-store query in the session and when using "Export"=>"Current screen" it uses that query from the session to run the export.

But your error message says that the session doesn't include the grid-store query for tasks.

Did you do something with the session prior you got this error message?

**Comment by Jonnybt4** [comment]
I got this error again this morning.

Logged in checked three emails and labelled them checked
Went to tasks click the box to say the task was complete
clicked export and got the error.

I then refreshed and tried to get the error again but dont seem to be able to.

**Comment by mschering** [comment]
This will be fixed in the next release.
