### ISSUE TITLE
Settings lang and Save error

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#237]
The setting > Synchronisation are language appears to be wrong
![settings](https://user-images.githubusercontent.com/37214605/46466668-d754a900-c7c3-11e8-90a5-d3da63e77260.png)

Also when I try to save the settings now I get this error
![save error](https://user-images.githubusercontent.com/37214605/46466693-e50a2e80-c7c3-11e8-8a9c-980269ed4412.png)

**Comment by mschering** [comment]
Can you retest this in the latest version?

**Comment by Jonnybt4** [comment]
Yes that fixed it
