### ISSUE TITLE
Base table or view not found: 1146 Table 'groupoffice.go_acl' doesn't exist

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#241]
When managing block in custom fields, after pressing the add button an exception occurred
 "Base table or view not found: 1146 Table 'groupoffice.go_acl' doesn't exist"

![clipboard01](https://user-images.githubusercontent.com/2633051/46498997-35fb4080-c81f-11e8-9ae3-d1108ca01b8a.jpg)

**Comment by thomasgg23** [comment]
Forget to add version is 6.3.41

**Comment by mschering** [comment]
We're planning to drop the block functionality. Do you use it?

**Comment by thomasgg23** [comment]
We are using it to group information for different departements with the same customer.
Via the ACL's you can show/don't show this to the different departments.

If you remove the function, were to the fields show off and can the fields have different acls?
