### ISSUE TITLE
Billing module: A invoice in the future will be not displayed

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#244]
1. Open Billing module
2. Create a new Invoice. Fill "Date:" and "Pay within / before:" with a date in the future
3. Save the new Invoice

Now the invoice will be not shown. I have not found a way to show the invoice in the Web-Frontend.

Workaround: setting btime, ptime, ctime an mtime of table bs_orders to a date in the past (may be only one of these fields). After that the invoice will be shown in the Web-Frontend again.

**Comment by mschering** [comment]
There's a checkbox above the status filter called "show scheduled orders":

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1314447/46671557-60f5e380-cbd5-11e8-9bca-93877e976cf2.png">

**Comment by stewert72** [comment]
I can confirm that. Thanks! :-)
