### ISSUE TITLE
StreamBuffer SSL Error when sending e-mail from ticket system

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#245]
We got the following error when sending an email from the ticket system:

ErrorException in /var/www_gpo/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 94: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Any hints?

**Comment by mschering** [comment]
Disable SSL verification if you don't have a real certificate at system settings -> notifications.

**Comment by thomasgg23** [comment]
I've checked this. 
I have four seperate e-mails installed in the mail module, which one is chosen for the ticketsystem?
There is only one field to choose a inbox.

**Comment by mschering** [comment]
The email accounts are note used. The account defined in system settings is used.
