### ISSUE TITLE
wrong path in url

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#246]
My Data is placed in a subfolder for easy backup.

.htacess of root web folder:

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /
    RewriteCond %{REQUEST_URI} !^/(.well-known/acme-challenge)
    RewriteRule ^(.*)$ /subfolder/$1

so normal access is www.domain.tld
www.doamin.tld is inside config.php and settings as admin
nevertheless some scripts are loaded as "/subfolder/views/..." instead of "/views/..." same for modules and so on

im using 6.3.42

**Comment by mschering** [comment]
Why would you use rewriting for this?

Just change the apache document root to /subfolder/

**Comment by remmedia** [comment]
change apache document root for this would be one possibility, bur rewrite is mich more flexible for backup and syncing of directory.

**Comment by mschering** [comment]
Can you try to replace PHP_SELF with SCRIPT_NAME in go/base/Config.php and see if that fixes it?

**Comment by remmedia** [comment]
No changes

**Comment by remmedia** [comment]
Might be a hint

<script type="text/javascript" src="views/Extjs3/ext/adapter/ext/ext-base-debug.js"></script><script type="text/javascript" src="views/Extjs3/ext/ext-all-debug.js"></script> is right all the time

**Comment by remmedia** [comment]
Looks good, except this one

<style>.go-menu-icon-bookmarks-id-1{background-image:url(/SUBPATH/index.php?r=core/thumb&src=public%2Fbookmarks%2FXXX.ico&w=16&h=16&security_token=OnuFdwNMDhUIEfamWjKy)}.go-menu-icon-bookmarks-id-2{background-image:url(modules/bookmarks/icons/view-pim-news.png)}.go-menu-icon-bookmarks-id-3{background-image:url(modules/bookmarks/icons/hibernate.png)}.go-menu-icon-bookmarks-id-6{background-image:url(/SUBPATH/index.php?r=core/thumb&src=public%2Fbookmarks%2FXXX%3Fkey%3Dj_c0PARP9I9PSu_NSPCfQfejuL_.ico&w=16&h=16&security_token=OnuFdwNMDhUIEfamWjKy)}.go-menu-icon-bookmarks-id-8{background-image:url(modules/bookmarks/icons/bookmark.png)}</style><style>/*
* Put custom styles here that will be applied to Group-Office. You can use the select file button to upload your logo and insert the URL in to this stylesheet.
*/

**Comment by mschering** [comment]
Will be fixed in the next release
