### ISSUE TITLE
Clearer errors

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#248]
Hi, guys

I imagine you plan to improve this already. Ive seen a few errors that are not treated, they arent so friendly.

Example attached, when user uses invalid pwd to login.

Thanks
![picturemessage_w2reil3e szl](https://user-images.githubusercontent.com/44004645/46693262-b0411180-cbdf-11e8-90c2-62209b7fe692.png)

**Comment by opensourcecompany** [comment]
Well, it should NOT disappear.
As an administrator, i like this kind of error message.
So, better show a nice/user friendly message, and with a click on "details" the original message should be still available.
