### ISSUE TITLE
Modules freezing

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#254]
6.3.42 
At least once a day I get the issue where a module will freeze (Grey out and not accept any input) This happened this morning for me on the calendar module and the only way to get it to work is to F5. 

Here are the error from this time.
![modules freezing](https://user-images.githubusercontent.com/37214605/46941160-65514f00-d062-11e8-96ea-5ec5dbc1085c.JPG)

This also happened over the weekend for one of our directors on the billing module and then later on the Projects module.
![141018 projects lock](https://user-images.githubusercontent.com/37214605/46941461-1657e980-d063-11e8-809c-6ab05a6de0a9.png)

**Comment by mschering** [comment]
Can you replicate this? I haven't seen this before.
