### ISSUE TITLE
Ticket module: Cannot write new email from ticket

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#255]
Version 6.4.42

In an active ticket I cannot open a new email with the + button in the right corner.
Opening a new task, contact, firm etc. works. All but the email.
![error1](https://user-images.githubusercontent.com/2633051/46942096-e44b8500-d06c-11e8-9827-3a03ef6c6251.jpg)

The following error is in the console.
![error2](https://user-images.githubusercontent.com/2633051/46942091-e01f6780-d06c-11e8-8453-86cf6cc8e86d.jpg)

**Comment by Jonnybt4** [comment]
I'm also getting the same error on the same version

**Comment by mschering** [comment]
Fixed in 6.3.43
