### ISSUE TITLE
Cannot resize date columns in eMail View

### ISSUE THREAD

**Issue by stewert72** [Intermesh/groupoffice#258]
In the email view I cannot change the column width of the date and "date sent" columns. If I move the mouse cursor to the column delimiter behind a date column the mouse cursor was changed (arrows to left and right). But if I press the left mouse button and move the mouse to left or right, the column will be not resized... All other columns I can resize.

GO-Version:  6.3.43
Used Browsers: Firefox and Chrome

**Comment by mschering** [comment]
Yes, this was intentional. We fixed the size because the content length is known and should fit. Or doesn't it for you?

**Comment by stewert72** [comment]
If you disable the new user option "Use short format for date and time in lists" (see at #194; thanks for the implementation :-) ) I can see only the date. For showing the time the column is too small. May be It will be a good idea to show the time in a second line below the date? Then the date column width should be ok ....

![go_datecol](https://user-images.githubusercontent.com/24894016/46998343-8e391900-d122-11e8-8e32-2f596f0e0a60.png)

**Comment by stewert72** [comment]
Ok. After removing the data from go_state table the date column width is correct. I can see now the time :-) . Short info: Before removing the table I have check if the problem existing also for another user. Seems that other users don't had this problem... However, after removing the table data it works also for me. 
You can close this ticket if you want.

**Comment by mschering** [comment]
Ok, so next update I need to reset state for everybody.

**Comment by stewert72** [comment]
Sorry, but I have the same effect again today :-( May be this occurred after toggling the "Use short format for date and time in lists" option some times ...

After "delete from go_state where name='em-pnl-west';" it works again

GO-Version: 6.3.47
