### ISSUE TITLE
Width and scrollbar problem

### ISSUE THREAD

**Issue by wsmits** [Intermesh/groupoffice#265]
When opening the user settings dialog a horizontal scrollbar is appearing.
This needs to be avoided.

It looks like this is happening because of the "Hint" text of the "Recovery e-mail" field.
![hscroll](https://user-images.githubusercontent.com/3314086/47721734-0fc79580-dc51-11e8-88d7-705519ecaa85.png)

In the Synchronization tab, the same is happening.

**Comment by mschering** [comment]
Fixed in the next release
