### ISSUE TITLE
Database check fails with "Access denied"

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#266]
Version 6.3.47 also occurred with 6.3.46

When running the database check I get the following after checking the tasklist "Access denied".

![clipboard02](https://user-images.githubusercontent.com/2633051/47731527-95a10c00-dc64-11e8-86bf-f200c0db9724.jpg)

![clipboard01](https://user-images.githubusercontent.com/2633051/47731536-99349300-dc64-11e8-850e-e853c6c0a97c.jpg)

**Comment by mschering** [comment]
Can you upgrade to the latest and rerun it with debug on and report the stack trace?

**Comment by mschering** [comment]
Thanks. This one will be fixed with the next release.
