### ISSUE TITLE
Sieve, GO Community 6.3.48

### ISSUE THREAD

**Issue by jensliebau** [Intermesh/groupoffice#268]
There seams to be a bug in GO (Community 6.3.48) while accessing Sieve filters:

These Problems show up, when you use GO as a normal user - the problems do not exist for the initial admin-account:

* When you open the mailaccount-settings. A warning does show up:
![bug_sieve_01](https://user-images.githubusercontent.com/19633649/47954309-24759780-df89-11e8-982d-79bd386fc10f.jpg)

* When you switch to "Rules" an other warning does show up:
![bug_sieve_02](https://user-images.githubusercontent.com/19633649/47954357-e2992100-df89-11e8-87bf-ab18b633f1d9.png)

* Interestingly the UI is missing some options for sieve-server for normal users. I'm not sure if this is the intended behaviour:
![bug_sieve_03](https://user-images.githubusercontent.com/19633649/47954350-c0070800-df89-11e8-98c3-42347e71440b.jpg)

**Comment by michalcharvat** [comment]
I have had similar problem after migration - problem is in invalid Sieve module permissions. Changing permissions solved the problem however maybe would be better ignore sieve when you dont have permissions (ignore silently). Tab with sieve was hidden in my case.

**Comment by mschering** [comment]
Will be fixed in the next release
