### ISSUE TITLE
Notification on recurring events 

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#269]
Each day just before one of my recurring events is due to take place I get a notification to remind me. However, this notification appears to be duplicated multiple times.

A customer emailed me over the weekend with the same issue. 

Here is a screenshot to show the issue, however, I think someone said that have this issue before but I can't seem to find it.

![nofifications](https://user-images.githubusercontent.com/37214605/47991288-a678d400-e0e1-11e8-8018-65543b187dea.PNG)

Once I delete all the notifications they don't appear until the next day. This only seems to happen with recurring events.

**Comment by mschering** [comment]
Can't replicate this one. Please contact support if still happening.
