### ISSUE TITLE
Groupoffice 5.0 (reference to ticket number 201816112)

### ISSUE THREAD

**Issue by LevadaNetcom** [Intermesh/groupoffice#272]
Hi, we found the same problem we encountered in the support ticket 201816112 inside the billing module. We created some custom fields in Invoice/Quote but when we search for one of these, the research doesn't report all the results. 
In our previous support ticket you sent us a patch, could you suggest us how to patch this section?

Thanks in advance, best regards
Alberto

![01](https://user-images.githubusercontent.com/45044143/48499046-d3428f00-e837-11e8-807f-039a53a936e4.jpg)
![02](https://user-images.githubusercontent.com/45044143/48499050-d3db2580-e837-11e8-9c5c-24f34d798103.jpg)

**Comment by mschering** [comment]
Please create a support ticket for this.
