### ISSUE TITLE
Tooltips in the way of email

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#276]
When creating an email very often the tooltips cover what you are typing even if you are not using them. Is there a way to sort this so you don't have to click into the email body twice to remove them?
![tooltips showing](https://user-images.githubusercontent.com/37214605/49018623-c866f300-f183-11e8-86f8-e9f7aeb7d8f7.PNG)

**Comment by mschering** [comment]
Fixed in the next release
