### ISSUE TITLE
download attachments as zip bug (?)

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#277]
In /usr/share/groupoffice/modules/email/controller/MessageController.php

protected function actionZipAllAttachments($params){

Is this check really necessary ? if(empty($att->content_id))

I haven't found any RFC that requires content_id to be empty for attachments and a lot of mail clients actually add a content_id for attached pieces, thus resulting in these items not being zipped by GO.

If I comment that line out this bug is resolved. Can you let me know why the check was added in the first place ?

**Comment by Shenken** [comment]
It's tricky because emails often contain logo's, icons for social media etc. These will all be zipped when you remove that check.

**Comment by gtech99** [comment]
Wouldn't it be better to check Content Disposition for this ? Usually those are displayed inline

Content-Disposition
The original MIME specifications only described the structure of mail messages. They did not address the issue of presentation styles. The content-disposition header field was added in RFC 2183 to specify the presentation style. A MIME part can have:

an inline content-disposition, which means that it should be automatically displayed when the message is displayed, or
an attachment content-disposition, in which case it is not displayed automatically and requires some form of action from the user to open it.

**Comment by mschering** [comment]
Yes, I'll do it that way thanks.
