### ISSUE TITLE
During database check

### ISSUE THREAD

**Issue by dehart** [Intermesh/groupoffice#280]
Checking 1046 GO\Calendar\Model\Event
Exception: Exception event ID can't be set to ID in /usr/local/share/git/groupoffice/www/modules/calendar/model/Event.php:513
Stack trace:
#0 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(3049): GO\Calendar\Model\Event->validate()
#1 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(4790): GO\Base\Db\ActiveRecord->save()
#2 /usr/local/share/git/groupoffice/www/modules/calendar/model/Event.php(2394): GO\Base\Db\ActiveRecord->checkDatabase()
#3 /usr/local/share/git/groupoffice/www/go/base/db/ActiveStatement.php(107): GO\Calendar\Model\Event->checkDatabase()
#4 /usr/local/share/git/groupoffice/www/go/base/Module.php(454): GO\Base\Db\ActiveStatement->callOnEach('checkDatabase')
#5 [internal function]: GO\Base\Module->checkDatabase(Array)
#6 /usr/local/share/git/groupoffice/www/go/base/ModuleCollection.php(168): call_user_func_array(Array, Array)
#7 /usr/local/share/git/groupoffice/www/controller/MaintenanceController.php(410): GO\Base\ModuleCollection->callModuleMethod('checkDatabase', Array)
#8 /usr/local/share/git/groupoffice/www/go/base/controller/AbstractController.php(487): GO\Core\Controller\MaintenanceController->actionCheckDatabase(Array)
#9 /usr/local/share/git/groupoffice/www/go/base/controller/AbstractController.php(396): GO\Base\Controller\AbstractController->callActionMethod('actioncheckdata...', Array)
#10 /usr/local/share/git/groupoffice/www/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('checkdatabase', Array)
#11 /usr/local/share/git/groupoffice/www/index.php(99): GO\Base\Router->runController()
#12 {main}Checking 1047 GO\Calendar\Model\Event

**Comment by dehart** [comment]
`Exception: Could not find relational ACL: type.acl_id (type) in GO\Projects2\Model\Project with pk: 22 in /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php:821
Stack trace:
#0 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(2629): GO\Base\Db\ActiveRecord->findRelatedAclModel()
#1 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(4341): GO\Base\Db\ActiveRecord->isAclOverwritten()
#2 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(4230): GO\Base\Db\ActiveRecord->setAttribute('type_id', '')
#3 /usr/local/share/git/groupoffice/www/go/base/db/ActiveRecord.php(4782): GO\Base\Db\ActiveRecord->__set('type_id', '')
#4 /usr/local/share/git/groupoffice/www/promodules/projects2/model/Project.php(1271): GO\Base\Db\ActiveRecord->checkDatabase()
#5 /usr/local/share/git/groupoffice/www/go/base/db/ActiveStatement.php(107): GO\Projects2\Model\Project->checkDatabase()
#6 /usr/local/share/git/groupoffice/www/go/base/Module.php(454): GO\Base\Db\ActiveStatement->callOnEach('checkDatabase')
#7 /usr/local/share/git/groupoffice/www/promodules/projects2/Projects2Module.php(450): GO\Base\Module->checkDatabase(Array)
#8 [internal function]: GO\Projects2\Projects2Module->checkDatabase(Array)
#9 /usr/local/share/git/groupoffice/www/go/base/ModuleCollection.php(168): call_user_func_array(Array, Array)
#10 /usr/local/share/git/groupoffice/www/controller/MaintenanceController.php(410): GO\Base\ModuleCollection->callModuleMethod('checkDatabase', Array)
#11 /usr/local/share/git/groupoffice/www/go/base/controller/AbstractController.php(487): GO\Core\Controller\MaintenanceController->actionCheckDatabase(Array)
#12 /usr/local/share/git/groupoffice/www/go/base/controller/AbstractController.php(396): GO\Base\Controller\AbstractController->callActionMethod('actioncheckdata...', Array)
#13 /usr/local/share/git/groupoffice/www/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('checkdatabase', Array)
#14 /usr/local/share/git/groupoffice/www/index.php(99): GO\Base\Router->runController()
#15 {main}Checking 28 GO\Projects2\Model\Project`

**Comment by mschering** [comment]
I think these are problems in your dev database.
