### ISSUE TITLE
Email notifications number

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#283]
Whilst it is helpful to know the number of emails unread at the "E-Mail" name at the top it would be more / equally helpful to know the number of unread emails per mailbox so that you don't have to go through every account to check.

As you are working on the development of 6.3 at the moment I thought it might be worth bringing this one up.

**Comment by mschering** [comment]
This was never done for performance reasons. When we refactor email we will cache all headers in the database and it will make this possible. But closing this for now as it will take time to get there.

**Comment by Lazza** [comment]
Would this be possible currently? I guess the email caching is working now.
