### ISSUE TITLE
Search Folder

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#287]
if I search for a folder in the search box and find this and click on nothing happens. the URL changes, but nothing is reloaded.

GO 6.3

**Comment by mschering** [comment]
Fixed in the next release

**Comment by drkkvfulda** [comment]
Even with the update, this does not work correctly. When I search for a folder, GO changes to the file module, but in the main view (middle column) my personal folder opens. Only in the right column are the details of the folder (Created on, created by etc.)
