### ISSUE TITLE
IMAP folder traversal problem

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#289]
If a folder has a \Noselect flag, GO 6.3.58 won't display its subfolders although they exist

* LIST (\Noselect \HasChildren) "." shared.andreea
* LIST (\HasNoChildren) "." shared.andreea.Trash

In this case, sub-folder display stops at shared.andreea although it should continue

**Comment by mschering** [comment]
Should be fixed in 6.3.68 that will come today.
