### ISSUE TITLE
Missing Features in 6.3.x

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#290]
Groups under System setting is not showing Module permissions, I don’t have any idea how to get it back in Group-Office 6.3.x well in the prevision version it’s present but in the newer version it’s missing.
![Image of Issue](http://i68.tinypic.com/9bktgx.jpg)
I found one Login message to be very handy but it’s lacks a disabling feature . How to switch off this message from system setting, a small cheek box can fix from the front end.

**Comment by mschering** [comment]
Hi,

When the login message is empty it won't display. I noticed the html editor always leaves a "<br />" tag. I will implement a checkbox for it.

The module permissions in the group dialog has not been implemented yet. There's already another issue for it: Module permissions in groups #242

**Comment by mschering** [comment]
Fixed in the next release
