### ISSUE TITLE
Disharmony between Files and Start Page

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#291]
As the title it self speaks out the problem loudly, I have created a group in which I have disabled the files to them, but the start page disrespect this choice and shows up in the options to show up in the select portlet,
![Image of Disrespecting Start page](http://i63.tinypic.com/s6t553.jpg)
I have a strong feeling that start page is behaving independently rather than it should be dependent upon the modules to show-up the various options in the select portlet.

**Comment by mschering** [comment]
Will be fixed in the next release
