### ISSUE TITLE
AccesToken created from API-Key will expire after 1 week of inactivity

### ISSUE THREAD

**Issue by pvdvendjc** [Intermesh/groupoffice#292]
When an accessToken created from an API-key will not be touched for 1 week the token will Expire and will be deleted from de database.
If you set expiresAt manually it will be overwritten every time the key is touched. So there must be another mechanism to solve this.

**Comment by pvdvendjc** [comment]
This problem still exists in version 6.4. Please provide a mechanism to set the expiration date manually at creating and modifying the key.

**Comment by mschering** [comment]
Fixed in the next 6.4 release
