### ISSUE TITLE
Go 6.3 No user in List

### ISSUE THREAD

**Issue by jostu2007** [Intermesh/groupoffice#293]
after upgrade from 6.2 to 6.3 , there is no ability to share a folder or calendar with other users  because the request to select users and groups shows only groups. 
I thought that's an upgrade issue, but it is'nt.
i installed a new instance with an empty database and there are also no users in the requester  only groups are shown.
I tried that with different php versions ( 7.0, 7,1 , 7.2 ) on several servers with the same result.
there are no errors in the log files.

**Comment by mschering** [comment]
This is probably a permissions issue. Please read this:

https://groupoffice.readthedocs.io/en/latest/system-settings/groups.html#group-defaults

**Comment by jostu2007** [comment]
That does not work properly.

If i change the "Group default", maybe add group "mygroup" and "Apply to all", the result is everone can see everyone , thats not the deal i want. 

Maybe I don't understand the principle of rights allocation in GO 6.3, but imho, something is wrong in the rights management. 
until point 3 everthing is logical for me.


So start a new try and log it:

( remove phalcon from system , because it makes problems with php 7.1, is that nessesary ? )

( install demo data [again], there is some different from the other installations -> i can see users in Point 2 )

1. login as "admin" ->add  "user1" , "user2" -> put them to internal

2. login as user "demo" -> create a new folder -> activate share -> add -> see all groups and users "elmer", "linda", "user1", "user2" -> cancel -> cancel

3. login as "admin" -> add new group "mygroup" -> put users "demo" and "user1" into "mygroup"
   remove users "demo" and "user1" from group "internal"
   set modul permissions for group "mygroup", so the users can see the needed modules

4. login as user "user1" -> create a new folder -> activate share -> add -> see groups "Everyone" "internal" "mygroup" and user "user2" 
    that makes no sence, because  
	"user2" is in group interal where is "user1" not, 
	Why can "user1" see "user2", which have no common group 

	"user1" can't see user "demo", which one is in group "mygroup" together with user "user1"
        Why can't "user1" see user "demo", they are both in the same group  ?
        Why can "user1" see group "internal" without being a member of that ?

5. login as user "demo" -> it can see "user1", "user2" and group "mygroup" but not the group "internal"
	"demo" is not member of "internal" so it should not see this group, thats ok 
	but
	"demo" see "user2" without being in the same group

**Comment by mschering** [comment]
Group member ship is not directly related. Being in the same group does not make each other visible. 

Following that link and putting everyone in the default, then click "Apply to all" should make everybody visible to each other.

**Comment by jostu2007** [comment]
that's too bad.
Maybe  we can go "back to the Future",  with this feature ;)

**Comment by mschering** [comment]
You mean to control visibility per user?

**Comment by jostu2007** [comment]
visibility per group as in Groupoffice 6.2, 

user1 is member of group1 can seen by all members of group1  and maybe  group2 (if it marked ), 
can not seen  by groups where visibilty is not marked.

or only with group affiliation

**Comment by mschering** [comment]
This has been reimplemented in 6.4
