### ISSUE TITLE
Z-Push-Admin

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#297]
GO6.3

require(dirname(__FILE__).'/../../../go/base/util/Cli.php');
and 
chdir(dirname(dirname(__DIR__)).'/z-push'); 
etc.

are wrong in the z-push-top / z-push-admin files, so commandline tool doesn't work

**Comment by weazil** [comment]
This was fixed

21-02-2019 6.3.65
ActiveSync: Fixed z-push-admin and z-push-top command line utilities

**Comment by mschering** [comment]
thanks for reporting!
