### ISSUE TITLE
6.3 grey login page

### ISSUE THREAD

**Issue by lepuil** [Intermesh/groupoffice#299]
Hello,

I contact you because I have a problem I updated to 6.3 today but after that I only have a grey screen.

I don't give you a screenshot because there's only grey it won't help;) 

I updated via softaculous and my php version is 7.0

Link : http://test.yseria.fr/

thank you for your help

**Comment by lepuil** [comment]
[16-Jan-2019 10:43:27 America/New_York] PHP Fatal error:  Uncaught Exception: SQLSTATE[28000] [1045] Access denied for user '*******'@'localhost' (using password: YES) in /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php:1681
Stack trace:
#0 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1039): GO\Base\Db\ActiveRecord->find(Array)
#1 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1003): GO\Base\Db\ActiveRecord->findSingleByAttributes(Array, false)
#2 /home/e/public_html/yseria/gestion/go/base/Session.php(276): GO\Base\Db\ActiveRecord->findSingleByAttribute('username', '******')
#3 /home/e/public_html/yseria/gestion/go/base/Session.php(140): GO\Base\Session->login('******', '*******', false)
#4 /home/e/public_html/yseria/gestion/index.php(36): GO\Base\Session->loginWithCookies()
#5 {main}
  thrown in /home/eebmfr/public_html/yseria/gestion/go/base/db/ActiveRecord.php on line 1681
[16-Jan-2019 10:43:28 America/New_York] PHP Fatal error:  Uncaught Exception: SQLSTATE[28000] [1045] Access denied for user '********'@'localhost' (using password: YES) in /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php:1681
Stack trace:
#0 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1039): GO\Base\Db\ActiveRecord->find(Array)
#1 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1003): GO\Base\Db\ActiveRecord->findSingleByAttributes(Array, false)
#2 /home/e/public_html/yseria/gestion/go/base/Session.php(276): GO\Base\Db\ActiveRecord->findSingleByAttribute('username', '*****')
#3 /home/eebmfr/public_html/yseria/gestion/go/base/Session.php(140): GO\Base\Session->login('*****', ****', false)
#4 /home/eebmfr/public_html/yseria/gestion/index.php(36): GO\Base\Session->loginWithCookies()
#5 {main}
  thrown in /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php on line 1681
[16-Jan-2019 10:43:29 America/New_York] PHP Fatal error:  Uncaught Exception: SQLSTATE[28000] [1045] Access denied for user '******'@'localhost' (using password: YES) in /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php:1681
Stack trace:
#0 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1039): GO\Base\Db\ActiveRecord->find(Array)
#1 /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php(1003): GO\Base\Db\ActiveRecord->findSingleByAttributes(Array, false)
#2 /home/e/public_html/yseria/gestion/go/base/Session.php(276): GO\Base\Db\ActiveRecord->findSingleByAttribute('username', '******')
#3 /home/e/public_html/yseria/gestion/go/base/Session.php(140): GO\Base\Session->login('*****', '*******', false)
#4 /home/e/public_html/yseria/gestion/index.php(36): GO\Base\Session->loginWithCookies()
#5 {main}
  thrown in /home/e/public_html/yseria/gestion/go/base/db/ActiveRecord.php on line 1681

**Comment by mschering** [comment]
That means the password in config.php is incorrect. Please review the database connection parameters.

**Comment by mschering** [comment]
I;m closing this one because GitHub is for bugs and not support. You seem to have an incorrect database password. If you need support from us you can get that if you obtain a pro license.
