### ISSUE TITLE
Search Folder

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#303]
Even with the update, this does not work correctly. When I search for a folder, GO changes to the file module, but in the main view (middle column) my personal folder opens. Only in the right column are the details of the folder (Created on, created by etc.)

_Originally posted by @drkkvfulda in https://github.com/Intermesh/groupoffice/issues/287#issuecomment-456540225_

**Comment by drkkvfulda** [comment]
The same problem arises when you double-click on a folder in the overview module under Folder.

**Comment by mschering** [comment]
Fixed in the next release
