### ISSUE TITLE
Issue with Administrator and User menus

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#304]
**Administrator** and **User** have different user-menu  as it’s evident in the first two images, but the options such as Help and product-info are unwanted  at the user level, and in order to hide those details at user level fails with css, so an option to hide those two entry at the user level from the system settings would be great as shown in the **fourth image**.
![1-4](https://user-images.githubusercontent.com/20767253/51615947-0d729000-1f4f-11e9-8bd9-e36718ab6455.png)

**Comment by mschering** [comment]
I disagree. Why would the manual not be useful to the user? It’s for them too. Info about the program is also relevant.

**Comment by s1-ranjan** [comment]
okay, Not any issue,
