### ISSUE TITLE
File locking not working

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#307]
File locking does not seem to work with GOTA Java or With GOTA Webdav.

**Comment by mschering** [comment]
Can you elaborate?

**Comment by Jonnybt4** [comment]
When you download a file using Gota (Java version) you get a popup that gives you the option to lock the file. If you click on it the file does not get lock so it can still be edited. 

However, if you right click on the file and choose lock then it does what it should.
