### ISSUE TITLE
Event from project

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#318]
When you create an event from a project and save the event is saved however the window freezes and greys out.

Also when you Add event the popup window then say Appointment, could they both say the same thing for continuity. Appointment sounds better to me but up to you.
![event](https://user-images.githubusercontent.com/37214605/52405673-b7abf500-2ac3-11e9-8a01-b6bc1e645111.PNG)

**Comment by Jonnybt4** [comment]
This freezes the whole system by the way and you have to refresh which then take a long time

**Comment by mschering** [comment]
This one was fixed a while ago. Closing it.
