### ISSUE TITLE
User contact informations

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#319]
Users cannot edit their own contact information. In 6.2, this went under Settings

**Comment by sirdemoncze** [comment]
This is important for E-mail templates :-(.

**Comment by mschering** [comment]
Perhaps you can use custom fields for the templates?

**Comment by sirdemoncze** [comment]
@mschering Are you planned remove contact information? Because I do not see the benefit of creating a custom field when I use (for example) a function or a phone number in the template.

**Comment by mschering** [comment]
We've discussed this and we will bring it back like it was before but optional. A user will get a profile tab with contact information. When something is entered here it will create a contact in the users address book. When it's not used then there won't be a contact.

**Comment by mschering** [comment]
Fixed in master / 6.4.
