### ISSUE TITLE
Error when enabling blocks

### ISSUE THREAD

**Issue by opensourcecompany** [Intermesh/groupoffice#324]
When trying to activate blocks in an users personal addressbook, the following sql error occurs:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'go_acl' doesn't exist

**Comment by michalcharvat** [comment]
Would be nice to provide more details like affected GO version or git commit hash of version you are running. Similar error in AB was already fixed.

**Comment by opensourcecompany** [comment]
Sorry :-)
Version: 6.3.64

**Comment by mschering** [comment]
How do you activate blocks? We took out this feature in 6.3.

**Comment by opensourcecompany** [comment]
Addressbook, Settings, select one, double click...
![enable-blocks](https://user-images.githubusercontent.com/37238981/53204251-6c4d2700-362b-11e9-8f0a-3553a54b538d.jpg)

**Comment by mschering** [comment]
This has been removed now.
