### ISSUE TITLE
Listener duplicates

### ISSUE THREAD

**Issue by sirdemoncze** [Intermesh/groupoffice#330]
Listeners that are cached are duplicated.

All events are happening twice.

![listeners](https://user-images.githubusercontent.com/32384277/53091066-43387380-3511-11e9-8ea6-8da8b22cf708.png)

**Comment by mschering** [comment]
Which version?

**Comment by sirdemoncze** [comment]
I'm sorry, 

version: **6.3.64**

**Comment by sirdemoncze** [comment]
Nothing changes in 6.3.66. Still duplicated :-(

**Comment by mschering** [comment]
It happens every time?

**Comment by sirdemoncze** [comment]
After my tests: 
- this happens after you enable or disable the module in Modules
- after run /install/upgrade.php listeners seem good

**Comment by mschering** [comment]
Will be fixed in the next release.
