### ISSUE TITLE
Mark as read shows incorrectly formatted confirmation window

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#333]
When Marking as REad, the confirmination message is spread out over two lines, and there is also a number in there. This happens in all languages

![mark as read](https://user-images.githubusercontent.com/15035337/53114850-c1494a00-3512-11e9-9567-ed4ef8bc3d84.png)

**Comment by fischli** [comment]
there is a fix inside pull request #285 for more information take a look at commit a5411ef

**Comment by gtech99** [comment]
Thank you!

**Comment by mschering** [comment]
Will be fixed in the next release
