### ISSUE TITLE
Invalid user / password not shown @ login

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#336]
When entering the wrong password, the input field becomes red but there is no error message to indicate other information to the end user. Could we display something to that effect ?

**Comment by mschering** [comment]
It's the same behaviour as anywhere. You get an info popup when you hover the mouse.

**Comment by flaviozluca** [comment]
Dear master Merijn,

With all respect, I have to agree with George. I felt the exact same and got confused, as well as customers of ours.

You know end users... :) Several here are confused with the lack of a clear error on the screen. Not everyone will rover the mouse over the to the username field (which is where it shows the label, even if pwd is wrong, it only rovers over in username field). Usually a customer panics and thinks something is broken.

Why not have a clear error on screen? Its just better/clearer usability.

Tested a few here. Gmail, IceWarp. They all show clearly on the screen the error...

![image](https://user-images.githubusercontent.com/44004645/66004233-a9f61600-e47e-11e9-8e70-73ba4710964a.png)

Its just better usability.

If not, then pls add the rover to pwd field too... but really, trust us, several cases here, users dont even rover their mouse there usally. And causes more work for us, they call, asking whats going on, etc.

Thanks,
Flavio

**Comment by rvdartel** [comment]
Error is now outputted on the screen in a dialog in 6.4

**Comment by flaviozluca** [comment]
Thanks a lot, guys!! All the best.
