### ISSUE TITLE
Bring back the "incomplete tasks" and "completed tasks" views in the displaypanel.

### ISSUE THREAD

**Issue by wsmits** [Intermesh/groupoffice#339]
These views where available in the displayPanel of GO6.2 but got lost in GO6.3
![incompleteandcomplete](https://user-images.githubusercontent.com/3314086/53164133-d506b600-35cf-11e9-8f60-3fd3aebcae01.png)

* Also maintaining the task name colors like the image above
* And show the due_date of the tasks instead of the creation date

**Comment by mschering** [comment]
Fixed in 6.4
