### ISSUE TITLE
Contact Import Match Fields Translation

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#355]
Not all fields in the Match Fields window, when CSV importing, are translated.

For example, the ZIP code field from PT-BR exists in translation but still shows as ZIP

**Comment by mschering** [comment]
Are you talking about 6.3 or 6.4?

**Comment by gtech99** [comment]
This was on 6.3.69

**Comment by mschering** [comment]
Since the whole address book is renewed in 6.4 we won't look into this for 6.3.
