### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#356]
Is there any way to turn off the auto complete in every part for the following areas:

Accounts
System Setting
Email Administration 

I keep opening users and it resets their user names, email addresses etc and the system settings changes the Portal name and lots more. Also if I go to add filters to an email account it changes the emails address too.

**Comment by Jonnybt4** [comment]
Sorry this is for 6.4.1  doesn't seem to happen any more in 6.3.67

**Comment by mschering** [comment]
Sorry, I don't understand the problem. Can you post a screenshot?
