### ISSUE TITLE
Unable to add projects 6.4.1

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#357]
When you click to add a project the templates are displayed however you cannot select one.

**Comment by Jonnybt4** [comment]
I found the issue for this was related to a custom field issue where is couldn't find a slave for the tree select, I have delete the custom field and now it allow me to add a project.

**Comment by mschering** [comment]
Strange, the slave should have been removed by the upgrade. 

I'm closing this one as I can't replicate it.
