### ISSUE TITLE
email contact search 6.4.1

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#361]
When you start typing an email address into the to or CC field it starts to search but never stops and doesn't find anything
![Capture](https://user-images.githubusercontent.com/37214605/55557130-131feb00-56e1-11e9-9a5b-0d0feceffef5.PNG)

**Comment by mschering** [comment]
Fixed in 6.4.4

**Comment by mschering** [comment]
PS: You need to run a database check with 6.4.4 after upgrading to fix the database collations

**Comment by Jonnybt4** [comment]
When will 6.4.4 be out?
