### ISSUE TITLE
address book columns  6.4.3

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#365]
There is no longer the option to add other columns to the grid just the ones in the snip
![Capture](https://user-images.githubusercontent.com/37214605/56039860-2825fb00-5d2d-11e9-9c1b-8cf5aa734ba3.PNG)

**Comment by mschering** [comment]
I've added all the flat fields of the contacts. But now that we have multiple emails, phones, addresses etc. it does not make sense to include those.
