### ISSUE TITLE
ALTER TABLE core_search ADD INDEX keywords - General error: 1709 Index column size too large.

### ISSUE THREAD

**Issue by opensourcecompany** [Intermesh/groupoffice#368]
When upgrading to the latest GO 6.3 version, installation is broken:

Excuting query: ALTER TABLE `core_search` ADD INDEX(`keywords`);
SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
Query: ALTER TABLE `core_search` ADD INDEX(`keywords`);
Package: core
Module: core
Module installed version: 57
Module source version: 58

No further proceeding, installation hangs.

**Comment by opensourcecompany** [comment]
Checking core_search:
keywords | varchar(512) | utf8mb4_general_ci
VARCHAR(512) takes 2048 (512*4) bytes using utf8mb4 -> index will fail.

**Comment by mschering** [comment]
Fixed in the next release. The size will be lowered to 192 chars.
