### ISSUE TITLE
Project custom fields 6.4.4

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#371]
Project custom fields do not fit to the window size and you have to maximise the window to be able to use many of the fields.
![proj cf](https://user-images.githubusercontent.com/37214605/56651814-cbf29d80-6681-11e9-8728-fa3f13404881.PNG)

**Comment by mschering** [comment]
But there's a scrollbar?

**Comment by Jonnybt4** [comment]
It is very difficult to be able to see the name any then edit the field at the same time. In the address book this works correctly, would it not be better to have them work the same?

**Comment by mschering** [comment]
Can you create a video? I have no such behaviour.

**Comment by mschering** [comment]
Fixed in 6.4.6
