### ISSUE TITLE
System setting > users 6.4.4

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#375]
When looking at the users area of system settings is get the following error and no users are displayed 

VM3563:2 Uncaught SyntaxError: Unexpected token E in JSON at position 1
    at JSON.parse (<anonymous>)
    at success (script.php?v= 6.4.4:1906)
    at Ext.data.Connection.handleResponse (ext-all-debug.js:4658)
    at handleTransactionResponse (ext-base-debug.js:2327)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js:2422)

**Comment by mschering** [comment]
I've improved the error logging so this error will display the invalid server response. But can you check the server error log for now?

**Comment by Jonnybt4** [comment]
[Thu Apr 25 13:07:06.312652 2019] [:error] [pid 23731] [client 80.5.45.88:57888] Error in /usr/share/groupoffice/go/core/acl/model/AclItemEntity.php at line 140: Call to a member function getPermissionLevel() on boolean, referer: https://myportal.mydomain.com/

**Comment by mschering** [comment]
I believe this is related to another error michael looked into on your demo. This will be fixed in the next release.
