### ISSUE TITLE
Star a contact not able to unstar 6.4.4

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#376]
If you "Star" a contact you are not then able to unstar a contact

**Comment by mschering** [comment]
Can't replicate this one. Please retest in 6.4.5

**Comment by Jonnybt4** [comment]
ETA on 6.4.5?

**Comment by mschering** [comment]
It's been released now.

**Comment by mschering** [comment]
There's a sorting issue not showing the stars in the list correctly. Fixed in 6.4.6
