### ISSUE TITLE
Email linking

### ISSUE THREAD

**Issue by Jonnybt4** [Intermesh/groupoffice#378]
When adding a link or many to an email the search for the link is very difficult to work with as you can choose which links you want to show. 

Would it be possible to add the link option as the global search has?

**Comment by mschering** [comment]
You can do this with the link  browser via the more menu. But it's broken in the current version. Will be fixed in the new release today.

**Comment by Jonnybt4** [comment]
Which release is this in as It's still not working for me?

**Comment by mschering** [comment]
I just checked on your portal and it seems to be working. Via the 3 dots in the menu -> open links. Then you can search through the links
