### ISSUE TITLE
ldap authenticator does not support username containing @

### ISSUE THREAD

**Issue by arminfelder** [Intermesh/groupoffice#383]
if a username contains a '@' e.g. "uid=max.mustermann@example.tld" , 
as in this case Authenticator.php:58 will produce nonsense(using "max.mustermann@example.tld@ldapDomain" as uid in the ldap search)

**Comment by mschering** [comment]
In the next release you can check "Login with email address" and it will leave the domain in.

**Comment by rasos** [comment]
Updated to GO version 6.3.76, enabling the LDAP module again.

Where can we see the check box "Login with email address" ? I can't see one at the login screen. 

And I am not able to see the LDAP settings any more in the System Settings / Authentication menu.
