### ISSUE TITLE
Installing new database in v6.4 gives an error

### ISSUE THREAD

**Issue by pvdvendjc** [Intermesh/groupoffice#385]
https://github.com/Intermesh/groupoffice/blob/8fc11d5c2e71a18e6ffd47866e1fa8c2cebcd024/www/go/core/Installer.php#L133

The ACL model is moved to go\core\model instead of go\core\acl\model.

This line has to be changed to $acl = model\Acl::findById(Group::getType()->getDefaultAclId());
to make the installation be successfull

**Comment by pvdvendjc** [comment]
The error exists in version 6.4

**Comment by mschering** [comment]
Thanks. Fixed in the next update.
