### ISSUE TITLE
Enhancement: Add GUI link to caldav calendar or carddav addressbook

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#390]
Add user facing links for CalDav calendars and CardDav address books inside GroupOffice GUI (maybe inside every calendar/address book settings area). Eliminates need to visit www.groupofficeserver.com/caldav or www.groupofficeserver.com/carddav, pass another password prompt and search trough all links to find URLs you need for importing calendars and address books into Thunderbird and other clients.

**Comment by rasos** [comment]
Most caldav or carddav clients (such as DavX for android) list alls the available calendars and addressbooks. But agree, for some use cases that link should be added.
