### ISSUE TITLE
Mail error "Null value not possible with comperator: LIKE"

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#392]
Version 6.4.21
When receiving an internal email from a scanner with the sender = null (From: <>) we are getting the following error in the mail application "Null value not possible with comperator: LIKE".

These email were working with the version 6.3.*

![image](https://user-images.githubusercontent.com/2633051/59347158-3a63eb80-8d14-11e9-9634-7766f794f1a3.png)

**Comment by mschering** [comment]
Fixed in the next release on Monday
