### ISSUE TITLE
Error in ...Acl.php - Call to a member function getUserId() on null

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#393]
After the upgrade to version 6.4.21 we are getting the following line in the apache2 error log

Error in /usr/share/groupoffice/go/core/model/Acl.php at line 275: Call to a member function getUserId() on null

Is this something we could disregard?

**Comment by mschering** [comment]
It will happen when something is called without a logged in user. Can you reproduce the error?

**Comment by mschering** [comment]
Thanks, should be fixed in 6.4.22.
