### ISSUE TITLE
No debug file in 6.4.21

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#394]
When we enable debug = true in the /etc/groupoffice/config.php the debug file won't be created. 

Are there some changes regarding the debug file in the 6.4.X version?

**Comment by mschering** [comment]
The debug is written to the browser console now.

**Comment by thomasgg23** [comment]
Okay, but this is only for the active browser.
So you can't see when a mobile client is syncing with the caldav/carddav server to find an error?

**Comment by mschering** [comment]
I will reenable the logging. I commented it out when I was doing some performance testing but it should log to allow debugging of non browser related operations. Next release will log it again.
