### ISSUE TITLE
install.php > Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'

### ISSUE THREAD

**Issue by olpo24** [Intermesh/groupoffice#396]
On installation of Version 6.4.21 I get this Error:

`PDOException in /home/www/go/go/core/db/Connection.php at line 101: SQLSTATE[42000] [1231] Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' at 2019-06-14T06:58:47+00:00

Debug dump: 

Not using cache. This will be slow!
PDOException in /home/www/go/go/core/db/Connection.php at line 101: SQLSTATE[42000] [1231] Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'
#0 /home/www/go/go/core/db/Connection.php(101): PDO->__construct('mysql:host=loca...', 'xxx', 'password', Array)
#1 /home/www/go/go/core/db/Connection.php(64): go\core\db\Connection->setPDO()
#2 /home/www/go/go/core/db/Connection.php(122): go\core\db\Connection->getPDO()
#3 /home/www/go/go/core/db/Database.php(24): go\core\db\Connection->query('SHOW TABLES')
#4 /home/www/go/go/core/db/Database.php(40): go\core\db\Database->getTableNames()
#5 /home/www/go/go/core/Installer.php(70): go\core\db\Database->getTables()
#6 /home/www/go/install/install.php(64): go\core\Installer->install(Array, Array)
#7 {main}`

Ho to resolve this?

Best regards,
Ole

**Comment by mschering** [comment]
Which version of mysql / mariadb are you running? Try removing "NO_AUTO_CREATE_USER" from that line in the code.

I will remove it anyway in the next release.

**Comment by olpo24** [comment]
MySql Version  8.0.13

In which line should I triy to remove this? All lines mentioned in debug dump do not contain "NO_AUTO_CREATE_USER"

**Comment by olpo24** [comment]
That seems to be fixed with 6.4.22

But now:

Fatal error: 
The encoded file /home/www/go/go/modules/business/wopi/Module.php requires a license file groupoffice-pro-6.4-license.txt. in Unknown on line 0
ErrorException in Unknown at line 0: 
The encoded file /home/www/go/go/modules/business/wopi/Module.php requires a license file groupoffice-pro-6.4-license.txt. at 2019-06-19T05:51:20+00:00

**Comment by mschering** [comment]
Thanks!
