### ISSUE TITLE
carddav not syncing to ios anymore

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#402]
carddav not syncing to ios anymore

v 6.4.21

6.3.x was working fine all time.

if i now login the browser via url/carddav i can see all cards but on iphone (newest os) all addressbooks are empty

**Comment by remmedia** [comment]
Got error 'PHP message: Error in /path_to_go/go/core/model/Acl.php at line 275: Call to a member function getUserId() on null'

**Comment by remmedia** [comment]
after changing to old, commented out code below addressbook sync is working again, also it now throws error on line 291

`'acl_u.userId' => isset($userId) ? $userId : App::get()->getAuthState()->getUserId()`

**Comment by mschering** [comment]
Thanks, will be fixed in 6.4.22
