### ISSUE TITLE
6.4.22 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'web36_db9.fs_folders' doesn't exist

### ISSUE THREAD

**Issue by olpo24** [Intermesh/groupoffice#406]
After a fresh installation i get this in DB Check.

Also on click on Modules in Admin i get "JsonStore load exception occurred"
I suspect that this is related.

Fehler
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'web36_db9.fs_folders' doesn't exist

Debug info:
GO\Base\Data\JsonResponse::__set_state(array(
   'data' => 
  array (
    'success' => false,
    'exceptionCode' => '42S02',
    'exceptionClass' => 'PDOException',
    'trace' => 
    array (
      0 => '#0 /home/www/go/go/core/db/Connection.php(122): PDO->query(\'SHOW FULL COLUM...\')',
      1 => '#1 /home/www/go/go/core/db/Table.php(94): go\\core\\db\\Connection->query(\'SHOW FULL COLUM...\')',
      2 => '#2 /home/www/go/go/core/db/Table.php(50): go\\core\\db\\Table->init()',
      3 => '#3 /home/www/go/go/core/db/Table.php(30): go\\core\\db\\Table->__construct(\'fs_folders\')',
      4 => '#4 /home/www/go/go/core/db/QueryBuilder.php(88): go\\core\\db\\Table::getInstance(\'fs_folders\')',
      5 => '#5 /home/www/go/go/core/db/QueryBuilder.php(277): go\\core\\db\\QueryBuilder->setTableName(\'fs_folders\')',
      6 => '#6 /home/www/go/go/core/db/QueryBuilder.php(245): go\\core\\db\\QueryBuilder->internalBuildSelect(Object(go\\core\\orm\\Query), \'\\t\')',
      7 => '#7 /home/www/go/go/core/db/QueryBuilder.php(608): go\\core\\db\\QueryBuilder->buildSelect(Object(go\\core\\orm\\Query), \'\\t\')',
      8 => '#8 /home/www/go/go/core/db/QueryBuilder.php(500): go\\core\\db\\QueryBuilder->buildSubQuery(Object(go\\core\\orm\\Query), \'\')',
      9 => '#9 /home/www/go/go/core/db/QueryBuilder.php(485): go\\core\\db\\QueryBuilder->buildToken(Object(go\\core\\orm\\Query), \'\')',
      10 => '#10 /home/www/go/go/core/db/QueryBuilder.php(595): go\\core\\db\\QueryBuilder->buildTokens(Array, \'\')',
      11 => '#11 /home/www/go/go/core/db/QueryBuilder.php(454): go\\core\\db\\QueryBuilder->buildColumn(Array, \'\')',
      12 => '#12 /home/www/go/go/core/db/QueryBuilder.php(432): go\\core\\db\\QueryBuilder->buildCondition(Array, \'\')',
      13 => '#13 /home/www/go/go/core/db/QueryBuilder.php(200): go\\core\\db\\QueryBuilder->buildWhere(Array)',
      14 => '#14 /home/www/go/go/core/db/Connection.php(410): go\\core\\db\\QueryBuilder->buildUpdate(\'addressbook_con...\', Array, Object(go\\core\\orm\\Query))',
      15 => '#15 /home/www/go/go/core/orm/Entity.php(715): go\\core\\db\\Connection->update(\'addressbook_con...\', Array, Object(go\\core\\orm\\Query))',
      16 => '#16 /home/www/go/controller/MaintenanceController.php(458): go\\core\\orm\\Entity::check()',
      17 => '#17 /home/www/go/go/base/controller/AbstractController.php(488): GO\\Core\\Controller\\MaintenanceController->actionCheckDatabase(Array)',
      18 => '#18 /home/www/go/go/base/controller/AbstractController.php(397): GO\\Base\\Controller\\AbstractController->callActionMethod(\'actioncheckdata...\', Array)',
      19 => '#19 /home/www/go/go/base/Router.php(182): GO\\Base\\Controller\\AbstractController->run(\'checkdatabase\', Array)',
      20 => '#20 /home/www/go/index.php(112): GO\\Base\\Router->runController()',
      21 => '#21 {main}',
    ),
  ),
))

**Comment by mschering** [comment]
Happens when files module is not installed. I fixed this for the next release.
