### ISSUE TITLE
loadtime script.php?v=%206.4.2x

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#407]
loadtime script.php?v=%206.4.2x is quite long sometimes (20s and more) while everthing else works blasting fast.

By the way it not seams to be cached while .css and .js files will be (css.php?v=6.4.2x won't be cached as well)

**Comment by mschering** [comment]
It's not supposed to be cached because it loads all settings of the old modules. They can change per user. It's strange that it takes that long. It usually only takes less then a second.

**Comment by mschering** [comment]
Sorry, I was wrong. script.php is supposed to be cached by the browser. I've changed this so it will be cached. But it's still wrong that it takes 20s. It takes only 200ms without caching on my Docker development environment.

**Comment by remmedia** [comment]
I have send the url via E-Mail. Can i do anything to debug Load/build Time?

**Comment by mschering** [comment]
I had replied to your email but it failed with unknown address!

To further debug this you could try to enable $config['debug']=true;
Run

tail -f debug.log

And login. The find out where exactly it hangs.

**Comment by remmedia** [comment]
can be closed, upp from 6.4.23 it loads blasting fast even without cache
