### ISSUE TITLE
6.4.23 Module > JsonStore load exception occurred

### ISSUE THREAD

**Issue by olpo24** [Intermesh/groupoffice#409]
**debug.log**

`Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:27] INIT POST /go/index.php?r=modules/module/store&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=modules/module/store
setIgnoreAclPermissions(true)
************ Model load error ************
Folder is not a module :: professional
Class  :: GO\Professional\ProfessionalModule
file  :: /home/www/go/modules/professional/ProfessionalModule.php
************ Model load error ************
Folder is not a module :: z-push
Class  :: GO\Z-push\Z-pushModule
file  :: /home/www/go/modules/z-push/Z-pushModule.php
************ Model load error ************
Folder is not a module :: modules
Class  :: GO\Modules\ModulesModule
file  :: /home/www/go/modules/modules/ModulesModule.php
************ Model load error ************
Folder is not a module :: groups
Class  :: GO\Groups\GroupsModule
file  :: /home/www/go/modules/groups/GroupsModule.php
ClassFinder find() used.
ErrorException in Unknown at line 0: <br>The encoded file <b>/home/www/go/go/modules/business/wopi/Module.php</b> requires a license file <b>groupoffice-pro-6.4-license.txt</b>.
#0 [internal function]: go\core\ErrorHandler->shutdown()
#1 {main}
Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:27] INIT POST /go/index.php?r=modules/module/store&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=modules/module/store
setIgnoreAclPermissions(true)
************ Model load error ************
Folder is not a module :: professional
Class  :: GO\Professional\ProfessionalModule
file  :: /home/www/go/modules/professional/ProfessionalModule.php
************ Model load error ************
Folder is not a module :: z-push
Class  :: GO\Z-push\Z-pushModule
file  :: /home/www/go/modules/z-push/Z-pushModule.php
************ Model load error ************
Folder is not a module :: modules
Class  :: GO\Modules\ModulesModule
file  :: /home/www/go/modules/modules/ModulesModule.php
************ Model load error ************
Folder is not a module :: groups
Class  :: GO\Groups\GroupsModule
file  :: /home/www/go/modules/groups/GroupsModule.php
ClassFinder find() used.
ErrorException in Unknown at line 0: <br>The encoded file <b>/home/www/go/go/modules/business/wopi/Module.php</b> requires a license file <b>groupoffice-pro-6.4-license.txt</b>.
#0 [internal function]: go\core\ErrorHandler->shutdown()
#1 {main}
Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:27] INIT POST /go/index.php?r=modules/module/store&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=modules/module/store
setIgnoreAclPermissions(true)
************ Model load error ************
Folder is not a module :: professional
Class  :: GO\Professional\ProfessionalModule
file  :: /home/www/go/modules/professional/ProfessionalModule.php
************ Model load error ************
Folder is not a module :: z-push
Class  :: GO\Z-push\Z-pushModule
file  :: /home/www/go/modules/z-push/Z-pushModule.php
************ Model load error ************
Folder is not a module :: modules
Class  :: GO\Modules\ModulesModule
file  :: /home/www/go/modules/modules/ModulesModule.php
************ Model load error ************
Folder is not a module :: groups
Class  :: GO\Groups\GroupsModule
file  :: /home/www/go/modules/groups/GroupsModule.php
ClassFinder find() used.
ErrorException in Unknown at line 0: <br>The encoded file <b>/home/www/go/go/modules/business/wopi/Module.php</b> requires a license file <b>groupoffice-pro-6.4-license.txt</b>.
#0 [internal function]: go\core\ErrorHandler->shutdown()
#1 {main}
Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:27] INIT POST /go/index.php?r=modules/module/store&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=modules/module/store
setIgnoreAclPermissions(true)
************ Model load error ************
Folder is not a module :: professional
Class  :: GO\Professional\ProfessionalModule
file  :: /home/www/go/modules/professional/ProfessionalModule.php
************ Model load error ************
Folder is not a module :: z-push
Class  :: GO\Z-push\Z-pushModule
file  :: /home/www/go/modules/z-push/Z-pushModule.php
************ Model load error ************
Folder is not a module :: modules
Class  :: GO\Modules\ModulesModule
file  :: /home/www/go/modules/modules/ModulesModule.php
************ Model load error ************
Folder is not a module :: groups
Class  :: GO\Groups\GroupsModule
file  :: /home/www/go/modules/groups/GroupsModule.php
ClassFinder find() used.
ErrorException in Unknown at line 0: <br>The encoded file <b>/home/www/go/go/modules/business/wopi/Module.php</b> requires a license file <b>groupoffice-pro-6.4-license.txt</b>.
#0 [internal function]: go\core\ErrorHandler->shutdown()
#1 {main}
Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:28] INIT POST /go/index.php?r=core/multiRequest&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=core/multiRequest
Controller route r=reminder/store
No default(en) language file for module "legacy/base" defined.
t.*
Controller route r=core/auth/checkclient
Is the user switched: false
Using \GO\Base\Cache\Apcu cache
[2019-06-21 12:30] INIT POST /go/index.php?r=core/multiRequest&security_token=ISO6PYrHdyepKFvg8jku
GO\Base\Observable::cacheListeners
setIgnoreAclPermissions(true)
setIgnoreAclPermissions(false)
Controller route r=core/multiRequest
Controller route r=reminder/store
No default(en) language file for module "legacy/base" defined.
t.*
Controller route r=core/auth/checkclient
Is the user switched: false`

**php error log:**
`[Fri Jun 21 12:27:58 2019] [notice] ErrorException in Unknown at line 0: <br>The encoded file <b>/home/www/go/go/modules/business/wopi/Module.php</b> requires a license file <b>groupoffice-pro-6.4-license.txt</b>.`

**Comment by rasos** [comment]
It seems you need a new license file for the pro modules.

**Comment by olpo24** [comment]
No, in my fresh install i missed the Module free for Community. There is just the adress and notes Module. So I thought i can activate the other free Modules in the admin>Modules. But when I go there the json Error comes.
How is there a nother way to activate the other free Modules?

**Comment by mschering** [comment]
Do you perhaps have display_erorrs=on ? Can you try turning it off?

**Comment by olpo24** [comment]
display_errors is off

**Comment by mschering** [comment]
I think you have some old code in your install. Please make sure you don't leave any code from older versions.

**Comment by olpo24** [comment]
It was a complete fresh installation. But I will try it again.

**Comment by olpo24** [comment]
Now I did a complete freh install again with this tarball: groupoffice-6.4.24-php-71.tar.gz

Same behavior again.

**Comment by mschering** [comment]
I think this one us fixed now in 6.4.27.

**Comment by olpo24** [comment]
I will test it tomorrow

**Comment by olpo24** [comment]
fixed with 6.4.27

Thank you
