### ISSUE TITLE
Invalid or unexpected token with script.php 6.3.78

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#412]
After the update to 6.3.78 we are getting the following error when loading the site on two servers which performed the update.

Uncaught: SyntaxError: Invalid or unexpected token (script.php?=6.3.78:1)
Uncaught TypeError: Cannot read property 'boot' of undefined at (index):65
Uncaught TypeError: Cannot read property 'isMobileOrTablet' of undefined at (index):67

Update via Ubuntu package manager and tested with browser firefox and chrome with cache emptied.

![error_groupoffice](https://user-images.githubusercontent.com/2633051/59976360-9b68aa80-95c3-11e9-9ff3-5fd9ce897282.jpg)

**Comment by thomasgg23** [comment]
Forgot to mention that the page loads fine in debug mode.

And switching back to script.php version (https://raw.githubusercontent.com/Intermesh/groupoffice/v6.3.77/www/views/Extjs3/script.php) also works fine.

**Comment by pvdvendjc** [comment]
Same problem at my servers. Mentioned workaround of Thomas solved the issue.

**Comment by mschering** [comment]
I will release 6.3.79 right away to fix this.
