### ISSUE TITLE
6.4.23 - Addressbook - Comments cannot be deleted

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#414]
When right-click to delete a comment within a contact nothing happen.
There are neither errors on the UI nor errors logged on the debug file with debug enabled.

**Comment by mschering** [comment]
Fixed in the next release.

**Comment by IT-AND-GENERAL** [comment]
Still user cannot remove or edit their own comments. Only the admin can. Is this how it is meant to be?
