### ISSUE TITLE
6.4.23 - Email - Bring back the Manage Sender Aliases

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#415]
Aliases are still there after the upgrade but not manageable from the usual place.
![Aliases](https://user-images.githubusercontent.com/52159663/60018506-70459000-9683-11e9-92a4-5306fff00e03.png)

**Comment by IT-AND-GENERAL** [comment]
GO 6.4.23
![Aliases-NotThere](https://user-images.githubusercontent.com/52159663/60022284-72abe800-968b-11e9-9ccd-f86bbf92ea06.png)

**Comment by mschering** [comment]
There should be a button next to folders. But you need manage permission on the mail module. I think this is the same as in 6.2.

**Comment by IT-AND-GENERAL** [comment]
I have manage permission on the email account where I want to see the aliases. This came from the 6.2 migration. Do I need Manage permission for the whole module now?

**Comment by mschering** [comment]
You've always needed manage permissions for the module to do this indeed.
