### ISSUE TITLE
6.4.24 Calendar e-mail invitations are not send

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#423]
When trying to send an invitation from the calendar module to an external contact I always get the error "Connection could not be established with host localhost (Connection refused #111)" (see screenshot)

I double checked my e-mail settings but cannot find an entry with localhost settings.

![Connection_refused_email](https://user-images.githubusercontent.com/2633051/60251615-24842800-98c9-11e9-8a9e-378c221e6edd.jpg)

Debug file:
Sending e-mail to (external contact)
EXCEPTION: Swift_TransportException: Connection could not be established with host localhost [Connection refused #111] in /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269
Stack trace:
#0 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#2 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /usr/share/groupoffice/go/base/mail/Mailer.php(112): Swift_Mailer->send(Object(GO\Base\Mail\Message), Array)
#4 /usr/share/groupoffice/modules/calendar/model/Event.php(2525): GO\Base\Mail\Mailer->send(Object(GO\Base\Mail\Message))
#5 /usr/share/groupoffice/modules/calendar/controller/AttendanceController.php(77): GO\Calendar\Model\Event->replyToOrganizer()
#6 /usr/share/groupoffice/go/base/controller/AbstractController.php(488): GO\Calendar\Controller\AttendanceController->actionSubmit(Array)
#7 /usr/share/groupoffice/go/base/controller/AbstractController.php(397): GO\Base\Controller\AbstractController->callActionMethod('actionsubmit', Array)
#8 /usr/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('submit', Array)
#9 /usr/share/groupoffice/index.php(112): GO\Base\Router->runController()
#10 {main}
Swift_TransportException in /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 269: Connection could not be established with host localhost [Connection refused #111]
#0 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#2 /usr/share/groupoffice/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /usr/share/groupoffice/go/base/mail/Mailer.php(112): Swift_Mailer->send(Object(GO\Base\Mail\Message), Array)
#4 /usr/share/groupoffice/modules/calendar/model/Event.php(2525): GO\Base\Mail\Mailer->send(Object(GO\Base\Mail\Message))
#5 /usr/share/groupoffice/modules/calendar/controller/AttendanceController.php(77): GO\Calendar\Model\Event->replyToOrganizer()
#6 /usr/share/groupoffice/go/base/controller/AbstractController.php(488): GO\Calendar\Controller\AttendanceController->actionSubmit(Array)
#7 /usr/share/groupoffice/go/base/controller/AbstractController.php(397): GO\Base\Controller\AbstractController->callActionMethod('actionsubmit', Array)
#8 /usr/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('submit', Array)
#9 /usr/share/groupoffice/index.php(112): GO\Base\Router->runController()
#10 {main}

**Comment by mschering** [comment]
Please review your System Settings -> Notifications.

**Comment by thomasgg23** [comment]
Okay that part I forgot to check.
I thought the calendar notifications are send with the user e-mail account.

After the right configuration of the notification settings, everything works.
Thanks
