### ISSUE TITLE
Systemsettings -> Modules not loading

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#427]
Auf dem Webserver ist ein Fehler aufgetreten. Kontaktieren Sie bitte Ihren Systemadministrator und senden Sie ihm die Fehlerbeschreibung.

JsonStore load exception occurred

Version: 6.4.25

**Comment by olpo24** [comment]
same as in [#409](https://github.com/Intermesh/groupoffice/issues/409)

**Comment by mschering** [comment]
Might be the same. Please supply the detailed error.
