### ISSUE TITLE
6.4.27 Calendar Grid is missing on Dektop

### ISSUE THREAD

**Issue by olpo24** [Intermesh/groupoffice#432]
![image](https://user-images.githubusercontent.com/48469242/60595338-16da1100-9da7-11e9-9bc3-d7d51af78d71.png)

**Comment by mschering** [comment]
Looks like your CSS was not built correctly. Try rerunning install/upgrade.php

**Comment by olpo24** [comment]
After rerunning install/upgrade und clear bwoser cache this grid is there. Thanks
