### ISSUE TITLE
New user addressbook bug

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#434]
It appears there's a bug when adding new users and their addressbooks:

GO appears to add a contact for each user, and this contact is only visible in ab_contacts table, and it creates the relation between the Addressbook and the User. Here are the two bugs, present in 6.3.80:

1. When adding a new user via GUI, the new contact gets created in ab_contacts but with column go_user_id set to 0 which causes the relation to fail and several features don't work because of this

2. When adding a user via jmap, the createContact() function in go/base/model/User.php never gets called so the same bug gets triggered again

**Comment by mschering** [comment]
Strange, GO 6.3 does not create a contact. It didn't in v6.2. Because people were missing that it has been re-added in GO 6.4.
Are you sure newly created users in 6.3 create a contact?

**Comment by gtech99** [comment]
yes, when you add a new user via GUI it also adds an entry in ab_contacts table but it's non-functional since it has go_user_id 0, if you set it manually to the user's ID then related functions start working, for example adding new contact from e-mail

**Comment by gtech99** [comment]
we add all of our users via JMAP and when we do that, no contact gets created but also the add new contact from e-mail feature is not-functional, because it checks for a contact...

In: modules/addressbook/model/Contact.php

if(\GO::user() && \GO::user()->contact){
                        $ab = Addressbook::model()->getDefault(\GO::user());
                }

**Comment by mschering** [comment]
If you want to create a contact together with a user I recommend to use 6.4. Because in 6.3 it's not supposed to create a contact at all.

In 6.4 you can post all contact properties as a "profile" property of the user.

**Comment by gtech99** [comment]
I don't need to create a contact at all, but at least one feature is affected by this.
When you lookup an e-mail address in Addressbook and it doesn't exist, and then you choose to create a new contact, that fails with an error message.

The reason is this:
In: modules/addressbook/model/Contact.php

if(\GO::user() && \GO::user()->contact){
$ab = Addressbook::model()->getDefault(\GO::user());
}

It checks if GO::user()->contact is set... since it's not set, the entire feature doesn't work.

So at least in 6.3 you need to disable that check I think

**Comment by mschering** [comment]
Could you upgrade to 6.4 and test this?
