### ISSUE TITLE
6.4.27 - Address book - Add organization - cosmetic issues

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#436]
The title show contact instead of Organization
There is a filed to add a Job title. Should this be a company other name or second name or perhaps trade name.
![Org](https://user-images.githubusercontent.com/52159663/60680499-7a397100-9e83-11e9-847e-acdbdef8bdd2.png)

**Comment by mschering** [comment]
I;m chaning jobTitle into LOB which stands for Line Of Business.
