### ISSUE TITLE
6.4.29 E-Mail keeps parsing content

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#440]
When I open an email with an *.ics file groupoffice shows an error "This parser only supports VCARD and VCALENDAR files", but it doesn't open the mail e-mail itself.
It seems like it stop parsing the e-mail and don't show the content.

![e_mail_gpo](https://user-images.githubusercontent.com/2633051/60987549-1959df00-a342-11e9-97d9-3d3ed1a4b209.jpg)

In Thunderbird I can read the e-mail and download the *.ics attachment.

![e_mail_thunderbird](https://user-images.githubusercontent.com/2633051/60987554-1ced6600-a342-11e9-8a84-98af3adec534.jpg)

**Comment by mschering** [comment]
Could you send me the ics file causing this?

**Comment by thomasgg23** [comment]
Sent you the ics to your e-mail.
Error still exists with version 6.4.43

**Comment by mschering** [comment]
Will be fixed in 6.4.50
