### ISSUE TITLE
6.4.29 Html parsing description field in tasks module

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#441]
There seems to be a parsing error with line breaks in the "preview" of the description field in the tasks module. Didn't check other formatting errors.

![html_parsing](https://user-images.githubusercontent.com/2633051/60989151-773bf600-a345-11e9-968b-c2bae57f4f79.jpg)

![html_parsing2](https://user-images.githubusercontent.com/2633051/60989160-799e5000-a345-11e9-8bb4-f7c209a6d960.jpg)

**Comment by mschering** [comment]
Fixed in 6.4.31
