### ISSUE TITLE
6.4.36 E-Mail created from task with wrong address

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#443]
When I create a task with the description test@test.de and click on the e-mail address inside the description field with the option to create a new e-mail.
The to address will only show an "e" inside the to header.

![image](https://user-images.githubusercontent.com/2633051/61720530-3d1c1c80-ad67-11e9-983b-e7bb7a52010a.png)

**Comment by IT-AND-GENERAL** [comment]
I can confirm the issue.
This happen also when reading an email that contain an email address in its body.
When I click on the email address to compose a new email I just get a one character of the email instead of the full email.

**Comment by mschering** [comment]
Fixed in the next release
