### ISSUE TITLE
Search in Email with 2 strings

### ISSUE THREAD

**Issue by donat1** [Intermesh/groupoffice#444]
Searching in Group-Office in the search field (not the extended search function) with 2 strings give this error:

count(): Parameter must be an array or an object that implements Countable

**Comment by mschering** [comment]
Can you explain in detail how you get this error?

**Comment by donat1** [comment]
Yeah
When searching in the email-modul over all text with "öäü" I get this error. Or when I search with two words with a space like "don test", then I get this error also.

**Comment by thomasgg23** [comment]
Can confirm that error message, when searching in the e-mail module with search "whole message" selected.

![Clipboard02](https://user-images.githubusercontent.com/2633051/63180145-eea02c00-c04d-11e9-9fb8-ff8b2b502025.jpg)

**Comment by mschering** [comment]
Fixed in 6.4.54
