### ISSUE TITLE
Several migration issues from 6.3 to 6.4

### ISSUE THREAD

**Issue by opensourcecompany** [Intermesh/groupoffice#446]
IGNORING: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'addressbook_email_address' from query: ALTER TABLE `addressbook_email_address` CHANGE `id` `id` INT(11) NOT NULL;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists
Query: ALTER TABLE `addressbook_email_address` DROP PRIMARY KEY;
Package: community
Module: addressbook
Module installed version: 10
Module source version: 11

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists from query: ALTER TABLE `addressbook_email_address` DROP PRIMARY KEY;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists
Query: ALTER TABLE `addressbook_email_address` DROP `id`;
Package: community
Module: addressbook
Module installed version: 11
Module source version: 12

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists from query: ALTER TABLE `addressbook_email_address` DROP `id`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists
Query: ALTER TABLE `addressbook_phone_number` DROP `id`;
Package: community
Module: addressbook
Module installed version: 13
Module source version: 14

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists from query: ALTER TABLE `addressbook_phone_number` DROP `id`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists
Query: ALTER TABLE `addressbook_date` DROP `id`;
Package: community
Module: addressbook
Module installed version: 14
Module source version: 15

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists from query: ALTER TABLE `addressbook_date` DROP `id`;

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'addressbook_url'
Query: ALTER TABLE `addressbook_url` CHANGE `id` `id` INT(11) NOT NULL;
Package: community
Module: addressbook
Module installed version: 16
Module source version: 17

IGNORING: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'addressbook_url' from query: ALTER TABLE `addressbook_url` CHANGE `id` `id` INT(11) NOT NULL;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists
Query: ALTER TABLE `addressbook_url` DROP PRIMARY KEY;
Package: community
Module: addressbook
Module installed version: 17
Module source version: 18

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists from query: ALTER TABLE `addressbook_url` DROP PRIMARY KEY;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists
Query: ALTER TABLE `addressbook_url` DROP `id`;
Package: community
Module: addressbook
Module installed version: 18
Module source version: 19

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists from query: ALTER TABLE `addressbook_url` DROP `id`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists
Query: ALTER TABLE `addressbook_address` DROP `id`
Package: community
Module: addressbook
Module installed version: 20
Module source version: 21

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'id'; check that column/key exists from query: ALTER TABLE `addressbook_address` DROP `id`

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'core_acl_ibfk_1'; check that column/key exists from query: ALTER TABLE `core_acl` DROP FOREIGN KEY `core_acl_ibfk_1`;

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'salutationTemplate'
Query: ALTER TABLE `addressbook_user_settings` ADD `salutationTemplate` TEXT NOT NULL AFTER `defaultAddressBookId`, ADD `sortBy` ENUM('name','lastName') NOT NULL DEFAULT 'name' AFTER `salutationTemplate`;
Package: community
Module: addressbook
Module installed version: 24
Module source version: 25

IGNORING: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'salutationTemplate' from query: ALTER TABLE `addressbook_user_settings` ADD `salutationTemplate` TEXT NOT NULL AFTER `defaultAddressBookId`, ADD `sortBy` ENUM('name','lastName') NOT NULL DEFAULT 'name' AFTER `salutationTemplate`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_user_ibfk_2'; check that column/key exists
Query: ALTER TABLE `bookmarks_bookmark` DROP FOREIGN KEY `bookmarks_user_ibfk_2`;
Package: community
Module: bookmarks
Module installed version: 2
Module source version: 3

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_user_ibfk_2'; check that column/key exists from query: ALTER TABLE `bookmarks_bookmark` DROP FOREIGN KEY `bookmarks_user_ibfk_2`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_category_user_ibfk_2'; check that column/key exists
Query: ALTER TABLE `bookmarks_category` DROP FOREIGN KEY `bookmarks_category_user_ibfk_2`;
Package: community
Module: bookmarks
Module installed version: 5
Module source version: 6

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_category_user_ibfk_2'; check that column/key exists from query: ALTER TABLE `bookmarks_category` DROP FOREIGN KEY `bookmarks_category_user_ibfk_2`;

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_category_ibfk_2'; check that column/key exists
Query: ALTER TABLE `bookmarks_category` DROP FOREIGN KEY `bookmarks_category_ibfk_2`;
Package: community
Module: bookmarks
Module installed version: 6
Module source version: 7

IGNORING: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'bookmarks_category_ibfk_2'; check that column/key exists from query: ALTER TABLE `bookmarks_category` DROP FOREIGN KEY `bookmarks_category_ibfk_2`;

Also the calendar is broken, not possible to show or add a date:
parameter calendar is missing

**Comment by mschering** [comment]
These errors can be ignored and should cause no harm.

**Comment by rasos** [comment]
@mschering We are stuck in the upgrade process due to a syntax error. 

Running mysql  Ver 14.14 Distrib 5.7.27 on Ubuntu. MariaDB is no option here (not available for i686). 

```
Upgrading Group-Office

Skipping module blacklist because it's not available.
Skipping module dokuwiki because it's not available.
Skipping module ispconfig3 because it's not available.
[core/core] Excuting query: ALTER TABLE `core_search` CHANGE `description` `description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;
core/core updated from 115 to 116
[community/addressbook] Running callable function
Migrating custom fields
ALTER TABLE addressbook_contact_custom_fields ADD `col_1` double NULL,
ADD `col_2` date NULL,
ADD `col_3` double NULL,
ADD `col_4` mediumtext(16777216) NULL,
ADD `col_5` double NULL,
ADD `col_6` tinyint(1) NOT NULL DEFAULT FALSE,
ADD `col_11` varchar(50) NOT NULL DEFAULT '',
ADD `col_23` varchar(50) NOT NULL DEFAULT '',
ADD `col_24` varchar(50) NOT NULL DEFAULT '',
ADD `col_25` varchar(50) NOT NULL DEFAULT '',
ADD `col_26` varchar(50) NOT NULL DEFAULT '',
ADD `col_27` varchar(50) NOT NULL DEFAULT '';

Error: PDOException in /usr/share/groupoffice/go/core/db/Connection.php at line 127: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777216) NULL,
ADD `col_5` double NULL,
ADD `col_6` tinyint(1) NOT NULL DEFAUL' at line 4

#0 /usr/share/groupoffice/go/core/db/Connection.php(127): PDO->query('ALTER TABLE add...')
#1 /usr/share/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php(141): go\core\db\Connection->query('ALTER TABLE add...')
#2 /usr/share/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php(107): go\modules\community\addressbook\install\Migrate63to64->mergeCompanyCustomFields()
#3 /usr/share/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php(42): go\modules\community\addressbook\install\Migrate63to64->migrateCustomFields()
#4 /usr/share/groupoffice/go/modules/community/addressbook/install/updates.php(11): go\modules\community\addressbook\install\Migrate63to64->run()
#5 [internal function]: go\core\Installer->{closure}()
#6 /usr/share/groupoffice/go/core/Installer.php(480): call_user_func(Object(Closure))
#7 /usr/share/groupoffice/go/core/Installer.php(314): go\core\Installer->upgradeModules()
#8 /usr/share/groupoffice/install/upgrade.php(45): go\core\Installer->upgrade()
#9 {main}
```

**Comment by rasos** [comment]
We were able to continue the upgrade process by patching the migration script `/usr/share/groupoffice/go/modules/community/addressbook/install/Migrate63to64.php`

        //              $this->mergeCompanyCustomFields();

**Comment by mschering** [comment]
Fixed in the next update. Please don't disable that feature or you will be missing your company custom fields.
