### ISSUE TITLE
6.4.46 - Calendar - Error accepting invite from other GO user when sent from a mobile phone

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#451]
FROM DEBUG FILE:

Using \GO\Base\Cache\Disk cache
[2019-08-28 17:26] INIT POST /index.php?r=calendar/event/acceptInvitation&security_token=6RmXUqPlwKYJk7EntBOx
Controller route r=calendar/event/acceptInvitation
imap::connect(172.16.0.1, 143, john, ***, , )
Use capability from login
Selecting IMAP mailbox INBOX
get_message_part_decoded(306321, 2, base64, )
#### EVENT BEFORE SAVE ####
Using \GO\Base\Cache\Disk cache
[2019-08-28 17:26] INIT POST /index.php?r=email/message/view&security_token=6RmXUqPlwKYJk7EntBOx
Controller route r=email/message/view
imap::connect(172.16.0.1, 143, john, ***, , )
Use capability from login
Selecting IMAP mailbox INBOX
get_message_part_decoded(306321, 1.2, quoted-printable, utf-8)
get_message_part_decoded(306321, 2, base64, )
Event 'go\modules\community\addressbook\model\Contact::filter' calls listener go\modules\business\newsletters\Module::onContactFilter
Using \GO\Base\Cache\Disk cache
[2019-08-28 17:26] INIT GET /index.php?r=calendar/attendance/load&security_token=6RmXUqPlwKYJk7EntBOx&_dc=1567009577465&tmp_files=&id=989&security_token=6RmXUqPlwKYJk7EntBOx
Controller route r=calendar/attendance/load
EXCEPTION: Exception: The participant of this event is missing in groupoffice-6.4.46-php-71/modules/calendar/controller/AttendanceController.php:21
Stack trace:
#0 groupoffice-6.4.46-php-71/go/base/controller/AbstractController.php(488): GO\Calendar\Controller\AttendanceController->actionLoad(Array)
#1 groupoffice-6.4.46-php-71/go/base/controller/AbstractController.php(397): GO\Base\Controller\AbstractController->callActionMethod('actionload', Array)
#2 groupoffice-6.4.46-php-71/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('load', Array)
#3 groupoffice-6.4.43-php-71/index.php(88): GO\Base\Router->runController()
#4 {main}
Exception in groupoffice-6.4.46-php-71/modules/calendar/controller/AttendanceController.php at line 21: The participant of this event is missing
#0 groupoffice-6.4.46-php-71/go/base/controller/AbstractController.php(488): GO\Calendar\Controller\AttendanceController->actionLoad(Array)
#1 groupoffice-6.4.46-php-71/go/base/controller/AbstractController.php(397): GO\Base\Controller\AbstractController->callActionMethod('actionload', Array)
#2 groupoffice-6.4.46-php-71/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('load', Array)
#3 groupoffice-6.4.43-php-71/index.php(88): GO\Base\Router->runController()
#4 {main}

**Comment by IT-AND-GENERAL** [comment]
See issue #424

**Comment by mschering** [comment]
Please retest this in the 6.5.87. This one should be fixed.
