### ISSUE TITLE
6.4.46 - Add Cronjobs - JsonStore load exception occurred

### ISSUE THREAD

**Issue by mischoe** [Intermesh/groupoffice#454]
When trying to add a cron job there is a "JsonStore load exception occurred" when trying to open the dropdown for a new action.

**Comment by mschering** [comment]
Can you check the server error log to find out what the error is?

**Comment by mischoe** [comment]
Errors attached… Top is the newest (and exported after the forced error)

**Comment by mischoe** [comment]
error is gone
