### ISSUE TITLE
Setting reminder to no sets it to zero minutes 

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#456]
In the personal setting you can set the event reminder length to "no reminder". However, this seems to be stored as zero, at least it is displayed as 0 minutes in the settings and at each new event. So I am reminded when the event starts, instead of being quiet.

![Bildschirmfoto_2019-09-02_15-24-11](https://user-images.githubusercontent.com/485723/64118255-8ebcbb80-cd97-11e9-8f73-1fa8cdb13683.png)

**Comment by mschering** [comment]
Fixed in the next release.
