### ISSUE TITLE
6.4.51 Address-Book Filter doesn't work in Email-Modul

### ISSUE THREAD

**Issue by donat1** [Intermesh/groupoffice#458]
The individual made Address-Book-Filter in the email-modul does not filter any addresses. So when choosing email-addresses with the plus button and then make a choice with the filter, all addresses are still displayed.

**Comment by donat1** [comment]
The filter works in the address book, but not in the email-module, when searching in the "email to" field with address filter.

**Comment by mschering** [comment]
What are the filter settings? I'll try to create the same filter.

**Comment by donat1** [comment]
Okay. I've made a screenshot as attached.
![2019-09-13 10_10_56-Start](https://user-images.githubusercontent.com/6271832/64847329-0e0b8400-d60f-11e9-9502-461b1b616913.png)

**Comment by mschering** [comment]
I can't replicate this. Please contact support if still having issues.
