### ISSUE TITLE
e-mail-settings

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#461]
save e-mail-settings of mailbox gives `Undefined index: name` error

some values are saved but especially filters are not

**Comment by mschering** [comment]
I can't reproduce. Can you test in 6.4.54?

**Comment by remmedia** [comment]
depends sieve server, on one it is working on the other not.
cli sieve-connect is working on both

**Comment by remmedia** [comment]
might be something else the error occurs whenever you save something in email settings. all other settings are saved regardless to the error, only filterroules are not saved

**Comment by mschering** [comment]
It was because your top mail rule doesn't have a name set like:

# rule:[Out of office]

I fixed that for the test user and also worked around it in the code.
