### ISSUE TITLE
6.4.54 - Billing - Street 2 on Addressbook became No.: on Quotes or Invoices

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#465]
Street 2 of Organization in the Addressbook became No.: on Quotes or Invoices and it is added to the same line of the address.

Please keep "Street 2" or make two or more lines for address as a typical UK address have many lines for House Name or Business Park name etc

**Comment by mschering** [comment]
Fixed for next release.
