### ISSUE TITLE
"Hamburger menu" in notes module don't work

### ISSUE THREAD

**Issue by alessandrogagliano** [Intermesh/groupoffice#466]
Version: 6.4.55

Description:
"Hamburger menu" in notes module don't work in mobile view

Possible fix:
File: go/modules/community/notes/views/extjs3/MainPanel.js

Row: 172
	cls: 'go-narrow',
	iconCls: "ic-menu",
	handler: function () {
//		this.westPanel.getLayout().setActiveItem(this.noteBookGrid);
//		this.noteBookGrid.show();
		this.sidePanel.show();
	},

**Comment by rvdartel** [comment]
Problem is now fixed thanks for pointing out the location aswell.
