### ISSUE TITLE
Logout button is not working

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#467]
I have tried numerous versions of Group Office such as 6.4.46,6.4.53, 6.4.56 and all of this have one common issue Logout button don't log out user, where as it brings back to the start page.

**Comment by mschering** [comment]
Did you perhaps login with a http authentication dialog in the browser? This can't be logged out. Only by closing the browser.

**Comment by s1-ranjan** [comment]
Yes you are correct I made my login with the http dialog in browser, as you mentioned it is not possible to logout without closing the browser, then it would be great to trigger a popup message asking user to close the browser.
 I hope this can be a good way to avoid confusion among new users at user point.
