### ISSUE TITLE
Emails Date format is not obaing the user time zone

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#468]
Under email date of emails are following +2 hrs time zone where as it should follow user defined time zone in order to avoid confusion with the mails date and time.
![time-issue](https://user-images.githubusercontent.com/20767253/65216847-dd749000-dacf-11e9-8532-69e3e9fe758c.png)

**Comment by mschering** [comment]
Which version is this? I can't replicate it on the latest 6.4

**Comment by s1-ranjan** [comment]
Now it is working normally as it is expected, I think issue was caused by the local cased file, when I cleared the case and reopening the browser fixed my problem

**Comment by mschering** [comment]
Strange, it can't be the local cache since this date is formatted server side. In the new framework it's formatted client side.
But anyway, I will close this one then.
