### ISSUE TITLE
Request for a new theme

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#469]
Although the theme provided with group office 6.3 onward is great, but it have a thick panel at the top, so why not to include a thin panel based theme, I am including a screenshot about how it will look like
![New-Theme-request](https://user-images.githubusercontent.com/20767253/65314101-38cb7e80-dbb3-11e9-9f60-9825c1f865e9.png)
Please let me know about this suggestion

**Comment by rvdartel** [comment]
Then we would have a problem with the logo not being able to fit in the top left corner.

**Comment by s1-ranjan** [comment]
I think we can go with two types of logos one with rectangular shape and other with square shape, large rectangular logo can be assigned to the default theme where as square shaped logo can be assigned to the new Thin theme, this is what I can think of now.

**Comment by mschering** [comment]
We will look into making the bar smaller later.

**Comment by mschering** [comment]
Coming to 6.5:

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/1314447/95759617-3bab7c80-0caa-11eb-8834-33d81699f1cd.png">
