### ISSUE TITLE
6.4.58 - Core - Google authenticator code asked at login also when not enabled

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#470]
Some users have no Google authentication enable but after the upgrade to 6.4.58 a code is asked regardless with the result these users cannot login at the moment.

Please resolve asap

**Comment by mschering** [comment]
I don't know how this situation came about. But you can fix it by deleting the entries in google auth_secret or by disabling GA as admin.

**Comment by mschering** [comment]
Found the problem. Will release a new version immediately.
