### ISSUE TITLE
serverclient account creation issue

### ISSUE THREAD

**Issue by svenvogel** [Intermesh/groupoffice#471]
Hi Merijn,

i use the serverclient plugin for postfix. it seems it is broken since any versions.

my actually version are 6.4.48

if i create my account with the serverclient settings i get an error. the account will be created but not the email in the serverclient module.

![image](https://user-images.githubusercontent.com/5433844/65588274-89622380-df87-11e9-8e4e-c856be923677.png)

i tried different pathes /etc/groupoffice/globalconfig.inc.php or config.php in the htdocs directory.

```bash
$config["serverclient_token"]='123456789';
$config["serverclient_server_url"]='https://192.168.102.104/';
$config["serverclient_domains"]='example.de';
$config["serverclient_mbroot"]='';
$config["serverclient_use_ssl"]='1';
$config["serverclient_novalidate_cert"]='0';
$config["serverclient_host"]='localhost';
$config["serverclient_port"]=143;
$config["serverclient_smtp_host"]='localhost';
$config["serverclient_smtp_port"]=25;
$config["serverclient_smtp_encryption"]='';
$config["serverclient_smtp_username"]='';
$config["serverclient_smtp_password"]='';
```

there are any changes or hints?

Cheers

Sven

**Comment by mschering** [comment]
I've improved the error reporting on this. Please try with the next release and see if the error is clear. Also try to enable debug and look at the log.

**Comment by svenvogel** [comment]
Sounds good. i will check and come back.

**Comment by svenvogel** [comment]
Hi Merjin,

i am now in version 6.4.67

![image](https://user-images.githubusercontent.com/5433844/67013832-0babb680-f0f4-11e9-94c4-aa9c177ea47e.png)

i get the following error.

```bash
[Thu Oct 17 15:30:43.428286 2019] [php7:notice] [pid 2596] [client XXXXXXX:57880] GO\\Base\\Exception\\AccessDenied in /mnt/active/www/webmail.qform.de/htdocs/modules/postfixadmin/controller/MailboxController.php at line 71: Zugriff verweigert
```

is that helpful for you?

Cheers

Sven

**Comment by mschering** [comment]
Is the token set to the same value on both group-office and mailserver:
$config["serverclient_token"]='123456789';

In case it's the same server then it's not relevant.

**Comment by svenvogel** [comment]
where i have to check on the mailserver if the token is set correctly?

**Comment by mschering** [comment]
In /etc/groupoffice/config.php or globalconfig.inc.php there should be:

$config["serverclient_token"]='123456789'; 

This value must match the one in the group-office trying to create the mailbox.

**Comment by svenvogel** [comment]
hmm. thanks for reply. maybe i stay on the line but i have the value set in $config["serverclient_token"]='123456789';

where i need to set it additional?

**Comment by svenvogel** [comment]
```bash
<?php
$config = [
        // GO will connect to this installation to add a mailbox. It is the full url to the Group-Office installation with the postfixadmin module installed.
        'serverclient_server_url' => 'https://x.x.x.x/',
        // A token to authenticate. The token has to be identical on the web and mail server. By default they are the same server so you can just set anything here.

        'serverclient_token' => '123456789',

        // Comma separated list of mailbox domains
        'serverclient_domains' => 'qform.de',

        // The email account properties that will be added for the user
        'serverclient_mbroot' => '',
        'serverclient_use_ssl' => false,
        'serverclient_use_tls' => false,
        'serverclient_novalidate_cert' => '1',
        'serverclient_host' => 'localhost',
        'serverclient_port' => 143,
        'serverclient_smtp_host' => 'localhost',
        'serverclient_smtp_port' => 25,
        'serverclient_smtp_encryption' =>'',
        'serverclient_smtp_username' => '',
        'serverclient_smtp_password' => ''
];
```
where i need to set additional ...

**Comment by svenvogel** [comment]
i get always 

`[Wed Nov 06 09:35:48.041471 2019] [php7:notice] [pid 11305] [client x.x.x.x:34598] GO\\Base\\Exception\\AccessDenied in /mnt/active/www/webmail.qform.de/htdocs/modules/postfixadmin/controller/MailboxController.php at line 71: Zugriff verweigert` (access denied)

**Comment by svenvogel** [comment]
Hi Merjin,

i tried it with the 4.6.125 the same error.

```log
p at line 368: Access denied\n\nGO\\Core\\Controller\\CoreController::multirequest, referer: https://webmail.qform.de/
[Sat Mar 07 13:56:04.868631 2020] [php7:notice] [pid 21089] [client x.x.x.x:49350] GO\\Base\\Exception\\AccessDenied in /mnt/active/www/webmail.qform.de/htdocs/modules/postfixadmin/controller/MailboxController.php at line 71: Zugriff verweigert <-- Access Denied
```

**Comment by mschering** [comment]
I can't replicate this issue. Please contact support so we can take a look on your server config to get this resolved.
