### ISSUE TITLE
serverclient group controller permission issue

### ISSUE THREAD

**Issue by svenvogel** [Intermesh/groupoffice#472]
in the serverclient module if i try to edit the permission i get the following error.

Version: 6.4.48

![image](https://user-images.githubusercontent.com/5433844/65589437-56209400-df89-11e9-9c79-1f5b98e28016.png)

under the hood
apache error.log
```bash
Error in /mnt/active/www/example.de/htdocs/go/base/Router.php at line 181: Class 'GO\\Groups\\Controller\\GroupController' not found, referer: https://mail.example.de/
```

**Comment by mischoe** [comment]
The whole User/Group System is broken right now.
Real name gets deleted, is not saveable, you can’t see group belongings like described here and trying to change group belongings for users ist not going to work...
Really, this is annoying if you - like me - are preparing to start the productive system and I can’t be sure if work for 72 users will be senseless.

**Comment by mschering** [comment]
@mischoe The error displayed is just about listing the members. That will be fixed today. 

But you describe all sorts of problems I haven't seen before. Can you show me the errors you're getting or perhaps steps to reproduce?

**Comment by mischoe** [comment]
@mschering - I also have a ticket running - will put anything in there (201919447)

**Comment by mschering** [comment]
Ok. I'll close this ticket as it has been fixed. I'll continue in the ticket with @mischoe
