### ISSUE TITLE
Sieve Mail-Rules wrong folderlist

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#473]
Add a new email-filter for moving e-mails will alwas show the folderlist of the main/first e-mail-address and not the one of the mail account filter belongs to.

**Comment by mschering** [comment]
I can't replicate this. Can you perhaps make a screen video showing this?

**Comment by remmedia** [comment]
you have got mail...

**Comment by mschering** [comment]
Aha, I see it's a bit different. The folder list only loads once. So it will show the list of the account you opened first.

**Comment by mschering** [comment]
This has been fixed.
