### ISSUE TITLE
rename() function

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#475]
Use of rename() function breaks functionality when for example tmp partition is separate from other data.

For example in :
go/core/fs/Blob.php line 236, consider changing to copy and unlink

                                        //rename($this->tmpFile, $this->path());
                                        copy($this->tmpFile, $this->path());
                                        unlink($this->tmpFile);

**Comment by mschering** [comment]
Because rename is much faster I've made it fallback on copy + unlink now.
