### ISSUE TITLE
6.4.61 - All days events on ActiveSync show one day early

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#478]
Hi,

We were using 6.3.80 version and everything was ok, but over weekend our provider updated to 6.4.61 version. After ActiveSync re-sync of mobile device (Samsung S9, android) I noticed every ALL DAY event I have shows one day earlier on my mobile device.

Thunderbird 60.9 with Lightning plugin via CalDav shows everything correctly.

I see in changelog there is entry for 6.4.52: ActiveSync: Fixed timezone issue with all day events, but it seams not fixed for me.

Anyway, my timezone is EU +2 (Berlin, Wiena, etc...), it's correctly defined in my account setting and same settings are applied to Thunderbird Lightning.

If I create new all day event via mobile phone, Thunderbird shows it correctly.
If I create new all day event via Thunderbird, mobile phone shows it 1 day earlier then it should.

If I can help debug this further, please let me know.

**Comment by mischoe** [comment]
Same problem here... Merijn looked into it and didn´t find the problem yet.

**Comment by DaddyAG** [comment]
It seams to be issue with "repeating events".
If I create all day event in GroupOffice web UI with following setup:
- name of event can be anything
- date, I placed 13. 10. 2019. for first event in series
- all day event
- I'm free
- repeat yearly
- repeat forever
- no reminder

GroupOffice UI and Thunderbird shows events correctly.
Android phone synced via ActiveSync doesn't show first event at all (on 13. 10. 2019.), and second event is shown on 12. 10. 2020. (etc. 12.10.2021. / 12.10.2022. ...).
If I create same event all day event, but without repeating, it shows correctly on 13.10.2019.

**Comment by mschering** [comment]
Fixed in 6.4.65

**Comment by DaddyAG** [comment]
Thank you.
