### ISSUE TITLE
logout all users in maintenance mode

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#481]
It should be possible to force a logout of all users when switching to maintenance mode. Is their another way to force a logout and kill all open sessions?

**Comment by mschering** [comment]
Yes, by clearing the core_auth_token table.

**Comment by fischli** [comment]
could you add it as a new feature to the admin?

**Comment by mschering** [comment]
Enabling maintenance mode logs out everyone but admin in current version! Closing this case.
