### ISSUE TITLE
Strange but real behaviour of CalDav and CardDav

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#482]
I am able to access CalDav and CardDav from the browser but unable to connect from evolution mail client.
Image
![1_mod](https://user-images.githubusercontent.com/20767253/66705760-95e8c900-ed48-11e9-9cf2-cf559aec8352.png)
![2_mod](https://user-images.githubusercontent.com/20767253/66705764-a26d2180-ed48-11e9-8d63-5b3673ed6692.png)

**Comment by s1-ranjan** [comment]
I am enclosing a debug log with a hope this will help to figure the issue
[debug.log](https://github.com/Intermesh/groupoffice/files/3761670/debug.log)

**Comment by mschering** [comment]
I can't test with evolution right now but with dav clients like davdroid and macOS I can connect fine. Please contact support if you still have issues.
