### ISSUE TITLE
Dovecot mysql password not escaped

### ISSUE THREAD

**Issue by psznm** [Intermesh/groupoffice#484]
If i have password for mysql database like `pass"wo\rd`
Then after `$ apt-get install groupoffice-mailserver`

My /etc/dovecot/dovecot-groupoffice-sql.conf.ext has line 
`connect = "host=localhost dbname=groupoffice user=groupoffice password=pass"wo\rd"`

But should be 

`connect = "host=localhost dbname=groupoffice user=groupoffice password=pass\"wo\\rd"`

Or anything else that would work.

**Comment by mschering** [comment]
Do you know which chars should be escaped? I found that the " quotes can be removed from the entire string.
