### ISSUE TITLE
Feature request - Translation arrangements

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#485]
Hello, friend

It would be very nice if, for major releases, you guys could inform translators the release date, send us the files, etc. Goal, to have an updated translation in all languages when a major version is released, or else, each time theres a new version, our language is outdated, mixed with strings in english.

Thanks!

**Comment by mschering** [comment]
Good idea. Can you send me an e-mail with the address to notify when this happens?

**Comment by flaviozluca** [comment]
flavio@lucanet.com.br

Thanks!
