### ISSUE TITLE
Issue with string not found in translation

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#486]
Hi!

For the latest version, we downlodaed the translation file, updated PT-BR...

However, one string was not found.

This is the string: "Não foi possive..."

See image: 

https://www.screenpresso.com/=q736g

Please advise.

Thanks.

**Comment by flaviozluca** [comment]
image attached if link expires
![image](https://user-images.githubusercontent.com/44004645/67206095-5de82280-f3e7-11e9-99c0-8f54e5f8aee4.png)

**Comment by mschering** [comment]
I think this is part of a non standard module. This string is not in our source files.

**Comment by flaviozluca** [comment]
Hi, friend

How can we fix it? It should be "possível" and not "possíve".

Thanks!!

**Comment by dehart** [comment]
Found and fixed!

**Comment by flaviozluca** [comment]
Thanks a lot!
