### ISSUE TITLE
6.4.70 Addressbook vcard export bug

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#487]
When exporting addressbook as vcard, the following exception gets thrown

'The destination <location of file containing freshly exported contacts> already exists!'

error gets thrown from go/core/fs/File.php in function 'copy'

It seems the file gets generated once and then another copy is attempted in the same location

**Comment by DaddyAG** [comment]
This exact problem happens with CSV export also.

**Comment by mschering** [comment]
I think this is related to issue #523 ?

**Comment by gtech99** [comment]
yes, it's caused by that bug

**Comment by mschering** [comment]
Closing as the related bug has been fixed.
