### ISSUE TITLE
6.4.70 - GroupOffice isn't respecting addressbook permissions - CRITICAL

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#492]
Hello all,

GroupOffice 6.4.70 isn't respecting set permissions.
We have one user account, which isn't used for anything except for shared address book (GAL). That address book is:
READY ONLY for group EVERYONE
MANAGE for that user

Those are only permissions.
From my account (which is READ ONLY account) I can delete any contact in that address book.

We noticed this when people inside company started complaining that some contacts were missing. After investigation we noticed we can all remove contacts from read only address book.

**Comment by mschering** [comment]
I've just tried this but I can't replicate it. I can't delete it and when pressing delete I get an error as expected.

**Comment by DaddyAG** [comment]
Sorry, I wasn't clear. You can delete it on mobile phone (activesync).

**Comment by mschering** [comment]
Thanks, I found the problem. Will release an update now.
