### ISSUE TITLE
SQLState Error

### ISSUE THREAD

**Issue by drkkvfulda** [Intermesh/groupoffice#494]
i get a lot of this errors after upgrade to 6.4.74. many functions no longer work.

SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

**Comment by mschering** [comment]
Can you check if you have mysqlnd support? Which mysql version do you run?

**Comment by drkkvfulda** [comment]
* Datenbank-Client Version: libmysql - mysqlnd 5.0.11-dev - 20120503
- $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
	* PHP-Erweiterung: mysqli [1]


	* Server: MySQL (Localhost via UNIX socket)
	* Server-Typ: MySQL
	* Server Version: 5.5.62-0+deb8u1 - (Debian)
	* Protokoll-Version: 10
	* Benutzer: groupoffice@localhost
	*  Server Zeichensatz:  UTF-8 Unicode (utf8)  






Mit freundlichen Grüßen
 
Dominik Ruffing
Stabstellenleiter Interne Betriebsorganisation /
Qualitätsmanagement 



DRK-Kreisverband
Fulda e.V.
St.-Laurentius-Str. 4
36041 Fulda


Tel. 0661 90291-0
Mobil 0151 64323830
Fax 0661 90291-30
dominik.ruffing@drk-fulda.de [2]
www.drk-fulda.de [3]








 [3]









Deutsches Rotes Kreuz Kreisverband Fulda e.V.
Vorstandsvorsitzender: Christoph Schwab
Präsidium: Prof. Dr. med. Martin H. Hessmann (Präsident), Dr.
Andreas Opitz (Vizepräsident), Christoph Jordan, Markus Schleicher,
Christian Erwin
(VR 534, Amtsgericht Fulda)
 
DRK-Fulda gGmbH (HRB 5171, Amtsgericht Fulda)
DRK Seniorenzentren Fulda gemeinnützige GmbH (HRB 5004, Amtsgericht
Fulda)
DRK Fulda Fahrdienste GmbH (HRB 6934, Amtsgericht Fulda)
Michaelshof GmbH (HRB 6579, Amtsgericht Fulda)
Geschäftsführer: Christoph Schwab
Gesellschafterversammlung: Prof. Dr. med. Martin H. Hessmann
(Vorsitzender), Dr. Andreas Opitz (stellv. Vorsitzender), Christoph
Jordan, Markus Schleicher, Christian Erwin
 
Diese Nachricht kann vertrauliche und/oder rechtlich geschützte oder
sonst relevante Informationen enthalten. Sollten Sie nicht der
richtige Adressat sein, sind Sie nicht zur Verwendung oder Weitergabe
der Information befugt. Bitte benachrichtigen Sie uns sofort über den
irrtümlichen Empfang und löschen Sie dann die Nachricht.




Am Montag, den 11.11.2019 um 19:16 schrieb Merijn Schering:




Can you check if you have mysqlnd support? Which mysql version do you
run?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [4], or unsubscribe
[5].





Links:
------
[1]
https://89.27.235.91/phpmyadmin/url.php?url=http%3A%2F%2Fphp.net%2Fmanual%2Fde%2Fbook.mysqli.php
[2] mailto://dominik.ruffing@drk-fulda.de
[3] https://www.drk-fulda.de
[4]
https://github.com/Intermesh/groupoffice/issues/494?email_source=notifications&email_token=AKEGNXJR26T2XE5WSC4PT73QTGOOTA5CNFSM4JLYOBS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDXU6LQ#issuecomment-552554286
[5]

**Comment by mschering** [comment]
Thanks, the strange thing is that I use "MYSQL_ATTR_USE_BUFFERED_QUERY".

Can you enable debug and show me the stack trace of the error?

**Comment by drkkvfulda** [comment]
tomorrow... i downgrade my system to 6.4.72 because with 6.4.74
it doesn't work... but i have upgrade bugs, see the other
mails/bugs/tickets....




Mit freundlichen Grüßen
 
Dominik Ruffing
Stabstellenleiter Interne Betriebsorganisation /
Qualitätsmanagement 



DRK-Kreisverband
Fulda e.V.
St.-Laurentius-Str. 4
36041 Fulda


Tel. 0661 90291-0
Mobil 0151 64323830
Fax 0661 90291-30
dominik.ruffing@drk-fulda.de [1]
www.drk-fulda.de [2]








 [2]









Deutsches Rotes Kreuz Kreisverband Fulda e.V.
Vorstandsvorsitzender: Christoph Schwab
Präsidium: Prof. Dr. med. Martin H. Hessmann (Präsident), Dr.
Andreas Opitz (Vizepräsident), Christoph Jordan, Markus Schleicher,
Christian Erwin
(VR 534, Amtsgericht Fulda)
 
DRK-Fulda gGmbH (HRB 5171, Amtsgericht Fulda)
DRK Seniorenzentren Fulda gemeinnützige GmbH (HRB 5004, Amtsgericht
Fulda)
DRK Fulda Fahrdienste GmbH (HRB 6934, Amtsgericht Fulda)
Michaelshof GmbH (HRB 6579, Amtsgericht Fulda)
Geschäftsführer: Christoph Schwab
Gesellschafterversammlung: Prof. Dr. med. Martin H. Hessmann
(Vorsitzender), Dr. Andreas Opitz (stellv. Vorsitzender), Christoph
Jordan, Markus Schleicher, Christian Erwin
 
Diese Nachricht kann vertrauliche und/oder rechtlich geschützte oder
sonst relevante Informationen enthalten. Sollten Sie nicht der
richtige Adressat sein, sind Sie nicht zur Verwendung oder Weitergabe
der Information befugt. Bitte benachrichtigen Sie uns sofort über den
irrtümlichen Empfang und löschen Sie dann die Nachricht.




Am Montag, den 11.11.2019 um 19:53 schrieb Merijn Schering:




Thanks, the strange thing is that I use
"MYSQL_ATTR_USE_BUFFERED_QUERY".



Can you enable debug and show me the stack trace of the error?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4].





Links:
------
[1] mailto://dominik.ruffing@drk-fulda.de
[2] https://www.drk-fulda.de
[3]
https://github.com/Intermesh/groupoffice/issues/494?email_source=notifications&email_token=AKEGNXI5YN5XJP4FM4MQAXDQTGS4NA5CNFSM4JLYOBS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDXYG5Y#issuecomment-552567671
[4]

**Comment by mschering** [comment]
It might be that your mysql server is too old. I don't see much 5.5 versions anymore. It's from 2010!

**Comment by drkkvfulda** [comment]
Which Version you recommend?






Von meinem Samsung Galaxy Smartphone gesendet.





-------- Ursprüngliche Nachricht --------
Von: Merijn Schering  
Datum: 11.11.19 20:05 (GMT+01:00) 
An: Intermesh/groupoffice  
Cc: drkkvfulda , Author  
Betreff: Re: [Intermesh/groupoffice] SQLState Error (#494)

Which Version you recommend?






Von meinem Samsung Galaxy Smartphone gesendet.





-------- Ursprüngliche Nachricht --------
Von: Merijn Schering  
Datum: 11.11.19 20:05 (GMT+01:00) 
An: Intermesh/groupoffice  
Cc: drkkvfulda , Author  
Betreff: Re: [Intermesh/groupoffice] SQLState Error (#494) 




It might be that your mysql server is too old. I don't see much 5.5
versions anymore. It's from 2010!



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].



Links:
------
[1]
https://github.com/Intermesh/groupoffice/issues/494?email_source=notifications&email_token=AKEGNXJIORN56R3ND2LHRQ3QTGUIDA5CNFSM4JLYOBS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDXZIRY#issuecomment-552571975
[2]

**Comment by michalcharvat** [comment]
MySQL 5.7/8 or MariaDb related version

**Comment by drkkvfulda** [comment]
can I just update mysql to keep GO working? or does the database need
to be updated somehow?






Von meinem Samsung Galaxy Smartphone gesendet.





-------- Ursprüngliche Nachricht --------
Von: michalcharvat  
Datum: 11.11.19 22:21 (GMT+01:00) 
An: Intermesh/groupoffice  
Cc: drkkvfulda , Author  
Betreff: Re: [Intermesh/groupoffice] SQLState Error (#494)

can I just update mysql to keep GO working? or does the database need
to be updated somehow?






Von meinem Samsung Galaxy Smartphone gesendet.





-------- Ursprüngliche Nachricht --------
Von: michalcharvat  
Datum: 11.11.19 22:21 (GMT+01:00) 
An: Intermesh/groupoffice  
Cc: drkkvfulda , Author  
Betreff: Re: [Intermesh/groupoffice] SQLState Error (#494) 


MySQL 5.7/8 or MariaDb related version



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].



Links:
------
[1]
https://github.com/Intermesh/groupoffice/issues/494?email_source=notifications&email_token=AKEGNXPRFWBESASQEYFFBJ3QTHED7A5CNFSM4JLYOBS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDYFK4Y#issuecomment-552621427
[2]

**Comment by fischli** [comment]
I also had to migrate to a newer version. Since 6.4 I'm using MariaDB-server-10.4.10 with CentOs 7.7.  The current version on CentOs is mariadb-server-5.5.64 which doesn't fullfill the requirements for GroupOffice 6.4.x. Migration from 5.5 to 10.4 went through without trouble.

**Comment by michalcharvat** [comment]
One of GO users runing 6.4 on 5.5.5-10.1.41-MariaDB without troubles.

@drkkvfulda when you update database server you should run server upgrade script. Just follow instructions on screen. Do not forget backup your database. However I didn't see any problem in migration process.

**Comment by mschering** [comment]
@michalcharvat Is that customer running the latest 6.4.74? I made some changes there were prepared statements are reused for performance improvement. It seems the server of drkkvfulda doesn't like that.

**Comment by michalcharvat** [comment]
@mschering He is still at 6.4.65 but I can test this update on stage server. However it would be great to define minimum database version for latest update - still 5.7 or 8 only? MariaDb is still supported till Ocrober 2020.  About GO changes - what was changed? I only found SQL_FOUND_ROWS usage in 6.4.72. From my experience second query returning total number of rows without order and limit will be faster. Probably number of rows in database will be the boundary that divides these two options -> calculate total number of rows in single query with SQL_CALC_FOUND_ROWS  or with two queries :)

**Comment by drkkvfulda** [comment]
i think the problem is the db connection:
if i change: PDO::ATTR_EMULATE_PREPARES => false
to: PDO::ATTR_EMULATE_PREPARES => true

it works i think... is this option required?

**Comment by mschering** [comment]
Yes it’s required. You will get other trouble without it. Can’t you upgrade to at least 5.7? Also make sure you really have mysqlnd Support in your pho.

**Comment by drkkvfulda** [comment]
mysqlnd 5.0.12-dev

yes i have mysqlnd according to phpinfo and also the new systemcheck
of groupoffice. sure that it must have something to do with it? google
I usually find solutions to problems such as with the prepare that it
has to do with the code.

**Comment by drkkvfulda** [comment]
> One of GO users runing 6.4 on 5.5.5-10.1.41-MariaDB without troubles.
> 
> @drkkvfulda when you update database server you should run server upgrade script. Just follow instructions on screen. Do not forget backup your database. However I didn't see any problem in migration process.

and he use maria db 10.1 without troubles, i use 10.3...

**Comment by drkkvfulda** [comment]
or the closeCursor() is needed maybe?

**Comment by mschering** [comment]
Perhaps, I will try this. But I can’t test because I can’t replicate the problem.

**Comment by drkkvfulda** [comment]
I send you over the ticket system (pro desk) information.
