### ISSUE TITLE
Printing shows blank Body

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#495]
Printing shows blank body
6.4.74

**Comment by fischli** [comment]
email printing produces garbage only!

**Comment by dehart** [comment]
I think it's a bug in Firefox but I have found a workaround. 😁
https://bugzilla.mozilla.org/show_bug.cgi?id=1596048

**Comment by remmedia** [comment]
It’s also on chrome

**Comment by mschering** [comment]
Fixed in 6.4.76
