### ISSUE TITLE
LDAP user cannot login on empty email address in server

### ISSUE THREAD

**Issue by rapha-dev** [Intermesh/groupoffice#499]
Just discovered a possible misbehavior in LDAP Authenticator.

A user cannot log in when no email address (`mail` attribute) is given in LDAP server regardless server profile setting `Login with e-mail address`.

```
[warn][go\core\orm\Property:67] Validation error in go\core\model\User::email: 1 = Property is required
[warn][go\core\orm\Property:67] Validation error in go\core\model\User::recoveryEmail: 1 = Property is required
[error][go\core\ErrorHandler:65] Exception in /var/www/office/groupoffice-6.4.74-php-70/go/modules/community/ldapauthenticator/model/Authenticator.php at line 95: Could not save user
```

`Login with e-mail address` is **not** checked in server profile.
Username attribute is `sAMAccountName`.
Create email account is disabled.
User/group synchronization is disabled.

Tested GO version: `6.4.74-php-70`
LDAP server: Windows AD (Server 2019)

Steps to reproduce: Remove `mail` attribute (or delete value) in LDAP server and try to log in.

Workaround: Add `mail` attribute in LDAP server for users.

**Comment by mschering** [comment]
Sorry, it's not a misbehaviour. Group-Office requires an e-mail address.
