### ISSUE TITLE
6.4.77 Send e-mail is not working - type error

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#500]
Since the update to 6.4.77 we get the following error when trying to forward/reply/reply all function in the e-mail module.
"Uncaught TypeError: Cannot read property 'length' of undefined...(see picture)" the script sse.php keeps loading forever and the screen is showing the loading sign.
Only thing that works is pushing F5, but you cannot use the forward/reply/reply all functions in the webclient.
![Clipboard01](https://user-images.githubusercontent.com/2633051/68927639-7e0dc600-0788-11ea-85bb-53d81f07f4d8.jpg)

**Comment by mschering** [comment]
sse.php is supposed to be constantly running. It's for Server Sent Events or push notifications.

The loading is obviously something that's not right. Can I check this out somewhere with a test account?

**Comment by thomasgg23** [comment]
When trying to change the permission setting in the e-mail tab I now get the error "Could not unserialize cache from file de-legacy-base data: ''" and the list doesn't load the user/group table.
Something related?

I will send you the credentials via e-mail.

**Comment by mschering** [comment]
Strange, I logged in. Sent a mail to myself. Replied to the sent item and it all worked fine ?!

**Comment by thomasgg23** [comment]
Okay, I'll check this on the weekend with different browser and computers.
Thanks for looking

**Comment by thomasgg23** [comment]
Did some checking and recalled the https://<URL>/install/upgrade.php script.
After the script cleared the cache everything works fine.

Sorry for the false alarm.
