### ISSUE TITLE
6.4.79 - Billing - Adding or removing columns from the grid is not saved

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#502]

**Comment by IT-AND-GENERAL** [comment]
I think this is not just billing ... all customization do not get saved

**Comment by mschering** [comment]
Fixed in 6.4.81.

I changed it to storing state in the browser so that mobiles have a different state.

**Comment by IT-AND-GENERAL** [comment]
Excellent many thanks.
