### ISSUE TITLE
6.4.79 - Addressbook - searching a contact by number does no work

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#503]

**Comment by mschering** [comment]
You mean phone number?

**Comment by IT-AND-GENERAL** [comment]
Yes, sorry, it is phone number. I tried to search for the exact number of one of the contact but it does not find it

**Comment by DaddyAG** [comment]
Searching by phone number doesn't work by default. As I see in comment box when you hover over search filed, you need to enter:

phone: 123456789
-this will only find EXACT phone number

phone: %56789
- this will find phone numbers ending with 56789

I liked better old behavior when you just entered number and it searched all fields and included all matches.

**Comment by mschering** [comment]
More and more tables are joined for these things. How often do you search for a phone number?
What if we created a combo where you can choose the field to search on?

**Comment by IT-AND-GENERAL** [comment]
A combo could work.
I search for a phone number when I get a call from a number I do not recognize :-)

I see you added the enhancement label. Thanks

**Comment by derjoachim** [comment]
Closing this ticket. Not only does this refer to a very old GO version, you can currently search by phone numbers just fine as the search cache has been radically enhanced in the meantime.
