### ISSUE TITLE
Adding contact to a group removes it from the addressbook

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#504]
Dropping contacts into a group removes them from the addressbook. Is this the desired behaviour? A Contact inside a group should be like a link to the origin. I thought that groups are a replacement to former addresslists.

**Comment by mschering** [comment]
I can't replicate this. Only thing to keep in mind that a group belongs to an address book. So if you move it to a group from another address book it will move it to that address book.

**Comment by fischli** [comment]
That's an explanation ... groups are not a replacement for the former addresslist with this restriction.

**Comment by mschering** [comment]
No but the newsletters module provides the old functionality.

**Comment by fischli** [comment]
![image](https://user-images.githubusercontent.com/832201/69612857-d4082680-1030-11ea-856e-5c19f568e0b9.png)
just tried to activate the module ... doesn't look very promising

**Comment by fischli** [comment]
I'm on 6.4.82 and I did the following #514 in the same context. Hope to get my database back.
