### ISSUE TITLE
Enhancement request:  Enforce 2 factor authentication

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#505]
I am not sure where is a correct place to suggest an enhancement. Sorry if this isn't the right place.

I believe it would be a good idea if we can enforce our GO users to activate 2 factor authentication at some point via the config file or System Settings.
Once enforced, the user should be taken to "My Account" -> "Account" and not allowed to go anywhere else until  Google authenticator is enabled.

**Comment by derjoachim** [comment]
This feature has crept into 6.5, so am closing this ticket. :)
