### ISSUE TITLE
6.4.83: Serverclient - invalid imap encryption

### ISSUE THREAD

**Issue by sirdemoncze** [Intermesh/groupoffice#507]
Hi, 

in file:

> /go/modules/community/serverclient/model/MailDomain.php

is bad settings variable **imap_encryption** from config. Exactly TLS override SSL.
```
$account->imap_encryption = !empty(\GO::config()->serverclient_use_ssl) ? 'ssl' : '';
$account->imap_encryption = !empty(\GO::config()->serverclient_use_tls) ? 'tls' : '';
```

Can you fixed like this (for example)?

```
$account->imap_encryption = '';

// SSL
if (!empty(\GO::config()->serverclient_use_ssl))
    $account->imap_encryption = 'ssl';

// TLS
if (!empty(\GO::config()->serverclient_use_tls))
    $account->imap_encryption = 'tls';
```

Maybe will be better cancel these variables (**use_tls** and **use_ssl**) and add direct **imap_encryption** to serverclient config.

**Comment by mschering** [comment]
Thanks, I changed that.
