### ISSUE TITLE
6.4.82 activating the notes module crashed the database

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#514]
![image](https://user-images.githubusercontent.com/832201/69613503-f3ec1a00-1031-11ea-90e6-d737e66f4cfb.png)
Tried to activate the notes module and afterwards I'm not able to login anymore. Had to restore the whole database from backup.

**Comment by fischli** [comment]
Since 6.4.87 it is possible to active the notes module without data corruption, but as additional damage I get an endless addressbook loading. This makes the notes module useless.

**Comment by mschering** [comment]
Is this still happening?

**Comment by fischli** [comment]
fixed in newer versions
