### ISSUE TITLE
Customfields:date

### ISSUE THREAD

**Issue by R3DN4KS** [Intermesh/groupoffice#515]
Created Customfields, type DATE doesn't recognize the Global Format Settings, when used in templates

If the global Format Settings are set to 

                                 day.month.year

it appears as

                                Year-Month-Day

But ONLY in Customfields.

![GObug](https://user-images.githubusercontent.com/58231732/69665293-64bf2080-108a-11ea-85be-59c7e934a00b.png)

**Comment by mschering** [comment]
This is fixed in the latest version.
