### ISSUE TITLE
6.4.82 - https request through proxy delivers content over http

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#516]
![image](https://user-images.githubusercontent.com/832201/69725872-7c94b400-111f-11ea-85a0-762a787c17c3.png)

While trying to access the internal GroupOffice through a proxy from outside over https, some content is addressed with the internal http server-uri.

**Comment by mschering** [comment]
Check your URL setting in System settings. I think it's set to http.

**Comment by fischli** [comment]
yes it's right and the server is listening on http only. This is as expected, but I'am connecting the server from outside through an proxy to the inside and some content isn't map to the original request. It is still deliverd as if I would connect it directly from the inside. The url http://go.fischer.ing/go/... should be https://HOSTNAME/go/...

**Comment by mschering** [comment]
Can't you just change that in system settings?

**Comment by fischli** [comment]
It's an nginx proxy missconfiguration. Had to set a propper X-Forwarded-Host header. Sorry for the trouble!
