### ISSUE TITLE
6.4.84 Calendar not loaded properly.

### ISSUE THREAD

**Issue by prbt2016** [Intermesh/groupoffice#517]
Hello,

After manually installing Group Office on Cloud Linux 7.7 , on PHP 7.1(PHP 7.1 zip downloaded from sourceforge), Apache 2.4 and MYSQL 5.6. Calendar is not loaded properly .

This error is thrown in browser's console i.e : 

TypeError: dn[d] is undefined ext-all-debug.js:19153:13
TypeError: this.grid is undefined ext-all-debug.js:50675:22
TypeError: this.grid is undefined ext-all-debug.js:48521:9

![calendar](https://user-images.githubusercontent.com/17871448/69804167-f7cf9600-1203-11ea-87ba-4195eeaa3b2c.png)

What could be the possible issue?. Could you check this at your end and fix this?

**Comment by mschering** [comment]
I can't replicate this. Any other errors in the server log or browser console prior to these?

**Comment by iklimeno** [comment]
I confirm this issue. Same screen. 6.4.115

Web console log starting from Login screen up to Calendar tab:
Module/query call without limit script.php: 2045:117
Bookmark/query call without limit script.php: 2045:117
Module/query call without limit script.php: 2045:117
Field/query call without limit script.php: 2045:117
FieldSet/query call without limit script.php: 2045:117
AddressBook/query call without limit script.php: 2045:117
CommentLabel/query call without limit script.php: 045:117
Object { displayType: "month", days: 7, calendars: (1) […], view_id: 0, group_id: 1 } script.php: 4135:64
TypeError: dn[d] is undefined ext-all-debug.js: 19173:13
TypeError: this.grid is undefined ext-all-debug.js: 50703:22
TypeError: this.grid is undefined ext-all-debug.js: 48549:9

​

**Comment by iklimeno** [comment]
Found out what is going on. For some reason this.startDay in line 19169 treated as String and '+' produce totally incorrect result. Just change it to:
var d = Number(this.startDay) + i;

**Comment by mschering** [comment]
I believe this has been fixed recently. Can you confirm?

**Comment by iklimeno** [comment]
Problem solved. I found out that this issue is not version dependent. Moreover the root of the problem causes a lot of other issues in Group Office. The problem is in MySQL module for PHP. It should be mysqlnd (ND is critical). Other MySQL connectors return incorrect values types. E.g. String instead of Int and so on. This causes a lot of weird problems in Group Office.

**Comment by pierrese** [comment]
`Uncaught TypeError: this.grid is undefined` and `TypeError: dn[d] is undefined`

**Comment by mschering** [comment]
Does you r test page show that mysqlnd is loaded?

**Comment by iklimeno** [comment]
Hi! If it will help... Right now I run 6.6.135 on PHP7.4 with the following "nd" modules enables. And it runs OK.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/61056200/205014360-257540ec-3302-4860-b563-e712ee144f79.png">

**Comment by iklimeno** [comment]
In addition: almost all pdo_ modules are disabled.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/61056200/205015128-0f601693-2f54-4ed2-9ed0-3b0c83bf5728.png">

**Comment by pierrese** [comment]
Thanks for your answer. Creating a View in calendars, I got rid of `Uncaught TypeError: this.grid is undefined` but I still have `TypeError: dn[d] is undefined ` ans Calendars not working...

![Uploading Screenshot 2022-12-01 at 10-32-39 Cloud ZRAD.png…]()

**Comment by pierrese** [comment]
And modules activated as above...

**Comment by pierrese** [comment]
What troubles me that first it worked. It just seems that I changed some default parameter somewhere in GroupOffice calendars and it broke everything...

**Comment by mschering** [comment]
I think it's a configuration issue that can only be solved with help from tech support. If you have a pro license please contact us and we'll connect and fix it!
