### ISSUE TITLE
while compose and sending email it sends to self only

### ISSUE THREAD

**Issue by deependhulla** [Intermesh/groupoffice#518]
while compose and sending email it sends to self only for version 6.4.83 * 6.4.85

usig IMAP Auth.

lease check email-module not useable ..as email are send forcefull to self.

**Comment by mschering** [comment]
You probably enabled debug email at system settings notifications. We will remove this option as you’re not the only one 😀

**Comment by deependhulla** [comment]
as guided .
unchecked the option : Send all system notifications to the specified e-mail address.
hope this is not enabled by default.

**Comment by deependhulla** [comment]
Thanks it
