### ISSUE TITLE
/etc/groupoffice/globalconfig.inc.php

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#519]
Error: ErrorException in /var/www/groupoffice/go/core/App.php at line 340: file_exists(): open_basedir restriction in effect. File(/etc/groupoffice/globalconfig.inc.php) is not within the allowed path(s):

adding dir groupoffice to /etc fixes error

**Comment by lonesomewalker** [comment]
Yes, but why is this an issue?
Your server uses open_basedir, which clearly is shown in the check script.

**Comment by mschering** [comment]
Yes open_basedir should not be used. Closing this one.
