### ISSUE TITLE
Address book export no longer working (REGRESSION)

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#520]
Hello everyone,

Somewhere in between versions 6.4.70 and latest 6.4.86 you introduced regression.
It's no longer possible to export whole address book.

Tested with Firefox and Chrome.
1. Log in to GO and open Address book tab.
2. Click on three dots, export, CSV (it's same with VCARD also).
3. If you somehow manage to bypass still active issue #487  you will get your CSV file saved to disk. CSV file contains just around 20+ entries (from 520 available in my case), probably just what was visible on screen.
4. If you scroll down to the last address book entry and export again, it will export just 1 line/contact and it will be contact which is first visible on screen.

**Comment by mschering** [comment]
This has been fixed in the latest version.
