### ISSUE TITLE
Calendar event recurrence month by date

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#521]
If you save a calendar event and set it to recur on a "month by date" option, when you re-open it, it will show as 'month by day' instead.

**Comment by flaviozluca** [comment]
this one is important, imho as since last year I cant schedule an event, for example, every 10th of every month.

thanks.

**Comment by dehart** [comment]
A recurring event that is schedule on the 10th of every month will not change to "month by day" when I re-open it.
Am I missing something?

**Comment by gtech99** [comment]
Here's how I'm testing.

Create a new event, set it to recur on Month by Date. Close the event and re-open it. It will show as Month by Dat
