### ISSUE TITLE
rename() function can't be trusted

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#523]
In go/core/fs/File.php function move()

                try {
                        $success = rename($this->path, $destination->getPath());
                } catch(\Exception $e) {
                        //renaming accross partitions doesn't work
                        $success = $this->copy($destination);
                        if($success) {
                                $this->delete();
                        }
                }

this function still doesn't work right because rename isn't an atomic operation and weird cases can happen such as: the copy operation succeeds but the removal of the original fails and in that case you are left with:

1. a copy being made
2. exception gets thrown
3. the code tries to do yet another copy which will fail because the copy has already been made

more info here:

https://stackoverflow.com/questions/45692433/php-rename-from-tmp-throws-warning-although-actually-works

I recommend you stick with copy and unlink

**Comment by mschering** [comment]
What was the problem you were having exactly?

I don't want to copy and remove because this is very slow.

**Comment by gtech99** [comment]
This error:

Exception in /usr/share/groupoffice/go/core/fs/File.php at line 373: The destination '/home/govhosts/multi_instance/go2/data/a3/36/a336d82a643826fe74d7008a1a6c576230532633' already exists

We debugged the issue and realized that the copy part of rename() was succeeding but still throwing an exception thus causing a second copy to be attempted and thus generating the error. Same as in that stackoverflow article I added

**Comment by mschering** [comment]
Can you try with: https://github.com/Intermesh/groupoffice/commit/a20f36bf8f8a000658920284c4abf1bb65823dc9

**Comment by mschering** [comment]
Didn't here anything back so I assume this one is fixed.

**Comment by gtech99** [comment]
it's fixed in the original file but it's still a problem in  go/base/fs/File.php
