### ISSUE TITLE
tmp directory attachments cleanup

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#524]
The attachments directory in the tmp folder can easily reach 32768 directories which is the limit for some file systems (ext2/3, ufs ). I recommend somehow limiting that number of directories, or recycling them, or somehow cleaning them via cron job as to avoid errors

**Comment by mschering** [comment]
We actually have a cron job for it:

0 0 * * * root find /tmp-type f -mtime +2 -delete && find /tmp-type d -empty -delete

**Comment by mschering** [comment]
I fixed a bug today where z-push would create and leave lots of temporary files. Upgrading is recommended.
