### ISSUE TITLE
V6.4.92 admin: no users or groups shown

### ISSUE THREAD

**Issue by Winteriver** [Intermesh/groupoffice#528]
Since Update from 6.4.36 to 6.4.92 Admin cannot see any users or groups in system settings any more. After pressing the link "users" or "groups", GO tries to load this forever.
Before we had no problem with users/groups in Admin-mode at all.

System: Debian 9, PHP 7.3.
GO Test script: everything is green, no error.

Users/groups a re selectable in e.g. rights mode for calendard (users, groups are shown).

Does anyone have an idea?

Thanks, birdiser

**Comment by mschering** [comment]
This one should already be fixed.
