### ISSUE TITLE
after upgrade from 6.4.46 -> 6.4.92 (login broken)

### ISSUE THREAD

**Issue by svenvogel** [Intermesh/groupoffice#529]
Hi Merjin,

i cant login after upgrade.

`call_user_func_array() expects parameter 1 to be a valid callback, class 'GO\Email\EmailModule' does not have a method 'head'`

the following error occurs.

hui some fixes for that?

Cheers

Sven

**Comment by mschering** [comment]
Try to run /install/upgrade.php

**Comment by svenvogel** [comment]
Hi Merijn,

thanks. works now!

Cheers

Sven
