### ISSUE TITLE
User e-mail template homepage variable not parsed

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#530]
When adding an e-mail template, the homepage variable ( and others ) are not being populated when composing a message. I traced the problem to:

public static function getContactAttributes  in go/base/model/Template.php

I fixed the homepage problem by adding this line:
$attributes[$tagPrefix . 'homepage'] = $contact->findUrlByType(\go\modules\community\addressbook\model\Url::TYPE_HOMEPAGE, false)->url ?? "";

but I'm unsure if it's the best solution. Further down homepage does get parsed but only for companies (?). Not sure if I'm misreading this or something else is happening

**Comment by mschering** [comment]
The homepage was only available for companies previously so this line was only present for contacts. I've added this for companies now too. Thanks.
