### ISSUE TITLE
Error after deleting calendar System Administrator

### ISSUE THREAD

**Issue by zero771977** [Intermesh/groupoffice#531]
After installing groupoffice I created several calendars and then deleted the calendar System Administrator, a message appeared: "An unknown error has occurred. SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_change`, CONSTRAINT `core_change_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE SET NULL)"
 This message appears at login, any change in settings.
I had to delete the associated key core_change_ibfk_2 completely. Visually everything works. However, you cannot recreate the key core_change_ibfk_2 (ADD CONSTRAINT `core_change_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE;): "cannot add or update a child row: a foreign key constraint fails....". 
What can be done in this situation?

**Comment by rvdartel** [comment]
Hello Zero,

The problem should be fixed in 45b61a3. Try recreating the key core_change_ibfk_2 with ON DELETE SET NULL  - ON UPDATE RESTRICT.

**Comment by zero771977** [comment]
Hello rvdartel, 
What does the command look like? If replaced ON DELETE SET NULL, to ON UPDATE RESTRICT, the error is similar.

**Comment by rvdartel** [comment]
Hello Zero,

This query should work for you.

ALTER TABLE core_change
ADD CONSTRAINT core_change_ibfk_2
FOREIGN KEY (aclid) REFERENCES core_acl(id)
ON DELETE SET NULL ON UPDATE CASCADE;

**Comment by zero771977** [comment]
Hello rvdartel,
I really appreciate your efforts, however the problem is more serious. After entering your command, the following error: 
MariaDB [groupoffice]> ALTER TABLE core_change
    -> ADD CONSTRAINT core_change_ibfk_2
    -> FOREIGN KEY (aclid) REFERENCES core_acl(id)
    -> ON DELETE SET NULL ON UPDATE CASCADE;
ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`#sql-216_ca3`, CONSTRAINT `core_change_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)
 Look at the following: `groupoffice`.`**#sql-216_ca3**`,
If you reconnect to the database, then the characters will change, but the general error will remain

**Comment by mschering** [comment]
I think a database check will fix this issue on the latest 6.4 release.
