### ISSUE TITLE
6.4.97 - Cannot login

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#532]
![image](https://user-images.githubusercontent.com/52159663/71408337-b8933a00-2635-11ea-9f74-57f0d84b8a0b.png)

No errors found on webserver log files

**Comment by IT-AND-GENERAL** [comment]
Debug enabled shows the following:

[log][go\core\orm\Entity:367] COMMIT DB TRANSACTION
[log][go\core\App:554] success
[log][go\core\ErrorHandler:87] ErrorHandler::exceptionHandler() called with Error
[error][go\core\ErrorHandler:65] Error in <go path>/groupoffice-6.4.94-php-71/api/auth.php at line 132: Class 'go\core\auth\model\Token' not found
[error][go\core\ErrorHandler:68] #0 <go path>/groupoffice-6.4.94-php-71/api/auth.php(149): getToken(Array)
[error][go\core\ErrorHandler:68] #1 {main}

**Comment by IT-AND-GENERAL** [comment]
it looks like there is somewhere a reference to the old version: 6.4.94 ?
The error above shows 6.4.94 instead of 6.4.97

The same happen on the browser console where the error refer to  6.4.94
![image](https://user-images.githubusercontent.com/52159663/71413623-f189d980-264a-11ea-8d0b-6066149d7bee.png)

**Comment by mschering** [comment]
I think you need to run /install/upgrade.php

**Comment by IT-AND-GENERAL** [comment]
I think I solved this.
It needed a restart of php-fpm.service
This was never required before
