### ISSUE TITLE
Translations of first/last name

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#533]
Hello,

After a long time I wanted to update translation, but noticed something strange.
When adding new contact in address book, english string used for name is "First" and for last name "Last" and those are part of strings "First", "Second", "Third", "Fourth" and "Last". Then I noticed that there are also strings "First name" and "Last name".

Problem here is, if "first" is used for anything else except for "first name" translation will suck since in most languages first and first name have very different meaning. Same goes for last and last name.

For example in croatian:
first (numbering, as first in line) = prvi
first name = ime
last (numbering, as last in line) = zadnji
last name = prezime

So, are this strings used just for contact first and last name or also something else? They are part of core/core module.
If they are used for something else, you should have different string First for contact and different First for everything else.

**Comment by mschering** [comment]
Hi,

You can make them part of the address book by adding new entries and referring to the address book module.
