### ISSUE TITLE
Which users can manage groups?

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#534]
Who is allowed to manage groups seems to have changed from GO 6.3 to 6.4. 

1. Members of the Admin group can access `Groups` from the System Settings menu. Here users can be assigned to groups (and permissions and access to modules can be set).

2. Normal users have in their profile a `Groups` menu which lists their memberships. It is always greyed out, except for an Admin user. 

![GOgroups](https://user-images.githubusercontent.com/485723/71734318-f79e6800-2e4b-11ea-9bd2-60dc9e91ed23.png)

In GO versions < 6.3 I think it was possible that also users not being in the Admin group could be given the right to manage memberships in groups. Do I have a blind spot or is this feature not available anymore?

**Comment by mschering** [comment]
It's no longer available. Only admins can manage groups.
