### ISSUE TITLE
CardDAV web server not showing job title

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#538]
Just noticed that I can't search via job title in Thunderbird any more.
All my contacts that had job title, don't have it any more.

Checked vcard pure text version on GroupOffice server, and it's missing job tags (I guess it's TITLE in vcard spec).
GroupOffice web version has job title, mobile phone synced with activesync has job title, but carddav sync doesn't have it.

Thunderbird 68.4.1 with Cardbook 43.5
But as I said, it's missing on server side also, not just in Cardbook addon.

**Comment by mschering** [comment]
Will be fixed in 6.4.102
