### ISSUE TITLE
CardDAV web server now showing new contacts

### ISSUE THREAD

**Issue by DaddyAG** [Intermesh/groupoffice#539]
1. Open GO web interface and address book.
2. Make new test contact.
3. Open https://groupoffice.url/carddav/addressbooks/username/abnumber/
4. Try to find contact you added last (I searched by date and year and hour).

New contacts aren't shown, but updated old contacts are shown with correct modified time.
New contacts made in GO aren't synced to Cardbook addon (version 43.5) in Thunderbird (version 68.4). It shows total number of contacts same as GO web interface, but it also shows that it synced only XX which is always less then total. It isn't showing any errors, but since it's syncing only old contacts and not new, my guess is that you somehow broke carddav format (or compatibility), or just aren't making new contacts available to carddav interface as mentioned above.

**Comment by mschering** [comment]
This has been fixed in 6.4.101
