### ISSUE TITLE
Folder hierarchy issues

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#540]
If you have a sub-folder ( using . as hierarchy ): Sales.Agents.John

and you remove that folder and the folder goes to the Trash folder

GO pretty much breaks down because inside Trash, Sales.Agents.John has no parent folders...

**Comment by mschering** [comment]
I think this has been fixed in the latest release as it moves the folder to the trash

**Comment by mschering** [comment]
I can't replicate this in the current version anymore (6.4). I think this was fixed recently.
