### ISSUE TITLE
Email Usage Not Showing Correctly

### ISSUE THREAD

**Issue by gabotronix** [Intermesh/groupoffice#546]
Version: Group Office 6.4.97
Installation: Ubuntu 18.04 LTS

I found an issue in panel > **E-mail domains**, where **Usage** of some domains are showing as **0 bytes**.

Upon checking the actual usage of an email account from that domain using the shell command, `doveadm quota get -u user@domain.com`, the results were not 0. So, it must be an issue on GO's side.

I found out that the script from the cron job in `/etc/cron.d/groupoffice-mailserver` stops when it encounters an email account that's disabled (Active = false).

I ran the script manually from command line:
`/usr/share/groupoffice/groupofficecli.php -r=postfixadmin/mailbox/cacheUsage -c=/etc/groupoffice/config.php`

It stopped when it saw a disabled account:
`Calculating size of /home/vmail/domain.com/john.doe/Maildir`
`Error: A non-numeric value encountered`

As a result, all the other domains and email accounts, regardless of their status (active or inactive), were not processed. The workaround is obviously, to enable or delete all disabled accounts.

**Comment by mschering** [comment]
Fixed in the next 6.4 release.
