### ISSUE TITLE
Postfix Maildir Folder is Hardcoded

### ISSUE THREAD

**Issue by mergeMarc** [Intermesh/groupoffice#547]
## Description 
The path to the mail folders is hardcoded in the postfixadmin module model. If the emails are stored in another path the mailbox usage will always show up as 0 in GroupOffice (Postfix/Dovecot still enforces the real limit).

https://github.com/Intermesh/groupoffice/blob/c945debced6cb0d508967d65b3e03a07dbec7317/www/modules/postfixadmin/model/Mailbox.php#L150

## Steps to reproduce

1.  Install GroupOffice
2. Change your Postfix, Dovecot configuration to store your inboxes in a non standard folder (`/var/local/mails/` for example).
3. Get some incoming E-Mails
4. Run the Postfixadmin Cronjob
4. Log into GroupOffice
5. Go to **Postfix**>Pick a Domain>**Mailboxes** 
6. Notice the Mailbox usage column

### Expected
I can have my dovecot/postfix store e-mails wherever i want on the server. The mailbox usage will show the actual occupied storage. I might have to provide the mail folder path in the main GroupOffice configuration file.

### Actual
If my mail folders are not in the standard `/home/vmail` folder, the mailbox usage column will always show 0. I have no way to tell GroupOffice that my mail folder path is somewhere else.

## My Environment
GO: 6.2.122 (This issue still persists in master)
OS: Ubuntu 18.04.3 LTS
Apache: 2.4.29
PHP: 7.2.24

> To Intermesh employees: See ticket 201919315

**Comment by mschering** [comment]
Fixed in version 6.4 now.
