### ISSUE TITLE
The CustomField Contact type does not use the addressBookId filter

### ISSUE THREAD

**Issue by lszabados** [Intermesh/groupoffice#548]
While looking at the code, you can theoretically filter to addressBookId, but you will not pass this parameter during filtering and will not get its value in the CustomField panel. In the migrated data, the options field contains our previous settings but does not use it. 

1. The /go/modulse/community/addressbook/views/extjs3/customfield/Contact.js
Add line to line 63: 	`c.addressBookId = customfield.options.addressBookIds;`

2. The /go/modulse/community/addressbook/views/extjs3/customfield/ContactDialog.js

Add new form numberfield item. 
  
`{
  xtype:'numberfield',
  decimals: 0,
  fieldLable: t("AddressBookId"),
  name: "options.addressBookIds",
  value: null,
  anchor: "100%"
}`

It works for me, but it would be nice to get into the official build.

**Comment by mschering** [comment]
This is in the next release.
