### ISSUE TITLE
VTimezone.php array issue

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#550]
in go/base/vobject/VTimezone.php

this code is faulty because on the last iteration when $i < $max, you are trying to read $i+1

                for ($i = 0, $max = count($transitions); $i < $max; $i++) {
                        if ($transitions[$i]['ts'] > $start_of_year) {

                                $weekday1 = $this->_getDay($transitions[$i]['time']);
                                $weekday2 = $this->_getDay($transitions[$i+1]['time']);

example:
array has 5 items (0,1,2,3,4)
first iteration: i is 0, max is 5
last iteration: i is 4, max is 5, $weekday2 tries to getDay(array[4+1]) which doesn't exist and errors out

not sure what the right fix would be

**Comment by mschering** [comment]
When did you encounter this error? The code is faulty indeed but it should never reach the end :)
