### ISSUE TITLE
Login as user / logout issue in Edge

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#555]
As title says, latest version 6.4.111 login as user from admin and logout from any account doesn't work in Edge. Please investigate

**Comment by mschering** [comment]
Did you perhaps login with basic auth on a /*dav or /Microsoft-Server-ActiveSync page?

**Comment by gtech99** [comment]
no, you can test this bug on your demo page:
https://demo.group-office.eu/

Try and logout using Edge

**Comment by mschering** [comment]
I can login and logout fine using edge.

Can you open the developer console and see if there are errors when logging out?

**Comment by gtech99** [comment]
I did, please see here: https://gofile.io/?c=hyVK7G

no errors come up, that warning you see in the video at the end shows regardless of whether I press logout or no. 

My version of edge is: Microsoft Edge 44.17763.831.0 / Microsoft EdgeHTML 18.17763

**Comment by mschering** [comment]
Aha I tested with the new chromium based edge. Please upgrade :)

**Comment by gtech99** [comment]
works for me too in that one but still, a lot of people using old edge.

Can you try and find a fix or maybe show a warning when users are using Edge to tell them it won't work ? Right now it's very confusing because people can't log out and no errors are shown anywhere, possibly other functionality is broken too.

**Comment by mschering** [comment]
I'm thinking of closing this one as no sensible person uses old Edge ;) ?

**Comment by derjoachim** [comment]
Since Edge is fully Chromium now (even on Linux!), I am brutally closing this ticket.
