### ISSUE TITLE
CardDav syncs only one way

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#556]
When syncing from Android or Lineage with DavX5 then changes on smartphone are not synced to server. Changes in GO are synced correctly. This behaviour is observed on 3 devices since several weeks. 
The sync log on device has been checked by DavX5 support people, they say all is okay, except that the server sends another UID of the contact and in that case the server always wins, even if a record has been changed on the device.
DavX5 syncing on the same devices works fine with nextcloud contacts, though.

**Comment by rasos** [comment]
DavX5 guys @bitfire have helped to debug this, here is their report:

Technically spoken etags are used to determine if a resource has changed on the server. This etag has to be in a special format - see the standard here [1].

In case of groupoffice they are sending the etag without the necessary quotes. These quotes are mandatory and therefore - when we try to send an updated resource to the server with the quotes - the server does not accept the resource. You can also try/reproduce it on the terminal console when using these commands (you don't need our app DAVx5 for this):


1. Get a vCard and its ETag

$ curl -vu maria.tester@fairkom.net:fairkom https://fairkom.net/carddav/addressbooks/maria.tester@fairkom.net/822/121387@fairkom.net-groupoffice.vcf >1.vcf

< HTTP/2 200
< etag: 568ab8984a865dd8628a1859cc627be9172dad37
The ETag is not within DQUOTE, which is not allowed – let's assume the ETag is "568ab8984a865dd8628a1859cc627be9172dad37"

2. Upload the same vCard again, with If-Match and the same ETag

$ curl -vu maria.tester@fairkom.net:fairkom -T 1.vcf -H 'If-Match: "568ab8984a865dd8628a1859cc627be9172dad37"' https://fairkom.net/carddav/addressbooks/maria.tester@fairkom.net/822/121387@fairkom.net-groupoffice.vcf

< HTTP/2 412
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.2.2</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>
  <s:header>If-Match</s:header>
</d:error>

!!! Should be successful, but it is not. This is why DAVx⁵ and probably other conforming clients can't upload contacts.

3. Upload the vCard, with unquoted incorrect ETag

curl -vu maria.tester@fairkom.net:fairkom -T 1.vcf -H 'If-Match: 568ab8984a865dd8628a1859cc627be9172dad37' https://fairkom.net/carddav/addressbooks/maria.tester@fairkom.net/822/121387@fairkom.net-groupoffice.vcf

< HTTP/2 204
< etag: 568ab8984a865dd8628a1859cc627be9172dad37
!!! Success

[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19

**Comment by mschering** [comment]
Thanks for pursuing this. I changed the etags. Hopefully next version works for you!

**Comment by rasos** [comment]
Confirming that syncing of contacts now works again both ways.
