### ISSUE TITLE
File compress permissions

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#558]
Looks like there is a bug on line 1302 - FolderController.php

Instead of 

```
if($destinationFolder->checkPermissionLevel(\GO\Base\Model\Acl::READ_PERMISSION)){
      throw new AccessDenied();
}
```

there should be

```
if(!$destinationFolder->checkPermissionLevel(\GO\Base\Model\Acl::WRITE_PERMISSION)){
    throw new AccessDenied();
}
```

**Comment by michalcharvat** [comment]
@mschering Please could you take a look on it?

**Comment by rvdartel** [comment]
Hello Michal,

I thought I had it fixed by changing the module permissions but your solution is better. Thank you
