### ISSUE TITLE
Request for implementing lables for email account

### ISSUE THREAD

**Issue by s1-ranjan** [Intermesh/groupoffice#560]
I was just thinking about to implementing the labes feature for email id as shown below in the image,
![Screenshot from 2020-02-21 23-42-03](https://user-images.githubusercontent.com/20767253/75060536-011b8680-5505-11ea-9ba7-8c2650c61c76.png)
As of now the email id are been shown, with this feature user have more choice to personalize their email interface.

**Comment by mschering** [comment]
Sorry, the e-mail address works for us.
