### ISSUE TITLE
Cant delete Folder in E-Mail-Account

### ISSUE THREAD

**Issue by aks-AP** [Intermesh/groupoffice#563]
In Version: 6.4.117 our customer can't delete any folders in his E-Mail-Accounts. The Request is being answered with a 200 Code, but the folder isn't deleted.

Could you reproduce this error?

**Comment by mschering** [comment]
I think this is related to some IMAP accounts not allowing subfolders in the Trash folder. Currently GO moves the folder to the trash folder first. I think this case should be handled and then the user must be asked to delete the folder permanently without moving it to trash.

**Comment by mschering** [comment]
This will be fixed in the next release.
