### ISSUE TITLE
PHP 7.4 issues

### ISSUE THREAD

**Issue by kmribti** [Intermesh/groupoffice#571]
File module not working.

  EXCEPTION: Exception: Serialization of 'ReflectionClass' is not allowed in /var/www/html/go/base/cache/Apcu.php:40
        Stack trace:
        #0 /var/www/html/go/base/cache/Apcu.php(40): apcu_store()
        #1 /var/www/html/modules/files/FilesModule.php(131): GO\Base\Cache\Apcu->set()
        #2 /var/www/html/modules/files/model/File.php(836): GO\Files\FilesModule::getAllFileHandlers()
        #3 /var/www/html/modules/files/controller/FolderController.php(963): GO\Files\Model\File->getDefaultHandler()
        #4 [internal function]: GO\Files\Controller\FolderController->formatListRecord()
        #5 /var/www/html/go/base/data/ColumnModel.php(390): call_user_func()
        #6 /var/www/html/go/base/data/Store.php(170): GO\Base\Data\ColumnModel->formatModel()
        #7 /var/www/html/go/base/data/Store.php(202): GO\Base\Data\Store->nextRecord()
        #8 /var/www/html/modules/files/controller/FolderController.php(824): GO\Base\Data\Store->getData()
        #9 /var/www/html/go/base/controller/AbstractController.php(489): GO\Files\Controller\FolderController->actionList()
        #10 /var/www/html/go/base/controller/AbstractController.php(398): GO\Base\Controller\AbstractController->callActionMethod()
        #11 /var/www/html/go/base/Router.php(182): GO\Base\Controller\AbstractController->run()
        #12 /var/www/html/index.php(98): GO\Base\Router->runController()
        #13 {main}

**Comment by mschering** [comment]
Sorry, php 7.4 is not supported yet. We'll look into that soon.

**Comment by mschering** [comment]
This one and some other php 7.4 issues are fixed.
