### ISSUE TITLE
some issues on 6.4.130

### ISSUE THREAD

**Issue by remmedia** [Intermesh/groupoffice#574]
after latest update (6.4.130) mail counter in menu does not refresh, nor does imap changes on folders do (i mark email as read on mobile but on group office there is no change as long as i do not refresh manual)

**Comment by thomasgg23** [comment]
Can confirm that issue, has been there since 6.4.129. Didn't had the time to fill a report.

Manual refresh works.

**Comment by mschering** [comment]
Fixed for the next release.
