### ISSUE TITLE
Integrity constraint violation if calendar color changed to auto

### ISSUE THREAD

**Issue by me-sp** [Intermesh/groupoffice#575]
Version: 6.4.132 (https://demo.group-office.eu/)

If I change the calendar color of e.g. "Demo User" to auto, I get this error

`
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'color' cannot be null`

This error also occurs with version 6.4.131 (self hosted)

**Comment by mschering** [comment]
Fixed in the next release!
