### ISSUE TITLE
 6.4.137 Error Uncaught TypeError: fb.sendOverwrite is not a function

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#576]
Hi, 

we got the following error, when trying to upload a file to a task.

The console output 
Uncaught TypeError: fb.sendOverwrite is not a function
    at sb.uploadComplete (script.php?v= 1588860327:4023)
    at callback (script.php?v= 1588860327:3810)
    at callback (script.php?v= 1588860327:1889)
    at Ext.data.Connection.handleResponse (ext-all-debug.js?mtime=1588336698:4661)
    at handleTransactionResponse (ext-base-debug.js?mtime=1588336698:2327)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js?mtime=1588336698:2433)

Don't know where to look what I perhaps missed in configuration.

**Comment by mschering** [comment]
Strange, I can't replicate this in 6.4.138. But there was no such issue fixed in this release.

**Comment by thomasgg23** [comment]
Could it be a configuration issue?
Perhaps some faulty rights on a module?

Didn't know where to look.

**Comment by thomasgg23** [comment]
Strange.
I got two installations with the same version / linux system etc. Similar groupoffice settings.
In one the upload works, in one not.

I encountered when you upload the file via the filebrowser it works without a problem. When I upload it via the task, the error occurs. 

The error also occurs in every dotted field with the text "put your files here". Upload via filebrowser works.

**Comment by mschering** [comment]
Found it. Its happens when the files tab is closed with right click on the tab.
