### ISSUE TITLE
Email - embedding pictures

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#577]
Composing a mail in html mode (6.4.136) with embedded pictures do not attach the picture. The file will only be linked and the recipient (outside of GroupOffice) will get a broken picture icon.

**Comment by mschering** [comment]
Which browser? And how you embed? (menu, drag drop or cut & paste)?

**Comment by fischli** [comment]
firefox usually. It only happens with copy+paste or as drop into the html editor frame.

**Comment by mschering** [comment]
Which OS do you use? I can't reproduce it in any browser on macOS.

**Comment by fischli** [comment]
windows and linux with firefox or chrome. It doesn't matter. Only a link to "/go/api/download.php?blob=3D65456..." will be inserted.

**Comment by mschering** [comment]
Yes, the link is correct. But when sending GO should detect it and replace it with an inline image link. Can you give me a test account on your environment so I can try to reproduce it there?

**Comment by fischli** [comment]
I would assume that this issue was triggered by a wrong Settings->General->URL. Embedding and/or attaching files only works reliable in the local network. I do have the following URL "http://go.fischer.ing/go/" in my settings.
In consequence it does not work if I come from another network path. We use differnet ways to access GroupOffice. Maybe the user uses a vpn or a mobile device from public internet. In this case the user has to use a different url and/or ip address and uploading does not work anymore. Pretty bad!

**Comment by mschering** [comment]
Yes, we recently changed this. It determines the URL from your browser now. Please upgrade.
