### ISSUE TITLE
Forwarding as attachment has a blank subject

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#578]
When you forward as attachment, the subject is blank. A message I sent was rejected, due to RFC 5321 that doesn't permit blank subject.

I think it might be worth adding origial subject of message, as Thunderbird does, or in case of several messages, subject of the first.

Thanks.

**Comment by mschering** [comment]
Sorry, but why don't you just enter a subject?

**Comment by flaviozluca** [comment]
Hi, friend
Sure, I can, but why not make it work 100% by default? Several clients I tested put the subject. It avoid's users error as happened in my case.
my report was in the best intention to improve GO. Not a big deal, of course, but IMHO worth improving.
Thanks a lot.
 Atenciosamente/Regards,

Flávio Zarur Lucarelli
Sócio-Diretor
LucaNet Sistemas (http://www.lucanet.com.br)
55-21-3005-9310 / 55-11-2122-4256
Celular / WhatsApp: 21-99542-4180 
Em Ter, Mai 12, 2020 às 08:26, Merijn Schering  escreveu: 
 Sorry, but why don't you just enter a subject?

**Comment by mschering** [comment]
I've fixed this. When forwading a single message it adds Fwd: subject. When multiple email are forwarded it's still blank.

**Comment by flaviozluca** [comment]
Thanks so much, Merijn!!
