### ISSUE TITLE
Mailbox autocreation with LDAP does not work

### ISSUE THREAD

**Issue by mdebus** [Intermesh/groupoffice#579]
- LDAP authentication itself works
- mailbox auto creation through serverclient module works, when I manually add a non-LDAP user

In the old documentation a config option ("'ldap_create_mailbox_domains") was mentioned but this seems not to work anymore.

**Comment by mschering** [comment]
Try enabling debug and see what happens.
The latest version has a new option to login with the email address instead of the LDAP username to the IMAP server. Perhaps that solves your problem too?

**Comment by mdebus** [comment]
Sorry, I have to open this again.

If using LDAP there is no mailbox created upon login. Is serverclient used when LDAP authentication is active? The documentation says nothing about this.

Login to Dovecot fails, because there is no mailbox for this user in the DB. 

Is there any way I can debug this?

**Comment by pmitCZ** [comment]
> Sorry, I have to open this again.
> 
> If using LDAP there is no mailbox created upon login. Is serverclient used when LDAP authentication is active? The documentation says nothing about this.
> 
> Login to Dovecot fails, because there is no mailbox for this user in the DB.
> 
> Is there any way I can debug this?

I have the same problem, did you manage to solve it somehow?

**Comment by mschering** [comment]
Sorry, the serverclient is only used when creating users from the web UI.

In most cases when LDAP was used this LDAP server was also used as backend for the mailserver. So these mailboxes already exist.

Contact us if you'd like us to offer a tailor made solution for you.

**Comment by pmitCZ** [comment]
Thank you for the response. I still have one more question. What does the checkbox 'Create e-mail account for users' do in LDAP authentication?

**Comment by mschering** [comment]
It creates a new e-mail account. Not on the mail server but as a client.
