### ISSUE TITLE
6.4.141 Quota cronjob not displayed correct

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#580]
When this job is run 

/usr/share/groupoffice/groupofficecli.php -r=postfixadmin/mailbox/cacheUsage -c=/etc/groupoffice/config.php -q

We always get an e-mail with empty entries like this

Quota name Type    Value  Limit                        %
Quota name Type    Value   Limit                        %
Quota name Type       Value    Limit                      %
Quota name Type      Value   Limit                       %
Quota name Type     Value   Limit                       %
Quota name Type      Value    Limit                       %
Quota name Type       Value    Limit                      %
Quota name Type       Value    Limit                      %
Quota name Type       Value    Limit                      %
Quota name Type      Value    Limit                       %
Quota name Type       Value    Limit                      %
Quota name Type      Value    Limit                       %
Quota name Type      Value   Limit                       %
...

When executing the job at the command line this is shown

Calculating size of /var/mail/vhosts/XXX.XXX/admin/Maildir
Quota name Type    Value  Limit                        %
202,0 K

Calculating size of /var/mail/vhosts/XXX.XXX/XXX.XXX/Maildir
Quota name Type    Value   Limit                        %
89,6 M

Calculating size of /var/mail/vhosts/XXX.XXX/XXX/Maildir
Quota name Type       Value    Limit                      %
23,4 G

and so on.

Is this an configuration issue with dovecot or groupoffice?

**Comment by mschering** [comment]
Which version do you use?

**Comment by thomasgg23** [comment]
6.4.141

Von meinem iPhone gesendet

**Comment by mschering** [comment]
Fixed in the next release
