### ISSUE TITLE
No Input Field for {user:department}

### ISSUE THREAD

**Issue by jostu2007** [Intermesh/groupoffice#581]
i just edit the email templates  and I noticed that there was no inputfield that serves the placeholder {user:department}, maybe it's just unfindable by users.

**Comment by derjoachim** [comment]
As per the [Documentation](https://groupoffice.readthedocs.io/en/latest/using/email.html#template-variables): 

> Fields of the logged in user

> {user:displayName}
> {user:email}
> {user:username}
> {user:\*} Any contact field listed below can be used if this user has a profile (6.4+).
> {usercompany:\*} Any company field listed below can be used if this user has a profile (6.4+).

There is a catch: the user has to fill in their profile.

This is an older ticket, that has been for an earlier version. I'll keep it open for a bit longer in case this does not answer the original question.
