### ISSUE TITLE
Error in GO in SyncFileSystem?

### ISSUE THREAD

**Issue by jvoix** [Intermesh/groupoffice#582]
Hello,

Using GO 6.4.142, I get this error when running the administrator's "Synchronize files" too:
```
Syncing users
mkdir(): File exists
Syncing projects2
mkdir(): File exists
Syncing addressbook
mkdir(): File exists
Syncing notes
mkdir(): File exists
Syncing tickets
Done
Deleting email
You can't delete this system folder
Deleting billing/notifications
```

I did activate the debug flag and got the following log:

```
[administrator] global::mkdir in file /usr/share/groupoffice/go/base/fs/Folder.php on line 240
[administrator] [20180519 17:01:13] PHP Warning: mkdir(): File exists in /usr/share/groupoffice/go/base/fs/Folder.php on line 240
[administrator] global::mkdir in file /usr/share/groupoffice/go/base/fs/Folder.php on line 240
[administrator] [20180519 18:02:43] PHP Warning: mkdir(): File exists in /usr/share/groupoffice/go/base/fs/Folder.php on line 240
[administrator] global::mkdir in file /usr/share/groupoffice/go/base/fs/Folder.php on line 240
        EXCEPTION: ErrorException: mkdir(): File exists in /usr/share/groupoffice/go/base/fs/Folder.php:279
        #0 [internal function]: go\core\ErrorHandler::errorHandler(2, 'mkdir(): File e...', '/usr/share/grou...', 279, Array)
        #1 /usr/share/groupoffice/go/base/fs/Folder.php(279): mkdir('/home/groupoffi...', 493, true)
[error][go\core\ErrorHandler:64] ErrorException in /usr/share/groupoffice/go/base/fs/Folder.php at line 279: mkdir(): File exists
[error][go\core\ErrorHandler:67] #0 [internal function]: go\core\ErrorHandler::errorHandler(2, 'mkdir(): File e...', '/usr/share/grou...', 279, Array)
[error][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/go/base/fs/Folder.php(279): mkdir('/home/groupoffi...', 493, true)

```

Does anyone of you have an idea on what could cause this issue?

Thanks.

Jeremie

**Comment by mschering** [comment]
Can you retry this with the latest version? I think it will give a more detailed error message. Could it be that there's a symlink or file with the same name?

**Comment by jvoix** [comment]
Using GO 6.4.181, I'm getting the same error message (and the file are not synced!).

The logfile is quite long, and I just look for the word "error", resulting in

`me@mygoserver:/home/groupoffice/log$ cat debug.log |grep error
[log][go\core\ErrorHandler:118] ErrorHandler:errorHandler called 2
[error][go\core\ErrorHandler:64] go\core\jmap\exception\InvalidResultReference in /usr/share/groupoffice/go/core/jmap/Router.php at line 259: Could not resolve path part changed
[error][go\core\ErrorHandler:67] #0 /usr/share/groupoffice/go/core/jmap/Router.php(219): go\core\jmap\Router->resolvePath(Array, Array)
[error][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/go/core/jmap/Router.php(205): go\core\jmap\Router->resolveResultReferences(Array)
[error][go\core\ErrorHandler:67] #2 /usr/share/groupoffice/go/core/jmap/Router.php(92): go\core\jmap\Router->callAction('Search/get', Array)
[error][go\core\ErrorHandler:67] #3 /usr/share/groupoffice/go/core/jmap/Router.php(68): go\core\jmap\Router->callMethod(Array)
[error][go\core\ErrorHandler:67] #4 /usr/share/groupoffice/api/jmap.php(14): go\core\jmap\Router->run()
[error][go\core\ErrorHandler:67] #5 {main}
            [0] => error
[error][go\core\ErrorHandler:64] Exception in /usr/share/groupoffice/go/base/Model.php at line 109: Can't set not existing property 'modifiedAt' in 'GO\Calendar\Model\Event'
[error][go\core\ErrorHandler:67] #0 /usr/share/groupoffice/go/base/db/ActiveRecord.php(4439): GO\Base\Model->__set('modifiedAt', Object(go\core\util\DateTime))
[error][go\core\ErrorHandler:67] #1 /usr/share/groupoffice/go/base/db/ActiveRecord.php(4283): GO\Base\Db\ActiveRecord->setAttribute('modifiedAt', Object(go\core\util\DateTime))
[error][go\core\ErrorHandler:67] #2 /usr/share/groupoffice/go/core/orm/CustomFieldsTrait.php(260): GO\Base\Db\ActiveRecord->__set('modifiedAt', Object(go\core\util\DateTime))
[error][go\core\ErrorHandler:67] #3 /usr/share/groupoffice/go/base/db/ActiveRecord.php(3226): GO\Calendar\Model\Event->saveCustomFields()
[error][go\core\ErrorHandler:67] #4 /usr/share/groupoffice/go/base/db/ActiveRecord.php(4920): GO\Base\Db\ActiveRecord->save(true)
[error][go\core\ErrorHandler:67] #5 /usr/share/groupoffice/modules/calendar/model/Event.php(2325): GO\Base\Db\ActiveRecord->duplicate(Array, true, true)
[error][go\core\ErrorHandler:67] #6 /usr/share/groupoffice/modules/calendar/controller/EventController.php(1858): GO\Calendar\Model\Event->createCopyForParticipant(Object(GO\Calendar\Model\Participant))
[error][go\core\ErrorHandler:67] #7 /usr/share/groupoffice/go/base/controller/AbstractController.php(500): GO\Calendar\Controller\EventController->actionInvitation(Array)
[error][go\core\ErrorHandler:67] #8 /usr/share/groupoffice/go/base/controller/AbstractController.php(398): GO\Base\Controller\AbstractController->callActionMethod('actioninvitatio...', Array)
[error][go\core\ErrorHandler:67] #9 /usr/share/groupoffice/go/base/Router.php(182): GO\Base\Controller\AbstractController->run('invitation', Array)
[error][go\core\ErrorHandler:67] #10 /usr/share/groupoffice/index.php(109): GO\Base\Router->runController()
[error][go\core\ErrorHandler:67] #11 {main}
[log][go\core\ErrorHandler:118] ErrorHandler:errorHandler called 2
[log][go\core\ErrorHandler:118] ErrorHandler:errorHandler called 2
[log][go\core\ErrorHandler:118] ErrorHandler:errorHandler called 2
`

Would the full log be more helpful for you?

Thanks.

**Comment by jvoix** [comment]
Indeed, with a more recent version of GO (6.4.207) I can see the detailed error message... and it was -as suggested by @mschering - a bad symlink that was blocking the whole process. Good job on making these error messages more explicit! :-)
