### ISSUE TITLE
ab_addressbooks.default_salutation not changing

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#585]
Changing the above content in the addressbook changes nothing.

Still getting the salutation added to new emails.

**Comment by mschering** [comment]
Hi,

ab_addressbooks is an old table. Are you using 6.4?

**Comment by lonesomewalker** [comment]
Yes :-)
Always upgraded to latest.
And this is in several installations.

**Comment by mschering** [comment]
Ok, but that table is just left from previous versions. It's no longer used. the addressbook_* are now used.
