### ISSUE TITLE
Upload in 6.4.147 is not possible

### ISSUE THREAD

**Issue by NT58** [Intermesh/groupoffice#588]
After updating to Version: 6.4.147 yesterday in the evening it is no more possible to upload files as attachements or in file area at all.
Regardles what i am doing in config.php or "System settings URL"
there pops a message up on the right  "Uploads 100% 1of1,  file abort all, Details Upload fehlgeschlagen, name of file, Please check if the System is using the correct URL at System settings -> General -> URL."

I need a solution. Please.

Addendum:
in /var/www/html are no groupoffice files but GO searches for on upload.

apache error.log:

[Thu Jun 11 09:16:40.580280 2020] [php7:warn] [pid 11049] [client 192.168.15.8:49378] PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/api/upload.php on line 9, referer: https://192.168.15.111/groupoffice/

[Thu Jun 11 09:16:40.580297 2020] [php7:error] [pid 11049] [client 192.168.15.8:49378] PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/api/upload.php on line 9, referer: https://192.168.15.111/groupoffice/

[Thu Jun 11 09:18:34.333039 2020] [php7:warn] [pid 8637] [client 192.168.15.8:49428] PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/api/upload.php on line 9, referer: https://192.168.15.111/groupoffice/

[Thu Jun 11 09:18:34.333062 2020] [php7:error] [pid 8637] [client 192.168.15.8:49428] PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/api/upload.php on line 9, referer: https://192.168.15.111/groupoffice/

[Thu Jun 11 09:22:22.397418 2020] [core:info] [pid 11472] [client 192.168.15.8:49533] AH00128: File does not exist: /var/www/html/api/upload.php, referer: https://192.168.15.111/groupoffice/

in apache2  *.conf 
#Main web applications
Alias /groupoffice /usr/share/groupoffice

**Comment by mschering** [comment]
HI,

Please upgrade to v..6.4.149. This bug has been fixed now.
