### ISSUE TITLE
6.4.149 Display error when moving e-mail in selection

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#589]
When moving i.e. an email from my inbox to another folder (within the same IMAP account) you see in the animated gif, that when you move the email the selection will jump to the next e-mail and even display the text of the next e-mail in the preview.

It is just an display error, because the right e-mail is moved. But it triggers a lot of confusion.

![error_selection](https://user-images.githubusercontent.com/2633051/84654160-fb600b80-af0e-11ea-90bd-189a6ec1c3b3.gif)

**Comment by gtech99** [comment]
Why do you think this is a bug ? Before when you moved messages it just refreshed the entire message list. It's much better this way

**Comment by mschering** [comment]
The new behaviour is almost there. I think it should jump to the next after dropping the email on a folder. I will change this.

**Comment by mschering** [comment]
Fixed in 6.4.156
