### ISSUE TITLE
Default Template is hardcoded and hidden 

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#59]
In file:

modules/addressbook/AddressbookModule.php

it appears the 'Best regards' template is uploaded at install time and can't be overwritten. It's also not visible in the Templates list:

As a suggestion:
- move templates to E-mail module, maybe merge with Signatures
- default template should be blank

This is where the template gets added but is not visible after..

                $message = new \GO\Base\Mail\Message();
                $message->setHtmlAlternateBody('{salutation},<br />
<br />
{body}<br />
<br />
'.\GO::t("Best regards", "addressbook").'<br />
<br />
<br />
{user:name}<br />
{usercompany:name}<br />');

**Comment by gtech99** [comment]
It's not. Even if I create a new one called 'Default', that text above is still showing up on newly composed e-mails

**Comment by mschering** [comment]
Are you sure you're not missing the templates menu:

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1314447/39930583-66973296-553b-11e8-81f1-96fd1464c9b7.png">

**Comment by gtech99** [comment]
Behavior appears to be like this. If the Template is read-only for the user, it won't appear in the Addressbook / Template list, but it does appear in the Compose screen. Maybe it's a good idea to show it as well in the Addressbook module ?

Also, another issue, as per the attached image.

If you start with the Default template, select None, select set this as Default Template, close the window and start it up again.. It will show template 'None' but with the template filled up in the window...
<img width="950" alt="capture" src="https://user-images.githubusercontent.com/15035337/39932439-23111208-550e-11e8-8a1b-37f6c55993ab.PNG">


Ideally, if possible, please leave template to 'None'

**Comment by mschering** [comment]
The behaviour for permissions is correct. We don't display read only templates in the administration because you're not allowed to administer them.

The bug when setting defaults is fixed.
