### ISSUE TITLE
I am conserned:

### ISSUE THREAD

**Issue by remi75** [Intermesh/groupoffice#590]
I decided to give another shot to GO, because I stumbled upon a bad bug : all the emails I send, to anyone , external or internal to my server, go to the 1st mailbox I have created .
Imagine me sending emails from 3 / 4 different accounts on GO, and come back 15minutes later to see all the emails landing on my mbox ... ;)

Anyway, lazy to fill-up a bug report , I went to sourceforge as usual to get the latest version, then I taught about github to see if there is any kind of change logs, because on sourceforge, nada.

I was very happy to see that GO is on github too , but

Why is the package on sourceforge more recent then the git repository ?

Best regards

**Comment by dehart** [comment]
We still release the packages on Sourceforge. I think we should put them on GitHub as well.

If all your outgoing emails go to the same mailbox you have probably configured a debug email address in System settings. This would cause the behaviour you describe

**Comment by remi75** [comment]
Well, that setting is for .. debugging, and it has been like that for the last 5 years

It is now at Version: 6.4.133 , the last two updates have not fixed it .

**Comment by mschering** [comment]
Did you disable the debug option in System Settings -> Notifications?

**Comment by remi75** [comment]
Thank you for doing it for me, I was too lazy ... and already switched to next-cloud .
