### ISSUE TITLE
6.4.150 - TypeError after reenabeling user

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#591]
An existing user has been disabled several month ago and now, after lots of update cycles, some modules will trigger an TypeError for this reenabled user. It happens while trying to use email and calendar module.
![image](https://user-images.githubusercontent.com/832201/85110948-edaecc80-b213-11ea-8a48-06c73d875e38.png)
![image](https://user-images.githubusercontent.com/832201/85110984-00290600-b214-11ea-82b5-142377f976dd.png)

**Comment by mschering** [comment]
Perhaps running /install/upgrade.php helps?

**Comment by fischli** [comment]
An upgrade to 6.4.153 and "php cli.php core/System/upgrade" probably fixed this issue.
