### ISSUE TITLE
Unable to upload files in GO after upgrading 6.3.90 -> 6.4.150

### ISSUE THREAD

**Issue by alexanonymous1** [Intermesh/groupoffice#592]
Hello,

After upgrading to the latest go version, I can't upload any files in the Files Module or as attachment in the Compose window.
I can't find any logs regards this error.

The only hint that I have is the error message in the right pane, Notifications window:
Please check if the system is using the correct URL at System settings -> General -> URL.
I already checked the URL value, in system settings -> general and in config.php (where that field is empty), all it seems to be ok configured.
![image](https://user-images.githubusercontent.com/67270070/85283576-455c6a80-b496-11ea-8344-310f4fd79f18.png)

One more thing, if I'm trying to upload a large file, over the php's upload max size, I receive the right 'error' message: File size exceeds the maximum 100mb.

Please help.
Thank you,

**Comment by fischli** [comment]
take a look at #577

**Comment by alexanonymous1** [comment]
Hello @fischli,

Yes, you are right.
Uploading files from local network is working, but from the outside of the network, using the server's public ip address and not the internal one, it doesn't work.
Do you know to what version @mschering suggests to upgrade to? I suppose is 6.4.148 but I already have the latest version (6.4.150).

Thank you,

**Comment by fischli** [comment]
I think @mschering talked about the latest version (6.4.150)

**Comment by mschering** [comment]
The URL for uploading used to be fixed to the one set in System Settings -> General -> URL but since the latest versions it determines it dynamically from the client request. So it should work everywhere now.
