### ISSUE TITLE
Upgrade from 6.1 to 6.3

### ISSUE THREAD

**Issue by RonGroen** [Intermesh/groupoffice#594]
I am running pro version Versie: 6.1.29 on Ubuntu 12.04.
Started a new (test) server on Ubuntu 18.04 and Latest version.

Standard Installation went oké.
After connecting my database I get.
Exception in /usr/share/groupoffice/go/core/Installer.php at line 251: This is not a Group-Office 6.3+ database. Please upgrade to 6.3.58 first.
I can't find the way to upgrade my current database.
Can you help?

**Comment by michalcharvat** [comment]
Did you upgrade to 6.3.58? Unless you can easily rename groupoffice folder created by packaging system, extrect to /usr/share/groupoffice package downloaded from sourceforge, upgrade to 6.3.58 and then simply replace this folder with backup.

**Comment by RonGroen** [comment]
I read you replay over and over but I don't understand.
I don't want to touch my current running server with Versie: 6.1.29 on Ubuntu 12.04.
Now I have installed GroupOffice 6.3 on Ubuntu 18.04 based on this documentation: https://groupoffice.readthedocs.io/en/latest/install/debian.html#core-system
then I copied my database from the old server to the new one and adjusted /etc/groupoffice/config.db accordingly. 
Starting GO gives: http://81.169.238.106/groupoffice/install/upgrade.php
Error: Exception in /usr/share/groupoffice/go/core/Installer.php at line 251: This is not a Group-Office 6.3+ database. Please upgrade to 6.3.58 first.

Question 1)
Is there a way to upgrade/update my database from 6.129 to 6.3.58?

Or do I have to  uninstall  6.3.58, Install 6.1.29 on the new server and than upgrade?

Thank you in advance
:-)

**Comment by mschering** [comment]
Hi Ron,

You need to upgrade in steps. First to 6.2, then 6.3 and finally 6.4.

More info can be found here:

https://groupoffice.readthedocs.io/en/latest/upgrade/upgrade.html

Good luck!
Merijn

**Comment by RonGroen** [comment]
Thank you Merijn,
I found the repository line for 6.2 on https://www.group-office.com/wiki/Installing_on_Debian_or_Ubuntu
deb http://repos.groupoffice.eu/ sixtwo main
But this is not valid for Ubuntu 18.04 or does not exist.

On https://groupoffice.readthedocs.io/en/latest/install/debian.html
I only found the latest version.
Where Can I find the right instructions for installing 6.2 on Ubuntu 18.04?
Regards
Ron

**Comment by RonGroen** [comment]
Additional information
apt-update gives
....
Genegeerd:4 http://repos.groupoffice.eu sixtwo InRelease            
Geraakt:5 http://repos.groupoffice.eu sixtwo Release                
Pakketlijsten worden ingelezen... Klaar
root@h2893867:/etc/apt/sources.list.d# apt-get install groupoffice
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
Pakket groupoffice is niet beschikbaar, hoewel er naar verwezen wordt door
een ander pakket. Mogelijk betekent dit dat het pakket ontbreekt,
verouderd is, of enkel beschikbaar is van een andere bron

**Comment by mschering** [comment]
For 6.2 the package name is groupoffice-com . So you have to do apt-get install groupoffice-com.
See also the old wiki for 6.2 https://www.group-office.com/wiki/Upgrading

**Comment by RonGroen** [comment]
Sorry Typo on my side.
