### ISSUE TITLE
6.4.153 CSP error in mixed environments

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#595]
Content security policy changed in go/views/Extjs3/themes/Paper/pageHeader.php and since then it is not possible to use differrent URLs anymore. We are using nginx as a proxy to access our internal GroupOffice and the following scenario doesn't work anymore.

1. WAN login with a mobil device from the internet (e.g. https://go.fischer-ing.net)
2. try to login with a different device directly located in the LAN (e.g. https://go.fischer.ing)
3. the second session does not succeed because of blocked resources by CSP

The user is not able to use different URLs. You may swap step 1 and 2, which means: only the first login succeeds. You have to clear the storage cache before login with an alternative URL. The problems may increase when the internal server only provides http.

**Comment by mschering** [comment]
Will be fixed in 6.4.156
