### ISSUE TITLE
Issue: Writing & Searching emails and contacts when you send email Version: 6.4.155

### ISSUE THREAD

**Issue by axrosen** [Intermesh/groupoffice#597]
Hello Again!
Still testing Group Office and just found a new issue. When I try to search for a contact or typing an email address when I write a new email I receive "Uncaught TypeError: Cannot read property 'length' of undefined".

This Is the error in the console:
script.php?v=1593552273:1915 server-side JMAP failure (3) ["error", {…}, "clientCallId-8"]0: "error"1: {message: "SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'UNION'"}2: "clientCallId-8"length: 3__proto__: Array(0)
(anonymous) @ script.php?v=1593552273:1915
success @ script.php?v=1593552273:1914
handleResponse @ ext-all-debug.js?mtime=1593551654:4658
handleTransactionResponse @ ext-base-debug.js?mtime=1593551654:2327
(anonymous) @ ext-base-debug.js?mtime=1593551654:2433
load (async)
asyncRequest @ ext-base-debug.js?mtime=1593551654:2432
request @ ext-base-debug.js?mtime=1593551654:2487
request @ ext-all-debug.js?mtime=1593551654:4633
processQueue @ script.php?v=1593552273:1914
(anonymous) @ script.php?v=1593552273:1912
setTimeout (async)
continue @ script.php?v=1593552273:1912
request @ script.php?v=1593552273:1908
doRequest @ script.php?v=1593552273:1944
request @ ext-all-debug.js?mtime=1593551654:25549
execute @ ext-all-debug.js?mtime=1593551654:24485
load @ ext-all-debug.js?mtime=1593551654:24384
(anonymous) @ script.php?v=1593552273:1979
load @ script.php?v=1593552273:1977
doQuery @ ext-all-debug.js?mtime=1593551654:42701
initQuery @ script.php?v=1593552273:879
call @ ext-all-debug.js?mtime=1593551654:1563
setInterval (async)
me.delay @ ext-all-debug.js?mtime=1593551654:1579
onKeyUp @ ext-all-debug.js?mtime=1593551654:42647
h @ ext-all-debug.js?mtime=1593551654:5205
ext-all-debug.js?mtime=1593551654:26242 Uncaught TypeError: Cannot read property 'length' of undefined
    at Ext.data.JsonReader.readRecords (ext-all-debug.js?mtime=1593551654:26242)
    at constructor.onRead (script.php?v=1593552273:1944)
    at constructor.callback (script.php?v=1593552273:1944)
    at Object.<anonymous> (script.php?v=1593552273:1917)
    at Array.forEach (<anonymous>)
    at Object.success (script.php?v=1593552273:1914)
    at Ext.data.Connection.handleResponse (ext-all-debug.js?mtime=1593551654:4658)
    at handleTransactionResponse (ext-base-debug.js?mtime=1593551654:2327)
    at XMLHttpRequest.<anonymous> (ext-base-debug.js?mtime=1593551654:2433)
readRecords @ ext-all-debug.js?mtime=1593551654:26242
onRead @ script.php?v=1593552273:1944
callback @ script.php?v=1593552273:1944
(anonymous) @ script.php?v=1593552273:1917
success @ script.php?v=1593552273:1914
handleResponse @ ext-all-debug.js?mtime=1593551654:4658
handleTransactionResponse @ ext-base-debug.js?mtime=1593551654:2327
(anonymous) @ ext-base-debug.js?mtime=1593551654:2433
load (async)
asyncRequest @ ext-base-debug.js?mtime=1593551654:2432
request @ ext-base-debug.js?mtime=1593551654:2487
request @ ext-all-debug.js?mtime=1593551654:4633
processQueue @ script.php?v=1593552273:1914
(anonymous) @ script.php?v=1593552273:1912
setTimeout (async)
continue @ script.php?v=1593552273:1912
request @ script.php?v=1593552273:1908
doRequest @ script.php?v=1593552273:1944
request @ ext-all-debug.js?mtime=1593551654:25549
execute @ ext-all-debug.js?mtime=1593551654:24485
load @ ext-all-debug.js?mtime=1593551654:24384
(anonymous) @ script.php?v=1593552273:1979
load @ script.php?v=1593552273:1977
doQuery @ ext-all-debug.js?mtime=1593551654:42701
initQuery @ script.php?v=1593552273:879
call @ ext-all-debug.js?mtime=1593551654:1563
setInterval (async)
me.delay @ ext-all-debug.js?mtime=1593551654:1579
onKeyUp @ ext-all-debug.js?mtime=1593551654:42647
h @ ext-all-debug.js?mtime=1593551654:5205

Thanks!
<img width="735" alt="Captura de Pantalla 2020-06-30 a la(s) 18 40 36" src="https://user-images.githubusercontent.com/67659006/86179723-319dad80-bb01-11ea-9119-c7723dcab6a3.png">
<img width="552" alt="Captura de Pantalla 2020-06-30 a la(s) 18 40 59" src="https://user-images.githubusercontent.com/67659006/86179768-40846000-bb01-11ea-9eaa-c420484e87d6.png">

**Comment by mschering** [comment]
Strange, can you check the collations of the tables core_user and addressbook_email_address and see if they’re both utf8mb4-Unicode-ci?

**Comment by axrosen** [comment]
Hi, yes they are.
<img width="1126" alt="Captura de Pantalla 2020-07-01 a la(s) 19 11 31" src="https://user-images.githubusercontent.com/67659006/86296229-af7bba80-bbce-11ea-8906-ff68446dc799.png">
<img width="1195" alt="Captura de Pantalla 2020-07-01 a la(s) 19 11 59" src="https://user-images.githubusercontent.com/67659006/86296252-bf939a00-bbce-11ea-97f7-8f28be775ab9.png">

**Comment by mschering** [comment]
And what about the fields in those tables:

core_user.displayName, core_user.email, core_user.avatarId, addressbook_contact.name, addressbook_email_address.email, addressbook_contact.photoBlobId.

They should all be having utf8mb4_unicode_ci except for photoBlobId and avatarId. They should both be binary.

**Comment by mschering** [comment]
Closing because there's no response.
