### ISSUE TITLE
6.4.155 Select of tasklists not keep when pages >2

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#598]
We habe a lot of tasks lists, so that one user has 2 pages of tasklists.
When selecting multiple tasklists from the first page and switching to the second page and selecting a list from the second page, all selections from the first page will be lost.

**Comment by mschering** [comment]
The only way to fix that currently is by increasing $config['nav_page_size'] = 100; for example.

**Comment by thomasgg23** [comment]
It works, thanks.
