### ISSUE TITLE
erroneous protocol in pages behind https proxy

### ISSUE THREAD

**Issue by beiDei8z** [Intermesh/groupoffice#599]
A recent change, (I can't say which because I can't back rev the installation to a last working version because old packages are not kept in the package repository), possibly since 6.4.150, has completely broken GO behind an https proxy.

My set up has nginx with TLS facing the World proxied to a virtual machine running Ubuntu and GO.  The proxy is http (no s).

The problem is the GO back-end thinks it is http: (no s) because that is the proxy URL used to call the back-end, it the embeds this non secure protocol in the pages.  This despite the site URL starting "https:" (System settings -> General -> URL).

The browser uses Strict-Transport-Security and blocks the files in the page, resulting in just a blank page to the user.  My browser's "padlock" in the URL bar shows insecure content is block and F12 and debug on the page shows the offending pages.

I have partially fixed this by changing the isHttps() functions,  used '//' (just double slash) for URLs. (Note function isHttps() is defined multiple times - once is one time too many.)  It would be even better if a page that stems from the root of the current server just started with a single slash only and dispensed with the complexity of adding a protocol and domain.  GO should either let the URLs use the enclosing page's protocol and domain or use the site URL.

My workaround is to run my GO sites without https.

**Comment by mschering** [comment]
Did you set this header on the Nginx proxy:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by beiDei8z** [comment]
No I did not. GO has no occurrence of X-Forwarded-Proto in its php so I don't see how it uses it. Whatever... I added:
   add_header X-Forwarded-Proto https;
to nginx and it made no difference.

**Comment by beiDei8z** [comment]
And another, it tries to load and blocks:
http://godomain.tld/groupoffice/api/auth.php?security_token=b4DxeWO8DHQdnft21Cpw

**Comment by fischli** [comment]
this issue also references #595
because of this, I added https to the internal webserver but it still delivers parts using http and CSP avoids a successfull loading

**Comment by beiDei8z** [comment]
Changing language on the https login page uses http. This is not an embedded link so a 301 corrects. and CSP does not block

**Comment by mschering** [comment]
I think it's because you didn't ran /install/upgrade.php after the header was set. Please try that.
In the next version it will use relative links everywhere so it shouldn't matter anymore.

**Comment by beiDei8z** [comment]
I ran /install/upgrade.php and it did fix it.  I won't attempt to understand why but I'm very happy that is does.

Using links starting / (where appropriate) should make it better anyway - unless you are paid by the square yard of code!

Thank you for your help and prompt responses.

**Comment by mschering** [comment]
It uses relative links in 6.4.156 now.

**Comment by beiDei8z** [comment]
6.4.156 installed, The added header and updated database did fix it for me however...
$ curl https://godomain/ | grep -c 'href="https://go'
...gives 8 matches
