### ISSUE TITLE
App.php syntax error

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#6]
Also, in go/core/App.php at line 154 you use '??' which is not valid. Did you want to use ternary operator ?

"dataPath" => $config['file_storage_path'] ?? '/home/groupoffice',

**Comment by mschering** [comment]
Actually, in php 7 this is valid. php 7 is the minimal version for 6.3.

**Comment by wsmits** [comment]
Please see this page: http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by gtech99** [comment]
Thank you, must have been a compatibility issue on my end after upgrading to 7.2.
