### ISSUE TITLE
Wrong label on Bill pdf

### ISSUE THREAD

**Issue by bastien-effetb** [Intermesh/groupoffice#600]
Hi,

I want to report a problem that occurs since last update on 6.4.

We need to show on each line of the bill the total amount without tax, and when we do so, the label of the column is "Total".

For better comprehension, in France we need to put the text "Total HT" which in english would be "Total excluding taxes".

I can update the label in the translation file, (modules/billing/language/fr.php) but If I do so, the label is also changed in the total including tax displayed in the bottom of the bill (surrounded in red in the attached picture)...
![image](https://user-images.githubusercontent.com/58260864/86769598-aa47c100-c04f-11ea-8037-4f7bf113bc8f.png)

So it would be really nice if you can use two different translations for these labels as they are not referring to the same type of amount (excluding taxes vs including taxes).

Best regards

**Comment by mschering** [comment]
I changed the label in the grid to "Total nett" and translated Total nett into Total HT for French.

**Comment by bastien-effetb** [comment]
Ok thank you, but how can i get this update on my local installation ?

**Comment by mschering** [comment]
It has just been released in 6.4.156.

**Comment by bastien-effetb** [comment]
Thank you very much for that quick fix, it's ok now.
