### ISSUE TITLE
Country label for french

### ISSUE THREAD

**Issue by bastien-effetb** [Intermesh/groupoffice#601]
Hi,

I have an issue with countries label on the bill pdf; it show the code instead of the label :
![image](https://user-images.githubusercontent.com/58260864/86892240-47623280-c100-11ea-8858-6d9bd386859e.png)

And there is also something strange in the translation file go/core/language/fr.php, the codes are not translated :
'FO' => 'pays[FO]',
    'FJ' => 'pays[FJ]',
    'FI' => 'pays[FI]',
    'FR' => 'pays[FR]',
    'FX' => 'pays[FX]',

I tried to update the translation, and after that it shows the country label in the dropdown list on the bill edit dialog, but on the PDF it keeps displaying the code

'FO' => 'pays[FO]',
    'FJ' => 'pays[FJ]',
    'FI' => 'pays[FI]',
    **'FR' => 'France',
    'FX' => 'France',**

Do I miss something ? On previous versions it was working,  I do not remember since which version it's not working anymore.

Thank you.

**Comment by mschering** [comment]
The countries contain invalid translations in the French file. I will remove them. After adjusting the language files manually you have to run /install/upgrade.php to clear the cache.

**Comment by derjoachim** [comment]
Have you run an `/install/upgrade.php` yet?

**Comment by bastien-effetb** [comment]
Yes I did

**Comment by bastien-effetb** [comment]
Can I have a reply as it is not solved ?
Thank you
