### ISSUE TITLE
6.4.159 - Email - Any simple search return "Sort error: <nothing>"

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#603]

**Comment by IT-AND-GENERAL** [comment]
I can see this issue on Firefox. It seems to work ok on Chrome.

**Comment by mschering** [comment]
Which field is selected for searching on?

**Comment by lonesomewalker** [comment]
I have the same issue now.
When searching in folders which are a bit "bigger" it takes longer -> might be a timeout issue?
Unfortunately when debugging, nothing usefull is shown.
Searching in all fields.

**Comment by mschering** [comment]
It probably is. Are you using the "Full message" option? It will only work fast if you setup IMAP with a Full Text search engine like solr.
