### ISSUE TITLE
6.4.156 - Integrity constraint violation on new email template

### ISSUE THREAD

**Issue by fischli** [Intermesh/groupoffice#606]
I get the following error when i try to apply or save a new email template. Modifying an existing one works as expected. I'm not able to add a new one anymore.
`PDOException in /var/www/GroupOffice/groupoffice-6.4.git/go/go/core/db/Statement.php at line 96: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Template' for key 'clientName'`

**Comment by mschering** [comment]
I can't replicate this one. Can you post a dump of your table "core_entity"?

**Comment by fischli** [comment]
As requested
[core_entity.txt](https://github.com/Intermesh/groupoffice/files/4970746/core_entity.txt)

**Comment by fischli** [comment]
![image](https://user-images.githubusercontent.com/832201/88921279-8bafa100-d26e-11ea-85e1-e379c96985a2.png)
still buggy database on 6.4.162
Any workarounds to fix db relations in this case?

**Comment by mschering** [comment]
Can you delete entry with id 48 from core_entity? It shouldn't be there.

**Comment by fischli** [comment]
OK! Error is gone! Thank you.
