### ISSUE TITLE
[Time registration] Entries copy bug

### ISSUE THREAD

**Issue by roosei** [Intermesh/groupoffice#608]
You have a time entry that is approved.
The user then makes a copy (left mouse button) to a future week day.
The status of the time entry is copied as well. (So when they're already closed, it's closed again)
The user should be entitled to copy the time and text only. It should be open to approval.
This, in my opinion, should not be happening.
Thanks!

**Comment by derjoachim** [comment]
As per the next release, a copied time entry will have the 'Open' status.

**Comment by derjoachim** [comment]
Hi,

This has been rolled out in 6.1.166. Closing this ticket.

Kind regards,
Joachim
