### ISSUE TITLE
Inline resize of images when composing bug

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#609]
When composing a new message and attaching an image inline, in Firefox it lets resize the image but not in Chrome

**Comment by flaviozluca** [comment]
this one remains in latest issue. if anyone can take a brief look, appreciate it. customer likes to use chrome and sometimes has to redimension images and it doesnt work. thanks.

**Comment by mschering** [comment]
It's a browser feature. Group-Office doesn't have this implemented in the editor.

**Comment by flaviozluca** [comment]
Thanks, Merijn. Possibility for future? I tested a few other webmails, they all let you either resize it dragging (even in Chrome) or change dimension. In Chrome, GO doesnt allow to resize in any way...

**Comment by mschering** [comment]
Yes, we might look into that later.

**Comment by flaviozluca** [comment]
Appreciate it, Merijn. All the best.

**Comment by mschering** [comment]
duplicate: #631
