### ISSUE TITLE
Not existing property ext-comp-2152

### ISSUE THREAD

**Issue by julyusito** [Intermesh/groupoffice#611]
Hello,

I've installed group office from hub.docker.com

Then enable the LDAP Authenticator module and restart apache, finally setup LDAP to SAMBA4 active directory mode, but the "Save" button does not working, does not save the configuration.

I was enable debug in config.php and when I hit "Save" button in Authentication config to add new domain I see this error:

[error][go\core\ErrorHandler:64] Exception in /usr/local/share/groupoffice/go/core/data/Model.php at line 256: Not existing property ext-comp-2152 for go\modules\community\ldapauthenticator\model\Server
[error][go\core\ErrorHandler:67] #0 /usr/local/share/groupoffice/go/core/data/Model.php(235): go\core\data\Model->setValue('ext-comp-2152', true)
[error][go\core\ErrorHandler:67] #1 /usr/local/share/groupoffice/go/core/jmap/EntityController.php(590): go\core\data\Model->setValues(Array)
[error][go\core\ErrorHandler:67] #2 /usr/local/share/groupoffice/go/core/jmap/EntityController.php(538): go\core\jmap\EntityController->create(Array)
[error][go\core\ErrorHandler:67] #3 /usr/local/share/groupoffice/go/core/jmap/EntityController.php(515): go\core\jmap\EntityController->createEntitites(Array, Array)
[error][go\core\ErrorHandler:67] #4 /usr/local/share/groupoffice/go/modules/community/ldapauthenticator/controller/Server.php(41): go\core\jmap\EntityController->defaultSet(Array)
[error][go\core\ErrorHandler:67] #5 [internal function]: go\modules\community\ldapauthenticator\controller\Server->set(Array)
[error][go\core\ErrorHandler:67] #6 /usr/local/share/groupoffice/go/core/jmap/Router.php(207): call_user_func(Array, Array)
[error][go\core\ErrorHandler:67] #7 /usr/local/share/groupoffice/go/core/jmap/Router.php(92): go\core\jmap\Router->callAction('LdapAuthServer/...', Array)
[error][go\core\ErrorHandler:67] #8 /usr/local/share/groupoffice/go/core/jmap/Router.php(68): go\core\jmap\Router->callMethod(Array)
[error][go\core\ErrorHandler:67] #9 /usr/local/share/groupoffice/api/jmap.php(14): go\core\jmap\Router->run()
[error][go\core\ErrorHandler:67] #10 {main}

Now, I uninstall the module and install it again, but now throw this error:

SQLSTATE[HY000]: General error: 1005 Can't create table `groupoffice`.`ldapauth_server` (errno: 150 "Foreign key constraint is incorrectly formed") on query (0) CREATE TABLE `ldapauth_server` ( `id` int(11) NOT NULL, `hostname` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL, `port` int(11) NOT NULL DEFAULT '389', `encryption` enum('ssl','tls') COLLATE utf8mb4_unicode_ci DEFAULT 'tls', `ldapVerifyCertificate` BOOLEAN NOT NULL DEFAULT TRUE, `followReferrals` BOOLEAN NOT NULL DEFAULT TRUE, `protocolVersion` TINYINT UNSIGNED NOT NULL DEFAULT '3', `username` VARCHAR(190) NULL DEFAULT NULL, `password` VARCHAR(512) NULL COLLATE ascii_bin DEFAULT NULL, `usernameAttribute` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'uid', `peopleDN` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ou=people,dc=example,dc=com', `groupsDN` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT 'ou=groups,dc=example,dc=com', `imapHostname` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `imapPort` int(11) NOT NULL DEFAULT '143', `imapEncryption` enum('tls','ssl') COLLATE utf8mb4_unicode_ci DEFAULT 'tls', `imapValidateCertificate` tinyint(1) NOT NULL DEFAULT '1', `imapUseEmailForUsername` BOOLEAN NOT NULL DEFAULT FALSE, `loginWithEmail` tinyint(1) NOT NULL DEFAULT '0', `smtpHostname` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `smtpPort` int(11) NOT NULL DEFAULT '587', `smtpUsername` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `smtpPassword` varchar(512) COLLATE ascii_bin DEFAULT NULL, `smtpUseUserCredentials` tinyint(1) NOT NULL DEFAULT '0', `smtpEncryption` enum('tls','ssl') COLLATE utf8mb4_unicode_ci DEFAULT NULL, `smtpValidateCertificate` tinyint(1) NOT NULL DEFAULT '1', `syncUsers` BOOLEAN NOT NULL DEFAULT FALSE, `syncUsersQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `syncGroups` BOOLEAN NOT NULL DEFAULT FALSE, `syncGroupsQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL ) ENGINE=InnoDB

Please help.

**Comment by derjoachim** [comment]
Both problems have been taken care of. in the 6.4 branch. They will be rolled out in the next release.

**Comment by julyusito** [comment]
Thank you.
Is there a way to install that branch?

**Comment by derjoachim** [comment]
If you installed as per the README, you are already running the 6.4 version. All you need to do, is run 

`docker-compose pull` 

from your installation subdirectory once in a while to keep up to date.

**Comment by derjoachim** [comment]
Rolled out in 6.4.166
