### ISSUE TITLE
Newsletter length limited to 65536 chars

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#614]
If you want to send a newsletter that includes an inline image, then chances are high that you get a message that the length of 65536 chars are exceeded. Only after deleting the image (in our case it was already compressed to 200k) sending was possible.

Please extend the length of the newsletter field.

**Comment by mschering** [comment]
Normally inline images are attached as attachment. How do you get it inline? Do you paste the full source?

**Comment by rasos** [comment]
Yes it seems that the user had pasted the image as source.
