### ISSUE TITLE
6.4.172 - Syncronization broken after upgrading to 6.4.172

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#615]
All users on both Android and iPhone gets access denied

**Comment by mschering** [comment]
I think I accidentally swapped this setting:

USE_FULLEMAIL_FOR_LOGIN

In modules/z-push/config.php

It only affects if you login with an @ sign in the username. Try changing it.

**Comment by IT-AND-GENERAL** [comment]
Hi,
Yes, we use LDAP so the @ sign is in the user name:  username@domain
I changed USE_FULLEMAIL_FOR_LOGIN from false to true and all seems to work fine now. 

Many thanks

**Comment by mschering** [comment]
Will be reverted in 6.4.173
