### ISSUE TITLE
Feature request: icon for CC/BCC

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#617]
Friends,

Customers always ask how to show CC/BCC. The current icon is not very intuitive.

Pls consider a more intuitive one, could even be CC or so written, or even some icon next to TO:

Thanks.

**Comment by derjoachim** [comment]
Hi Flavio,

This is better, no?

![image](https://user-images.githubusercontent.com/1264970/96424258-c20c1500-11fa-11eb-8e0f-411413972173.png)

I have added a more user friendly tooltip as well.

**Comment by flaviozluca** [comment]
Hi, friend

Awesome! Yes, that's really good. Thanks a lot.

All the best.

**Comment by IT-AND-GENERAL** [comment]
Awesome! 
I like it too.

**Comment by derjoachim** [comment]
Heh. Finally had an excuse to tackle this. :-) Will be released in 6.4.182
