### ISSUE TITLE
Request, hide work week

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#619]
Friends,

Just at all if possible... The option working week is not relevant for us... I enter know it lets you how many hours you work each day then it's used in other modules, but my users are very curious what it's for. The interface is not super clear, you just see week days with 2 values, separated by comma.

We cant hide it since its separate module, etc. If, by any chance, you find some way to let us hide it, we would appreciate it.

Thanks.

**Comment by derjoachim** [comment]
This is an old ticket which has possibly already been solved, but I'll bite. Are you referring to the business module? Or rather: could you elaborate with a screen shot or anything?

**Comment by flaviozluca** [comment]
Sorry for not replying sooner, I was checking with my sysadmin. I believe it's Ok. There used to be something regarding work hours, working week, inside My account, that my sysadmin said, I believe, at the time, he couldn't remove. I don't see it anymore. So it's Ok. ;)
Thanks.
