### ISSUE TITLE
Groupoffice

### ISSUE THREAD

**Issue by RobertoGrazzi-Palagini** [Intermesh/groupoffice#620]
With the latest update this error appears

Upgrade GroupOffice
Error: ErrorException in /usr/share/groupoffice/go/core/Installer.php at line 76: Creating default object from empty value

**Comment by mschering** [comment]
Your garbage collection cron job seems to be missing. The next release will auto fix that.

**Comment by RobertoGrazzi-Palagini** [comment]
when will the next update be available?


Roberto Grazzi
reparto ERP

[cid:image001.png@01D6A94B.C59D4CB0]

T 0571 961210
F 0571 920448
Via R. Martini, 70
50053 Empoli (FI) - Italy

Ai sensi e per gli effetti della Legge sulla tutela del trattamento dei dati ed alla protezione delle persone fisiche (Regolamento UE 2016/679 del Parlamento Europeo e del Consiglio del 27 aprile 2016) questa mail è destinata unicamente agli enti indicati e le informazioni in essa contenute sono da considerarsi strettamente riservate.
E' proibito leggere, copiare, usare o diffondere il contenuto della presente mail senza autorizzazione. Se avete ricevuto questo messaggio per errore siete pregati di rispedire la stessa al mittente. Grazie
Confidentially notice. This mail transmission may contain legally privileged and/or confidential information. Please do not read it if you are not the intended recipient(S). Any use, distribution, reproduction or disclosure by any other person is strictly prohibited. If you have received this mail in error, please notify the sender and destroy the original transmission and its attachments without reading or saving it in any manner.


Da: Merijn Schering <notifications@github.com>
Inviato: venerdì 23 ottobre 2020 12:04
A: Intermesh/groupoffice <groupoffice@noreply.github.com>
Cc: Roberto Grazzi <roberto.grazzi@palagini.it>; Author <author@noreply.github.com>
Oggetto: Re: [Intermesh/groupoffice] Groupoffice (#620)


Your garbage collection cron job seems to be missing. The next release will auto fix that.

**Comment by mschering** [comment]
Right now :)
