### ISSUE TITLE
availability in calendar shows HTML code

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#621]
Friends,

have you seen this? Notice the BOLD tag between the word PARTICIPANT.

![problem 1](https://user-images.githubusercontent.com/44004645/97042808-f576d880-1547-11eb-871f-70917be7519e.png)

**Comment by mschering** [comment]
Thanks, this was fixed some time ago.

**Comment by flaviozluca** [comment]
My pleasure. thank you!
