### ISSUE TITLE
Feature request: Bullet Lists in ticket system

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#622]
Hi,

would be nice to have some markup code/html code in the text field in the ticket system.
We use a lot of unordered lists and with nested lists it get's a ugly formating in ascii.

![image](https://user-images.githubusercontent.com/2633051/97145569-af4b9000-1766-11eb-9f3f-80527ec0f612.png)

**Comment by mschering** [comment]
We're working on a new version of the ticket system where the messages are made with HTML so they can contain inline images, lists etc.

**Comment by derjoachim** [comment]
Closing this ticket as current ticket module is being um.. sent to greener pastures.
