### ISSUE TITLE
[6.4.185] Error: PDOException with update

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#623]
Got the following error message when trying to update to the latest version 6.4.185

Error: PDOException in /usr/share/groupoffice/go/core/db/Connection.php at line 160: SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation

#0 /usr/share/groupoffice/go/core/db/Connection.php(160): PDO->exec('SET GLOBAL inno...')
#1 /usr/share/groupoffice/go/core/Installer.php(398): go\core\db\Connection->exec('SET GLOBAL inno...')
#2 /usr/share/groupoffice/install/upgrade.php(67): go\core\Installer->upgrade()
#3 {main}

**Comment by thomasgg23** [comment]
Ok fixed it with giving the groupoffice user SUPER rights in mysql and the switched it back.

**Comment by mschering** [comment]
Fixed in 6.4.186
