### ISSUE TITLE
6.4.187 - Notes - No prompt for password for old encrypted notes

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#626]
Cannot access the content of old encrypted notes.
There is no prompt for password. It only shows: Encrypted data
![image](https://user-images.githubusercontent.com/52159663/97572806-b7166900-19e0-11eb-94dc-47462b4adcb6.png)

**Comment by IT-AND-GENERAL** [comment]
Not sure if this was a user error ... it seems to happen only this one note.
All the others notes seems fine.

**Comment by derjoachim** [comment]
This was apparently a bit of a glitch. Closing this ticket. If the problem persists, please open a new support ticket.
