### ISSUE TITLE
advanced search, translation

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#627]
In advanced search (clicking on STAR), ADVANCED is untranslatable. Checked in Spanish, same thing.

**Comment by derjoachim** [comment]
Could you post a screen shot please or any other way to reproduce your problem? There is an older module for searching within projects. Are you referring to that module?

**Comment by flaviozluca** [comment]
Hi, friend

Thanks for reply. This is what I mean, the last term not translatable. Maybe this changed in a more recent release? If so, sorry

![image](https://user-images.githubusercontent.com/44004645/97892180-75522f00-1d0e-11eb-9a10-4ac678b969ff.png)

**Comment by derjoachim** [comment]
Hi,

It appears to be part of the email module. I made sure to search explicitly in the email translations.

The PT-BR translation is currently `Avançado`, whereas the ES translation is `Avanzado`.

A fix should be rolled out in the next release.

Joachim

**Comment by flaviozluca** [comment]
Thanks a lot, Joachim. Will keep an eye here.

All the best.
