### ISSUE TITLE
Systemtest does not check post_max_size

### ISSUE THREAD

**Issue by mergeMarc** [Intermesh/groupoffice#628]
The installation gotest.php script checks if upload_max_filesize is at least 20Mb.
What it does not do is check if post_max_size is also at least 20Mb (Apache default 8Mb). This would be important to check because it directly dictates how big the file a user uploads can be.
If the upload size is bigger than the maximum post size the upload fails silently.

From experience this would also greatly help with troubleshooting GroupOffice installations.

**Comment by derjoachim** [comment]
Makes sense. It will be rolled out in the next 6.4 version
