### ISSUE TITLE
investment scam files installed....

### ISSUE THREAD

**Issue by crobincouk** [Intermesh/groupoffice#630]
Hello 

This is now the 3rd time that som hacker did upload to the same folder investment scam files.
How to make this secure ? how to fix this ?

Path:
/intranet/go/modules/community/dev/resources/site_map/softimg.php?real=b1ft05rcra9ws6&simple=sure&longer=warm 

Regards

Chris.R

**Comment by mschering** [comment]
You have to start with examining your log files. There are no known vulnerabilities in group-office. It’s likely to be other software running on your server.
