### ISSUE TITLE
6.4.190 - Cut off email when forwarded from Thunderbird

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#632]
Since a few days we see e-mail cut off after the email is forwarded from a thunderbird client.

The message stopped after the line "to:" in the display of the forwarded message.

When you open the "source code view" of the mail in groupoffice, everything is there, but won't show in the email view.

![image](https://user-images.githubusercontent.com/2633051/98991742-8e3bbb00-252c-11eb-93f4-69b5bc7c057e.png)

**Comment by mschering** [comment]
Can you forward such a message as attachment to support@intermesh.nl? You can do that by right clicking in the list and choose "Forward as attachment".
Thanks!

**Comment by thomasgg23** [comment]
Ì send it to support@intermesh.nl, did you receive it?

**Comment by mschering** [comment]
Thanks, will be fixed in the next release today.
