### ISSUE TITLE
wordpaste can't be undone and disables formatting

### ISSUE THREAD

**Issue by tmikaeld** [Intermesh/groupoffice#633]
A few clients keep hitting the wordpaste button by mistake, when they want to use remove formatting.

wordpaste removes all styling without the possibility to add new formatting to the text, not sure if that's by design? Seems kind of useless as a feature in that case.

Maybe you can make it possible to at least undo a wordpaste?

**Comment by mschering** [comment]
I can't reproduce it. It's supposed to just clean jibberish.

I made a small change that hopefully helps.

Which browser do you use?

**Comment by tmikaeld** [comment]
Client use Chrome I use Firefox, I'll try updating soon then and see if that helped.

Thanks for looking into it!
