### ISSUE TITLE
Error: CardDAV - response code 500

### ISSUE THREAD

**Issue by sirdemoncze** [Intermesh/groupoffice#635]
If object **$blob** is empty from this row:
https://github.com/Intermesh/groupoffice/blob/99f36ef95120e4b9a29e197907cacaed0de0a98d/www/go/modules/community/carddav/Backend.php#L138

You get exception on this rows, because blob is not object.
https://github.com/Intermesh/groupoffice/blob/99f36ef95120e4b9a29e197907cacaed0de0a98d/www/go/modules/community/carddav/Backend.php#L140-L142

Fixed:
```
if(empty($blob) || $blob->modifiedAt < $contact->modifiedAt) {
    //blob won't be deleted if still used
    if (!empty($blob))
        $blob->setStaleIfUnused();
```

**Comment by mschering** [comment]
Thanks! Fixed in the next release.
