### ISSUE TITLE
Everyone group and all contacts translatable

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#636]
Can you make this special EVERYONE group translatable (the term EVERYONE, want to translate it)?

See image, when sending an email:

![image](https://user-images.githubusercontent.com/44004645/100487617-59ad2f00-30e8-11eb-94bd-06cecaa042fc.png)

Also, all contacts in address book, can you make that ALSO translatable??

See:

![image](https://user-images.githubusercontent.com/44004645/100487621-603ba680-30e8-11eb-91eb-b2a1e13db12e.png)

Thanks.

**Comment by mschering** [comment]
I fixed "All contacts". But the Everyone group name is stored in the database. You can rename it in the system settings.

**Comment by flaviozluca** [comment]
Thanks a lot!

**Comment by flaviozluca** [comment]
Friend, my sys admin says its not possible to start modifying directly in the database. as it creates too many headaches, hard to maintain etc. If you can consider doing it directly from the code, Id truely appreciate it. Happy holidays!

**Comment by flaviozluca** [comment]
The GAL shows now as USERS... Pls, Merijn, can you make it translatable? Its on the to-do list?

Thanks.

**Comment by derjoachim** [comment]
You want to have the 'Everyone' group renamed, no? Just open the 'Everyone' group in System settings and update the name. No direct fiddling in databases necessary.

**Comment by flaviozluca** [comment]
Friend Joachim,

On the server? I can't as there are folks using the same webmail with another language.

Can't it be translatable?

Here, after clicking on the + in the TO field of an email:

![image](https://github.com/Intermesh/groupoffice/assets/44004645/c324103d-29da-42a5-83e9-270fbb3692e1)

and here, in contacts, USERS, instead of USERS, showing my translation. Thats where GAL is.

![image](https://github.com/Intermesh/groupoffice/assets/44004645/b37ed527-0de0-44c1-a392-116d4fc4013b)

Thanks

**Comment by mschering** [comment]
Fixed in the next 6.8 release

**Comment by flaviozluca** [comment]
So Ill be able to translate it, right?
