### ISSUE TITLE
FormGroup extra items

### ISSUE THREAD

**Issue by alessandrogagliano** [Intermesh/groupoffice#637]
FormGroup show extra empty fields:
![immagine](https://user-images.githubusercontent.com/16006514/101064161-fc0b5d80-3593-11eb-9e59-c9c259d5bb7e.png)

I found a bug in "setValue" method (line 318, go/core/views/extjs3/form/FormGroup.js), this may be a fix:

```
setValue: function (records) {
		this.dirty = true;
		this.removeAll();
		this.markDeleted = [];
		var me = this, wrap;
		function set(r) {
			wrap = me.addPanel();
			wrap.formField.key = r.id;
			wrap.formField.setValue(r);
		}
		if(this.mapKey) {
//			for(var r in records) {
			for (var r = 0, l = records.length; r < l; r++) {
				set(records[r]);
			}
		} else {
			records.forEach(set);
		}

		this.doLayout();
	},
```

**Comment by mschering** [comment]
Are you using master? It's supposed to always add one empty value so you can fill it right away.

**Comment by alessandrogagliano** [comment]
Yes, I used master. I think the problem is that "records" is an array, and "for...in" loop iterates over both array indices and property keys
