### ISSUE TITLE
6.4.203 Integrity constraint violation with database check

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#640]
Hello,

on two instances we are getting the following problems when running a database check:

> Check Database:
> Checking go\core\model\SmtpAccount
> Done
> Checking go\core\model\User
> Done
> Checking go\modules\community\notes\model\Note
> Done
> Checking go\modules\community\notes\model\NoteBook
> 
> Fehler
> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_acl`, CONSTRAINT `core_acl_ibfk_2` FOREIGN KEY (`ownedBy`) REFERENCES `core_user` (`id`) ON DELETE SET NULL)

> Checking database for summary
> No check needed for GO\Summary\Model\UserCalendar
> No check needed for GO\Summary\Model\RssFeed
> Checking GO\Summary\Model\Announcement
> No check needed for GO\Summary\Model\Note
> No check needed for GO\Summary\Model\LatestReadAnnouncementRecord
> Checking database for email
> Checking GO\Email\Model\Account
> Checking 32 GO\Email\Model\Account
> Checking 33 GO\Email\Model\Account
> Checking 40 GO\Email\Model\Account
> Exception: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_acl`, CONSTRAINT `core_acl_ibfk_2` FOREIGN KEY (`ownedBy`) REFERENCES `core_user` (`id`) ON DELETE SET NULL) in /usr/share/groupoffice/go/base/db/ActiveRecord.php:3962
> Stack trace:
> #0 /usr/share/groupoffice/go/base/db/ActiveRecord.php(3229): GO\Base\Db\ActiveRecord->_dbUpdate()
> #1 /usr/share/groupoffice/go/base/db/ActiveRecord.php(4784): GO\Base\Db\ActiveRecord->save()
> #2 /usr/share/groupoffice/go/base/db/ActiveStatement.php(107): GO\Base\Db\ActiveRecord->checkDatabase()
> #3 /usr/share/groupoffice/go/base/Module.php(516): GO\Base\Db\ActiveStatement->callOnEach('checkDatabase', true)
> #4 [internal function]: GO\Base\Module->checkDatabase(Array)
> #5 /usr/share/groupoffice/go/base/ModuleCollection.php(190): call_user_func_array(Array, Array)
> #6 /usr/share/groupoffice/controller/MaintenanceController.php(444): GO\Base\ModuleCollection->callModuleMethod('checkDatabase', Array)
> #7 /usr/share/groupoffice/go/base/controller/AbstractController.php(500): GO\Core\Controller\MaintenanceController->actionCheckDatabase(Array)
> #8 /usr/share/groupoffice/go/base/controller/AbstractController.php(398): GO\Base\Controller\AbstractController->callActionMethod('actioncheckdata...', Array)
> #9 /usr/share/groupoffice/go/base/Router.php(186): GO\Base\Controller\AbstractController->run('checkdatabase', Array)
> #10 /usr/share/groupoffice/index.php(110): GO\Base\Router->runController()
> #11 {main}No check needed for GO\Email\Model\DefaultTemplate
> No check needed for GO\Email\Model\DefaultTemplateForAccount
> No check needed for GO\email\Model\PortletFolder
> No check needed for GO\Email\Model\AccountSort
> No check needed for GO\Email\Model\Label
> Checking GO\Email\Model\Alias
> Checking 12 GO\Email\Model\Alias
> Checking 13 GO\Email\Model\Alias
> No check needed for GO\Email\Model\ContactMailTime
> No check needed for GO\Email\Model\Filter

And with the checking search cache:

> .: Record cached, E: Error while occurred, S: Record skipped (probably normal)
> ==============================================================================
> Processing GO\Calendar\Model\Event
> Done
> Processing GO\Tasks\Model\Task
> Done
> Processing GO\Files\Model\Folder
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
> Done
> Processing GO\Files\Model\File
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`groupoffice`.`core_search`, CONSTRAINT `core_search_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE CASCADE)
> SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by mschering** [comment]
This should have been fixed already. Can you try with the latest release?

**Comment by thomasgg23** [comment]
Did an update this morning before writing this post, currently running on 6.4.203-php-71

on one instance we are also getting this kind of error via e-mail every several minutes

> cron.php is locked (already running)

**Comment by mschering** [comment]
Is the user with ID = 1 deleted?

**Comment by thomasgg23** [comment]
Not to my knowledge will check that

**Comment by thomasgg23** [comment]
In both instances in table core_user the ID=1 exists

**Comment by mschering** [comment]
Please retry with the next release/

**Comment by thomasgg23** [comment]
6.4.204 did the trick.

Thanks for the fast support.
