### ISSUE TITLE
Still aborting cron job every minute after successful upgrade

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#641]
We've done a successful update, but we still get every minute a notification by e-mail: 

> Aborting CRON because an update is needed: 6.4.196 -> 6.4.204

It seems some check mechanism failed. Is there a manual way to fix this update locking situation?

**Comment by mschering** [comment]
Should be gone in .205.

**Comment by rasos** [comment]
Confirmed, upgrading from 204 to 205 fixed the issue.

**Comment by rasos** [comment]
It seems we have a regression here. Getting again every 5 minues: 

>  Aborting CRON because an update is needed: 6.4.215 -> 6.4.218

GO is up-to-date.

**Comment by mschering** [comment]
What happens if you run /install/upgrade.php?

**Comment by rasos** [comment]
```
# /usr/share/groupoffice/install# sudo -u www-data php ./upgrade.php
<b>Error:</b> ErrorException in /usr/share/groupoffice/install/gotest.php at line 107: Undefined index: SERVER_SOFTWARE
</pre></div></section>
<footer>&copy; Intermesh - <a href="https://www.group-office.com">https://www.group-office.com</a></footer>
</body>
</html>
```

line 107 in gotest.php is 

         $test['pass']=stripos($_SERVER["SERVER_SOFTWARE"], 'apache') !== false;

but we have deployed with apache.

**Comment by rasos** [comment]
Oh, you meant running it in the browser `https://mydomain/groupoffice/install/upgrade.php` , here all is fine and the messages stopped - thanks: 

```
Upgrade GroupOffice

Upgrade output will be logged into: log/upgrade/20210209_185120.log

Skipping module blacklist because it's not available.
Skipping module chat because it's not available.
Skipping module dokuwiki because it's not available.
Skipping module ispconfig3 because it's not available.
Rebuilding cache
Registering all entities
Done!
```

**Comment by mschering** [comment]
If you want to run the upgrade on the CLI you can do:

sudo -u www-data cli.php core/System/upgrade

**Comment by rasos** [comment]
Sharing here my experience when upgrading from 6.4 to 6.5 I got with [the web based upgrade](https://fairkom.net/groupoffice/install/upgrade.php)

> TypeError in /usr/share/groupoffice/install/gotest.php at line 86: Return value of ini_return_bytes() must be of the type integer, float returned at 2021-11-22T19:28:27+00:00

CLI based upgrade did all DB migrations

           sudo -u www-data php cli.php core/System/upgrade
          ...
          Rebuilding cache
          Registering all entities
          Done!

but web browser was still asking for upgrade with above error.

Commented out in upgrade.php :

//      require("gotest.php");
//      if(!systemIsOk()) {
//              header("Location: test.php");
//              exit();
//      }

Now I could run the upgrade.

Server is Ubuntu 20.04 32bit with php 7.2

**Comment by mschering** [comment]
Thanks for sharing. I made a change that prevents this error.
