### ISSUE TITLE
mysql version check fails with 6.4.206

### ISSUE THREAD

**Issue by githubrsys** [Intermesh/groupoffice#643]
I tried an update on freebsd from 6.4.196 to 6.4.206

In the frontend the installer check appears and complains

```
MySQL version: MySQL 5.7.0 or greater is required
```

Installed is Distrib 5.7.27, for FreeBSD12.0 (amd64)

I assume it is a bug.

**Comment by derjoachim** [comment]
Hi,

The version check happens by running the query 

`SELECT VERSION()`

and parsing the output. If you open your MySQL client (whichever you use on FreeBSD) and run said query, what is your output?

**Comment by mschering** [comment]
Next release will show the version you're running.
