### ISSUE TITLE
Do not see the resource groups for which I have no rights

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#645]
Is there a way to not see the resource groups for which I have no rights ?

![image](https://user-images.githubusercontent.com/76783618/103364169-54fbe200-4abd-11eb-988a-6066cb90f19a.png)

![image](https://user-images.githubusercontent.com/76783618/103364181-6218d100-4abd-11eb-9736-663ae62a4857.png)

**Comment by mschering** [comment]
No, this is the administration side. Groups have no permissions. Only the items inside the groups.
