### ISSUE TITLE
Disable linked email : an email becomes public after having linked it to a contact in a public address book

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#646]
An email becomes public after having linked it to a contact in a public address book.

Is there a way to avoid an user to link a mail with anything ?

**Comment by mschering** [comment]
Hi,

It’a a module called “save mail as” which you can uninstall.

best regards,
Merijn

**Comment by michaelSoluris** [comment]
OK, module disabled.

Thank you
