### ISSUE TITLE
Import and subscribe to calendars from URLs

### ISSUE THREAD

**Issue by KevoSoftworks** [Intermesh/groupoffice#647]
Hi,

In migrating my workflow over to Group Office I noticed that it is not possible to import iCal calendars from an URL, nor is it possible to periodically update (or be subscribed to) them (or I haven't found the feature yet). Since a number of services that I want to incorperate into Group Office rely on these "dynamic" calendars, I was wondering if such a feature could be implemented.

Let me know if I can provide more info and/or help with testing.

**Comment by mschering** [comment]
We're going to refactor the calendar module soon and we'll make sure this feature is in there.

**Comment by mschering** [comment]
PS: If you need it fast you may always contact us for a quote.
