### ISSUE TITLE
Feature request, download mail option in free version :)

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#648]
Friends,

I know the download email is a paid feature and, of course, I respect that. :) Just kindly ask you to reconsider. Not having it is more work for support. We end up having to teach users to right click, show source code, copy to notepad, save... when we need some evidence, etc. to track emails or whatever. Just doesn't seem as a good option to restrict, imho...

Thanks!

**Comment by mschering** [comment]
Yes, it's part of all the "Save" functions which we really feel is part of the business package.
