### ISSUE TITLE
Feature request: Totals in email view

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#651]
Many customers don't see the total emails in the email listing, depending on the width of the window.

Id consider trying to find some other way to show totals, so this doesnt happen. Not sure exactly how... Maybe next to the quota or something.

![image](https://user-images.githubusercontent.com/44004645/104469910-ce083880-5597-11eb-92df-099816143541.png)

**Comment by mschering** [comment]
This will be fixed when we refactor email. It will show like in the address book then.

**Comment by flaviozluca** [comment]
Thanks a lot, Merijn!

**Comment by mschering** [comment]
This one is fixed in current 6.5 as it shows it differently now.
