### ISSUE TITLE
CSV importation

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#653]
I was really unsure to report this or not. We had to import some CSVs into GO, but it seemed a bit hard. It was simply 1 field, email address, 1 per line. We simply converted from CSV to vcard and then it was easy.

I just think, as time permits, might be nice to make it easy to do importations. With Gmail, I imported a list of emails (1 per line) easily, just a text file with 1 email per line, imported fine.

With GO, it would say  "no delimiter". 

So I created a header

name,email

and put in file

Flavio,flavio@flavio.com

still, it wont work. I got a web error.

From documentation it seems Id have to have all header fields.

I create a single contact in an account with just name and email. I got this

![image](https://user-images.githubusercontent.com/44004645/104529224-fcadff80-55e7-11eb-8e89-b6f63b1bed4e.png)

So to import a list of emails Id have to add tons of fields (blank), until I get to the email addresses? Like this?

![image](https://user-images.githubusercontent.com/44004645/104529259-164f4700-55e8-11eb-9ec1-0cb68b13aa29.png)

Sorry if Im wrong. 

Thanks

**Comment by mschering** [comment]
What's the error?

It worked fine for me when I entered:

name,email
Flavio,flavio@example.com

**Comment by mschering** [comment]
PS: Group-Office requires a name so at lease name and e-mail are required I guess and a single value won't be very useful.

**Comment by flaviozluca** [comment]
It would show Web error. Tested again now, we updated go recently, now it worked :))

Great. Might wanna add the example to doc. it's nice, sometimes useful to import a simple list of emails.

Thanks
