### ISSUE TITLE
Multi Instance -> Login as admin gives error since Core: Set "samesite=Strict" on all cookies 

### ISSUE THREAD

**Issue by pvdvendjc** [Intermesh/groupoffice#655]
Since this modification the function Login as Admin in Multi Instance gives the next error:
DEBUGGER: Showing error message because debug is enabled. Normally we would have redirected to install. I you're doing a freah install and your database is empty then you can safely ignore this.:

ErrorException in /home/pieter/git/groupoffice/www/index.php at line 73: Undefined variable: expires

#0 /home/pieter/git/groupoffice/www/index.php(73): go\core\ErrorHandler::errorHandler(8, 'Undefined varia...', '/home/pieter/gi...', 73, Array)
#1 {main}

The variable expires is never set.
[https://github.com/Intermesh/groupoffice/commit/ece78d0a8f218d5492eef8a0886e7bbaa2eddd18](https://github.com/Intermesh/groupoffice/commit/ece78d0a8f218d5492eef8a0886e7bbaa2eddd18)

**Comment by mschering** [comment]
This one is fixed.
