### ISSUE TITLE
6.4.211 - ErrorException in latest release

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#657]
Hi,

we got the following error after installing 6.4.211

Keep loading the site /install/test.php with this error.

<!DOCTYPE html>
<html lang="de">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="HandheldFriendly" content="true"/>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	<meta http-equiv="x-ua-compatible" content="IE=edge">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-title" content="Installation">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="apple-touch-icon" sizes="180x180" href="/views/Extjs3/themes/Paper/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/views/Extjs3/themes/Paper/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/views/Extjs3/themes/Paper/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/views/Extjs3/themes/Paper/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/views/Extjs3/themes/Paper/img/favicon/safari-pinned-tab.svg" color="#888888">

	<meta name="msapplication-TileColor" content="#2b5797">
	<meta name="theme-color" content="#ffffff">

	<title>Installation</title>
		<link href="/views/Extjs3/themes/Paper/style.css?v=1610983324" media="print, (min-device-width:1201px)" type="text/css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" media="screen and (max-device-width:1200px)" href="/views/Extjs3/themes/Paper/style-mobile.css?v=1610983324" />

    	<style>
        	</style>
</head>
<body class="go-page">

<header>
    <div class="go-app-logo"></div>
</header>

<section>

<section>
	<form method="POST" action="" onsubmit="submitButton.disabled = true;">
		<fieldset>
			
			<h2>System requirements test</h2>
			
			
ErrorException in /usr/share/groupoffice/go/base/Session.php at line 65: Array to string conversion at 2021-01-18T15:35:15+00:00

**Comment by mschering** [comment]
Sorry, It happens on PHP versions lower than 7.3 only. I will release a fix right away.

**Comment by thomasgg23** [comment]
Is it possible to update a ubuntu version 18.04 LTS to 20.04 LTS? with this version of groupoffice?

**Comment by thomasgg23** [comment]
Version 6.4.212 is working, thanks for the fast fix
