### ISSUE TITLE
Go scrolls up on new email

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#658]
Dear friends,

I noticed when a new email comes in automatically, email listing scrolls up to the top, which is a non-desired behaviour, as one has to scroll back down to where he was reading emails... That doesnt happen in another webmail I tested, new email comes in and it says where it was.

Pls check.

Thanks a lot.

**Comment by mschering** [comment]
Fixed in 6.5.87

**Comment by flaviozluca** [comment]
Thanks a lot, this issue was a bit annoying, happy it was improved.
