### ISSUE TITLE
Managing folders (right click) while viewing emails in another folder

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#659]
Found out something interesting which is a bit disturbing while using GO on the day to day basis.

Im viewing emails inside some folder, let's say inbox, then I want to create a folder or rename a folder, on the left side. As soon as I right-click on the folder tree to create a new folder, it loads that folder... So after I create that new folder, I have to go back where I was to move the message inside that folder.

Tested in other webmail, that doesn't happen. When you right click, it doesn't load the folder in which you clicked with right button on top to create a sub-folder... Which is ideal, as I want to create folders without leaving from where I am.

Hope it's comprehensible :))

Thanks.

**Comment by mschering** [comment]
Fixed in 6.5.87
