### ISSUE TITLE
Out of office button

### ISSUE THREAD

**Issue by axrosen** [Intermesh/groupoffice#660]
Hi community! 
We are using GO 6.4.155 in own server.
The button Out of office should be on email according to the manual: https://groupoffice.readthedocs.io/en/latest/using/email.html
However in our instance its not appearing.
Any ideas?
Thanks!
<img width="1014" alt="Captura de Pantalla 2021-01-22 a la(s) 17 11 08" src="https://user-images.githubusercontent.com/67659006/105540384-e2091400-5cd4-11eb-80d2-e82c61150cc4.png">
<img width="437" alt="Captura de Pantalla 2021-01-22 a la(s) 17 11 50" src="https://user-images.githubusercontent.com/67659006/105540417-ef260300-5cd4-11eb-8d05-675e1f0affd3.png">

**Comment by derjoachim** [comment]
Do you have the Sieve module enabled? You can find it in System settings > Modules > Community.
