### ISSUE TITLE
json_encode() error on malformed input

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#661]
Some malformed messages failed to be properly encoded by json_encode() in /usr/share/groupoffice/views/Extjs3/Default.php
and therefore they can't be displayed in the email module.

The issue can be worked around by sanitizing the $data variable in that page. We can use this function for example:

function utf8ize( $mixed ) {
    if (is_array($mixed)) {
        foreach ($mixed as $key => $value) {
            $mixed[$key] = utf8ize($value);
        }
    } elseif (is_string($mixed)) {
        return mb_convert_encoding($mixed, "UTF-8", "UTF-8");
    }
    return $mixed;
}

and then replace
$string = json_encode($data);
with
$string = json_encode(utf8ize($data));

or maybe you guys have a better method for sanitizing the data ?

**Comment by mschering** [comment]
fixed in current release.
