### ISSUE TITLE
6.4.213 SQLSTATE error in tickets

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#662]
We sometimes get this error in the console when changing a ticket.
It doesn't occur everytime, so I cannot say what this error triggers and the changes to the tickets are saved all the time.

/#tickets:1 Uncaught (in promise) Objectmessage: "SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 's'"options: method: "Link/changes"params: sinceState: "19:0:23"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()reject: ƒ ()resolve: ƒ ()__proto__: Object__proto__: Object

**Comment by mschering** [comment]
Fixed in 6.4.226
