### ISSUE TITLE
Date showing as NaN:NaN on mobile

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#663]
On version 6.4.210 , on mobile display the Date shows as NaN:NaN
haven't seen a fix for this in the ChangeLog since then. Can anyone else confirm this bug ?

**Comment by gtech99** [comment]
Same issue confirmed on demo.group-office.eu

**Comment by mschering** [comment]
which date?

**Comment by mschering** [comment]
And which mobile?

**Comment by gtech99** [comment]
![Screenshot_20210201-110253](https://user-images.githubusercontent.com/15035337/106484293-7ca7e680-647d-11eb-85b1-860b3fe3bcb2.png)

This is on a Pixel 4XL

**Comment by mschering** [comment]
Is this still an issue?
