### ISSUE TITLE
zpushadmin version error after upgrade

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#666]
In file:
/usr/share/groupoffice/modules/zpushadmin/model/Device.php

$isLowerCaseNeeded = \GO\Zpushadmin\ZpushadminModule::checkZPushVersion('2.3');

zpush verison is hardcoded to 2.3 but you guys upgraded to 2.6 recently so this breaks new syncs.

**Comment by mschering** [comment]
How does this break new syncs? We haven't been using z-push 2.3 for years now and I've never experienced any problems.

**Comment by gtech99** [comment]
Something funky is going on for sure. There is a new field for devices in zpushadmin Enabled/Disabled and you can toggle that via 'Can Connect' checkbox. For some reason new registered devices start off as Disabled and they must be manually enabled for them to be able to connect. Is this wanted behavior ? I thought it was caused by this apparent bug that I saw in the logs

[03:27:32][log][GO\Zpushadmin\Model\Device:72] Compare active z-push version with: 2.3
[03:27:32][log][GO\Zpushadmin\Model\Device:72] Found z-push version :2.6.1
[03:27:32][log][GO\Zpushadmin\Model\Device:72] Short z-push version :2.6
[03:27:32][log][GO\Zpushadmin\Model\Device:72] Comparison WRONG: 2.3 - 2.6

**Comment by mschering** [comment]
It's not a bug it's a feature ;)

You can control if devices can connect by default via zpush admin -> settings. This is enabled by default.

**Comment by gtech99** [comment]
Hmm, my install.sql under zpushadmin has can_connect default 0

CREATE TABLE IF NOT EXISTS `zpa_devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(50) NOT NULL,
  `device_type` varchar(50) NOT NULL,
  `remote_addr` varchar(20) NOT NULL,
  **`can_connect` tinyint(1) NOT NULL DEFAULT '0',**
  `ctime` int(11) NOT NULL,
  `mtime` int(11) NOT NULL,
  `new` tinyint(1) NOT NULL DEFAULT '1',
  `username` varchar(190) NOT NULL DEFAULT '',
  `comment` text,
  `as_version` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
        KEY `device_id` (`device_id`,`username`)
) ENGINE=InnoDB ;

**Comment by mschering** [comment]
yes but on install it's changed to true in the code.

**Comment by gtech99** [comment]
alright, I'll investigate as to why this didn't happen for us.
