### ISSUE TITLE
Feature request: Friendlier errors

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#667]
Friends,

I believe you guys mentioned this is already planned. Just wanted to keep registered here, imho it's important.

The errors are really huge and hard for an average user (even some admins... :)) to understand.

Example, sending mail...

![image](https://user-images.githubusercontent.com/44004645/107236317-5990b000-6a04-11eb-8902-02183d9e4528.png)

Thanks.

**Comment by flaviozluca** [comment]
1 more example, huge error, when account limit (send out msgs/day) reached
![Uploading huge.png…]()

**Comment by derjoachim** [comment]
In 6.6, the error boxes are way more friendly, so I'll close this ticket.
