### ISSUE TITLE
iCalendar interpreter outlook error

### ISSUE THREAD

**Issue by julyusito** [Intermesh/groupoffice#669]
Hi,

Using outlook with activesync throws an error when sending calendar events, maybe GO is not interpreting correctly the invitation
Groupoffice version: 6.4.206
Source invitation: GO user
Destination invitation: another GO user in the same server

The destination user in GO receive an email with this content:
![Captura de pantalla 2021-02-13 a la(s) 1 01 44 p  m](https://user-images.githubusercontent.com/69789966/107857642-9fcb8200-6dfd-11eb-8a3d-b7865512c7f8.png)

![Captura de pantalla 2021-02-13 a la(s) 1 17 18 p  m](https://user-images.githubusercontent.com/69789966/107857715-16687f80-6dfe-11eb-9168-873b4a602428.png)

When review the calendar app in destination user, the event is presented ok
This only occurs sending with outlook; from web interface the email destination invite arrives ok

If I cancel the event, the mail cancelation event arrives ok
![Captura de pantalla 2021-02-13 a la(s) 2 50 58 p  m](https://user-images.githubusercontent.com/69789966/107860084-6994ff00-6e0b-11eb-8485-ab29f1f531ea.png)
It seems only happens with the invitation event.

Also when the invite is sending from a mobile phone, outlook not understand the .ics file, it just show on mail, but not understand the event:
![Captura de pantalla 2021-02-13 a la(s) 2 55 57 p  m](https://user-images.githubusercontent.com/69789966/107860189-efb14580-6e0b-11eb-8688-f8162ccf27b7.png)

Thanks

**Comment by julyusito** [comment]
Hello, somebody knows if this is fixed on latest versions?

**Comment by mschering** [comment]
Yes this one should be fixed!

**Comment by julyusito** [comment]
Hi,

I upgrade to 6.5.59 and the error persist.

**Comment by julyusito** [comment]
And now the cancel event arrives with same error.  Before versions only occurrs on invitation event.

**Comment by julyusito** [comment]
Maybe z-push version is too old?
Maybe is related to this?
https://forum.kopano.io/topic/3584/z-push-2-6-1-outlook-365-not-synching-any-more-stuck/26
https://forum.kopano.io/topic/3579/more-invitation-calendar-issues

**Comment by mschering** [comment]
Are you syncing outlook with activesync or imap?

**Comment by julyusito** [comment]
Hi,

With activesync.
