### ISSUE TITLE
6.4.220 Tickets not working

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#670]
Since the update we are getting the following error with "random" tickets (which we could access yesterday)

![image](https://user-images.githubusercontent.com/2633051/108515043-ef5df200-72c4-11eb-88cd-f451e2ee2ae4.png)

Debug Log:
[debug_log1613727656647.log](https://github.com/Intermesh/groupoffice/files/6010516/debug_log1613727656647.log)

It does not affect all tickets, but I can't see a pattern.

**Comment by derjoachim** [comment]
Hi,

This issue has been (localy) fixed. A new version will ship out ASAP
