### ISSUE TITLE
6.4.224 Problem displaying some email content

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#675]
We are having problems displaying some email content.

The text is "pushed together" like in the image.
Browser is Edge and Firefox, behaviour is the same.

![Clipboard01](https://user-images.githubusercontent.com/2633051/110123524-484b8100-7dc1-11eb-8748-c2ecfba3afbf.jpg)

**Comment by mschering** [comment]
Could you send the source of such a message to my personal e-mail for testing?

**Comment by thomasgg23** [comment]
Sure no problem.

Am Freitag, den 05.03.2021 um 14:57 schrieb Merijn Schering:








Could you send the source of such a message to my personal e-mail for
testing?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].





Links:
------
[1]
https://github.com/Intermesh/groupoffice/issues/675#issuecomment-791434938
[2]

**Comment by mschering** [comment]
Thanks, 6.4.225 fixes this.
