### ISSUE TITLE
issue forwarding as attachment

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#676]
Friends,

Ive had an odd issue of forwarding as attachment in GO and folks say the EML attached that way is blank. We're on on 6.4.210 but going through changelog, it doesn't seem as if this issue was found/fixed, that is, if it really exists, as it seems...

See this email

![image](https://user-images.githubusercontent.com/44004645/110131950-71f8ae00-7da9-11eb-98c2-552c1053fbdf.png)

An email I right clicked FORWARD AS ATTACHMENT in GO.

Recipient in OL/Office 365 gets attachment blank.

So do I in thunderbird.

See

![image](https://user-images.githubusercontent.com/44004645/110131995-79b85280-7da9-11eb-8741-cba5117e8387.png)

[teste pelo GO.zip](https://github.com/Intermesh/groupoffice/files/6091281/teste.pelo.GO.zip)

Source is blank.

In GO it opens fine.

Thanks.

**Comment by flaviozluca** [comment]
We upgraded to 6.5. I thought this issue was solved, but it still happens in some emails. Pls contact me and I can provide evidence.

Really odd, I right click certain emails in GO, forward as attachment, theyre received attached BLANK in Thunderbird and Outlook, but in Gmail, they appear fine, for example.

For example, open this in GO. BinaryCanary.com PASS  Up - New GO (lucanet, 10 min.)

forward it as attachment. See test.eml. Its attached and the attachment appears blank in TB, as such:

![image](https://user-images.githubusercontent.com/44004645/121254106-44c40c00-c880-11eb-88c7-e5c4d2314f0a.png)
[fwd-evid.zip](https://github.com/Intermesh/groupoffice/files/6619478/fwd-evid.zip)

**Comment by flaviozluca** [comment]
issue remains...

**Comment by mschering** [comment]
Hi, 

Please report this to Thunderbird. All Group-Office does is attach the raw MIME file. There's no processing of it so I can't really change anything.
I can open it with Mac mail and Gmail but Thunderbird can't read it. I believe this is a thunderbird issue.

Best regards,
Merijn

**Comment by flaviozluca** [comment]
Thanks, Merijn, but really, Id prefer id you did that. I fear they might ask me many questions and I wont now how to argue, etc. It's strange, it doesn't happen with other clientes, with icewarp, gmail, any other that I tested. Just with GO. And it's not just thunderbird. The attachment doesnt open in Outlook either... Really, IMHO it's something else. We can test again, if you want but its not just Thunderbird, folks with Outlook also couldnt read the attachments I sent.

**Comment by mschering** [comment]
It's really a thunderbird bug. We encode attachments with base64 by default to save memory (swiftmailer bug perhaps?). I changed it to 7bit and then it works. Hopefully this won't cause memory problems.

**Comment by mschering** [comment]
Fixed in 6.5.87

**Comment by flaviozluca** [comment]
Friend,

basic emails work, but some that have attachments in them fail, both to TB and Gmail. Can I send you an example via email as dont wanna put here the pvt emai?

tks.

**Comment by mschering** [comment]
Related to:

https://github.com/swiftmailer/swiftmailer/issues/258

**Comment by mschering** [comment]
Using $file->setEncoder(new \Swift_Mime_ContentEncoder_NullContentEncoder("8bit")); fixed it.
