### ISSUE TITLE
6.4.226 Error creating ticket from e-mail

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#677]
We are getting an error SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '536' for key 'ti_tickets_custom_fields.PRIMARY' when creating an ticket from e-mail.

Nevertheless the ticket is created but without the attachment in the e-mail.

![Ticket error](https://user-images.githubusercontent.com/2633051/110376316-56b0cb80-8053-11eb-9fcc-26581ebdcc59.jpg)

**Comment by derjoachim** [comment]
Hi,

In 6.4.228, this problem does not appear to be reproducible. If you run into this again, could you please check the Javascript console for errors? The stack trace should help us pinpoint what happens.

Thank you

**Comment by thomasgg23** [comment]
Yes happened again with 6.4.228.
Can I send the log via email because it contains some urls

**Comment by derjoachim** [comment]
Sure.

support at intermesh dot nl

**Comment by thomasgg23** [comment]
Error didn't occur for some time now.
Cannot send you any new debug file.
We are closing this for now.
Thanks.
