### ISSUE TITLE
6.5.33 Caldav does not Authenticate user

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#678]
Apache 2.4.46 with  Alias pointing to

`Alias /caldav /home/web/go/modules/caldav/calendar.php`

reports

`Error in /home/web/go/go/core/auth/Authenticate.php at line 135: Using $this when not in object context`

Greetings robw

**Comment by robshnup** [comment]
Hello Merijn, now in 6.5.34 this authentication fault has  gone away, but therefore has come another quirk.
The first login runs like a charm. But then if I log out and wish to log in subsequently i get this message 

![Zwischenablage-1](https://user-images.githubusercontent.com/80580927/111172433-1c40b480-85a6-11eb-9184-c9d2fa4af27a.jpg)

It's coming from  the lost cookie named "groupoffice". If I delete it everything runs as usual.

Greetings robw

**Comment by mschering** [comment]
I can't reproduce this error on my machine. Can you check your server logs for more details about the error?

**Comment by robshnup** [comment]
HEllo Merijn,
 the tail aof debug.log says




[log][go\core\webclient\Extjs3:49].
        SELECT m.id [1], m.name [2], m.package, m.version,
m.sort_order, m.admin_menu, m.aclId, m.enabled, m.id [1] AS `m.id
[1]`.
        FROM `core_module` `m`
        WHERE.
         `m`.`enabled` = true (1.55ms)
[log][GO\Base\Session:225].
        SELECT core_auth_token.loginToken,
core_auth_token.accessToken, core_auth_token.userId,
core_auth_token.createdAt, core_auth_token.exp        FROM
`core_auth_token`
        WHERE.
         `core_auth_token`.`accessToken` =
'604f7c6f60b3f32b739b2d992f72dbfcf69d9ffebd638'
        LIMIT 0,1 (1.55ms)
[log][go\core\jmap\State:133].
        SELECT core_auth_token.loginToken,
core_auth_token.accessToken, core_auth_token.userId,
core_auth_token.createdAt, core_auth_token.exp        FROM
`core_auth_token`
        WHERE.
         `core_auth_token`.`accessToken` =
'604f7c6f60b3f32b739b2d992f72dbfcf69d9ffebd638'
        LIMIT 0,1 (2.55ms)


[start] auth 2021-03-15 15:25:57
[log][go\core\auth\Authenticate:135].
        SELECT id.
        FROM `core_auth_password` `p`
        INNER JOIN `core_user` `u` ON.
         u.id [3]=p.userId
        WHERE.
         `u`.`username` = 'robbie'
        LIMIT 0,1 (2.68ms)
[log][go\core\ErrorHandler:93] ErrorHandler::exceptionHandler() called
with TypeError
[error][go\core\ErrorHandler:64] TypeError in
/home/web/go/go/core/model/Token.php at line 326: Argument 1 passed to
go\core\model\Token::addP[error][go\core\ErrorHandler:73] #0
/home/web/go/api/auth.php(114):
go\core\model\Token->addPassedAuthenticator()
[error][go\core\ErrorHandler:73] #1 {main}










I've proved with Firefox and Chrome Edge ond a server running Apache2
and on another server running Nginx.
Every Connection on my intranet with http:// not https://



 Viele Grüße - Robert



Am Montag, den 15.03.2021 um 16:03 schrieb Merijn Schering:








I can't reproduce this error on my machine. Can you check your server
logs for more details about the error?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [4], or unsubscribe
[5].





Links:
------
[1] http://m.id
[2] http://m.name
[3] http://u.id
[4]
https://github.com/Intermesh/groupoffice/issues/678#issuecomment-799491958
[5]

**Comment by mschering** [comment]
Can you provide a bit longer log? You cut it at a point where it started to get interesting :)

**Comment by mschering** [comment]
Nevermind, I found the problem. To increase performance with DAV protocols and ActiveSync which do a lot of logins I cache the login for 60 seconds. During this period the error occurs now. So if you wait one minute it works again.

**Comment by robshnup** [comment]
Okay , I understand! Thanks for investigating. Is this evtually a prob which occurs while going in with getting a token over a small php-skript?
robw

**Comment by mschering** [comment]
Next release will have this fixed.
