### ISSUE TITLE
6.5.35 community - Modules admin broken 

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#679]
Hello,
since 6.5.35 my admin has no access to the modules section. (6.5.32 works fine however)
With FF and Chrome on Apache2

Debug.log says:

> [log][GO\Base\Db\Columns:69] Using \GO\Base\Cache\Apcu cache
[log][GO:13] [2021-03-16 18:17] INIT POST /go/index.php?r=modules/module/store&security_token=jENvyprWM9g8lufBc3GC
[log][GO\Base\Router:125] Controller route r=modules/module/store
[log][GO\Base\Controller\AbstractController:373] setIgnoreAclPermissions(true)
[log][GO\Modules\Controller\ModuleController:74] ************ Model load error ************
[log][GO\Modules\Controller\ModuleController:74] Folder is not a module :: z-push
[log][GO\Modules\Controller\ModuleController:74] Class  :: GO\Z-push\Z-pushModule
[log][GO\Modules\Controller\ModuleController:74] file  :: /home/web/go/modules/z-push/Z-pushModule.php
[log][GO\Modules\Controller\ModuleController:74] ************ Model load error ************
[log][GO\Modules\Controller\ModuleController:74] Folder is not a module :: professional
[log][GO\Modules\Controller\ModuleController:74] Class  :: GO\Professional\ProfessionalModule
[log][GO\Modules\Controller\ModuleController:74] file  :: /home/web/go/modules/professional/ProfessionalModule.php
[log][GO\Modules\Controller\ModuleController:74] ************ Model load error ************
[log][GO\Modules\Controller\ModuleController:74] Folder is not a module :: groups
[log][GO\Modules\Controller\ModuleController:74] Class  :: GO\Groups\GroupsModule
[log][GO\Modules\Controller\ModuleController:74] file  :: /home/web/go/modules/groups/GroupsModule.php
[log][GO\Modules\Controller\ModuleController:74] ************ Model load error ************
[log][GO\Modules\Controller\ModuleController:74] Folder is not a module :: modules
[log][GO\Modules\Controller\ModuleController:74] Class  :: GO\Modules\ModulesModule
[log][GO\Modules\Controller\ModuleController:74] file  :: /home/web/go/modules/modules/ModulesModule.php
[log][go\core\util\ClassFinder:84] ClassFinder find() used.
[log][GO\Base\Db\Columns:69] Using \GO\Base\Cache\Apcu cache
[log][GO:13] [2021-03-16 18:19] INIT POST /go/index.php?r=core/multiRequest&security_token=jENvyprWM9g8lufBc3GC
[log][GO\Base\Router:125] Controller route r=core/multiRequest
[log][GO\Core\Controller\CoreController:589] Controller route r=reminder/store
[log][GO\Base\Db\ActiveRecord:1315] t.*
[log][GO\Core\Controller\CoreController:589] Controller route r=core/auth/checkclient
[log][GO\Base\Controller\AbstractController:497] Is the user switched: false
[log][GO\Core\Controller\CoreController:589] Controller route r=files/notification/unsent
[log][GO\Base\Db\ActiveRecord:961] 
        SELECT groupId 
        FROM `core_user_group` `t`
        WHERE 
         `t`.`userId` = 1.0 (1.42ms)
[log][GO\Core\Controller\CoreController:589] Controller route r=email/account/checkUnseen
[log][GO\Base\Db\ActiveRecord:961] 
        SELECT groupId 
        FROM `core_user_group` `t`
        WHERE 
         `t`.`userId` = 1.0 (1.22ms)
[log][GO\Email\Controller\AccountController:164] Session writing closed
[log][GO\Base\Db\ActiveRecord:1315] t.*
[log][GO\Base\Db\ActiveRecord:1429] 
        SELECT groupId 
        FROM `core_user_group` `t`
        WHERE 
         `t`.`userId` = 1 (1.27ms)
[log][GO\Base\Controller\AbstractController:500] Total unseen: 0

Hope this helps - robw

**Comment by derjoachim** [comment]
The messages you are seeing are no reason for alarm. On my environment, against 6.5.35, I can open my modules screen just fine and I have the same messages in my debug.log.

Are you getting any errors in your Javascript console?

**Comment by robshnup** [comment]
Hello Joachim,
this is what comes on console:

>  Starting SSE script.php:1903:9
13:02:19.743
XHRGEThttp://192.168.123.202/go/api/sse.php?types=Group,User,Field,FieldSet,Module,Link,Search,EntityFilter,SmtpAccount,EmailTemplate,CronJobSchedule,AuthAllowGroup,OauthClient,SpreadSheetExport,Note,NoteBook,Contact,AddressBook,AddressBookGroup,Key
13:02:20.028
XHRPOSThttp://192.168.123.202/go/index.php?r=modules/module/store&security_token=a1jFMXLUhV7bK5kdOA4D
[HTTP/1.1 200 OK 112ms]

13:02:20.180
Site error: the <a href="http://www.ioncube.com">ionCube</a> PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.

Please visit <a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a> for install assistance.

script.php:443:199
13:02:20.182 console.trace() errordialog script.php:837:73
    show http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:837
    decode http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:443
    read ExtJS
    onRead http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:530
    ExtJS 2
    handleTransactionResponse http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:2332
    asyncRequest http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:2438
    (Async: EventListener.handleEvent)
    asyncRequest http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:2437
    request http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:2492
    ExtJS 5
    afterRender http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:3061
    ExtJS 9
    selectionchange http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:2856
    ExtJS 7
    (Async: EventListener.handleEvent)
    ret http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:1888
    addListener http://192.168.123.202/go/views/Extjs3/javascript/ext-base-debug.js?mtime=1615893232:2049
    ExtJS 8
    onLayout http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:2371
    ExtJS 6
    show http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:2860
    openSystemSettings http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:395
    addDefaultRoutes http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:372
    handleRoute http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:2454
    check http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:2451
    onAuthentication http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:372
    (Async: promise callback)
    onAuthentication http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:372
    (Async: promise callback)
    onAuthentication http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:372
    boot http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:363
    (Async: promise callback)
    boot http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:363
    boot http://192.168.123.202/go/views/Extjs3/script.php?v=1615907230:363
    ExtJS 10

​
Here with FF 86 on nginx
Greets

**Comment by derjoachim** [comment]
Hi Rob,

Can you double check the test script under System Settings > Tools > System check please? It is odd that the modules screen worked in earlier versions, but seeing the first line of your stack trace, I want to make absolutely sure that ionCube is indeed properly installed. 

You need to look out for the following output:

![image](https://user-images.githubusercontent.com/1264970/111469064-8e400780-8726-11eb-93e1-0bcd6bf13db1.png)

**Comment by robshnup** [comment]
Hello Joachim,
no - I have not installed Ioncube, since I do not use the commercial features.
In older versions (6.4.xx till 6.5.32) this did not expose as a problem.
Have I to install Ioncube even if I don't need the commercial modules?
All the other tests are OK.

> PHP apcu support: OK
Operating System: OK
Web server: Warning, your web server nginx/1.18.0 is not officially supported
PHP SAPI mode: OK
Expose PHP: OK
PHP version: OK
Output buffering: OK
DOM extension: OK
fileinfo extension: OK
intl: OK
mbstring function overloading: OK
Magic quotes setting: OK
PDO support: OK
GD support: OK
File upload support: OK
File upload size: OK
Post max size: OK
Post max size > File upload size: OK
Safe mode: OK
Open base_dir: OK
Register globals: OK
zlib compression: OK
Calendar functions: OK
Memory limit: OK
Error logging: OK
MultiByte string functions: OK
CURL extension: OK
TAR Compression: OK
ZIP Compression: OK
TNEF: OK
pdfinfo: OK
Ioncube enabled: Warning: Ioncube is not installed. The professional modules will not be enabled.
Ioncube version check: Warning: Ioncube is not installed. The professional modules will not be enabled.
JSON functions: OK
zend.ze1_compatibility_mode: OK
MySQLnd driver: OK
Shared Memory Functions: OK
Process Control Extensions: OK
Floating point precision: OK
Passed! Group-Office should run on this machine


Greets Rob

**Comment by derjoachim** [comment]
I hear you.

What confuses me, is this error:

> Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.
> 
> Please visit get-loader.ioncube.com for install assistance.
 
This does not come from within GroupOffice. Are you on some kind of shared web hosting by any chance? As far as I can tell, the message above  appears to be cpanel or plesk related. One thing that does not make sense is that this error suddenly appears. I checked the relevant code and the last change is over almost 2 months old, so it should have worked with 6.5.32.

**Comment by robshnup** [comment]
Hi Joachim,
nothing like cpanel or like that. I'm running a plain Debian/bullseye with Nginx and - on another server - Apache2.
No matter on which environment - if I copy a GO 6.5.32 therein it runs, with 6.5.35 modules admin broken. Nothing changed in between.
With 6.5.32 I receive no errors at all in js-console

> 16:32:48.201
XHRPOSThttp://192.168.123.200/go/api/jmap.php?security_token=zaEnTHhG7t4B2CWpLjs1
[HTTP/1.1 200 OK 222ms]
16:32:51.455
XHRPOSThttp://192.168.123.200/go/index.php?r=modules/module/store&security_token=zaEnTHhG7t4B2CWpLjs1

That was it!

I don't know what I can do anymore... ;-)
Greets

**Comment by robshnup** [comment]
Hi,
I'v looked once more. Perhaps this helps:
The lines you're irritated by were raised by _**.../go/views/Extjs3/script.php:443:199**_

There I find this switch statement:

return json}catch(e){switch(jsonStr.trim()){
	case 'NOTLOGGEDIN':break;
	case 'UNAUTHORIZED':Ext.Msg.alert(t("Unauthorized"),t("You don't have permission to perform this action"));break;
	default:console.error(jsonStr);jsonStr+='<br /><br />Ext.decode exception occurred';GO.errorDialog.show(t("An error occurred on the webserver. Contact your system administrator and supply the detailed error from the server log."));break}}};

Apparently it has chosen the default branch error.

Greetings

**Comment by mschering** [comment]
This is fixed now. Some files were accidentally encoded. I have corrected this in the latest 6.5 and 6.4 release.
