### ISSUE TITLE
after upgrade to 6.5.41: fallback tu upgrade-screen

### ISSUE THREAD

**Issue by wokrat** [Intermesh/groupoffice#684]
after upgrade to 6.5.41 (manual upgrade) i get to the upgrade or to the install screen

- after changeing user profile data (look & feel)
- after trying to accept event invitation from "outside" (i.e. non-go-user)
- (maybe several other things not tried so far)

**Comment by mschering** [comment]
Can you check your webserver error log for errors?

**Comment by wokrat** [comment]
here the example for accepting events for external users:

[Tue Apr 13 13:32:04.426996 2021] [fcgid:warn] [pid 10209] [client XXX.XXX.XXX.XXX:5916] mod_fcgid: stderr: ErrorException in /[path to my go]/views/Extjs3/externalHeader.php at line 7: require(themes/Default/pageHeader.php): failed to open stream: No such file or directory, referer: https://deref-gmx.net/
[Tue Apr 13 13:32:04.427041 2021] [fcgid:warn] [pid 10209] [client XXX.XXX.XXX.XXX:5916] mod_fcgid: stderr: ErrorException in /[path to my go]/views/Extjs3/externalHeader.php at line 7: require(themes/Default/pageHeader.php): failed to open stream: No such file or directory, referer: https://deref-gmx.net/

after changing look & feel:

[Tue Apr 13 13:44:59.806551 2021] [fcgid:warn] [pid 30113] (104)Connection reset by peer: [client XXX.XXX.XXX.XXX:57301] mod_fcgid: error reading data from FastCGI server
[Tue Apr 13 13:44:59.806653 2021] [core:error] [pid 30113] [client XXX.XXX.XXX.XXX:57301] End of script output before headers: index.php

**Comment by mschering** [comment]
There seem to be files missing. Please make sure the source is completely transferred.
