### ISSUE TITLE
6.5.40 No auto-link when opening e-mail from ticket

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#686]
When we open a new e-mail message from a ticket with the plus sign in the top of the ticket, usually the ticket was "auto-linked" with the e-mail.

Since the update to 6.5 this function doesn't work anymore.

Creating a new appointment, contact, task and even email files is working with the auto-link feature.
![nolink](https://user-images.githubusercontent.com/2633051/114718619-74e6a700-9d36-11eb-83ac-2bd732a6cd03.jpg)

**Comment by mschering** [comment]
This one has been fixed in the next 6.5 release.
