### ISSUE TITLE
6.5.40 "auto-refresh" tickets detail

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#687]
Would be nice to have a kind of "auto-refresh" the ticket details, when switching back to the tickets tab.
For example: you are in the e-mail tab and link a e-mail to a ticket already created, when you go back to the tickets tab you have to manually refresh the ticket to see the new linked email.

**Comment by mschering** [comment]
This will be fixed when we rewrite the tickets module in 6.7.
