### ISSUE TITLE
Change in requesting notifications stops Firefox working

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#690]
If the standard config doesn't allow notifications for a website (which is the case on every site connected to over http:// in intranet) Firefox stops working until restart. This is because GO doesn't claim the allowance for notifications in FF (like many others do e.g. nextcloud etc.) Besides, it's an old behaviour of GO...
If you don't grant this allowance manually FF reacts with this message:
![Zwischenablage-1](https://user-images.githubusercontent.com/80580927/116787679-c5376600-aaa5-11eb-90e7-7be07d84dfbc.jpg)

It's quite fiddling to get to the manual config for this website:
![Zwischenablage-2](https://user-images.githubusercontent.com/80580927/116787783-7b02b480-aaa6-11eb-9c3a-d56569701e14.jpg)

Would be nice GO claiming the right for notifications itself.

Edit;
It's due to an adjustment in FF itself.
`user_pref("dom.webnotifications.allowinsecure", false);`

This has to be turned to `true` in order to be asked at all on unsecured http-sites.
Either by the `about:config` configuration site or by an according entry in the `user.js`-file in the FF-Profile directory to be created.
Alternative is also to create an according `autoconfig.js`- file. See -> [https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig](url)

Greetings robw

**Comment by mschering** [comment]
I changed it that it won't request notifications when in insecure context.
