### ISSUE TITLE
after 6.5.45 upgrade -> sabredav caldav -> Module legacy/dav not available

### ISSUE THREAD

**Issue by DrDBanner** [Intermesh/groupoffice#691]
After the upgrade to GO 6.5.45 from 6.3.x the caldav doesn't work like expected. When I try to open it in the browser (https://DOM/caldav/principals/USER/) it says Module legacy/dav not available after putting in the credentials. 

<img width="798" alt="Bildschirmfoto 2021-05-03 um 01 44 13" src="https://user-images.githubusercontent.com/25568865/116831683-12542e80-abb1-11eb-8098-a65f5a370b3b.png">

On MacOS it says 403 -> CalDAVRefreshDelegatedListQueueableOperation.

CardDav works properly.

**Comment by DrDBanner** [comment]
This problem only appears with a particular user. Another user is able to the the sabredav webui. The credentials put in are correct since the user is able to login to the GO Webinterface.

**Comment by mschering** [comment]
You can work around by granting access to the webdav module. But the new release today will fix it too.
