### ISSUE TITLE
IMAP error

### ISSUE THREAD

**Issue by Papagenos** [Intermesh/groupoffice#693]
After restart of GO and its server I got the following error:
[Mon May 03 11:45:07.837130 2021] [:error] [pid 4255] [client 192.168.0.111:53058] ErrorException in /usr/share/groupoffice/go/base/mail/Imap.php at line 200: stream_socket_enable_crypto(): SSL: Success, referer: https://realgroupofficeserveradress/
[Mon May 03 11:45:07.838201 2021] [:error] [pid 4255] [client 192.168.0.111:53058] IMAP error: , referer: https://realgroupofficeserveradress

GO doesn't pickup mails anymore, while editing mail settings and pressing OK I get: tream_socket_enable_crypto(): SSL: Success

With Thunderbird I can access the mailserver at  https://realgroupofficeserveradress/ and pickup mails. Both are IMAP.

**Comment by mschering** [comment]
Something must be wrong with the mailserver if tls cant be enabled. Perhaps it's not supported.
