### ISSUE TITLE
Z-Push - IMAP (imap.strato.de)

### ISSUE THREAD

**Issue by cm91** [Intermesh/groupoffice#695]
Hi,

i have a strange issue with my mailbox provider Strato.
I can fetch the Mailbox in GroupOffice without Problems.

I'm using the latest version from Docker Hub.

Unfortunately i cannot sync the Mails with ActiveSync.

I already did some tests:

Strato IMAP Server --> not working
Selfhosted Dovecot IMAP Server --> working.

The error i get when i use Strato is: [  226] [ERROR] [user@example.com] [appldmdm4kj3fk10] IMAP returned error response
From the goMail.php z-push config i guess this is beacause the variable headers is empty or does not exist.

                                if(!$headers) {
                                        ZLog::Write(LOGLEVEL_ERROR, "IMAP returned error response" . $imap->last_error() );
                                        return [];
                                }

I added some debug parameters which shows me the UIDs and the headers when i try to sync:
05/05/2021 16:33:06 [  230] [ERROR] [user@example.com] [appldmdm4kj3fk10] UIDs: Array
(
    [0] => 1
)

05/05/2021 16:33:06 [  230] [ERROR] [user@example.com] [appldmdm4kj3fk10] HEADERS:

The UIDs are ok, i gives me one entry back (The INBOX only has one mail)

For the Dovecot mailserver i also get a output for $headers (two mails in the INBOX):

(
    [0] => Array
        (
            [uid] => 23
            [flags] => Array
                (
                    [0] =>
                )

            [date] => 05-May-2021 08:27:20 +0200
        )

    [1] => Array
        (
            [uid] => 24
            [flags] => Array
                (
                    [0] =>
                )

            [date] => 05-May-2021 08:27:23 +0200
        )

)

It looks like the follwing part is not working with the Strato IMAP Server:
$headers = $imap->get_flags(min($uids) .':*');

For comparison a also attached the output of $imap for both servers.
[dovecot.txt](https://github.com/Intermesh/groupoffice/files/6428802/dovecot.txt)
[strato.txt](https://github.com/Intermesh/groupoffice/files/6428807/strato.txt)

**Comment by mschering** [comment]
Is the imap account fully working in the web interface?

**Comment by cm91** [comment]
Yes, it is.

**Comment by mschering** [comment]
Coul you provide me with a test IMAP account so I can replicate it? You can send it to support@intermesh.nl.

**Comment by cm91** [comment]
Sent via email.
