### ISSUE TITLE
6.4.229 + 6.4.234 + 6.5.45 - LDAP authenticator Modul activation fail

### ISSUE THREAD

**Issue by wnglobal2000** [Intermesh/groupoffice#696]
### Environments:
GO Version: 6.4.229-php-71 all
OS: Ubuntu 18.04.3 LTS
PHP 7.2.24-0ubuntu0.18.04.4 (cli) (built: Apr  8 2020 15:45:57) ( NTS )
MySQL: mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

GO Version: 6.4.234-php-71 all
OS: Ubuntu 20.04.2 LTS
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
MySQL: mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce:
1. install fresh groupoffice (6.4.229 or 6.4.234) apt install 
2. System settings -> Modules (Community) -> LDAP authenticator - enable (Checkbox)

The following error occurs:
SQLSTATE[42000]:
 Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON 
column 'syncUsersQuery' can't have a default value on query (0) CREATE 
TABLE `ldapauth_server` (
`id` int(11) NOT NULL,
`hostname` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
`port` int(11) NOT NULL DEFAULT '389',
`encryption` enum('ssl','tls') COLLATE utf8mb4_unicode_ci DEFAULT 'tls',
`ldapVerifyCertificate` BOOLEAN NOT NULL DEFAULT TRUE,
`followReferrals` BOOLEAN NOT NULL DEFAULT TRUE,
`protocolVersion` TINYINT UNSIGNED NOT NULL DEFAULT '3',
`username` VARCHAR(190) NULL DEFAULT NULL,
`password` VARCHAR(512) NULL COLLATE ascii_bin DEFAULT NULL,
`usernameAttribute` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL 
DEFAULT 'uid',
`peopleDN` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 
'ou=people,dc=example,dc=com',
`groupsDN` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT 
'ou=groups,dc=example,dc=com',
`imapHostname` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`imapPort` int(11) NOT NULL DEFAULT '143',
`imapEncryption` enum('tls','ssl') COLLATE utf8mb4_unicode_ci DEFAULT 
'tls',
`imapValidateCertificate` tinyint(1) NOT NULL DEFAULT '1',
`imapUseEmailForUsername` BOOLEAN NOT NULL DEFAULT FALSE,
`loginWithEmail` tinyint(1) NOT NULL DEFAULT '0',
`smtpHostname` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`smtpPort` int(11) NOT NULL DEFAULT '587',
`smtpUsername` varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
`smtpPassword` varchar(512) COLLATE ascii_bin DEFAULT NULL,
`smtpUseUserCredentials` tinyint(1) NOT NULL DEFAULT '0',
`smtpEncryption` enum('tls','ssl') COLLATE utf8mb4_unicode_ci DEFAULT 
NULL,
`smtpValidateCertificate` tinyint(1) NOT NULL DEFAULT '1',
`syncUsers` BOOLEAN NOT NULL DEFAULT FALSE,
`syncUsersQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci 
NOT NULL DEFAULT '',
`syncGroups` BOOLEAN NOT NULL DEFAULT FALSE,
`syncGroupsQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci 
NOT NULL DEFAULT ''
) ENGINE=InnoDB

I tried in both environments, same error.
I had this module running in both environments. 

For debugging I checked the Backup from the running system and the table structure was different:
...
DROP TABLE IF EXISTS `ldapauth_server`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `ldapauth_server` (
  `id` int NOT NULL AUTO_INCREMENT,
  `hostname` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `port` int NOT NULL DEFAULT '389',
  `encryption` enum('ssl','tls') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'tls',
  `ldapVerifyCertificate` tinyint(1) NOT NULL DEFAULT '1',
  `followReferrals` tinyint(1) NOT NULL DEFAULT '1',
  `protocolVersion` tinyint unsigned NOT NULL DEFAULT '3',
  `username` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(512) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `usernameAttribute` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'uid',
  `peopleDN` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ou=people,dc=example,dc=com',
  `groupsDN` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ou=groups,dc=example,dc=com',
  `imapHostname` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `imapPort` int NOT NULL DEFAULT '143',
  `imapEncryption` enum('tls','ssl') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'tls',
  `imapValidateCertificate` tinyint(1) NOT NULL DEFAULT '1',
  `imapUseEmailForUsername` tinyint(1) NOT NULL DEFAULT '0',
  `loginWithEmail` tinyint(1) NOT NULL DEFAULT '0',
  `smtpHostname` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpPort` int NOT NULL DEFAULT '587',
  `smtpUsername` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpPassword` varchar(512) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `smtpUseUserCredentials` tinyint(1) NOT NULL DEFAULT '0',
  `smtpEncryption` enum('tls','ssl') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `smtpValidateCertificate` tinyint(1) NOT NULL DEFAULT '1',
  `syncUsers` tinyint(1) NOT NULL DEFAULT '0',
  `syncUsersQuery` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `syncGroups` tinyint(1) NOT NULL DEFAULT '0',
  `syncGroupsQuery` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

As far I could see the problem is somewhere here:
  `syncUsers` BOOLEAN NOT NULL DEFAULT FALSE,
  `syncUsersQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `syncGroups` BOOLEAN NOT NULL DEFAULT FALSE,
  `syncGroupsQuery` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''

I will try to rollback to 6.3 and install LDAP authenticator there.

**Comment by wnglobal2000** [comment]
Just tested with a plain and fresh groupoffice 6.5.45 same issue!

**Comment by mschering** [comment]
Will be fixed in the next 6.5 release.
