### ISSUE TITLE
All categories are visible (even with permission)

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#700]
Hi,

In the 6.5.49 version,

All categories are visible to the user event if the category is not shared to the user or on of his group.

In the exemple below the user is not admincc-olr and does not below to CC-OLR_AGENT.

![image](https://user-images.githubusercontent.com/76783618/118663892-58d09c80-b7f1-11eb-9ece-3f2699ca9c81.png)

![image](https://user-images.githubusercontent.com/76783618/118663258-f9728c80-b7f0-11eb-8114-eb3172a1ccb9.png)

**Comment by mschering** [comment]
Thanks, will be fixed in the next 6.5
