### ISSUE TITLE
[Language] Language file not used in Googlauth module

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#702]
While all the french language files are taken into account, in the googleauthenticator modul , the translation doesn't work.

![image](https://user-images.githubusercontent.com/76783618/119156824-e3650600-ba54-11eb-8483-6d227154b5aa.png)

![image](https://user-images.githubusercontent.com/76783618/119156910-f677d600-ba54-11eb-9b73-6948905cee5f.png)

**Comment by mschering** [comment]
Thanks, will be fixed in the next release.
