### ISSUE TITLE
[CustomField] Some Custom Field information are visible in details view

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#704]
I can only see the "Frais" and "SI17_GC" Custom field in my event. It's normal I don't have right to the others CF.

Nevertheless, I can see all the Custum Filds in the detail view of the event.

![image](https://user-images.githubusercontent.com/76783618/120219308-516eb180-c23b-11eb-9344-dae28676e8aa.png)

I should not see here : 
SI17 Interne
CAPR
SIG
PA
STP_Résa
CCAS
SDE
MINIBUS
BUS_Résa
LRD_Location
.....

**Comment by derjoachim** [comment]
Hi Michael,

Good catch! Starting from the next 6.5 release, custom  field sets will be hidden from event detail screens if a user has no  permissions for said field set.
