### ISSUE TITLE
[Category in Calendar] All categories are visible in administration

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#705]
A user don't see all categories in the event windows but in the administration panel, all the categories are visible.

Connected with m.edlich I see this category (for example) :
![image](https://user-images.githubusercontent.com/76783618/120314589-afeb6c80-c2db-11eb-8d7a-0c1992bce67e.png)

Connected in Admin, I can see m.edlich doesn't have any acces to this category
![image](https://user-images.githubusercontent.com/76783618/120314611-b679e400-c2db-11eb-8d0e-bb10b056d9b0.png)

**Comment by derjoachim** [comment]
A fix will be deployed in the next 6.5.X version.
