### ISSUE TITLE
[Custom filed] Error in selection field

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#708]
When we choose Selection as custom field there is 2 issues : 
 - If we type something and then erase one too many times, an error appears (1)
 - The auto-completion does not work as well as before (GOv6.2) on selection type. It does not search in middle of the string (2)
(1)
![image](https://user-images.githubusercontent.com/76783618/120514399-89a5f980-c3cd-11eb-8bcb-ea91f553ec23.png)

(2) The "PARC" search does not give any result (you have to type the beggining of the string)
![image](https://user-images.githubusercontent.com/76783618/120514809-f7eabc00-c3cd-11eb-930f-467121e98236.png)
![image](https://user-images.githubusercontent.com/76783618/120514876-089b3200-c3ce-11eb-83e7-0fc6ee7847af.png)
![image](https://user-images.githubusercontent.com/76783618/120515053-354f4980-c3ce-11eb-8f99-23c8ca6f178e.png)

**Comment by mschering** [comment]
Fixed in the next release
