### ISSUE TITLE
Clicking the links Button leads to en error: Failed to send the request to the server

### ISSUE THREAD

**Issue by cymuc** [Intermesh/groupoffice#710]
When I click on the link button inside a project or inside a task that leads to a popup Windows with the error:

Failed to send the request to the server. Please check your internet connection.

It is not possible to close that error modal. And the error repeats itself permanently.

In the Browser console there is an error:

Clearing invalid sort state: {} script.php?v=1623762577:2128
server-side JMAP failure (3) ["error", {…}, "clientCallId-178"] script.php?v=1623762577:1891
bug-report

https://user-images.githubusercontent.com/15957773/122066033-b0632780-cdf2-11eb-822e-a876efa3507c.png

The debug.log: 

[error][go\core\db\Connection:573] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'eTo.name' in 'order clause'
[error][go\core\db\Connection:574] 
        #0 /usr/share/groupoffice/go/core/db/Connection.php(561): PDO->prepare()
        #1 /usr/share/groupoffice/go/core/db/Query.php(592): go\core\db\Connection->createStatement()
        #2 /usr/share/groupoffice/go/core/db/Query.php(608): go\core\db\Query->createStatement()
        #3 /usr/share/groupoffice/go/core/db/Query.php(697): go\core\db\Query->execute()
        #4 /usr/share/groupoffice/go/core/jmap/EntityController.php(208): go\core\db\Query->getIterator()
        #5 /usr/share/groupoffice/go/core/controller/Link.php(50): go\core\jmap\EntityController->defaultQuery()
        #6 [internal function]: go\core\controller\Link->query()
        #7 /usr/share/groupoffice/go/core/jmap/Router.php(209): call_user_func()
        #8 /usr/share/groupoffice/go/core/jmap/Router.php(92): go\core\jmap\Router->callAction()
        #9 /usr/share/groupoffice/go/core/jmap/Router.php(68): go\core\jmap\Router->callMethod()
        #10 /usr/share/groupoffice/api/jmap.php(14): go\core\jmap\Router->run()
        #11 {main}
[error][go\core\db\Query:617] 
        SQL FAILED: SELECT DISTINCT l.id 
        FROM `core_link` `l`
        INNER JOIN `core_search` `search` ON 
         search.entityId = l.toId AND search.entityTypeId = l.toEntityTypeId
        WHERE 
         (
        	 (
        		 `l`.`fromEntityTypeId` = 42 
        		AND `l`.`fromId` = 168
        	)
        )
        ORDER BY `search`.`modifiedAt` DESC, `eTo`.`name` ASC
        LIMIT 0,40
[error][go\core\ErrorHandler:64] go\core\jmap\exception\UnsupportedSort in /usr/share/groupoffice/go/core/jmap/EntityController.php at line 260: unsupportedSort
[error][go\core\ErrorHandler:73] #0 /usr/share/groupoffice/go/core/controller/Link.php(50): go\core\jmap\EntityController->defaultQuery()
[error][go\core\ErrorHandler:73] #1 [internal function]: go\core\controller\Link->query()
[error][go\core\ErrorHandler:73] #2 /usr/share/groupoffice/go/core/jmap/Router.php(209): call_user_func()
[error][go\core\ErrorHandler:73] #3 /usr/share/groupoffice/go/core/jmap/Router.php(92): go\core\jmap\Router->callAction()
[error][go\core\ErrorHandler:73] #4 /usr/share/groupoffice/go/core/jmap/Router.php(68): go\core\jmap\Router->callMethod()
[error][go\core\ErrorHandler:73] #5 /usr/share/groupoffice/api/jmap.php(14): go\core\jmap\Router->run()
[error][go\core\ErrorHandler:73] #6 {main}
[end] Link/query,  ID: clientCallId-38, time: 2ms, Peak memory usage: 1.32MB

**Comment by derjoachim** [comment]
What's the exact GroupOffice version you are currently using? I have tried to reproduce this error against both 6.5.60 and 6.4.237 and did not get the error you posted.

**Comment by cymuc** [comment]
The problem was with 6.5.58 and was resolved with the update to 6.5.59. I have also posted a support ticket regarding this issue. 

Thank you.

**Comment by mschering** [comment]
OK thanks!
