### ISSUE TITLE
Authentication via POST-Request over '/api/auth.php' doesn't work any longer

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#712]
Hello,
since version 6.5.61 the authentication via POST-Request isn't working anymore.
I put it by curl. Here's my code:

> $auth_string = '{ "username": "'.$u.'", "password": "'.$p.'" }';
$url = 'https://192.168.123.200/go/api/auth.php';
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
curl_setopt($ch,CURLOPT_TIMEOUT,3);
curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,3);
curl_setopt($ch,CURLOPT_HTTPHEADER,array('Content-type:application/json',));
curl_setopt($ch,CURLOPT_POST,1);
curl_setopt($ch,CURLOPT_POSTFIELDS,$auth_string);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
$res = curl_exec($ch);
curl_close($ch);
return $res;

Nowadays it returns only one line:
> {"debug":[]} 

The php-faillog returns:
> [29-Jun-2021 15:06:17 UTC] InvalidArgumentException in /home/web/go/vendor/donatj/phpuseragentparser/src/UserAgentParser.php at line 50: parse_user_agent requires a user agent

The JS-console returns nothing

Greetings robw

**Comment by mschering** [comment]
GO stores the platform and browser in the authentication tokens so it can be presented to the user in the account page now.

I'll fix the requitrement in the next release. In the meantime you can fix it by setting a user agent:

curl_setopt($ch, CURLOPT_USERAGENT, "My Awesome Script");

**Comment by mschering** [comment]
PS: It's better to use an API key instead of storing username and passwords elsewhere.

https://groupoffice.readthedocs.io/en/latest/developer/jmap.html
