### ISSUE TITLE
[Appointment Recurrence] Recurrence is changed to "Forever" after any modification

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#714]
In GO 6.5.62

When modifying an event who have a reccurence (like the subject), the recurrent is changed to "Repeat forever"

Step to reproduce :
 - create an event 
 - choose a recurrence like 3 times
 - Save and close the event
 - Open the event (entire series)
 - Change the subject
 - Save and close the event
 - The event is now repeating forever

**Comment by mschering** [comment]
This one is fixed in 6.54.70
