### ISSUE TITLE
[Encodage Categorie] Defaut encodage in category choice

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#715]
In GO 6.5.62

Adding a category with an "&" is ok : 

![image](https://user-images.githubusercontent.com/76783618/124577683-c8f0bb80-de4d-11eb-9974-f3b371dd8d55.png)

Choosing a category in an appointment (encodage issue) : 

![image](https://user-images.githubusercontent.com/76783618/124577779-defe7c00-de4d-11eb-9355-244735e1aa69.png)

**Comment by derjoachim** [comment]
Fixed. This will be rolled out in 6.5.69.
