### ISSUE TITLE
6.5.66 SQLSTATE[23000] Integrity constraint violation

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#719]
I'm getting the following SQLSTATE error when trying to add an E-Mail template.
The error pops up when trying to save the new template.

Refresh and logout/login doesn't help.

![Clipboard01](https://user-images.githubusercontent.com/2633051/126124569-637ff2e4-6363-432d-916e-068ef2f0cd40.jpg)

**Comment by mschering** [comment]
Can you retest in .67?

**Comment by thomasgg23** [comment]
Did the upgrade, but sorry keeps the same.

Also have the same output in checkDatabase as in #718

**Comment by mschering** [comment]
Can you send me your core_module and core_entity table?

**Comment by thomasgg23** [comment]
You got mail

**Comment by mschering** [comment]
thanks, please try 6.5.68

**Comment by thomasgg23** [comment]
6.5.68 works for me.

Mail templates and checkDatabase without errors.

Thanks.
