### ISSUE TITLE
"Exeption" in code

### ISSUE THREAD

**Issue by beiDei8z** [Intermesh/groupoffice#720]
`[Wed Jul 21 11:53:11.061977 2021] [php7:notice] [pid 5663] [client 192.168.99.99:40142] Error in /usr/share/groupoffice/go/core/model/Group.php at line 239: Class 'Exeption' not found, referer: https://go.domain.tld/
`

Why it gets there is a more difficult problem for another day.

Also please edit /usr/share/groupoffice/go/base/exception/Database.php at the same time, clearly a bad typing habit.

**Comment by mschering** [comment]
Thanks, just fixed that.
