### ISSUE TITLE
Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by beiDei8z** [Intermesh/groupoffice#721]
I am getting the error:
`[Fri Jul 23 10:07:25.556265 2021] [php7:notice] [pid 12875] [client 2aff:8888:aaaa:11::22:52889] ErrorException in /usr/share/groupoffice/modules/tasks/scripts.inc.php at line 2: Trying to get property 'id' of non-object, referer: https://go.domain.tld/`

As admin logging in twice works; as a user no attempt succeeds. The same "'id' of non-object".
Commenting the includes in /usr/share/groupoffice/views/Extjs3/modulescripts.php allows login but then unsurprisingly other errors prevent use full use of modules.

Debug log below.

I have done a fresh install, including the OS.  I create one admin instance and enable multi instance, I create one sub instance, I login in as admin and "install", I create one user.  I have been working on this for too long and need some help, please ask for whatever information you require to help fix this.

**Comment by beiDei8z** [comment]
Debug log
[debug.log](https://github.com/Intermesh/groupoffice/files/6867840/debug.log)

**Comment by mschering** [comment]
Somehow the session cookie is not registered correctly. Are you perhaps blocking cookies?

**Comment by beiDei8z** [comment]
Firefox Cookie setting are set to standard. It sets 2 cookies: accessToken and groupoffice.

The (first) problem is it can't login.  There is no user at this point so it is not surprising the modules can't load based on user anyway.

Given it complains about being a non-object I have added if (is_object(\GO::user())) in front of "foreach ($load_modules as $module) {"  This lets it log in.

It then complains further "An error occurred. More details can be found in the console." only there is NO error in the console.  Which console / file am I expected to see these errors?  /var/log/apache2/error.log ?

Is there a logger set up so I can do something like:
logger.print("\GO::user() = " + \GO::user());
This is PHP so I am finding debugging hard.

**Comment by beiDei8z** [comment]
It would be really helpful if when it said "An error occurred. More details can be found in the console." I know which console this is supposedly in. It's not /var/log/apache2/error.log.

**Comment by beiDei8z** [comment]
The problem has something to do with blocking cookies and proxying to https.  If I connect in pure http it works including via the proxy.  It also works http without the proxy but then I run out of IPv4 address (and uses don't have IPv6) and of course it is not https.

It is not the proxy but some combination of the back-end thinking it is https when it is not or vice vesa. Like the Cookie gets "secure" added, like the back end thinks it is http when it is not and the browser blocks the Cookie as it thinks it is cross-site.

**Comment by beiDei8z** [comment]
Cookie “groupoffice” will be soon treated as cross-site cookie against “https://go.xxxxxxx/#summary” because the scheme does not match. go.xxxxxxxx
Cookie “accessToken” will be soon treated as cross-site cookie against “https://go.xxxxxxxx/#summary” because the scheme does not match. go.xxxxxxxxx
Cookie “groupoffice” will be soon treated as cross-site cookie against “https://go.xxxxxxxx/#summary” because the scheme does not match. go.xxxxxxxx
Cookie “accessToken” will be soon treated as cross-site cookie against “https://go.xxxxxxxx/#summary” because the scheme does not match.

etc.
The site is https. Every page it is loading is https, how is the cookie https only?  Or not?

**Comment by mschering** [comment]
Have you set these headers so GO knows about being on https or not?

https://groupoffice.readthedocs.io/en/latest/install/extras/httpproxy.html

**Comment by beiDei8z** [comment]
Thank you, good advice, The proxy already had:

        proxy_set_header   Host $host;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_set_header   X-Forwarded-For $remote_addr;

"Host" appears to be usedl for "X-Forwarded-Host" line 274 go/core/http/Request.php but I have added this anyway:
       proxy_set_header   X-Forwarded-Host $host;
Where the documentation says "hostname of the proxy server" I assume that is of the requested virtual host, $host in nginx variables; the proxy server itself has multiple names.

Removing "Host" in favour of "X-Forwarded-Host" results in:
```
Not found
Sorry, this instance wasn't found. Please double check the URL you've entered.
```
so I now have both.

I think the documentation omits "X-Forwarded-For", see line 361 go/core/http/Request.php.

**Comment by mschering** [comment]
And does it work now with both?

**Comment by beiDei8z** [comment]
I have partial success as it was.  I cleaned out all cookies, cleared the browser cache, allowed it to use http and https.  I have several subdomains, eg go.domain.tld, gotest.domain.tld, goadmin.domain.tld, I wondered it the cookies are *.domain.tld - that is a theory for me to investigate I haven't proved anything yet.  Maybe stored the cookie values where just wrong.

A tester user can't get it to work yet but we are still searching for why so don't concluded anything yet.  The fact it worked at least once gives me something to study.

**Comment by mschering** [comment]
Strange, we haven't encountered a problem like this before. My best guess it's something with the proxy settings.

**Comment by mschering** [comment]
Did you manage to solve this? Can I close this issue?

**Comment by beiDei8z** [comment]
Yes.  Odd though as the fix was just to delete the cookies and cache.  I agree that the proxy is the obvious suspect however the failure started with out change to the proxy - at least I could see none. Somewhat embarrassing [for me] if all it needed was cookies cleaned out but I can't be sure that was the actual problem, highly likely proxy corrupted something including the cookies.  It might get confused as I have been logging in as multiple uses from one browser. Whatever, it is working and I thank you for your help.

**Comment by mschering** [comment]
Okay thanks. I'll close this issue.
