### ISSUE TITLE
email attachments not able to open/download

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#723]
When trying to get the attachment of an email, i get a file with this content:

file_exists(): open_basedir restriction in effect. File(/dummypath/file.xlsx) is not within the allowed path(s): ...

To be honest, /dummypath/ is the real path from the error message, but not the right path from webserver.
So, where does this come from?

**Comment by mschering** [comment]
open basedir might not work reliably with GO. But I made a fix for this in the next 6.5 release.
