### ISSUE TITLE
[6.5.73] SQL Access denied error after update

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#725]
We got those errors after the last two updates.
System running on ubuntu 20.04 LTS, mysql server 8.0.26

From 6.5.72 -> 6.5.73
Upgrade output will be logged into: log/upgrade/20210825_192953.log
Failed to disable 'innodb_strict_mode': SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation
Rebuilding cache
Registering all entities
Done!

From 6.5.73 -> 6.5.74
Upgrade output will be logged into: log/upgrade/20210901_060733.log
Failed to disable 'innodb_strict_mode': SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SYSTEM_VARIABLES_ADMIN or SESSION_VARIABLES_ADMIN privilege(s) for this operation
Rebuilding cache
Registering all entities
Done!

**Comment by mschering** [comment]
It tries to disable that on upgrades because in some cases it failed to migrate large sets of custom fields from 6.3 to 6.4. You can safely ignore this error.

**Comment by thomasgg23** [comment]
Okay thanks
