### ISSUE TITLE
Incorrect image path for two factor authentication

### ISSUE THREAD

**Issue by FireFrei** [Intermesh/groupoffice#727]
Hi,

I'd like to enable two factor authentication with the google authenticator module, but after entering my password, it ends up with the following error message:

`imagepng(/tmp/groupoffice/163272634xxxxxxxx5264328.mysite //HELLO): failed to open stream: No such file or directory`

Note: "mysite //HELLO" is my configured site name (I replaced my actual site name with "mysite //HELLO" for this post, but the styling with " //" is the same). Looks like the URL forming for the QR code image uses the configured site name but does not handle spaces and special characters correctly.

Cheers!
Matthias

**Comment by FireFrei** [comment]
Group Office Version: 6.5.78

**Comment by derjoachim** [comment]
When generating a QR code for enabling OTP, it is saved as a temporary PNG file in /tmp/groupoffice . This blob is then retrieved for display in the OTP . The error you see, is triggered when a temporary file is not being saved properly, thus not found. 

Is there any earlier error in your apache log that may lead to reproducing / solving your error?  Perhaps, an error is triggered before saving the QR code temporarily.

**Comment by FireFrei** [comment]
I think the problem is, that the global site name is included in the file path. If the site name contains special characters like '/', they are simply copied to the filename - resulting in an invalid path.
Example:
Sitename: "Example / Partner" will result in file path "/tmp/groupoffice/Example / Partner" for the QR-Code, where "Partner" is interpreted as a separate folder rather than part of the file name.

I guess when using the site name in file paths it should be slugified or converted to whitelisted characters, like:
 "/tmp/groupoffice/Example_Partner".
