### ISSUE TITLE
Go 6.5 Disable default group by Date  in Email Module

### ISSUE THREAD

**Issue by deependhulla** [Intermesh/groupoffice#734]
Go 6.5 has default group by ..date  in Email Module..and so it group show, today ,yesterday, date wise group.
in 6.4 it was available  as option to ON and Off,  while 6.5 does not have option to Disable this.

How to disable this feature.

As evaluating Version: 6.5.81 for using php 8 on Server on Debian 11

Thanks in advance.

**Comment by mschering** [comment]
This is due to the new button for disabling and enabling columns. It has no support for grouping yet. We'll need to fix that.

**Comment by deependhulla** [comment]
Thanks would wait for feature, till that time would go with 6.4

**Comment by derjoachim** [comment]
See the date grouping option in 6.6. Closing this ticket. :-)
