### ISSUE TITLE
[Permission Module by Default / API] Remove the default permissions

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#737]
When creating a group with the API, there is some default Module permission : 
Example here just after creating the group with API : 
![image](https://user-images.githubusercontent.com/76783618/140413758-a694897f-6423-4e4a-9a9b-9a4c1dc843c5.png)

Is there a way to not assign this module's permissions ?

This problem does not occur when creatin the group in the admin web interface.

**Comment by mschering** [comment]
Can you share the way you use the API?

**Comment by michaelSoluris** [comment]
Sorry, the problem was in our code
