### ISSUE TITLE
[Inviting participants]  no consideration of the answer

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#738]
For some users, not all, but many, without me being able to determine why, the invitations do not work correctly:

The event appears by default as accepted by the participant and regardless of the answer chosen, it appears in detail in "Not yet answered"

![image](https://user-images.githubusercontent.com/76783618/140422305-53598a6a-2101-419e-b63c-c6d52f03279b.png)

**Comment by michaelSoluris** [comment]
You can check on our GroupOffice (i've just send you access by mail)
I've just made a this example : 
 - event the November 14, 2021 7:45am
 - m.edlich invite t.boyer
 - the answer of t.boyer is not saved

**Comment by mschering** [comment]
It happens when a user doesn't have any email addresses configured or when he has access to the email address of another participant. I made a fix for that for the next 6.5 release!
