### ISSUE TITLE
[Calendar export Module] Available even if no permission on it

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#739]
The calendarexport  module is available for the user even if there is no permission for this module : 

![image](https://user-images.githubusercontent.com/76783618/140423008-d8100a2b-4cb8-4858-b8b5-a9c5301a10fc.png)
![image](https://user-images.githubusercontent.com/76783618/140423066-aa682d19-c13f-4b91-ba71-ff7f65d18948.png)
![image](https://user-images.githubusercontent.com/76783618/140423094-31e47a60-2cf7-4cbd-bc04-695c7474560c.png)

**Comment by mschering** [comment]
Fixed in the next 6.5 release
