### ISSUE TITLE
[User's Groups] No way to list them

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#740]
When having a lot of groups,
And you want to see to which group belong an user, it's not possible : 
![image](https://user-images.githubusercontent.com/76783618/140423383-273bed4c-caa0-4fb2-8dd8-3a294a51d55a.png)

Is it a way to see easily all the groups of an user ?

**Comment by derjoachim** [comment]
I would suggest adding a toggle filter above the groups grid, just like the user management screen:

![image](https://user-images.githubusercontent.com/1264970/140538825-79739797-55de-4f47-9525-970b5885f153.png)

Will do that as soon as I get the chance.

**Comment by derjoachim** [comment]
As of 6.5.85, the user's groups will be sorted by membership status:

![image](https://user-images.githubusercontent.com/1264970/140772773-76dde76e-234f-4da0-8f5f-40caf4a69bc4.png)
