### ISSUE TITLE
6.4.235 delete calendar entry with deactivated user

### ISSUE THREAD

**Issue by wnglobal2000** [Intermesh/groupoffice#741]
In 6.4.235 we noticed this behaviour: 
if you want to delete a calendar entry with a deactivated user and notify the recipients this error message occurs:
**Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients "**

### To reproduce this behaviour:

1. create calendar entry and add and invite users
2. deactivate one invited user (usersettings -> active checkbox)
3. delete this calendar entry and notify them
4. all users before the deactivated user will get a cancellation mail, but entry will not delete until the deactivated user is removed from participients list.

Error message:
![pasted-image1](https://user-images.githubusercontent.com/23655076/140906267-c3d0af2e-ace9-448b-b1a2-180c501d123b.png)

**Comment by wnglobal2000** [comment]
It would be helpful to mark "deactivated" users in the participants or change the error message to something "remove deactivated users from calendar entry"...

**Comment by derjoachim** [comment]
Fixed for 6.4 and 6.5 . The system will not try to send a cancellation email to a disabled user.
