### ISSUE TITLE
Using MariaDB cluster doesnt work

### ISSUE THREAD

**Issue by trickert76** [Intermesh/groupoffice#742]
Today I tried to install a fresh 6.4.244 version together with a running 3-node MariaDB cluster. I could try the same with "master" branch, but the source didn't change at the concrete classes.

The installation breaks, because the PHP expects in some situations to have concrete auto_increment primary keys (1,2,3) but in a cluster the primary key is not a +1 but a +(node-count). So concrete it generates the row id (1,4,7)...

For example in in addressbook/Module

		$addressBook->setAcl([
			Group::ID_INTERNAL => Acl::LEVEL_DELETE
		]);

And Group contains three constants

    class Group extends AclOwnerEntity {
        const ID_ADMINS = 1;
        const ID_EVERYONE = 2;
        const ID_INTERNAL = 3;

And that is not good. When I switch to a single node database - everything is fine

So here is the debug stack trace:

```
INSERT INTO core_acl_group (
aclId,
groupId,
level
)
VALUES
(
31,
1,
50
) (0.86ms)
SQL FAILURE: INSERT INTO core_acl_group (
aclId,
groupId,
level
)
VALUES
(
31,
3,
40
)
PDOException in /usr/local/share/groupoffice/go/core/db/Statement.php at line 96: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (si00172.core_acl_group, CONSTRAINT core_acl_group_ibfk_1 FOREIGN KEY (groupId) REFERENCES core_group (id) ON DELETE CASCADE)
#0 /usr/local/share/groupoffice/go/core/db/Statement.php(96): PDOStatement->execute(NULL)
#1 /usr/local/share/groupoffice/go/core/orm/Property.php(1547): go\core\db\Statement->execute()
#2 /usr/local/share/groupoffice/go/core/orm/Property.php(1619): go\core\orm\Property->insertTableRecord(Object(go\core\orm\MappedTable), Array)
#3 /usr/local/share/groupoffice/go/core/orm/Property.php(1083): go\core\orm\Property->saveTable(Object(go\core\orm\MappedTable), Array)
#4 /usr/local/share/groupoffice/go/core/orm/Property.php(1042): go\core\orm\Property->saveTables()
#5 /usr/local/share/groupoffice/go/core/orm/Property.php(1338): go\core\orm\Property->internalSave()
#6 /usr/local/share/groupoffice/go/core/orm/Property.php(1224): go\core\orm\Property->saveRelatedArray(Object(go\core\orm\Relation))
#7 /usr/local/share/groupoffice/go/core/orm/Property.php(1046): go\core\orm\Property->saveRelatedProperties()
#8 /usr/local/share/groupoffice/go/core/orm/Entity.php(345): go\core\orm\Property->internalSave()
#9 /usr/local/share/groupoffice/go/core/model/Acl.php(110): go\core\orm\Entity->internalSave()
#10 /usr/local/share/groupoffice/go/core/orm/Entity.php(296): go\core\model\Acl->internalSave()
#11 /usr/local/share/groupoffice/go/core/acl/model/AclOwnerEntity.php(107): go\core\orm\Entity->save()
#12 /usr/local/share/groupoffice/go/core/acl/model/AclOwnerEntity.php(44): go\core\acl\model\AclOwnerEntity->saveAcl()
#13 /usr/local/share/groupoffice/go/core/orm/Entity.php(296): go\core\acl\model\AclOwnerEntity->internalSave()
#14 /usr/local/share/groupoffice/go/modules/community/addressbook/Module.php(103): go\core\orm\Entity->save()
#15 /usr/local/share/groupoffice/go/core/Module.php(160): go\modules\community\addressbook\Module->afterInstall(Object(go\core\model\Module))
#16 /usr/local/share/groupoffice/go/core/Installer.php(155): go\core\Module->install()
#17 /usr/local/share/groupoffice/install/install.php(77): go\core\Installer->install(Array, Array)
#18 {main}
```

For further informations have a look at https://galeracluster.com/library/kb/auto-increment-multiples.html

**Comment by trickert76** [comment]
So, I would advice to remove the constants at least from go\core\model\Group and create a function that makes a select on core_group and maybe cache the response. The problem maybe to concrete identify the concrete row, so maybe add a separate unique column for admins, internal, everyone that cannot be customized. I think, the only other position is the ID_SUPER_ADMIN in go\core\model\User.

**Comment by mschering** [comment]
Wouldn't inserting them with the hardcoded ID's work as well?

**Comment by trickert76** [comment]
Yes, I think, that would work (because then the auto_increment is not used)

**Comment by mschering** [comment]
Fixed this for the next release!

**Comment by trickert76** [comment]
I must reopen the issue. I've tested the solution with v6.5.94 today and got the error

    Could not set user with id 1 in Session::setCurrentUser()!

during installation process. The database was empty and the files are completly fresh (using a docker image).

The error is correct. In table core_user there is only one row and it contains: id=2, username=admin, ...
After that the installation isn't finished. There are only 58 tables created.
