### ISSUE TITLE
6.4.235 + 6.5.45 - Start page open URL if scrollbar active

### ISSUE THREAD

**Issue by wnglobal2000** [Intermesh/groupoffice#747]
We found out that if there is too much text on the start page and the scrollbar gets active, URLs from the text do not work.

Behaviour:
scrollbar jumps to top, but URL is not openend

Reproduce:
Copy many lines with URL into the startpage until the scrollbar gets active - scroll down and try to open link

**Comment by mschering** [comment]
Will be fixed in the next release.
