### ISSUE TITLE
Call to undefined function delete_calendar_dav()

### ISSUE THREAD

**Issue by slt-rapha** [Intermesh/groupoffice#748]
Got an error when trying to sync mails via mobile:
`AH01071: Got error 'PHP message: Error in /var/www/office/groupoffice-6.5.89/modules/z-push/backend/go/goMailInvite.php at line 84: Call to undefined function delete_calendar_dav()'`

Last synced mail is just before a "meeting is cancelled" automated mail. When I delete this mail syncing continues.

Version 6.5.89

**Comment by mschering** [comment]
Fixed in 6.5.92
