### ISSUE TITLE
After upgrading, no login possible, missing method getcolor

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#752]
Error in go/core/data/Model.php at line 300: Call to undefined method go\modules\community\addressbook\model\Contact::getcolor()

**Comment by mschering** [comment]
Did you upgrade from 6.4 to 6.5?

In 6.5 this function is no longer there. It could be due to some old cache. Can you try to run /install/upgrade.php again?

Did you upgrade on the command line by the way? There's a problem with apcu not being cleared from the command line.
