### ISSUE TITLE
sodium error when launching

### ISSUE THREAD

**Issue by jlockman2** [Intermesh/groupoffice#755]
### Discussed in https://github.com/Intermesh/groupoffice/discussions/754

<div type='discussions-op-text'>

<sup>Originally posted by **jlockman2** December  8, 2021</sup>
I have installed Group Office on our server and when I launch the URl I get the following error:  ErrorException in Unknown at line 0: Module 'sodium' already loaded at 2021-12-08T20:57:47+01:00    I previously installed sodium PHP extension as required for another application.  Is there a way to resolve this for Group Office?</div>

**Comment by mschering** [comment]
The error occurs when the module sodium.so is loaded twice in the php configuration.
