### ISSUE TITLE
Installation on DB cluster still not working

### ISSUE THREAD

**Issue by trickert76** [Intermesh/groupoffice#760]
I must reopen the issue #742. I've tested the solution with v6.5.94 today and got the error

Could not set user with id 1 in Session::setCurrentUser()!

during installation process. The database was empty and the files are completly fresh (using a docker image).

The error is correct. In table core_user there is only one row and it contains: id=2, username=admin, ...
After that the installation isn't finished. There are only 58 tables created.

**Comment by mschering** [comment]
Sorry, I should have foreseen this. I fixed the ID's on the groups but not on the admin user. I changed this too in the attached commit.
