### ISSUE TITLE
Blank UI when upgrade to versions above 6.4.150

### ISSUE THREAD

**Issue by kokmik** [Intermesh/groupoffice#763]
My installation is behind an apache reverse proxy. The relevant parts of the proxy config:
```
        ServerName mail.<mydomain>
        ProxyPass "/" "http://webmail.<mydomain>/"
        ProxyPassReverse "/" "http://webmail.<mydomain>/"
        ProxyPreserveHost on
```
The actual Group-Office installation runs on a VM, its vhost config's relevant part is:
```
    ServerName webmail.<mydomain>
    <Directory "/srv/http/webmail.<mydomain>">
        Require all granted
    </Directory>
```
I am currently on version 6.4.150. I use GO with only some of the community modules (mail, contacts, calendar, files, etc.), with activesync. We have mobile clients, using this GO installation as exchange accounts. Both the GO web UI and the activesync works.

However, if I upgrade to any versions after 6.4.150, I experience the following:

- The installer UI appears, I can use its steps to upgrade the DB, and it shows no issues with the server components.
- After the upgrade wizard, I receive a completely white, empty screen (instead of the GO UI or its login screen).
- Activesync continues to work.

Please help me figure out what can be the issue. I see no errors in my apache logs on the VM which is hosting the GO installation.

**Comment by mschering** [comment]
Can you check the apache log for server errors? When there's a white screen there's probably a fatal PHP error.

**Comment by kokmik** [comment]
Unfortunately I see no errors anywhere. My php.ini has these settings regarding error logging:
```
error_reporting = E_ALL
log_errors = On
error_log = syslog
```
After upgrading from 6.4.150 to 6.4.151 I had this error in my syslog:
```Dec 28 11:56:18 webmail php[307043]: ErrorException in /srv/http/webmail.<mydomain>/go/core/cache/Disk.php at line 89: unserialize(): Error at offset 0 of 6 bytes at 2021-12-28T10:56:18+00:00```
After clearing my cache folder I see no errors anywhere. The apache access log has only HTTP 200 messages. The apache error log does not have any new lines at all.
If I have PHP 7.4, the package to use would be groupoffice-6.4.151-php-71.tar.gz, right?

**Comment by derjoachim** [comment]
> After upgrading from 6.4.150 to 6.4.151 I had this error in my syslog:
Dec 28 11:56:18 webmail php[307043]: ErrorException in /srv/http/webmail.<mydomain>/go/core/cache/Disk.php at line 89: unserialize(): Error at offset 0 of 6 bytes at 2021-12-28T10:56:18+00:00
After clearing my cache folder I see no errors anywhere. The apache access log has only HTTP 200 messages. The apache error log does not have any new lines at all.

The error pops up because for some reason, a file in the cache is not readable. After emptying the cache, the error disappears as well. It makes sense, but I am not sure whether that would explain your initial problems. I would expect the cache to be emptied anyway, since that is part of the upgrade process. 

> If I have PHP 7.4, the package to use would be groupoffice-6.4.151-php-71.tar.gz, right?

You are using the right package indeed.

Here's a few thoughts:

- You may want to try enabling the `display_errors` temporarily in php.ini . It may help you find a concrete error message.
- Since you are not seeing any server side errors, are you seeing any on the client side, i.e. in your Javascript Console? You may also want to check the Network tab for any failed requests.

Good luck.

**Comment by kokmik** [comment]
Hi Joachim,

thanks for your suggestions I might have found something (using Firefox console).
After upgrading to 6.4.151, I see the following errors in the console (which does not appear with 6.4.150):

```
Blocked loading mixed active content "http://mail.<mydomain>/views/Extjs3/themes/Paper/style.css?v=1593173989" mail.<mydomain>
Blocked loading mixed active content "http://mail.<mydomain>/views/Extjs3/themes/Paper/style-mobile.css?v=1593173989" mail.<mydomain>
Blocked loading mixed active content "http://mail.<mydomain>/views/Extjs3/css.php?theme=Paper&v=1640863009" mail.<mydomain>
Loading failed for the <script> with source “http://mail.<mydomain>/views/Extjs3/javascript/ext-base-debug.js?mtime=1593173987”. mail.<mydomain>:43:1
Loading failed for the <script> with source “http://mail.<mydomain>/views/Extjs3/javascript/ext-all-debug.js?mtime=1593173987”. mail.<mydomain>:43:1
Loading failed for the <script> with source “http://mail.<mydomain>/views/Extjs3/lang.php?lang=en&v=1640863009”. mail.<mydomain>:43:1
Uncaught ReferenceError: Ext is not defined
    <anonymous> https://mail.<mydomain>/:46
mail.<mydomain>:46:2
Loading failed for the <script> with source “http://mail.<mydomain>/views/Extjs3/script.php?v=%201640863011”. mail.<mydomain>:56:1
Uncaught ReferenceError: Ext is not defined
    <anonymous> https://mail.<mydomain>/:58
mail.<mydomain>:58:1
Loading mixed (insecure) display content "http://mail.<mydomain>/views/Extjs3/themes/Paper/img/favicon/apple-touch-icon.png" on a secure page FaviconLoader.jsm:191:19
Loading mixed (insecure) display content "http://mail.<mydomain>/views/Extjs3/themes/Paper/img/favicon/favicon-32x32.png" on a secure page FaviconLoader.jsm:191:19
Content Security Policy: The page's settings blocked the loading of a resource at http://mail.<mydomain>/views/Extjs3/javascript/ext-base-debug.js?mtime=1593173987 ("script-src").
Content Security Policy: The page's settings blocked the loading of a resource at http://mail.<mydomain>/views/Extjs3/javascript/ext-all-debug.js?mtime=1593173987 ("script-src").
Content Security Policy: The page's settings blocked the loading of a resource at http://mail.<mydomain>/views/Extjs3/lang.php?lang=en&v=1640863009 ("script-src").
Content Security Policy: The page's settings blocked the loading of a resource at http://mail.<mydomain>/views/Extjs3/script.php?v=%201640863011 ("script-src").
```
I replaced all occurences of my FQDN to `mail.<mydomain>`.

This might be the issue: "Uncaught ReferenceError: Ext is not defined"
Also, the non-loading of resources from the http URL could be a problem, because my installation is running in https. However, there is a http vhost configured, which redirects all traffic to the https URL, so I don't really understand these messages. All requests to the http URL should be redirected to https, and served from there.

Regards,
Miklos

**Comment by derjoachim** [comment]
Hmm... I have no experience with reverse proxies, so I am afraid that I cannot help you there. One thought though: if you browse the database table core_setting, there should be a record where the column labeled 'name' is URL. Does its corresponding value start with 'http://' or 'https://'?

**Comment by mschering** [comment]
I think Group-Office is missing the x-forwarded-* headers to determine the hostname. See this:

https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers

**Comment by mschering** [comment]
And this:

https://groupoffice.readthedocs.io/en/latest/install/extras/httpproxy.html

**Comment by kokmik** [comment]
Thanks for your tips, but unfortunately none of them worked. Joachim, the URL was https in the DB. Merijn, the headers are handled properly by default with apache.
I managed to fix my problem by changing the backend webserver's vhost to https (previously it was http, and the proxy frontend was using https). It seems GO was trying to access some elements via http because that was its vhost's setting. Now I am able to upgrade above 6.4.150.

Thank you guys for your help with this case!

**Comment by michalcharvat** [comment]
@kokmik I know this is pretty old issue but few things to it:
We are running GO behind nginx proxy without issues so it has to be proxy configuration problem. 

You should check headers like:

- X-Forwarded-Protocol: https
- X-Forwarded-Proto: https
- X-Forwarded-Ssl: on
- X-Url-Scheme: https
- Front-End-Https: on

X-Real-IP is also useful header.

**Comment by kokmik** [comment]
Thank you for your input @michalcharvat. I remember I tried the header related settings for apache too, and didn't help. I think it works a bit differently than nginx. Ultimately changing the backend to an SSL vhost is what solved my problem.

**Comment by michalcharvat** [comment]
I could ask around if you are still interested in. I dont think there will be different behaviour. Headers mentioned above are +- same headers we are setting on nginx but I have found them in configuration for apache.

**Comment by kokmik** [comment]
No, I used a HTTP backend out of lazyness, and as this issue forced me to change it,  I plan to keep it HTTPS from now on. Even if the traffic goes inside a vswitch in the same box, it is better this way. But if you are interested, I can easily change it back for some tests. Let me know.

**Comment by kokmik** [comment]
@mschering I am closing this issue, my problem has been solved by changing the proxy backend to HTTPS (previously only the frontend was HTTPS, backend was HTTP). It seems it was a problem before 6.4.150 too, just I didn't realized it because the GUI worked.
