### ISSUE TITLE
[API] Call to /index.php?r=calendar/calendar/load doesn't work with debug=false.

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#765]
This call works when debug (in config.php) is set to true :  

http://localhost:8081/index.php?r=calendar/calendar/load&id=4
![image001](https://user-images.githubusercontent.com/76783618/147074049-0fb34d8b-941e-4b87-81c8-856afc43d9b4.png)

Then the same call is not working anymore after debug set to false : 

http://localhost:8081/index.php?r=calendar/calendar/load&id=4
![image002-1](https://user-images.githubusercontent.com/76783618/147074393-19053505-f69a-4bdf-b766-362c32d93514.png)

**Comment by michalcharvat** [comment]
Problem is, you didnt add security_token to the request when you disabled debug mode. You can disable token check via disable_security_token_check directive. Security token have to be available in login response.
