### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.core_module' doesn't exist

### ISSUE THREAD

**Issue by shivnath11** [Intermesh/groupoffice#767]
Hi,
I am installing GO6.5.59 on centos7 php-7.4.27 and mariadb 10.6.5
but on installation its giving error of 

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.core_module' doesn't exist
on Page INSTALL LICENSE.

Didnot find solution .
Pls help me out.
I want to use it free .

Regards
Shivnath
![Capture](https://user-images.githubusercontent.com/96863335/147733669-f913374c-abf9-4f8c-a9bb-e8a3241917cf.JPG)

**Comment by mschering** [comment]
Strange, your should not be seeing this page before the database has been installed. Did you get any errors before this?

Can you restart from scratch and report the first error you're getting?

**Comment by derjoachim** [comment]
Closing this ticket due to inactivity. @shivnath11 please reopen as needed. Also, I would advise updating PHP to a currently maintained version and Group Office to 6.6.X. MariaDB seems fine.
