### ISSUE TITLE
Can't activate Newsletter module with community license

### ISSUE THREAD

**Issue by zavrazhny** [Intermesh/groupoffice#769]
Newsletter module is a community feature that I believe shouldn't require any license, but unfortunately I just can't activate this module - checkbox is inactive. What I am doing wrong or maybe policy has changed?

**Comment by derjoachim** [comment]
You are correct about the policy change. Starting from version 6.4, it was separated into its own module. During that time it was moved to the professional package as well.

**Comment by zavrazhny** [comment]
OK though a bit pity. I would suggest the company updating website which is stating different things.

**Comment by mschering** [comment]
Yes, we're working on a complete new website. 

The reasons are explained in the post here:
https://www.group-office.com/blog/post?id=806777747112516534

We want to make the groupware part always fully open source. And all business oriented features as paid add ons. We feel that the newsletters are a business feature. On the other side we open sourced all of the sync features.
