### ISSUE TITLE
Files -> Folder thumbnail broken

### ISSUE THREAD

**Issue by gtech99** [Intermesh/groupoffice#772]
the core/thumb function tries to show a folder preview thumbnail but it fails because the folder image file (/usr/share/groupoffice/views/Extjs3/themes/Paper/img/filetype/folder_shared.svg) is SVG and can't be parsed using the GD functions in 
/usr/share/groupoffice/go/base/util/Image.php

therefore, showing folder thumbnails isn't possible. This happens in the big thumbnails option of Files, not the list option

**Comment by mschering** [comment]
I can't replicate that. Folders show up fine:

![image](https://user-images.githubusercontent.com/1314447/203985546-c02128a7-e896-4e29-9780-5183f2b6afe9.png)
