### ISSUE TITLE
Import into address book is not possible

### ISSUE THREAD

**Issue by perasser** [Intermesh/groupoffice#775]
**Description:**
It is not possible to import a VCF-file into the address book in v6.6.28.

**How to reproduce:**
1) Export in v6.6.28 works
2) Import in v6.5.96 works, but it does not work in v6.6.28

**Error message:**
<img width="594" alt="Bildschirmfoto 2022-01-09 um 16 31 33" src="https://user-images.githubusercontent.com/56738244/148690545-e9365a17-991f-45b8-bf86-47c042a71be3.png">

**Comment by mschering** [comment]
Thanks, will be fixed in the next release.
