### ISSUE TITLE
task filter grouping like faktura

### ISSUE THREAD

**Issue by migoe101** [Intermesh/groupoffice#777]
Using the filters you can select the desired entries but it always remains a grouping by address list.

It would be nice to be able to group not only by address list, but also by status or responsibility, for example.

![image](https://user-images.githubusercontent.com/46790962/149358876-0e08a67a-a4c9-4abe-9d63-b0e373641292.png)

**Comment by migoe101** [comment]
This is how it was in the old task module unitl 6.5

**Comment by mschering** [comment]
This was implemented some time ago.
