### ISSUE TITLE
Notes exportation, small request - category name

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#786]
@derjoachim , you were so nice to add notes exportation. Great, I only later noticed I can export all of them at once too, great! :)

Just 1 thing. 

See image, pls.

I miss the category name in the exportation (in the example, it would be "8dweb"). It puts, instead, a code.
![go-image-0](https://user-images.githubusercontent.com/44004645/150535082-2523b368-1c88-45e3-9ec1-bde7909ee7ce.png)
![go-image](https://user-images.githubusercontent.com/44004645/150535086-50c41296-e1f1-4d68-9a7c-081ec24ac53b.png)

Thanks!

**Comment by mschering** [comment]
Fixed for the next release
