### ISSUE TITLE
Feature request: ActiveSync + GAL

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#789]
In newer ActiveSync implementations (other systems), it's possible to sync public folders of contacts, not just one address book, as I believe its the case with GO.

Would be nice if we had this, so customers can sync, not just their PVT contacts, but also GAL and other address books (example: one containing company's provers/furnishers).

Thanks.

**Comment by mschering** [comment]
This has been implemented in the most recent versions.

**Comment by flaviozluca** [comment]
Great! Starting in which version?

**Comment by mschering** [comment]
Since 6.8.36

**Comment by flaviozluca** [comment]
Thanks.
