### ISSUE TITLE
tasklist ID option for Import

### ISSUE THREAD

**Issue by migoe101** [Intermesh/groupoffice#790]
Nice Import dialog, pls also add in other modules like adressbooks and notes. Make it easy for normal user without id lists.

But pls add an option to select entity id by import tasklistID and so on to make it possibel to Import over all. 

![Image 1](https://user-images.githubusercontent.com/46790962/151182129-b3e5cf26-9f2d-476d-a31c-8470109eff39.png)

Or only set tasklistID by dialog as fixed value in Import dialoge , so advance user can change them i need to import in more than one tasklist by a singel import.

![image](https://user-images.githubusercontent.com/46790962/151183044-3ae52729-b7c4-4449-95d8-79beeb47c137.png)

**Comment by mschering** [comment]
NIce idea! Will look into this.

**Comment by derjoachim** [comment]
Did look into it. :-)

To be released in 6.6.136
