### ISSUE TITLE
GO 6.6 not working with PHP8.1

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#798]
Hello,
since updating to php 8.1 I get only a "blank" GO and following php errors:

> [03-Feb-2022 16:54:14 UTC] PHP Fatal error:  During inheritance of JsonSerializable: Uncaught Error: Class "go\core\util\ArrayObject" not found in /home/web/go/go/core/App.php:388
Stack trace:
#0 /home/web/go/go/core/Debugger.php(79): go\core\App->getConfig()
#1 /home/web/go/go/core/App.php(614): go\core\Debugger->__construct()
#2 /home/web/go/go/core/App.php(630): go\core\App->getDebugger()
#3 /home/web/go/go/core/ErrorHandler.php(133): go\core\App->debug()
#4 /home/web/go/go/core/util/ArrayObject.php(8): go\core\ErrorHandler::errorHandler()
#5 /home/web/go/vendor/composer/ClassLoader.php(444): include('...')
#6 /home/web/go/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#7 /home/web/go/go/core/App.php(388): Composer\Autoload\ClassLoader->loadClass()
#8 /home/web/go/go/core/App.php(510): go\core\App->getConfig()
#9 /home/web/go/go/core/Settings.php(99): go\core\App->getCache()
#10 /home/web/go/go/core/Settings.php(33): go\core\Settings::dbIsReady()
#11 /home/web/go/go/base/Config.php(326): go\core\Settings::get()
#12 /home/web/go/go/base/Config.php(1334): GO\Base\Config->getdefault_timezone()
#13 /home/web/go/go/GO.php(645): GO\Base\Config->__get()
#14 /home/web/go/GO.php(13): GO::init()
#15 /home/web/go/index.php(59): require('...')
#16 {main} in /home/web/go/go/core/util/ArrayObject.php on line 8
[03-Feb-2022 16:54:14 UTC] PHP Fatal error:  Uncaught Error: Class "go\core\util\ArrayObject" not found in /home/web/go/go/core/App.php:388
Stack trace:
#0 /home/web/go/go/core/Debugger.php(79): go\core\App->getConfig()
#1 /home/web/go/go/core/App.php(614): go\core\Debugger->__construct()
#2 /home/web/go/go/core/App.php(630): go\core\App->getDebugger()
#3 /home/web/go/go/core/ErrorHandler.php(98): go\core\App->debug()
#4 /home/web/go/go/core/ErrorHandler.php(40): go\core\ErrorHandler->exceptionHandler()
#5 [internal function]: go\core\ErrorHandler->shutdown()
#6 {main}
  thrown in /home/web/go/go/core/App.php on line 388
`

Do I have to go back to php 7.4 or is there a hope for remedy?
Thanks robw

**Comment by michalcharvat** [comment]
Hello, do you have installed php-json extension?

**Comment by robshnup** [comment]
Hello,
good question!
Here with Debian-Testing (Bookworm) there is no special module php8.1-json.
If I install the default module php-json I get the following error:

> Uncaught exception: Error in /home/web/go/go/core/App.php at line 388: Class "go\core\util\ArrayObject" not found at 2022-02-03T21:29:20+00:00

In so far no clearance...
Greetz robw

**Comment by michalcharvat** [comment]
It is similar to previous log. I guess error is probably on line 116 in file ArrayObject.php. Method jsonSerialize is incompatible with PHP 8.1. You have to try downgrade to 8.0 or 7.4 which are compatible. I am afraid there won't be the version compatiblle with 8.1 until there will be new branch. However this version will be compatible only with 8.1+ and because there are customers who still use supported PHP 7.4 and 8.0 I don't think this version will be available in next few months 

@mschering fyi

**Comment by robshnup** [comment]
Really a pity.
Debian bookworm doesn't offer php8.0 (or 7.4) - only 8.1.
And that would lead to a complete re-installation.

Such a bummer...
Greetings robw

**Comment by mschering** [comment]
I'll look into it today.

**Comment by mschering** [comment]
It's impossible right now. As we use libraries that haven't been upgraded yet too. But why do you use an unstable distro anyway?

**Comment by robshnup** [comment]
Perhaps not my best idea! It's because of the new ntfs implementation.
Anyway - many thanks for your efforts!
Greetings robw

**Comment by mschering** [comment]
I actually did succeed now. Next 6.6. release should be 8.1 compatible.

Unfortunately the pro version won't be as Ioncube has no php 8 loaders yet :(

**Comment by robshnup** [comment]
Hey Merijn, these are *great* news!
I have to thank you very very much. Makes me happy these dark days

Good greetings robw
