### ISSUE TITLE
JAMP Router error

### ISSUE THREAD

**Issue by migoe101** [Intermesh/groupoffice#799]
6.6.36 to 6.6.37

![image](https://user-images.githubusercontent.com/46790962/152392003-742795bc-b98b-4dee-994d-124b6769cc71.png)

**Comment by michalcharvat** [comment]
How did you get that error? I just updated to latest 6.6 without issues.

**Comment by michalcharvat** [comment]
Nvm found it 

![image](https://user-images.githubusercontent.com/8058273/152411374-be94b4a1-4c90-4fac-9afb-8be4d2bc88b6.png)

**Comment by migoe101** [comment]
Then i need to check this. I set up a plain vm for 6.6 testing and updated them via apt without problems first from 6.6.36 to 6.6.37. The massage was created by using task and note module, other without error.

**Comment by michalcharvat** [comment]
@migoe101 Quick fix - go/core/jmap/Router.php line 253 change to $params[$name] = $possibleResultReference;

@mschering Could you confirm this fix please?

**Comment by mschering** [comment]
Sorry, will release a fix in a few minutes!

Best regards,
Merijn
