### ISSUE TITLE
GO 6.6 Caldav sign-in fails

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#802]
With the new GO 6.6 sign-in is failing no matter if I go via DaVx5 or via browser.
I cannot say for sure, whether its because of my PHP 8.1 or on account of GO since unfortunately I can't go back to my old Debian bullseye.

A Browser login to caldav reports
`4.1.5 Sabre\DAV\Exception\NotAuthenticated No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured`

Authentication and passwords is thoroughly tested and enabled.
Addresses and Logins were functioning since multiple years.

Greetings robw

**Comment by mschering** [comment]
I have no trouble signing in to caldav on php 8.1 running as apache module.

Perhaps you're using cgi / fpm and you need to forward the header?

See: https://groupoffice.readthedocs.io/en/latest/install/tarball.html#authentication-with-cgi-or-fastcgi

**Comment by robshnup** [comment]
Many thanks Merijn - that did the trick!
But I wonder why it has not been a prob in all of these years?
I use fpm since beginning.
Anyway - have a good week!
