### ISSUE TITLE
Import Files via E-Mail

### ISSUE THREAD

**Issue by migoe101** [Intermesh/groupoffice#804]
It would be nice if there is a function to import Files from Mail to Folder like the auto create function in tickets. 

This make it easy, to connect solutions without any code. Eg for Scan to Mail, if scanner doesnt support Webdav or FTP or simple Upload for non users. Via Mail it is easy to control rules of incoming mails in the mailserver; everyone, only ip, only adress.

**Comment by michalcharvat** [comment]
You can always extend GO with the custom made module :) 

This one could be pretty simple - settings where you define email folder from which will be files imported and second field will be target folder where will be stored. 

Then you just need cronjob which will periodically check the mailbox and import files. 

However don't forget there could be trash in attachment so you have to exclude files like certificates or so. Also don't forget there could be files with same name so perhaps you have to create folder for incoming mail or so. 

And here we are - the general mind is great however devil is always hidden in details :) So perhaps you have to extend module with other options or just use as is and do some things manually.

**Comment by mschering** [comment]
Nice idea! Please contact us for a quote if you'd like us to make this for you.
