### ISSUE TITLE
Back to  issue Feature request: Totals in email view #651 

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#809]
Friends,

The adjustment you made, so that total emails in a pane always appear, the flotating total, is really neat.

Only thing is, not sure if it's worth adjusting or how, it stays on top of the message that's at the very bottom, on top of the time.

See

![image](https://user-images.githubusercontent.com/44004645/153456056-6f1422f7-126c-4234-ba32-9edbcb033b3d.png)

Thanks,
Flávio

**Comment by mschering** [comment]
It dissappears when you click on it.

**Comment by mschering** [comment]
Good idea. I made it disappear on hover

**Comment by flaviozluca** [comment]
Dear Merijn,

Wow, really happy that you liked the idea and thankful.
  

 
 luca.gif
 		 
 		traco_roxo.png
 Atenciosamente/Regards,

Flávio Zarur Lucarelli
Sócio-Diretor
LucaNet Sistemas [1]
55-21-3005-9310 / 55-11-2122-4256
Celular / WhatsApp: 21-99542-4180 (apenas chat) 
 

 


Em Quinta-feira, 21/07/2022 no 5:32 Merijn Schering escreveu:









Good idea. I made it disappear on hover



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1] http://www.lucanet.com.br
[2]
https://github.com/Intermesh/groupoffice/issues/809#issuecomment-1191201415
[3]
