### ISSUE TITLE
IMAP: Unable to connect to ssl after upgrade to 6.5.101

### ISSUE THREAD

**Issue by computersalat** [Intermesh/groupoffice#810]
Did upgrade from
`groupoffice-6.4.247-php-71`
to
`groupoffice-6.5.101`

When trying to access my mail accounts I get
```
ErrorException in xxxxx/groupoffice-6.5.101/go/base/mail/Imap.php at line 135: stream_socket_client(): unable to connect to ssl://imap.xxxxx:993 (Network is unreachable),
```
php --version
```
#PHP 7.4.6 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
```

**Comment by michalcharvat** [comment]
Is your system up to date? Ie do you have latest SSL certificate bundle? What is the output when you run "telnet imap.xxxxx 993" ? Also could you attach output from debug log? Did you try uncheck "Allow self signed certificate when using SSL or TLS" option in account settings?

**Comment by computersalat** [comment]
> Is your system up to date?

Yes

> Ie do you have latest SSL certificate bundle?

of course

> What is the output when you run "telnet imap.xxxxx 993" ?

it is opening.
```
telnet imap.xxxxx 993
Trying IP...
Connected to imap.xxxxx
Escape character is '^]'.
```
What did you expect ?
Be assured that the IMAP Server is working as expected.

> Also could you attach output from debug log?

No, because I did roll back to **working** version

> Did you try uncheck "Allow self signed certificate when using SSL or TLS" option in account settings?

Why should I do that. I am not using that feature because the IMAP server is using Let'S Encrypt certificates.
So why is IMAP not working in 6.5.x while it is working just fine with 6.4.x ?

**Comment by computersalat** [comment]
@michalcharvat
any further ideas on how to solve it ?

**Comment by michalcharvat** [comment]
It would be great see debug log because there should be described what could be wrong. Also please change PHP error reporting to E_NOTICE. Could you try run 6.5 on any different environment where you can test connection to mail server?

**Comment by mschering** [comment]
I checked all differences between 6.4 and 6.5 in the IMAP handling code and there are no relevant differences. I can't think of any reason why 6.5 wouldn't work if 6.4 works.

The only thing I can offer now is to have one of our engineers investigate it on your machine. If you want that please contact us at support@intermesh.nl and mention this issue.
