### ISSUE TITLE
Error: SQLSTATE ; Invalid datetime format: 1992 Truncated

### ISSUE THREAD

**Issue by pa2eon** [Intermesh/groupoffice#813]
At the moment the user login is made.
The Notifications will come up, with the error shown in the picture.
The system is Ubuntu ( US) 20.04 LTS on hosted server.
Any idea what I have to fix about this error ?

The error shown is just a few seconds after make new write en note.

![afbeelding](https://user-images.githubusercontent.com/4719917/155104848-a2476b4f-ccc7-46f6-b652-dbd7d4ea37f2.png)

**Comment by mschering** [comment]
Can you check if the column tag in core_alert is opf type varchar(50)?

**Comment by pa2eon** [comment]
Yes I have checked this value .. and it is configure with varchar(50).
Is the error something in conflict with the (hardware) system time .. the application is hosted at VPS server from Strato.

**Comment by mschering** [comment]
It really looks like the column is an int instead of a string. I can't replicate this error here.
Can you enable debug in config.php and post the error with stack trace here?

**Comment by mschering** [comment]
This one is fixed.
