### ISSUE TITLE
Login via AccessToken or ApiKey throws SSE error

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#816]
Since 6.6.48 login via keys throws this error (SSE in config is enabled):

>Starting SSE
 Firefox kann keine Verbindung zu dem Server unter https://192.168.123.200/go/api/sse.php?types=Alert,Group,User,UserDisplay,Field,FieldSet,Module,Link,Search,EntityFilter,SmtpAccount,EmailTemplate,PdfTemplate,CronJobSchedule,AuthAllowGroup,OauthClient,SpreadSheetExport,Key,Note,NoteBook,Contact,AddressBook,AddressBookGroup,TaskCategory,Tasklist,Task aufbauen.

Afterwards GO is fully functioning except avatar pic is broken.
Logine via user/password has no probs.
Bug or feature?
Greetings robw

**Comment by mschering** [comment]
How exactly do you login via AccessToken or ApiKey?

**Comment by robshnup** [comment]
First e.g. I get AccessToken by curl. (Alternatively take an installed ApiKey)

> function goAuth($u,$p) {
	$auth = '{ "username": "'.$u.'", "password": "'.$p.'" }';
	$url = SRV.'/go/api/auth.php';
	$cmd = 'curl -L -k -H "Content-Type:application/json;charset=utf-8" -X POST '.$url.' -d \''.$auth.'\'';
	$xml = json_decode(shell_exec($cmd));
	return $xml->accessToken;
}

Then send it to GO by Form

> function gotoGO() {
	try {
		const form = eCreate('form','id','myForm','action','/go/index.php','method','POST');
		const name = eCreate('input','type','hidden','name','User','value','username');
		const key = eCreate('input','type','hidden','name','accessToken','value','AccessTokem');
		form.appendChild(name);
		form.appendChild(key);
		document.body.appendChild(form);
		form.submit();
	} catch(err){alert(err);}
}

No matter wether I send an AccessToken or an installed ApiKey - same error response

**Comment by mschering** [comment]
Will be fixed in the next release.
