### ISSUE TITLE
Undefined offset:2

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#819]
Sometimes I got an email which I cannot open in GO (version is now 6.6.54 but I've seen this also in earlier versions). The popup is showing Undefined offset: 2.

Apache log says: [Thu Mar 17 19:06:13.673049 2022] [php7:notice] [pid 899899] [client removed] ErrorException in /usr/share/groupoffice/go/base/util/StringHelper.php at line 813: Undefined offset: 2

PHP version 7.4.28 and Apache 2.4.52

In other mail readers the email is readable. Is this a problem at my side or not? If you need an example I'm happy to send one.

**Comment by koekie71** [comment]
Hmm, that works! I can't remember I have changed that PHP setting in the past.

Thanks :)

**Comment by mschering** [comment]
Could you share the source of the message with this problem for testing? You can send it to support@intermesh.nl

**Comment by koekie71** [comment]
> Could you share the source of the message with this problem for testing? You can send it to [support@intermesh.nl](mailto:support@intermesh.nl)

Done.

**Comment by mschering** [comment]
Sorry, can you send it as an attachment? The CSS in the mail was lost now.

**Comment by mschering** [comment]
Thanks, this issue is fixed in the next release.
