### ISSUE TITLE
Dark theme after refresh not dark anymore

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#820]
I use the dark theme for my account. Sometimes after a refresh (opening browser again or after an update) the dark theme is replaced by the normal theme. After another refresh the dark theme is back again. I've tried to set the theme preference again but that didn't fix the issue. GO version 6.6.54 but this is happening for a while.

**Comment by derjoachim** [comment]
I had this issue occasionally in the past. Are you still able to reproduce this on 6.6.91? When the theme is switched upon reloading, are you getting any error messages?

**Comment by koekie71** [comment]
Today, unfortunately, the same thing. I get the message regarding authentication, then the screen refreshes (FF 100.0.2) and I get to see the default theme. After a refresh by myself I get the dark theme again.

I see no other error message, not even in the Apache log.

**Comment by koekie71** [comment]
Since version 6.6.106 (I think, maybe the earlier version) this little problem is solved. Thank you!

**Comment by mschering** [comment]
Great!
