### ISSUE TITLE
keyserver pool.sks-keyservers.net not working

### ISSUE THREAD

**Issue by 262media** [Intermesh/groupoffice#821]
Following the instructions for Debian based distributions to install Group Office Assistant.
I can't pass step 2 because
gpg --keyserver pool.sks-keyservers.net --recv-keys 0758838B

**Comment by mschering** [comment]
Hi,

Try this command instead:

apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0758838B

Best regards,
Merijn

**Comment by 262media** [comment]
Fixed thank you
