### ISSUE TITLE
Suggestions for the default email client

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#826]
It's really neat, congrats, love the possibility of doing this.

1) The icon here shows up as a blank icon, when you set it up in default clients. See image, Win 11.

2) In the documentation, here https://groupoffice.readthedocs.io/en/latest/using/email.html#default-mail-client-on-your-computer, seems it doesn't mention to add the URL as safe.

Thanks.

![go-default](https://user-images.githubusercontent.com/44004645/162189591-78a3baaa-ddf9-4e11-b6ed-b94b1165c1b5.png)

**Comment by mschering** [comment]
Strange, it used to show as you can see in the docs screenshot. I was able to add the icon in the uninstall apps section but I can't get it to show in the default apps with innosetup :(

What do you mean with number 2?

**Comment by mschering** [comment]
Thanks, I'v e added a note to the docs:

_For this to work you will have to edit at least one file so the assisant knows where your Group-Office installation is hosted._
