### ISSUE TITLE
Jitsi module throws error

### ISSUE THREAD

**Issue by rasos** [Intermesh/groupoffice#827]
Great to be able to set a Jitsi room with new events. 

However, when activating and adding our Jitsi server URL I get when adding a new event:

> Parameter 1 to GO\Jitsimeet\JitsimeetModule::checkIfHasLink() expected to be a reference, value given

**Comment by mschering** [comment]
This has already been fixed in the latest release.

**Comment by rasos** [comment]
We had updated recently and have seen this error on 6.5.108. Ah, when checking the [changelog](https://github.com/Intermesh/groupoffice/blob/master/CHANGELOG.md) I see there is already GO 6.6 out there, so we'll schedule a version upgrade and assume that this error will be gone then.
