### ISSUE TITLE
Service unavailable after upgrade

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#830]
For a couple of weeks I see always after an update the message 'Service unavailable after upgrade' when I refresh the browser window.

When I try to update from the CLI (php /usr/share/groupoffice/cli.php core/System/upgrade -c=/etc/groupoffice/config.php) this works but I got the message to run install again via the browser.  After this GO is working fine. 

I have now version 6.6.71. I'm using the Debian package. Is there something wrong with my system/installation that I have to update manually?

**Comment by mschering** [comment]
Hi,

This message was intentional. Before it redirected to the upgrade database page immediately. This was confusing for end users. The system admin must launch that page manually now,

Best regards,
Merijn
