### ISSUE TITLE
Email not interpreted 100%

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#833]
Dear friends,

Kindly check this? See, the button how it is in GO and also the dark color.
[evidence.zip](https://github.com/Intermesh/groupoffice/files/8489673/evidence.zip)
![evidence-go](https://user-images.githubusercontent.com/44004645/163405605-baf2c748-ea81-4995-a247-fa2729e8c7c3.png)
![evidence-thunderbird](https://user-images.githubusercontent.com/44004645/163405612-808562cd-813e-45d9-b047-c8e944e72ee1.png)

TB/Gmail interpret it fine.

Thanks.

**Comment by flaviozluca** [comment]
Friends,

2 more that appear fine in TB but in GO they present some issue.

Thanks.
[2 more.zip](https://github.com/Intermesh/groupoffice/files/8512863/2.more.zip)

**Comment by flaviozluca** [comment]
1 more
[Dê sua opinião sobre Centrum Silver Mulher Women 50+ Multivitaminico 275 Tablets - 05-05-2022 735.zip](https://github.com/Intermesh/groupoffice/files/8631075/De.sua.opiniao.sobre.Centrum.Silver.Mulher.Women.50%2B.Multivitaminico.275.Tablets.-.05-05-2022.735.zip)

**Comment by flaviozluca** [comment]
Friend,
See this one. Paypal. Same type of issue. The text can't be seen in GO.
![tb](https://user-images.githubusercontent.com/44004645/175283969-aa3b6f8d-4b04-4c2f-b79a-1e1de0c6fc22.png)
![GO](https://user-images.githubusercontent.com/44004645/175283974-89000a2e-6fbe-4a58-bfbb-2ba2ae24ea1d.png)
[Seus valores recebidos transferidos automaticamente para sua conta bancária ou de pagamentos. - 22-06-2022 2104.zip](https://github.com/Intermesh/groupoffice/files/8966600/Seus.valores.recebidos.transferidos.automaticamente.para.sua.conta.bancaria.ou.de.pagamentos.-.22-06-2022.2104.zip)

**Comment by derjoachim** [comment]
Is this still an issue? About a week after the last message in this ticket, a bugfix was released that at least fixes some emails.

**Comment by flaviozluca** [comment]
Thanks, Joachim. In which version?

I'll keep an eye out, Ok?

Thanks.
