### ISSUE TITLE
GO version 6.6.x: Search in cyrillic does not work

### ISSUE THREAD

**Issue by john3v** [Intermesh/groupoffice#834]
In every subversion of GO 6.6. search in Cyrillic does not work.

example:
when I search "Google", everything is as should be, but if string is "Гугъл", results are not reliable.
Temporary solution for that is, when search string is in cyrillic, in front of it I have to write '"name:" or something like that. e.g.
name: Гугъл
will display anything that contains string "Гугъл" in "name"

That maybe is because of code of search string.
I found some examples [here](https://stackoverflow.com/questions/466745/cyrillic-search)

**Comment by mschering** [comment]
Please try to rebuild the search index at System Settings -> Tools -> Update search cache (Complete rebuild). There used to be a bug corrupting those characters but it should be fixed now.

**Comment by john3v** [comment]
It's been done many times. Nothing from admin tolls does not help for that.
You can see same behavior in groupoffice demo site as well.
Exact same issue was detected in version [6.5.77](https://www.group-office.com/support/ticket?ticket_number=202123025&ticket_verifier=41517605) and it was removed in future versions until 6.6

**Comment by mschering** [comment]
Ah sorry, I broke it again. Will be fixed in the new release today. I also added a unit test for it so it won't happen again!
