### ISSUE TITLE
Feature request: Notes not accepting HTML code

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#837]
Friends,

I paste some text from the web to a note, GO doesn't accept it, informing Im not allowed to use scripts. I have to copy x paste to notepad, then to a note in GO.

It's basic HTML codes that used to be permitted (and are accepted in tasks, for example). Example code attached.
[code.txt](https://github.com/Intermesh/groupoffice/files/8624758/code.txt)
![error](https://user-images.githubusercontent.com/44004645/166745849-d5c1d795-61ac-47d7-bf33-3c0cd0f052ad.png)

If it's really needed, would be nice to filter it out automatically instead of rejecting. Old notes I have I now have to copy x paste to notepad, to remove any code, then back to GO.

Thanks.

**Comment by derjoachim** [comment]
Hi Flavio,

Your attached code snippet has expired.

I am assuming that you are using the new tasks module (versions 6.6 and up). You *can* paste HTML code into the text fields (like description), but it will be handled as unformatted text and HTML tags (including scripts) will not be saved into the task. 

You can emulate the same behavior by not simply pasting in the note editor, but using the past as 'Paste as text' action from the browser. The check for scripts is part of our XSS prevention and I would feel a lot less comfortable if it were not there.

**Comment by flaviozluca** [comment]
Dear Joachim,

On 6.6, this became a non-issue. It's letting me save notes with HTML and I'm not having to resave.

Can close.

Thanks a lot.
