### ISSUE TITLE
Deleted links re-appear when email with deleted link gets forwarded or replied to.

### ISSUE THREAD

**Issue by honki-bobo** [Intermesh/groupoffice#838]
Hello everyone,

maybe I'm missing something, but this feels like a bug to me.

Steps to reproduce:
- turn off automatic linking in address book settings
- A sends email to B and links B to the email manually
  - link appears on email in A's and B's account and in B's address book entry
- A (or B) removes link from email via B's address book entry
  - link disappears from email in both A's and B's accounts and also from B's address book entry
- A (or B) forwards or replies to email
  - link re-appears in forwarded/reply email and also in B's address book entry

I would expect the deleted link to be permanently deleted and not to re-appear when the email gets forwarded or replied to.

Best regards,
Martin

**Comment by mschering** [comment]
The link is added inside the body so any replies from external parties get linked. So this is by design but has this as a side effect.
