### ISSUE TITLE
update hangs

### ISSUE THREAD

**Issue by imkermichel** [Intermesh/groupoffice#840]
update to latest sixsix version on debian.
cant access web interface, say's update in progress, already 3 hours.

**Comment by michalcharvat** [comment]
Did you try access <domain>/install/upgrade.php page?

**Comment by imkermichel** [comment]
Hi ,

Yes, after going trough the source code i try that and all works fine
now.

Best regards


Michel Daggelinckx


Op Dinsdag, 10-05-2022 om 13:22 schreef Michal Charvat:









Did you try access /install/upgrade.php page?



—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1]
https://github.com/Intermesh/groupoffice/issues/840#issuecomment-1122260290
[2]
