### ISSUE TITLE
Totals in an email pane cut off

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#843]
Friends,

Customer thought email pane was bugged, as not all emails were showing, but actually, the issue is, part of the number showing the total # of pages, doesn't appear.

Firefox:

See:

![image](https://user-images.githubusercontent.com/44004645/168143690-4539d453-652d-4e78-8353-c77e77e56daf.png)

![image](https://user-images.githubusercontent.com/44004645/168143727-8811dff8-60b8-414a-945b-d856ba0b3e79.png)

Happens in Chrome too.

Thanks.

**Comment by mschering** [comment]
I made it a bit wider to fit 4 digits. But don't ask when he reaches 10.000 pages :)
