### ISSUE TITLE
Interesting, pane total pages incorrect

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#844]
Friends,
Not sure how it happened, but it's not the first time. I was reading emails from the older to the newest and, when I went to page 5, there is no page 5 anymore. Maybe emails were deleted and change the total.

Maybe this is normal, not sure if it can be auto-updated...

See:
![image](https://user-images.githubusercontent.com/44004645/168144076-8220207e-f019-422b-809b-63c24c3f22b9.png)

**Comment by mschering** [comment]
This could happen if messages were removed while paging or when filtering on unread and some where marked read  for example.

**Comment by flaviozluca** [comment]
Thanks, Merijn. No worries, was more to inform, surely not worth persuing.

All the best.
