### ISSUE TITLE
Email formatting not entirely correct

### ISSUE THREAD

**Issue by koekie71** [Intermesh/groupoffice#848]
Sometimes the links are not shown in an email (but can be clicked), as for example in the attached picture. In the pink rectangles the text should be readable. The other screenshot is from my mobile client (not GO), where the links are displayed correctly.

I have this with much more HTML emails, not only this but the whole layout.

If you want some example emails I can email it as attachments.

FF 100.0.2 and GO 6.6.92

![Screenshot 2022-05-24 200532](https://user-images.githubusercontent.com/101827396/170102830-cb022984-8c9e-4689-b81e-578e8ee98b05.jpg)
![Screenshot_20220524_200226](https://user-images.githubusercontent.com/101827396/170102923-4f422102-2825-44d8-bc93-67019b8eeabd.jpg)

**Comment by derjoachim** [comment]
This is an older ticket. In the meantime, a bugfix was added which may or may not fix your error.  Have you tried reproducing the error against a more recent version?

**Comment by koekie71** [comment]
I've upgraded to version 6.6.105 today but I still have this problem. I also tried Chrome and Edge and Firefox mobile and it's still the same. When I try a web version of these kind of emails it's going fine.

**Comment by mschering** [comment]
These were related to the dark theme. They should all be fixed now.
