### ISSUE TITLE
Feature request: Save to drafts

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#851]
Friends,

What is the interval of time in which GO saves e-mails to drafts?

Can we make thsi configurable with some setting? Worth it?

Thanks.

**Comment by mschering** [comment]
It's 2 minutes. In my opinion not worth it.

**Comment by flaviozluca** [comment]
Cool. every 2 minutes. Seems fine to me.

What would be really neat is some info, as Ive had customers ask how it works. Like GMail has "saving to drafts"... or "saving to drafts (every 2 min)". If not, perhaps just document it at least or add to some help file inside GO (which is another idea I dont think we have, right?).

**Comment by mschering** [comment]
Good idea, I made a notification

**Comment by flaviozluca** [comment]
Very nice of you, Merijn. Thanks.
  

 
 luca.gif
 		 
 		traco_roxo.png
 Atenciosamente/Regards,

Flávio Zarur Lucarelli
Sócio-Diretor
LucaNet Sistemas [1]
55-21-3005-9310 / 55-11-2122-4256
Celular / WhatsApp: 21-99542-4180 (apenas chat) 
 

 


Em Segunda-feira, 28/11/2022 no 5:30 Merijn Schering escreveu:









Good idea, I made a notification



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1] http://www.lucanet.com.br
[2]
https://github.com/Intermesh/groupoffice/issues/851#issuecomment-1328711269
[3]
