### ISSUE TITLE
GroupOffice 6.4.245  does not show on FireFox 100.0.2 (64-bit) on Ubuntu 20.04.5 LTS 

### ISSUE THREAD

**Issue by RonGroen** [Intermesh/groupoffice#852]
Hello Intermesh or supporters,

GroupOffice 6.4.245  does not show on FireFox 100.0.2 (64-bit) on Ubuntu 20.04.4 LTS, screen remains all blue.
Using a link with or without a valid SSL certificate, no difference.
On Version Chromium 102.0.5005.61 (Official Build) snap (64-bit) Everything works fine.

I gave FireFox a full refresh, but no difference. Clearing cache, no difference.
The view-source looks normal for GroupOffice.

Any suggestions?

**Comment by michalcharvat** [comment]
Check the error log (PHP, GO log) there is probably error on server side so Javascript execution is terminated. That is why you see just the blue screen.

**Comment by RonGroen** [comment]
thank you Michal,
I used to find the logfiles: https://groupoffice.readthedocs.io/en/latest/logging.html?highlight=log

/var/log/apache2: no files updates/added after a refresh of the page.

/var/lib/groupoffice does not show updated logfiles.
/var/lib/groupoffice/log/z-push# idem

Where can I continue to look?
Regards

**Comment by RonGroen** [comment]
Is this a bug in GroupOffice?

**Comment by RonGroen** [comment]
php.ini gives error_reporting = E_ALL and display_errors = On but /var/log/apache2/access.log and /var/log/apache2/error.log don't report GroupOffice items and no screen errors. (testing with something else, display errors appear on the screen like Undefined index: op in <b>/var/www/html/artikel.php</b> on line).

**Comment by michalcharvat** [comment]
Well I would recommend you use error_reporting E_ALL & ~E_DEPRECATED & ~E_STRICT on production. Also display_errors should be disabled.

However you should still have to check the PHP error logs to find the source of this issue :) By default errors on Ubuntu should be logged to /var/log/apache2/error.log until you change configuration in php.ini. 

Also you still didnt specify if you are running GO in debug or normal mode. If debug mode is disabled change it in config.php and then check the GO logs inside storage directory / log

**Comment by RonGroen** [comment]
Now config.php:   'file_storage_path' => '/var/lib/groupoffice/', and   'debug' => 'true',

debug.log reports when I open home page on Firefox:
log][GO:13] [2022-06-08 14:19] INIT GET /groupoffice/
[log][GO\Base\Observable:103] Using \GO\Base\Cache\Apcu cache
[log][GO\Base\Router:125] No r parameter given
[log][GO\Core\Controller\AuthController:36] GO\Base\Observable::cacheListeners
[log][GO\Base\ModuleCollection:179] setIgnoreAclPermissions(true)
[log][GO\Tasks\TasksModule:26] addListener(delete,GO\Tasks\TasksModule, deleteUser) => GO\Base\Model\User
[log][GO\Email\EmailModule:38] addListener(reminderdisplay,GO\Email\EmailModule, reminderDisplay) => GO\Core\Controller\ReminderController
[log][GO\Email\EmailModule:43] addListener(delete,GO\Email\EmailModule, deleteUser) => GO\Base\Model\User
[log][GO\Calendar\CalendarModule:88] addListener(delete,GO\Calendar\CalendarModule, deleteUser) => GO\Base\Model\User
[log][GO\Calendar\CalendarModule:89] addListener(dismiss,GO\Calendar\Model\Event, reminderDismissed) => GO\Base\Model\Reminder
[log][GO\Files\FilesModule:36] addListener(save,GO\Files\FilesModule, saveUser) => GO\Base\Model\User
[log][GO\Files\FilesModule:37] addListener(delete,GO\Files\FilesModule, deleteUser) => GO\Base\Model\User
[log][GO\Files\FilesModule:41] addListener(store,GO\Files\FilesModule, afterBatchEditStore) => GO\Core\Controller\BatchEditController
[log][GO\Sieve\SieveModule:26] addListener(submit,GO\Sieve\SieveModule, saveOutOfOfficeMessage) => GO\Email\Controller\AccountController
[log][GO\Sieve\SieveModule:27] addListener(load,GO\Sieve\SieveModule, loadOutOfOfficeMessage) => GO\Email\Controller\AccountController
[log][GO\Base\ModuleCollection:194] setIgnoreAclPermissions(false)
[log][go\core\webclient\Extjs3:42] 
        SELECT m.id, m.name, m.package, m.version, m.sort_order, m.admin_menu, m.aclId, m.enabled, m.id AS `m.id` 
        FROM `core_module` `m`
        WHERE 
         `m`.`enabled` = true (1.29ms)
[log][go\core\util\ClassFinder:84] ClassFinder find() used.

**Comment by RonGroen** [comment]
Also getting:
[error][go\core\ErrorHandler:64] ErrorException in Unknown at line 0: <br>The encoded file <b>/usr/share/groupoffice/modules/savemailas/model/LinkedEmail.php</b> requires a license file.<br>The license file <b>/usr/share/groupoffice/groupoffice-pro-6.4-license.txt</b> is not valid for this server.

I don't understand, verything is just working fine on Chrome

**Comment by RonGroen** [comment]
Results with Chrome and Firefox the same:
only remarks:
Ioncube version check: OK ( Installed: version 10.4 - No additional configuration required. )
Modules directory writable: Warning: Modules subdirectory is not writable. You will not be able to use GroupOffice Studio.
Passed! GroupOffice should run on this machine

**Comment by RonGroen** [comment]
I just want to run GO on Firefox..

**Comment by mschering** [comment]
Please contact support if you have a license error.

**Comment by RonGroen** [comment]
I did some further investigation. Firefox 102 runs fine on my laptop, phone,  but not on my pc (anymore) (all on ubuntu 20.04)
clear startup cache, refresh firefox. reinstall, install as snap no difference GO does not start.
Any suggestions?

**Comment by RonGroen** [comment]
TypeError: GO.lang is undefined script.php:268:4
TypeError: go.browserStorage is undefined script.php:362:455
they keep comming back and don't appear on my laptop...
