### ISSUE TITLE
gmail oath refresh url not found

### ISSUE THREAD

**Issue by imkermichel** [Intermesh/groupoffice#856]
installed from repo.
groupoffice url: 
http://192.168.1.58/groupoffice
oath2 url:
http://192.168.1.58/go/modules/community/oauth2client/gauth.php/authenticate/11

file exists on server @ groupoffice/go/modules/community/oauth2client/gauth.php/authenticate/11

**Comment by mschering** [comment]
Is the URL in your System Settings -> General set correctly?

**Comment by derjoachim** [comment]
Also, how did you configure the redirect URI in your [Google Credentials page](https://console.cloud.google.com/apis/credentials)?

**Comment by imkermichel** [comment]
Hi ,


When I manually change the url on the refresh page it works.

file: AccountDialog.php
line: 88

window.open('/go/modules/community/oauth2client/gauth.php/authenticate/'
+ this.account_id, 'do_da_auth_thingy'); 


I think it should be
window.open('/groupoffice/go/modules/community/oauth2client/gauth.php/authenticate/'
+ this.account_id, 'do_da_auth_thingy'); 


Best regards


Michel Daggelinckx


Op Maandag, 13-06-2022 om 16:49 schreef Joachim van de Haterd:









Also, how did you configure the redirect URI in your Google
Credentials page [1]?



—
Reply to this email directly, view it on GitHub [2], or unsubscribe
[3].
You are receiving this because you authored the thread.Message ID: 





Links:
------
[1] https://console.cloud.google.com/apis/credentials
[2]
https://github.com/Intermesh/groupoffice/issues/856#issuecomment-1154020022
[3]

**Comment by derjoachim** [comment]
I have fixed this to make it work for both of us. However, Google will not accept your redirect URI:

![image](https://user-images.githubusercontent.com/1264970/177128969-ea5657a2-7f00-4c5e-afd2-b7db05b68f85.png)


That's not something I can fix. :-(
