### ISSUE TITLE
Kanban new board

### ISSUE THREAD

**Issue by olegchensky** [Intermesh/groupoffice#857]
It is not possible to add a new kanban board.
Error: Undefined offset: 0

**Comment by lonesomewalker** [comment]
For latest GO 6.6 you get a:
`Argument 1 passed to go\core\data\Model::setValues() must be of the type array, null given, called in /go/core/orm/Property.php on line 2153****`

**Comment by derjoachim** [comment]
@olegchensky @lonesomewalker I think that this particular issue has been resolved in 6.6.98.

**Comment by olegchensky** [comment]
Yes, thanks!
