### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by cpozdena** [Intermesh/groupoffice#858]
Good morning, i'm new to GitHub and i'm sorry if this issue was adressed already in the past. 
I'm working on a GroupOffice install, version 6.5.106 and i'm getting this issue when trying to create a recurring calendar entry for a user.
From what I found, it might be related to the PHP version on the hosting server (running PHP v8.0.20) not supporting curly braces as part of the code. 
Could anyone point me to the right file in GroupOffice that I would need to modify to get this error fixed? 
Thank you

**Comment by derjoachim** [comment]
I am assuming that you use the community edition. AFAIK, the 6.6 version unofficially supports PHP 8.0 (not sure about 6.5), but we are not familiar with your problem. Officially, we are bound to a library that refuses to support 8.0+, so I cannot guarantee that GO will run in PHP 8 as yet.

>  i'm getting this issue when trying to create a recurring calendar entry for a user.

Please elaborate. What is the exact error message? What is the input and what is the expected output?
