### ISSUE TITLE
LDAP login but can't create email account and IMAP password wrong

### ISSUE THREAD

**Issue by lily148** [Intermesh/groupoffice#863]
Hi, I enabled the LDAP authentication. Successfully setup the LDAP and manage to login.
However, the system is not able to create the email account automatically. I had already check the "Create e-mail account for users" and fill in the correct information.

If I manually create an email in the email domain, but put different password then it will say "Sorry, an error occurred: Authentication failed for user example@examplemail.com on IMAP server localhost"

Anyone successfully setup the LDAP before?

I do enable IMAP external access because we are using IMAP for email pulling so password sync with LDAP is important.
Thanks in advanced.

**Comment by mschering** [comment]
This will only work if the username and password of the imap server are identical. If that is the case then try to enable debug an watch the debug log while logging in.

**Comment by lily148** [comment]
@mschering , thanks for the quick response.
Yes, if the IMAP username and password are identical then it is able to login.
We faced the problem is that, some users setup email as external IMAP access. 
If they change the password in the LDAP then new password does not sync to IMAP password db. They will have problem accessing it during the next login.

Unlike the Serverclient module, it will automatically sync the password when user change password in groupoffice.

Would like to know is there a way to sync/update LDAP password to IMAP password db?

**Comment by mschering** [comment]
When you login with LDAP it finds accounts with matching IMAP hostname and LDAP user name configured in the LDAP profile. It will update those accounts. It can't know which other accounts it must change.

**Comment by lily148** [comment]
Thanks for the feedback. In this case, if user change their LDAP password, then group office will no longer works right?
Because it will throw the following error:
"Sorry, an error occurred: Authentication failed for user [example@examplemail.com](mailto:example@examplemail.com) on IMAP server localhost"
I just double confirmed just now.
Would like to know if there is any workaround or any implementation that I can help to do...?
Thanks..

**Comment by lily148** [comment]
As of now, beside the login id. I couldn't figure out what else is the other relation..

**Comment by mschering** [comment]
Are you saying the login ID is identical to the e-mail account username? In that case when the  IMAP hostname also matches the LDAP profile's IMAP hostname it should automatically update the password.
