### ISSUE TITLE
LDAP synchronization doesn't work

### ISSUE THREAD

**Issue by MarekGrossman** [Intermesh/groupoffice#864]
Hello, 
    our sync with LDAP doesn't work as I have set "ldapMapping" as showed down, but the item "jobTitle" (maybe others too) isn't set to new value over i run sync manualy with this command:

`/usr/bin/php cli.php community/ldapauthenticator/Sync/users --id=<address_book>`

Can You check the LDAP sync function?
Thanks, Mareg

P.S. What about the ticket number 202223609 ? :-)

```
$config['ldapMapping'] = [
                             'enabled' => function($record) {
                                     //return $record->ou[0] != 'Delivering Crew';
                                     return true;
                             },


                             'diskQuota' => function($record) {
                                 // return in bytes
                                     //return 1024 * 1024 * 1024;
                                     return null;
                             },
                             'email' => 'mail',
                             'recoveryEmail' => 'mail',
                             'displayName' => 'description',
                             'firstName' => 'givenname',
                             'lastName' => 'sn',
                             'initials' => 'initials',

                             'jobTitle' => 'employeeType',
                             'department' => 'businesscategory',
                             'notes' => 'info',

//                           'addressType' => function($record) {
//                                   return \go\modules\community\addressbook\model\Address::TYPE_WORK;
//                           },
//                           'street' => 'street',
//                           'zipCode' => 'postalCode',
//                           'city' => 'l',
//                           'state' => 's',
//                           'countryCode' => function($record) {
//                                   return "NL";
//                           },
//
//                           'homePhone' => 'homePhone',
//                           'mobile' => 'mobile',
//                           'workFax' => 'facsimiletelephonenumber',
//                           'workPhone' => 'telephonenumber',
//
//                           'organization' => 'organizationname',
//
//                           'homeDir' => function($record) {
//                                   //relative path from group-office file_storage_path
//                                   return "ldap_homes/" . $record->uid[0];
//                           }
                             ];


```

**Comment by mschering** [comment]
I think I found the problem now. If only a field of the contact profile is modified. It won't save. The next release will fix this,

**Comment by MarekGrossman** [comment]
Should I install it from tarball?
apt-get doesn't offer new release.

**Comment by mschering** [comment]
It's in the apt repo for sure:

root@houtwerf:~# apt show groupoffice
Package: groupoffice
Version: 6.6.103-sixsix
Priority: extra
Section: web
Maintainer: Merijn Schering <mschering@intermesh.nl>
Installed-Size: 127 MB
Depends: php-common, php-json, php-mysql, php-gd, php-cli, php-curl, php-xsl, php-xml, php-mbstring, php-intl, unzip, tar, zip, tnef, debconf (>= 0.5) | debconf-2.0, perl:any, dbconfig-common, dbconfig-mysql, ucf (>= 0.28)
Recommends: apache2, libapache2-mod-php, default-mysql-server
Suggests: php-apcu
Conflicts: groupoffice-billing, groupoffice-com, groupoffice-documents, groupoffice-pro
Homepage: http://www.group-office.com
Download-Size: 44.5 MB
APT-Sources: http://repo.group-office.com sixsix/main amd64 Packages
Description: Group-Office groupware and CRM
 Group-Office is a web based groupware and CRM application
 Take your office online. Share projects, calendars, files and e-mail online
 with co-workers and clients. Easy to use and fully customizable, Group-Office
 takes online collaboration to the next level.

N: There is 1 additional record. Please use the '-a' switch to see it

**Comment by MarekGrossman** [comment]
I tried run just "apt-get update; apt-get upgrade", but there wasn't mention about new version.
`apt(-get) upgrade groupoffice ` offer instalation of new verison.

Thanks

**Comment by mschering** [comment]
Are you on the v6.6 branch?

**Comment by MarekGrossman** [comment]
Yes, I am.
To be clear - now I can install the new version 6.6.103 by the `apt upgrade groupoffice `command.
It's OK

**Comment by mschering** [comment]
OK and the field updates now too?

**Comment by MarekGrossman** [comment]
I deployed the new version in the late evening. Now is the update OK.
Thank You.

**Comment by MarekGrossman** [comment]
Problem solved.
