### ISSUE TITLE
Create new email account not available

### ISSUE THREAD

**Issue by semaf** [Intermesh/groupoffice#865]
Hey,

I think I miss a setting to be able to create email accounts. All permission to manage email accounts to groups has been set but still nothing I can add an email. I can not find Email > Administration

![image](https://user-images.githubusercontent.com/8831145/177137353-28ade1da-bfb7-4f46-a6f6-d19b479f1098.png)

**Comment by derjoachim** [comment]
![image](https://user-images.githubusercontent.com/1264970/177175288-9521387c-4f1d-414f-a202-c27e5bd07385.png)

You should see the link to the accounts dialog if you click the three dot menu just right of the search icon.

**Comment by semaf** [comment]
> ![image](https://user-images.githubusercontent.com/1264970/177175288-9521387c-4f1d-414f-a202-c27e5bd07385.png)
> 
> 
> 
> You should see the link to the accounts dialog if you click the three dot menu just right of the search icon.

Thank you very much! Got it.
