### ISSUE TITLE
hotmail support

### ISSUE THREAD

**Issue by imkermichel** [Intermesh/groupoffice#873]
I installed groupoffice on a VM after multiple problems with production server (probably hardware related).
I can no longer access outlook/hotmail e-mail's.

Expected response code 250 but got code "530", with message "530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]
"
Log data:
++ Starting GO\Email\Transport
<< 220 CWLP123CA0237.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 4 Aug 2022 21:44:35 +0000

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

>> STARTTLS

<< 220 2.0.0 SMTP server ready

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

++ GO\Email\Transport started
>> MAIL FROM:<daggelinckx@hotmail.com>

>> RCPT TO:<vdbw1961@gmail.com>

>> DATA

<< 530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]

!! Expected response code 250 but got code "530", with message "530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]
" (code: 530)
Log data:
++ Starting GO\Email\Transport
<< 220 CWLP123CA0237.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 4 Aug 2022 21:44:35 +0000

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

>> STARTTLS

<< 220 2.0.0 SMTP server ready

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

++ GO\Email\Transport started
>> MAIL FROM:<daggelinckx@hotmail.com>

>> RCPT TO:<vdbw1961@gmail.com>

>> DATA

<< 530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]

!! Expected response code 250 but got code "530", with message "530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]
" (code: 530)
!! Expected response code 250 but got code "530", with message "530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]
"
Log data:
++ Starting GO\Email\Transport
<< 220 CWLP123CA0237.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 4 Aug 2022 21:44:35 +0000

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

>> STARTTLS

<< 220 2.0.0 SMTP server ready

>> EHLO [192.168.1.45]

<< 250-CWLP123CA0237.outlook.office365.com Hello [2a02:a03f:8184:6e00:2024:c3ff:fe4d:658]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

++ GO\Email\Transport started
>> MAIL FROM:<daggelinckx@hotmail.com>

>> RCPT TO:<vdbw1961@gmail.com>

>> DATA

<< 530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]

!! Expected response code 250 but got code "530", with message "530 5.7.57 Client not authenticated to send mail. [CWLP123CA0237.GBRP123.PROD.OUTLOOK.COM]
" (code: 530) (code: 530)

**Comment by derjoachim** [comment]
> 250-AUTH LOGIN XOAUTH2

I think that this is the problem. We do not support OAuth2 for Microsoft environments yet. However, we are working on it, since basic auth will be killed off on the first of October.

Source: https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-may-2022/ba-p/3301866

**Comment by imkermichel** [comment]
The problem was in account setup:
when i use 'use same credentials from imap server' i get the error.
If i manually input the same credentials it works.

**Comment by derjoachim** [comment]
Ok, closing this ticket as it appears to work fine now.
