### ISSUE TITLE
A small bug in Files module

### ISSUE THREAD

**Issue by pekkasqcoy** [Intermesh/groupoffice#876]
When trying to drag and drop a file when folder path is empty (it goes empty when I click the Shared folder), it gives an error "Call to a member function checkPermissionLevel() on bool".

**Environment:**
Group-office 6.6.97
Apache
PHP Version 7.4.30
10.5.15-MariaDB-0+deb11u1 - Debian 11

**Comment by mschering** [comment]
Thanks, this was fixed.
