### ISSUE TITLE
A possible bug when trying to run the upgrade with open_basedir set

### ISSUE THREAD

**Issue by pekkasqcoy** [Intermesh/groupoffice#877]
I am not sure is this a bug or server misconfiguration, but when I try to run the upgrade command _https://mysite.mydomain.fi/install/upgrade.php_, I see an error Error: ErrorException in /web-data/mysite.mydomain.fi/www/install/gotest.php at line 799: realpath(): open_basedir restriction in effect. File(/usr/lib/php/20190902) is not within the allowed path(s): (/web-data/mysite.mydomain.fi/www:/web-data/mysite.mydomain.fi/tmp)
© Intermesh - https://www.group-office.com/

**Environment:**
Group-office 6.6.97
Apache
PHP Version 7.4.30
10.5.15-MariaDB-0+deb11u1 - Debian 11

**Comment by mschering** [comment]
Please create a support ticket.
