### ISSUE TITLE
6.6.111 - Checking Smime certificate

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#880]
When I check my own SMime certificate I get an error OCSP: Failed to convert issuer certificate.

When I check the same mail with thunderbird or apple mail i got no complain.

![image](https://user-images.githubusercontent.com/2633051/185141693-c5985f16-f819-494b-bf10-66cd6d88c087.png)

**Comment by mschering** [comment]
Please create a support ticket and include the source of a test message.
