### ISSUE TITLE
GO Mail-App external content

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#883]
Is there an option in mail app to block reloading external content in mails?
I haven't found one.
It wold be a useful feature to stop spam and phishing.
Or does GO block it out of the box as standard?

Greetings robw

**Comment by lonesomewalker** [comment]
It should be default?

**Comment by robshnup** [comment]
That would be my intention!
Frequently there is the message, that GO has blocked external pictures.
But I don't know that it's default behavior also for other external content.
Is it?

**Comment by lonesomewalker** [comment]
Yes, that is the "good" way.
If you want to see "external content" you have to click.

**Comment by mschering** [comment]
What kind of external content do you mean? Are the others than images?

**Comment by robshnup** [comment]
I thought about docx's, pdf's, exe's, vfbs' etc.

**Comment by mschering** [comment]
GO blocks external images which is the only content as far as I know can be autoloaded.

Do you mean hyperlinks to external docs? I once thought of a warning when clicking the hyperlink "Are you sure you want to visit https://evil.hacker.foo/virus.exe ?"

**Comment by robshnup** [comment]
Yes, these were my concerns...
