### ISSUE TITLE
Addressbook - node is badly encoded

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#885]
When you create tree node with "&" in the name the text is badly encoded.

<img width="165" alt="image" src="https://user-images.githubusercontent.com/8058273/188824841-253b0d5b-3281-4af0-91da-1cf3b3c91b07.png">

Affected version: 6.5.x, 6.6.x

**Comment by derjoachim** [comment]
To be deployed in 6.6.117
