### ISSUE TITLE
Emails that dont appear correctly in GO

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#886]
Friends,

I sent many in another ticket, got a reply once but no more.

Pls, can you check them and this new one too? Emails that appear fine in TB, other clients and not in GO, from major companies such as Mercadolivre (our ebay) among others.
[O seu envio está atrasado - 06-09-2022 2332.zip](https://github.com/Intermesh/groupoffice/files/9527320/O.seu.envio.esta.atrasado.-.06-09-2022.2332.zip)

Thanks.

**Comment by flaviozluca** [comment]
Friends, 1 more, a bit critical, the text doesnt appear... 

see image and EML.

In TB it's fine.
![imageissue](https://user-images.githubusercontent.com/44004645/189669433-7cfeae90-a6a7-4a75-a672-c92553b30e3c.png)
[Já adicionou sua conta bancária ou de pagamento - 09-09-2022 1538.zip](https://github.com/Intermesh/groupoffice/files/9548518/Ja.adicionou.sua.conta.bancaria.ou.de.pagamento.-.09-09-2022.1538.zip)

**Comment by mschering** [comment]
I can't replicate this. Here's a screenshot of Group-Office 6.6 and macos mail side by side:

<img width="1824" alt="image" src="https://user-images.githubusercontent.com/1314447/195779159-5135cbc5-c6ad-4390-8d8e-fd22c8a2ae1c.png">

**Comment by mschering** [comment]
And the ohter one appears fine too:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/1314447/195779375-933800a1-6dca-4059-adb9-b1ff2d40b4c9.png">
