### ISSUE TITLE
Clear formatting doesn't work inside certain notes

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#888]
Friends,

Attached same code of a note where the option to remove formatting
[sample.txt](https://github.com/Intermesh/groupoffice/files/9635322/sample.txt)
 doesn't work.

Thanks.

![image](https://user-images.githubusercontent.com/44004645/192005306-973566ab-1915-4c89-b7f3-142571ecb17b.png)

**Comment by derjoachim** [comment]
As far as I can see, the HTML editor serves as a wrapper for browser internal commands to manipulate rich text. In this case a `removeFormat` is fired. It is up to the browser itself what exactly is being removed. The MDN is not very specific on what is being removed and what stays though.

**Comment by flaviozluca** [comment]
Thanks. SO it's not a bug, right? Can you reproduce it? I used Firefox.

**Comment by derjoachim** [comment]
Well it is not a Group Office bug. I could reproduce the bug, but have to say that other, more visible CSS code was neatly sanitized out.
