### ISSUE TITLE
findById nullable id 

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#889]
Couldn't be passed value to $id variable nullable + int? Currently you have to check if value is non-empty and then you have to check if returned value is not null too. Looks like this hint is there since 6.6 so code is incompatible with 6.5.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/8058273/192215054-d8c8fd37-5037-474a-8b62-7c961c5b2813.png">

**Comment by michalcharvat** [comment]
Well from my point of view it is just shorter do same thing on one plase instead of duplicating code everywhere just because findById does not support null value. Also output should be probably similar - invalid ID or records not found -> null, in other case valid entity instance. You (or I) can extend GO model handling by findOrFail, findOrNew etc. You can inspire Eloquent/Builder.php (https://github.com/laravel/framework/blob/07aae35474ab412911566c7ec060ea4853efc13c/src/Illuminate/Database/Eloquent/Builder.php)

**Comment by mschering** [comment]
In what use cases do you pass null?

**Comment by michalcharvat** [comment]
Uf not sure right now - it could be input from import or so. It could be also part of code where you are trying load entity by another entity attribute value which could be nullable. Basically I was looking for clean code.  Code could be much cleaner if you dont have to check null before you call findById because you have to check the input either. Sure hints are nice things but if you allow call findById('') and return null why you can't simply allow nullable value and return null when it will be null or empty string?

**Comment by mschering** [comment]
I guess it can't hurt. I'll change this.
