### ISSUE TITLE
Recommended configurations in php.ini

### ISSUE THREAD

**Issue by Yramgar** [Intermesh/groupoffice#892]
I have set up Groupoffice on a VPS with 8gb of ram and 4cpu (20 users). I see 2 problems:

1) Cache not working
I have seen other webmails that connect with IMAP. And they download the message and keep it temporarily to avoid another query. However in Groupoffice I don't see it working. I see the same message again and I see that the query (request) is made again and it is downloaded again.

2) Slow is certain moments
This I must assume to a misconfiguration from my side. I would like to ask what are the main parameters (php.ini) that will ensure a good performance in the query of messages in IMAP (external). Over there I saw something about imap proxy but not very detailed.
When I check messages, it is very slow at times. They have taken up to 55 seconds.

Any suggestion? Thanks

**Comment by michalcharvat** [comment]
For this purpose you can use imapproxy 

https://installati.one/ubuntu/22.04/imapproxy/ 
https://groupoffice.readthedocs.io/en/latest/install/extras/imapproxy.html

Another option could be https://wiki2.dovecot.org/HowTo/ImapcProxy
