### ISSUE TITLE
SQL error when attempting to login to new instance from "Multi instance" panel

### ISSUE THREAD

**Issue by kevo-gt** [Intermesh/groupoffice#894]
I get the following error when I select "Log in as administrator" on any new instance after creating  under "Multi instance"

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'instance1.core_auth_token' doesn't exist

The instance is successfully created and I can enable which modules to use but cannot access the admin panel of the new instance

**Comment by mschering** [comment]
I'm guessing it's not installed yet. When you add it you need to open it and go through the install.

**Comment by kevo-gt** [comment]
Thanks Merjin, I was under the impression it is generated from the multi instance panel. I have gone to the appropriate URL and managed to install another instance.
