### ISSUE TITLE
Charset detection error

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#897]
In some cases messages are malformed but GO relies on the information provided by the message for certain tasks.

For example, in go/base/mail/Utils.php function mimeHeaderDecode () detects the charset from the message only.

If the e-mail message contains an invalid charset, such as 'UTF8', then GO propagates that error further down:
trace error: /usr/share/groupoffice/go/core/util/StringUtil.php:156 iconv(): Wrong charset, conversion from `UTF8' to `UTF-8//TRANSLIT' is not allowed (8) - backtrace: 15 steps

There should either be a list of known accepted charsets or maybe a way to force conversion to UTF-8 as last resort

**Comment by mschering** [comment]
But this error is caught there already? If the charset is unknown then there's no way to convert to utf8.

**Comment by polarismail** [comment]
Theoretically you're right, however if you let the error propagate then other things break down the line. In this case z-push syncing was breaking because of this exception.

Ideally I believe we would want to only accept known character sets, and if the message contains one we don't know about, we force default to UTF-8.

Right now we fixed this simple case by adding this line:

if ($charset=='UTF8') { $charset='UTF-8'; }

The entire list of character sets is here, it's quite extensive:
https://www.iana.org/assignments/character-sets/character-sets.xhtml

So we could maybe put all those charsets in an array, go through them and if no match, default to UTF-8 ?
Or maybe one of your libraries can already detect invalid charsets ?

**Comment by mschering** [comment]
I don't understand this. If the charset is valid and in that list then iconv() will succeed. If it's not in the list then it will fail and the error is caught. There's no way to determine the correct charset when this happens as far as I know. We can then only sanitise the string and make sure there are no invalid characters in it.

How did z-push break?

**Comment by polarismail** [comment]
you are correct, there is no way to determine the correct charset. But throwing an exception also breaks sync in z-push

08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace error: /usr/share/groupoffice/go/core/util/StringUtil.php:156 iconv(): Wrong charset, conversion from `3DISO-88=^M59-1' to `UTF-8//TRANSLIT' is not allowed (8) - backtrace: 13 steps
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 1:/usr/share/groupoffice/go/core/util/StringUtil.php:156 - iconv()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 2:/usr/share/groupoffice/go/core/util/StringUtil.php:112 - go\core\util\StringUtil::convertToUTF8()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 3:/usr/share/groupoffice/go/base/util/StringHelper.php:284 - go\core\util\StringUtil::cleanUtf8()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 4:/usr/share/groupoffice/go/base/mail/Imap.php:2303 - GO\Base\Util\StringHelper::clean_utf8()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 5:/usr/share/groupoffice/modules/email/model/ImapMessage.php:456 - GO\Base\Mail\Imap->get_message_part_decoded()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 6:/usr/share/groupoffice/modules/email/model/ImapMessage.php:406 - GO\Email\Model\ImapMessage->getPlainBody()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 7:/usr/share/groupoffice/modules/z-push/backend/go/goMail.php:134 - GO\Email\Model\ImapMessage->getHtmlBody()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 8:/usr/share/groupoffice/modules/z-push/vendor/z-push/lib/default/diffbackend/exportchangesdiff.php:160 - goMail->GetMessage()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 9:/usr/share/groupoffice/modules/z-push/vendor/z-push/lib/request/sync.php:1199 - ExportChangesDiff->Synchronize()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 10:/usr/share/groupoffice/modules/z-push/vendor/z-push/lib/request/sync.php:956 - Sync->syncFolder()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 11:/usr/share/groupoffice/modules/z-push/vendor/z-push/lib/request/requestprocessor.php:116 - Sync->Handle()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 12:/usr/share/groupoffice/modules/z-push/vendor/z-push/index.php:107 - RequestProcessor::HandleRequest()
08/08/2022 05:54:25 [64749] [ERROR] [user@test.com] trace: 13:/usr/share/groupoffice/modules/z-push/index.php:10 - require()

**Comment by mschering** [comment]
Thanks for the stack trace. That's very helpful.

But it's very strange that this is possible. The error thrown in /usr/share/groupoffice/go/core/util/StringUtil.php:156 

Should be caught and ignored by the catch(Thowable $e) at line 158. Did you modifiy this perhaps?

**Comment by mschering** [comment]
This is what it normally looks like:

![image](https://user-images.githubusercontent.com/1314447/204018960-5b4cbf2e-586d-4c56-9e86-47a6c47afb99.png)

**Comment by polarismail** [comment]
Nope, I have the same thing, the only modification we made, afterwards was to change strtoupper to mb_strtoupper due to the other bug in the second related issue

`        private static function convertToUTF8($str, $fromCharset) {
                $fromCharset = mb_strtoupper($fromCharset);
                $toCharset = 'UTF-8';

                if ($fromCharset == $toCharset) {
                        // cleanup invalid chars
                        return mb_convert_encoding($str, 'UTF-8', 'UTF-8');
                }
                try {
                        if(in_array($fromCharset, array_map("mb_strtoupper", mb_list_encodings()))) {

                                $str = mb_convert_encoding($str, 'UTF-8', $fromCharset);
                        } else
                        {
                                $str = iconv($fromCharset, 'UTF-8//TRANSLIT', $str);
                        }
                }catch (Throwable $e) {
                        App::get()->debug("Could not convert from ".$fromCharset." to UTF8 ".$e->getMessage());
                }

                return $str;
        }
`

**Comment by mschering** [comment]
Hmm, I have to go watch soccer now but I have to figure out how this is possible. Thowable is supposed to catch everything:

https://www.php.net/manual/en/class.throwable.php
