### ISSUE TITLE
Charset manipulation error

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#898]
error: trace error: /usr/share/groupoffice/go/core/util/StringUtil.php:156 iconv(): Detected an illegal character in input string (8) - backtrace: 13 steps

This is related to the other issue I mentioned. There is improper handling of multibyte strings in some places - we couldn't verify them all.

For example: go/core/util/StringUtil.php , function convertToUTF8

it's not correct to use strtoupper as it's not safe in this context
you must use mb_strtoupper()

Same is true for strtolower, substr

https://stackoverflow.com/questions/275411/php-output-showing-little-black-diamonds-with-a-question-mark/15138120#15138120
https://stackoverflow.com/questions/8727735/iconv-detected-an-illegal-character-in-input-string

**Comment by mschering** [comment]
But we use strtoupper on the charset which should be ascii text?
