### ISSUE TITLE
file module

### ISSUE THREAD

**Issue by nuwohg** [Intermesh/groupoffice#9]
Trying to call file module: ErrorException in /var/www/html/go63/go/base/db/ActiveRecord.php at line 3122: Undefined index: type

Trying to create a folder in file module:
Exception in /var/www/html/go63/go/base/db/ActiveRecord.php at line 938: Could not find ACL for GO\Files\Model\Folder with pk:

Trying to upload a file: nothing happens. After reload: ErrorException in /var/www/html/go63/go/base/db/ActiveRecord.php at line 3122: Undefined index: type

**Comment by mschering** [comment]
Hi Peter,

All your issues seem to be related to the same error:

Trying to upload a file: nothing happens. After reload: ErrorException in /var/www/html/go63/go/base/db/ActiveRecord.php at line 3122: Undefined index: type

Please hold off for a moment and I'll release an update to fix that error today.

**Comment by mschering** [comment]
Closed because it's a duplicate.
