### ISSUE TITLE
Semaphore buildup due to faulty unlock

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#901]
in go/core/util/Lock.php function unlock

line 205, you are releasing the semaphore but not removing it
this causes a buildup of hanging semaphores in the system
you need to add an extra call to sem_remove ()

                if(isset($this->sem)) {
                        sem_release($this->sem);
                        **sem_remove($this->sem);**
                        $this->sem = null;
                } else  if(is_resource($this->lockFp)) {
                        flock($this->lockFp, LOCK_UN);
                        fclose($this->lockFp);
                        $this->lockFp = null;
                }

**Comment by mschering** [comment]
Are you sure it's building up? It should reuse the same semaphore each time.

**Comment by polarismail** [comment]
Yes, at least on FreeBSD the semaphores hang around causing an eventual exhaustion of semaphore space.

**Comment by mschering** [comment]
Every instance uses 2 or 3 sems. Do you have many instances?

**Comment by polarismail** [comment]
yes we do, and the issue happens mostly at upgrade time

**Comment by mschering** [comment]
I guess it can't hurt to remove it. I made the change
