### ISSUE TITLE
Connecting CalDAV by cURL fails on delete event

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#903]
I update sometimes calendar events by cURL (PHP-FPM)
The headers are correctly sended by rewrite:
> RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

The quirk is: setting a NEW appointment by  cURL works fine, but **deleting  this event not**!
There I get the notification: "403 Forbidden"
> Authorization: Basic cm9iYmllOlZpZy1LaWIhMzk4
User-Agent: cURL CalDAV client
Accept: */*
Content-type: text/xml
Depth: 1
If-Match: "20221031 09:52:57-921"
<br>last response:<br><br>HTTP/1.1 403 Forbidden
Date: Mon, 31 Oct 2022 08:25:20 GMT
Server: Apache
X-Sabre-Version: 4.3.1

My php-curl looks like that:
>$this->ch = curl_init();
curl_setopt_array($this->ch, array(
    CURLOPT_RETURNTRANSFER => TRUE,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_USERAGENT => 'cURL CalDAV client',
    CURLINFO_HEADER_OUT => TRUE,
    CURLOPT_HEADER => TRUE,
    CURLOPT_SSL_VERIFYPEER => FALSE
    ));

Can't get behind this clue?!
Many thanks for every hint... Greetings robw

**Comment by polarismail** [comment]
Check under Synchronization settings, Delete is now disabled by default due to a Samsung bug

**Comment by robshnup** [comment]
Oh man! Thanks so much!
You have to come up with that first!
Greetings
