### ISSUE TITLE
HTML issues in 6.6.123 

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#904]
Merijn, friend
[Doces ou travessuras - 28-10-2022 1831.zip](https://github.com/Intermesh/groupoffice/files/9901362/Doces.ou.travessuras.-.28-10-2022.1831.zip)
![tb](https://user-images.githubusercontent.com/44004645/199018035-178444e7-446b-46a2-8174-13b1199b1a65.png)

Check this one out.  Cant read the text in GO.
![GO](https://user-images.githubusercontent.com/44004645/199018043-0bac22a7-7862-4445-aa46-4971cad25e30.png)

[Doces ou travessuras - 28-10-2022 1831.zip](https://github.com/Intermesh/groupoffice/files/9901382/Doces.ou.travessuras.-.28-10-2022.1831.zip)

**Comment by flaviozluca** [comment]
1 more, from my bank. Similar issue with text outlined.
![Itaú](https://user-images.githubusercontent.com/44004645/199020753-63b2f431-35de-4007-9d20-3a0aaeabeed1.png)

pls contact me and Ill send you it. Prefer not adding it here, as it has part of my credit card's digits.

Thanks.

**Comment by flaviozluca** [comment]
1 more. notice how, in GO, extra code appears up top.

In Gmail and TB, something broken appears, some tracking or so, so there is something in the message in this case, but if possible, might be nice for the huge URL not to appear, which only seems to occur in GO.
![yoga gmail](https://user-images.githubusercontent.com/44004645/199022365-dc164e97-a1a8-4f75-a56a-2fd65dbf7dea.png)
![tb yoga](https://user-images.githubusercontent.com/44004645/199022375-f0ba8904-c60d-438b-977f-c556350c6f97.png)
[yoga cats.zip](https://github.com/Intermesh/groupoffice/files/9901610/yoga.cats.zip)
![go yoga cats](https://user-images.githubusercontent.com/44004645/199022384-c48e87ea-bf51-45a3-b786-20a91227c268.png)

**Comment by flaviozluca** [comment]
really, many emails with this issue, a bit critical... as one can't read text without highlighting it.

see, 1 more.

![image](https://user-images.githubusercontent.com/44004645/202203570-136930ce-c361-4116-9180-18d8ac66ce9d.png)
[Pesquisa de Satisfação Laboratório Bronstein - 15-11-2022 807.zip](https://github.com/Intermesh/groupoffice/files/10022503/Pesquisa.de.Satisfacao.Laboratorio.Bronstein.-.15-11-2022.807.zip)

**Comment by flaviozluca** [comment]
1  more... all the time, really.

![image](https://user-images.githubusercontent.com/44004645/202206365-e3500739-47d6-4ad9-82c5-14489c7e9c6b.png)
[Bárbara acabou de enviar uma mensagem a você - 16-11-2022 1049.zip](https://github.com/Intermesh/groupoffice/files/10022616/Barbara.acabou.de.enviar.uma.mensagem.a.voce.-.16-11-2022.1049.zip)

**Comment by mschering** [comment]
All issues were only present in the Dark theme. I fixed that.

Except for the Yoga cats example. The HTML source is invalid and I can't fix that easliy. It contains a strange tracking code in the image tag. Max mail also has problems displaying that (notice the question mark in the top left corner):

![image](https://user-images.githubusercontent.com/1314447/202408996-58f600ec-8562-4042-b106-a6828c46c992.png)

**Comment by flaviozluca** [comment]
Thank you!!
