### ISSUE TITLE
6.6.124 -> SQL-Error in history_log_entry

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#905]
6.6.124 throws continously this error:

> Failed to register new entity type for class 'go\modules\community\history\model\LogEntry'.
PDOException in /home/web/go/go/core/db/Statement.php at line 124: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'LogEntry' for key 'clientName'

I don't know, where this comes from. There's neither an entry 'LogEntry' nor a key 'clientName' to find in this table.
Debian with PHP 8.1
Greetings robw

**Comment by mschering** [comment]
It's not a bout that table. The key is in core_entity.

Can you find a "LogEntry" there? Is it perhaps in the wrong case?

**Comment by robshnup** [comment]
Hi, there is an entry 'LogEntry', but in right case. Have I to delete it?
![image](https://user-images.githubusercontent.com/80580927/200301035-cbdf0985-a1b1-4249-b75f-3039bf5ed86e.png)

**Comment by robshnup** [comment]
After deletion this "LogEntry" everything runs OK:
