### ISSUE TITLE
Group Office Assistant 1.1.22 on Windows 10

### ISSUE THREAD

**Issue by IT-AND-GENERAL** [Intermesh/groupoffice#906]
Undefined index: path returned when saving a file 
![image](https://user-images.githubusercontent.com/52159663/200264622-f56e9aca-8936-4b41-872d-1f7249ac6e86.png)

**Comment by mschering** [comment]
I can't reproduce the error on windows. Is it perhaps a very large file? Larger than post_max_size in php.ini?

See also: https://groupoffice.readthedocs.io/en/latest/install/config.html#recommended-php-settings

**Comment by IT-AND-GENERAL** [comment]
Hi Merijn,
This is happening only on Windows since the new version of Group Office Assistant 1.1.22 and it is happening also with small files. The error pop-up I attached earlier was generated when trying to save a 40KB file.

Is there anything else I can do to help you troubleshooting this issue?

**Comment by mschering** [comment]
do you see any errors in the webserver logs?

The only thing that has changed it the SSL connection. Before we disabled TLS v1.3 because of an old bug. It has been re-enabled now. Perhaps that helps.

**Comment by IT-AND-GENERAL** [comment]
Nothing on the webserver log but I enabled debug and I get this:

![image](https://user-images.githubusercontent.com/52159663/200299572-00c62a32-0065-4420-97e7-f61506f74d78.png)


as well as the following on debug.log:

        EXCEPTION: ErrorException: Undefined index: path in /var/www/html/groupoffice-6.6.124/modules/assistant/controller/FileController.php:20
        Stack trace:
        #0 /var/www/html/groupoffice-6.6.124/modules/assistant/controller/FileController.php(20): go\core\ErrorHandler::errorHandler(8, 'Undefined index...', '/var/www/html/g...', 20, Array)
        #1 /var/www/html/groupoffice-6.6.124/modules/professional/controller/AbstractController.php(46): GO\Assistant\Controller\FileController->actionUpload(Array)
        #2 /var/www/html/groupoffice-6.6.124/go/base/controller/AbstractController.php(387): GO\Professional\Controller\AbstractController->callActionMethod('actionupload', Array)
        #3 /var/www/html/groupoffice-6.6.124/go/base/Router.php(179): GO\Base\Controller\AbstractController->run('upload', Array)
        #4 /var/www/html/groupoffice-6.6.124/index.php(115): GO\Base\Router->runController()
        #5 {main}

**Comment by mschering** [comment]
We are unable to replicate the issue. Can you send a link to our support with a demo login so we can investigate it?

**Comment by IT-AND-GENERAL** [comment]
link sent to your support team

**Comment by mschering** [comment]
Please try with 1.1.24
