### ISSUE TITLE
6.6.128 - PHP8.1 complains about loosing precision

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#907]
Several times a day I get mails from cron about "StringHelper.php" complaining of loosing precision:

`Uncaught exception: ErrorException in /home/web/go/go/base/util/StringHelper.php at line 1249: Implicit conversion from float 517599.00000000006 to int loses precision at 2022-11-10T13:53:01+00:00`

This line is:
`mt_srand(( double ) microtime() * 1000000);`

If I would replace (double) by (int) the spook should go away, but I don't now whether this would be correct.
Greetings robw

**Comment by michalcharvat** [comment]
The solution for this issue should looks like:

```
list($usec, $sec) = explode(' ', microtime());
mt_srand($sec + $usec * 1000000);

**Comment by robshnup** [comment]
Changing the concerned line in "StringHelper.php" (1249) to:

`mt_srand(( int) microtime() * 1000000);`

does the trick for PHP8.1

**Comment by mschering** [comment]
Strange, I don't get this error with PHP Version 8.1.12. Which one do you use?

**Comment by robshnup** [comment]
Same as you 8.1.12-1
Debian bookworm

**Comment by michalcharvat** [comment]
@mschering https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

**Comment by mschering** [comment]
Yes I know. I just don't understand why it doesn't happen here with error_reporting set to E_ALL.

**Comment by mschering** [comment]
I made th

**Comment by svenvogel** [comment]
> Changing the concerned line in "StringHelper.php" (1249) to:
> 
> `mt_srand(( int) microtime() * 1000000);`
> 
> does the trick for PHP8.1

this also works for me.
