### ISSUE TITLE
Update from 6.4.190 to 6.4.191 doesn't work

### ISSUE THREAD

**Issue by Matthias-Mue** [Intermesh/groupoffice#909]
Hi

I treid to update from Version 6.4.190 to 6.4.191, but when i try to update the database with /install/update.php the follwing error appears:

_**--------------------------------------------------------------------------
Upgrade output will be logged into: log/upgrade/20221116_074314.log

Skipping module chat because it's not available.
Rebuilding cache
Registering all entities

ErrorException in /is/htdocs/XXXXXXXX/www/groupoffice/go/core/data/convert/Spreadsheet.php at line 619: Declaration of go\core\data\convert\Spreadsheet::importEntity() must be compatible with go\core\data\convert\AbstractConverter::importEntity($entityClass, $fp, $index, array $params) at 2022-11-16T07:43:14+00:00
-----------------------------------------------------------------------------**_

Can you give me a hint?

Thanks

Matthias

**Comment by mschering** [comment]
This is quote an old version. Why don't you upgrade to 6.6?

**Comment by Matthias-Mue** [comment]
You can't update directly from version 6.4.190 to 6.6, can you?

**Comment by derjoachim** [comment]
> You can't update directly from version 6.4.190 to 6.6, can you?

[Nope](https://groupoffice.readthedocs.io/en/latest/upgrade/upgrade.html).

**Comment by Matthias-Mue** [comment]
Is it possible to switch directly to the latest 6.4 version? I seem to remember that the update process asked for version 6.4.192 next

**Comment by derjoachim** [comment]
6.4.191 is the minimum version for the upgrade to 6.5 . That being said, I would advise to update to the latest 6.4 version first.
