### ISSUE TITLE
v6.6.131 and Xeams email server: clearing the Trash folder removes other folders belonging to the same account

### ISSUE THREAD

**Issue by l-github-245** [Intermesh/groupoffice#910]
Hi, when I try to clear the contents of the Trash folder of an imap account, I get that only Inbox / Sent Items / Trash / Junk / PossibleJunk remain. All other folders are removed without warning.

I had the same behaviour in 3 accounts under the same domain. 

To replicate the issue, click on the Trash folder to select, then right click and choose Empty Folder. It refreshes the page and only the mentioned folders are left. 

If I insist doing that on the same account, even the Sent Items folder disappears.

I can understand some folders are created with the account and may be rarely used. However, clearing the Trash should not affect the existing folders of the account.

Apache 2.4.38, PHP 7.4.33, groupoffice 6.6.131 and Xeams 8.4 build 6238

**Comment by mschering** [comment]
This doesn 't happen with any other IMAP servers we have seen. If you want us to investigate please register for a license and get support from us.
