### ISSUE TITLE
Calendar publishing update has problem with file_put_contents

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#912]
I wanted to publish a calendar and update it every 2 hours.

With PHP 8.1. it complains about the line 223 in "/go/go/base/fs/File.php"

`public function putContents($data, $flags=null, $context=null)
{
if(file_put_contents($this->path, $data, $flags, $context))
{
....
`
Php doesn't tolerate 'null' as $flags, it must be an int - e.g. '0'
Changing to 'flags=0' is the solution.
Greetings robw

**Comment by mschering** [comment]
Thanks, will be changed in the next release.

PS: we have a 6.7 beta release where we will support 8.1 officially.
