### ISSUE TITLE
core_auth_remember_me foreign key error

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#913]
When trying to delete an user that has remember me set, it errors out with:
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ccm`.`core_auth_remember_me`, CONSTRAINT `core_auth_remember_me_core_user_id_fk` FOREIGN KEY (`userId`) REFERENCES `core_user` (`id`))

This is caused by the definition of the foreign key which by default is set to RESTRICT.

Please change fk definition to on delete cascade

**Comment by polarismail** [comment]
fix:

ALTER TABLE `core_auth_remember_me` DROP FOREIGN KEY `core_auth_remember_me_core_user_id_fk`;

ALTER TABLE `core_auth_remember_me` ADD CONSTRAINT `core_auth_remember_me_core_user_id_fk` FOREIGN KEY (`userId`) REFERENCES `core_user` (`id`) ON DELETE CASCADE;

**Comment by mschering** [comment]
Thanks, fixed this one.
