### ISSUE TITLE
dav_event sql data column too small

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#916]
Stumbled upon the following bug.

When an event in cal_events has a description that hits the limit of 65535 characters ( TEXT column ) then it's impossible to export it via DAV. 

In modules/caldav/CaldavModule.php line 42, that data gets repackaged from this function: self::exportCalendarEvent($event) and the resultant string may well be over 65535 characters which is the limit in dav_events for the data column.

It seems a bit tricky to solve since we're not sure how big the repackaged data could be due to recurrent serries.

Ideally you would truncate the data before saving it, or the 'easy' approach would be to convert the data column to mediumtext although that may impose other penalties to performance due to the _much_ bigger column size.

**Comment by michalcharvat** [comment]
Well in different project we are using mediumblob column for ics data and there isnt any problem with performance (over 12M rows stored in calendar objects) However it is still up to @mschering if he accept this change :-)

**Comment by mschering** [comment]
I made it a mediumtext. I don't think it affects performance since it's stored off table.
