### ISSUE TITLE
Sanitize corrupted html

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#922]
Some messages arrive with corrupted encoding and that causes all preg_replace functions to stop working, thus rendering the html message empty. This happens in go/base/util/StringHelper.php function sanitizeHtml

Instead of rendering empty messages it might be better to try and fix those messages by forcing conversion to UTF-8

For example, we added this code at the beginning of the sanitizeHtml function which sort of takes care of the problem

                // Unknown encoding, force UTF-8
                if (!mb_detect_encoding($html, 'auto')) {
                        $html = mb_convert_encoding($html, "UTF-8");
                }

This causes the message to be rendered. Not sure if you guys already tried something similar or other work-arounds for corrupted messages but I think it's better than nothing

**Comment by polarismail** [comment]
Actually, this solution works much better:

in modules/email/model/ImapMessage.php

function getHtmlBody around line 388

```
$htmlPartStr = $imap->get_message_part_decoded($this->uid, $htmlPart['number'],$htmlPart['encoding'], $htmlPart['charset'],$this->peek,false);

// Convert to message defined charset 
if (!mb_detect_encoding($htmlPartStr, 'auto')) {
   $htmlPartStr = mb_convert_encoding($htmlPartStr, "UTF-8", $htmlPart['charset']);
 }

$htmlPartStr = \GO\Base\Util\StringHelper::convertLinks($htmlPartStr);
$htmlPartStr = \GO\Base\Util\StringHelper::sanitizeHtml($htmlPartStr);
```

**Comment by mschering** [comment]
Thanks, will be fixed in the new update today.

**Comment by polarismail** [comment]
thank you as well, your solution is much nicer! :)
