### ISSUE TITLE
Feature request: Automatically add new notes to Synchronization

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#927]
Feature request: Automatically add new notes to Synchronization, currently you have to add 1 by 1, inside my account/sync.

Also a way to add in batch.

Thanks.

**Comment by mschering** [comment]
I Have changed that you can add more than one item at a time. But I don't think it's desired to automatically add new note books for most users.

**Comment by flaviozluca** [comment]
Thanks.
