### ISSUE TITLE
Creating an announcement is allways shared with "everyone" group by default

### ISSUE THREAD

**Issue by michaelSoluris** [Intermesh/groupoffice#930]
When an user create an announcement, it's always shared to "everyone" group. Even if the user don't have usualy the permission to share something to this group.

The new announcement shouldn't be shared to the group "Everyone" by default.

![image](https://user-images.githubusercontent.com/76783618/205867971-8727c7e4-688b-4a47-84c1-8d905e344218.png)

**Comment by mschering** [comment]
You're right. I have changed this in the next release.
