### ISSUE TITLE
Event request in mail

### ISSUE THREAD

**Issue by michalcharvat** [Intermesh/groupoffice#932]
When you receive mail with ics request, the link "Indicate whether you participate in this event" is displayed above the message body. However when you click on it and you are not a participant of this event, you get error message "trying to get property 'statusName' on a non object".  There is probably wrong annotation so this bug has to be visible in static analyze. The workaround could be simple 

replace
```
$response['feedback']=sprintf(\GO::t($langKey,'calendar'), $event->calendar->name, $participant->statusName);
```
with
```
$response['feedback']=sprintf(\GO::t($langKey,'calendar'), $event->calendar->name, $participant ? $participant->statusName : '');
```

or even better

```
$response['feedback']=sprintf(\GO::t($langKey,'calendar'), $event->calendar->name,  $participant->statusName ?? '');
```

**Comment by mschering** [comment]
Thanks, I fixed this in the master branch.
