### ISSUE TITLE
Cannot install sixsix

### ISSUE THREAD

**Issue by jh197033** [Intermesh/groupoffice#939]
OS: ubuntu 22.04 Server fresh install

I have followed all the instructions on installing GO and tried installing over 20 times and I still get the same error:

Uncaught exception: Error in /usr/share/groupoffice/go/core/model/Group.php at line 173: Class 'go\core\model\model\Acl' not found at 2022-12-14T08:38:03+00:00

When I check the database it only gets to installing 60 tables.

I have adjusted the php execution times and mysql timeouts as example below

Maximum memory allocation 256M
Maximum file upload size 1000M
Maximum input parsing time 300
Maximum HTTP POST size 1000M
Maximum execution time 300 seconds

nano /etc/mysql/mysql.conf.d/mysqld.cnf
wait_timeout = 31536000
interactive_timeout = 31536000
connect__timeout = 31536000

If I change the version of GO FROM:

echo "deb http://repo.group-office.com/ sixsix main" > /etc/apt/sources.list.d/groupoffice.list

TO 

echo "deb http://repo.group-office.com/ sixfive main" > /etc/apt/sources.list.d/groupoffice.list

It installs.

On the ubuntu 22.04 server I have also added:

apt install -y php7.4 php7.4-mbstring php7.4-mysql php7.4-xml php7.4-curl php7.4-gd php7.4-intl php7.4-xsl php7.4-apcu
update-alternatives --set php /usr/bin/php7.4
a2dismod php8.1
a2enmod php7.4
systemctl restart apache2

But still doesnt install, any ideas what I am doing wrong?

**Comment by thomasgg23** [comment]
Had the same on a test installation.

This should help.
https://github.com/Intermesh/groupoffice/pull/936

**Comment by jh197033** [comment]
So should I just wait for an update?

**Comment by thomasgg23** [comment]
You also can change this file https://github.com/Intermesh/groupoffice/pull/936/files before calling the install page.

You should do an uninstall of the package first.

This worked for me

**Comment by mschering** [comment]
Sorry. I’ll release an update tomorrow to fix this.

**Comment by jh197033** [comment]
Thanks to all for you help, I will wait for update.

**Comment by jh197033** [comment]
Got the update, installs fine.. Thank you :)
