### ISSUE TITLE
Feature request: Show note categories in alphabetical order when choosing a note's category

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#940]
Friends,

When changing a note's category, can you please show the notes' categories in Alphabetical order so I can find them easier?

See, they are out of order in the menu.

![image](https://user-images.githubusercontent.com/44004645/207632343-45b043a9-967d-4b17-9884-3646a1724bf8.png)

Thanks.

**Comment by mschering** [comment]
Fixed in 6.6.141

**Comment by flaviozluca** [comment]
Thanks a lot.
