### ISSUE TITLE
Category field not respecting RFC 5545 standard for tasks

### ISSUE THREAD

**Issue by Ownezx** [Intermesh/groupoffice#942]
Hi,

I was working on a way to use the Category field of the CalDav in order to be able to filter on an external tool. 

I would have expected to see something like `CATEGORIES:APPOINTMENT,EDUCATION` like in the [RFC 5545 Documentation](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.1.2). But I was surprised to see an SQL request in the Category field of the GroupOffice ICS file.

I created an ICS file using my IOS device that was syncing with the CalDav from group office, then modified the categories and here was the result : 

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Intermesh//NONSGML Group-Office 6.6.135//EN
BEGIN:VTODO
X-APPLE-SORT-ORDER:11
DTSTAMP:20221221T150941Z
LAST-MODIFIED:20221221T150941Z
CREATED:20221221T005825Z
UID:B7126631-4924-4843-9FD8-C18DFF7F9D89
SUMMARY:Example summary
PRIORITY:0
DTSTART;VALUE=DATE:20221223
DUE;VALUE=DATE:20221223
DESCRIPTION:
LOCATION:
CATEGORIES:SELECT name \nFROM `tasks_category` `t`\nWHERE \n `t`.`id` IN (8
 9)
STATUS:NEEDS-ACTION
END:VTODO
END:VCALENDAR
```

What I would have expected for the category would have been something like this, with a custom field for the SQL request : 

```
CATEGORIES:CATEGORY_NAME
X-GO-CATEGORY-REQUEST:SELECT name \nFROM `tasks_category` `t`\nWHERE \n `t`.`id` IN (8
 9)
```

This makes it impossible to filter by categories on external software where you do not have access to the GO database.

**Comment by mschering** [comment]
Sorry for the late reply. It will be fixed in the next release.
