### ISSUE TITLE
Feature request: icons up top in inbox (search, accounts, etc.)

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#947]
Friends,

Users get confused. The search disappeared, etc. They dont understand that they get added to the 3 vertical dots.

One if, as you minimize the pane, make the icons appear in a second row, instead of hiding them and adding them to the 3 vertical dots.

Many users get confused.

Thanks.

https://user-images.githubusercontent.com/44004645/210624325-16eb90c6-4c14-4c60-852b-2d69f7acf34f.mp4

**Comment by flaviozluca** [comment]
How did u fix this? Force width?

**Comment by mschering** [comment]
Yes, I set a minimum width.

**Comment by flaviozluca** [comment]
Friend,

In the demo I can still shorten it and hide search, see

![image](https://github.com/user-attachments/assets/69fa9f73-fb85-4831-bb4a-0aa7b40f0757)

**Comment by mschering** [comment]
We'll fix this in the new email module
