### ISSUE TITLE
Export .ics via Tasks -> Export -> vCalendar: BEGIN:VCALENDAR/END:VCALENDAR around every BEGIN:VTODO/END:VTODO

### ISSUE THREAD

**Issue by Kieltux** [Intermesh/groupoffice#950]
Hello, thank you very much for GroupOffice. I am using GroupOffice for around 12 years now.

After a long time I updated from 6.2.134 to 6.6.143 (and today to 6.6.145) without only one problem.
The ics file from Tasks -> Export -> vCalendar will not work with e.g. Kontact (KDE PIM).

The reason is, that after the the update from 6.2 to 6.6 every VTODO in ics file is wrapped with BEGIN:VCALENDAR/END:VCALENDAR.
If I remove all extra BEGIN:VCALENDAR/END:VCALENDAR. around all BEGIN:VTODO/END:VTODO, I can import the ics file into Kontact.

Non working ics file (from Tasks -> Export -> vCalendar)
```

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Intermesh//NONSGML Group-Office 6.6.145//EN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:19701025T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700329T010000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Intermesh//NONSGML Group-Office 6.6.145//EN
BEGIN:VTODO
DTSTAMP:20230114T055247Z
LAST-MODIFIED:20230101T142120Z
CREATED:20190316T184258Z
RRULE:FREQ=MONTHLY;INTERVAL=1
UID:21
SUMMARY:Test
PRIORITY:0
DTSTART;VALUE=DATE:20230201
DUE;VALUE=DATE:20230201
DESCRIPTION:
LOCATION:
CATEGORIES:SELECT name \nFROM `tasks_category` `t`\nWHERE \n `t`.`id` IN (1
 )
STATUS:NEEDS-ACTION
END:VTODO
END:VCALENDAR
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Intermesh//NONSGML Group-Office 6.6.145//EN
BEGIN:VTODO
DTSTAMP:20230114T055247Z
LAST-MODIFIED:20230101T150240Z
CREATED:20190316T184258Z
UID:22
SUMMARY:Test
PRIORITY:0
DTSTART;VALUE=DATE:20230801
DUE;VALUE=DATE:20230801
DESCRIPTION:
LOCATION:
CATEGORIES:SELECT name \nFROM `tasks_category` `t`\nWHERE \n `t`.`id` IN (1
 )
STATUS:NEEDS-ACTION
END:VTODO
END:VCALENDAR
END:VCALENDAR

```
I read the RFC 5545, but I am not sure, if this is a problem with the export or with Kontact (KDE PIM).

The calender export does not wrap  BEGIN:VCALENDAR/END:VCALENDAR around every event (BEGIN:VEVENT/END:EVENT).

**Comment by mschering** [comment]
Fixed in the next release.
