### ISSUE TITLE
Auto-complete and semi-colons

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#951]
GO supports commas and semi-colons as emails separators. The default is commas. I noticed that, if I use semi-colons, then auto-complete doesn't work.

**Comment by flaviozluca** [comment]
this one relatively important and, perhaps not so hard to fix. Just a though.

**Comment by mschering** [comment]
Fixed this by inserting comma when you type a ;.

**Comment by flaviozluca** [comment]
Awesome! Thanks!!
