### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by jh197033** [Intermesh/groupoffice#953]
I have been doing many test installs with GO over the past month, no issues. But the last few days on a fresh install of debian 11 using 

echo "deb http://repo.group-office.com/ sixsix main" > /etc/apt/sources.list.d/groupoffice.list
wget -O- https://repo.group-office.com/downloads/groupoffice.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/groupoffice.gpg
apt update -y && apt install -y groupoffice

After installing GO and login and then select Multisite, I add the url with all modules and the navigate to the url and I get:

Uncaught exception: PDOException in /usr/share/groupoffice/go/core/db/Connection.php at line 174: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'domainname.core_module' doesn't exist at 2023-01-18T12:54:23+00:00

Has something changed?

I have installed over 4 times today and same error but last week no issues following the same instructions I have written down.

**Comment by mschering** [comment]
Thanks, this error will be fixed in the next release today.
