### ISSUE TITLE
PHP 8.0/8.1

### ISSUE THREAD

**Issue by Matthias-Mue** [Intermesh/groupoffice#955]
Hello

I have a problem with the reinstallation of Groupoffice.

`PHP version: Fatal error: Your PHP version (8.0.27-he.0) is not supported. PHP 7.2 or higher is required. PHP 8+ is not supported yet.`

Which version supports PHP 8.0 or 8.1? My hoster does not allow PHP 7.X - version anymore.

Thanks for your help in advance.

Greetings
Matthias

**Comment by mschering** [comment]
Hi,

You can only use 6.7 on PHP 8.1. It's in beta but I think it's stable enough to use!

Best regards,
Merijn
