### ISSUE TITLE
typo on word 'Separator'

### ISSUE THREAD

**Issue by polarismail** [Intermesh/groupoffice#956]
Throughout the code, you guys are using the word 'Seperator' when in fact it should be 'Separator'
for example

go/core/views/extjs3/usersettings/LookAndFeelPanel.js:                                          fieldLabel: t("Thousand Seperator", "users", "core"),
go/core/views/extjs3/usersettings/LookAndFeelPanel.js:                                          fieldLabel: t("Decimal Seperator", "users", "core"),
go/core/views/extjs3/users/UserDefaultsWindow.js:                                                                       fieldLabel: t("Thousand Seperator", "users", "core"),
go/core/views/extjs3/users/UserDefaultsWindow.js:                                                                       fieldLabel: t("Decimal Seperator", "users", "core"),

**Comment by derjoachim** [comment]
Good catch! Fixed in 6.6 and 6.7
