### ISSUE TITLE
S/MIME not working anymore

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#957]
Sorry that i don't know when this got broken, but we just got into trouble yesterday by communicating with a customer who had our public key from the past, so he would be able to send us signed/encrypted messages.

Signed emails work fine, however not encrypted ones.
GO says, it does not have the private key to encrypt that.

Also, outgoing emails are not signed anymore either.
The checkbox is pre-checked by default, sorry no time for debugging so far today :-/
So, for all outgoing emails it is not possible to be signed/encrypted.

**Comment by thomasgg23** [comment]
Did you update your ubuntu to 22.04 LTS ?
Or updated openssl to 3.x

My certificate users uses 40BitRC2-CBC encryption so I had to enable legacy support.
See first answer how to switch on the legacy support
https://stackoverflow.com/questions/73832854/php-openssl-pkcs12-read-error0308010cdigital-envelope-routinesunsupported

**Comment by lonesomewalker** [comment]
No, this is an older Debian system.
