### ISSUE TITLE
deleting user gives error

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#958]
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`databasename`.`core_change`, CONSTRAINT `core_change_ibfk_2` FOREIGN KEY (`aclId`) REFERENCES `core_acl` (`id`) ON DELETE SET NULL)

**Comment by derjoachim** [comment]
Which version are you currently using?

**Comment by lonesomewalker** [comment]
Latest 6.6

**Comment by derjoachim** [comment]
Could you run a database check and try again please? I think that the system is trying some record with a incorrect ACL reference. A database check will fix that.
