### ISSUE TITLE
Problem with install of V6.7.9

### ISSUE THREAD

**Issue by Matthias-Mue** [Intermesh/groupoffice#960]
Hello

I have problems installing version 6.7.9.

During the installation appears the error:
_Create an administrator account
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint on query (151) ALTER TABLE `core_email_template_attachment` ADD CONSTRAINT `core_email_template_attachment_ibfk_1` FOREIGN KEY (`blobId`) REFERENCES `core_blob` (`id`), ADD CONSTRAINT `core_email_template_attachment_ibfk_2` FOREIGN KEY (`emailTemplateId`) REFERENCES `core_email_template` (`id`) ON DELETE CASCADE_

The next time the install.php is called, the following error message appears:
_Error: Exception in /is/htdocs/wp12281741_C65PWQR0MY/www/groupoffice/go/core/Settings.php at line 68: Could not find module core/core_

Can someone help me here?

Greetings

**Comment by mschering** [comment]
I have tested the install in mysql 5.7, 8.0 and Mariadb latest. In all 3 I don't get this error. Which version are you using?

**Comment by mschering** [comment]
Yes, the minimum supported mysql version is 5.7

**Comment by shree0** [comment]
Hello, 
I am also getting exactly the same error during installation. My  Mariadb version is 10.6.15.
please help to resolve this.
