### ISSUE TITLE
No modules with 6.7.11 ff. without ioncube

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#962]
Hello, here with 6.7 (from 6.7.9 -> 6.7.12) everything works like a charm. Thanks a lot!
Upgrade no prob too.

The only drawback is that the modules config does not work without installed ioncube.
And since Debian bookworm has upgraded to php8.2 and ioncube offers only php8.1-loaders there is no way out.

But not a big trouble. Ioncube will bring it sooner or later...
Greetings robw

**Comment by michalcharvat** [comment]
You can always downgrade (or upgrade) PHP to your favourite version with debian sury repository. 

https://www.cloudbooklet.com/how-to-install-or-upgrade-php-8-1-on-debian/

**Comment by robshnup** [comment]
Hi michalcharvat,
but if I have only the community edition og GO, it should be possible to manage the modules as admin without any ioncube-loader installed I think.
This would be the clean solution.

**Comment by michalcharvat** [comment]
I just wanted offer you a way how to run different version PHP on Ubuntu or Debian. I personally use Sury's repo on my servers because you almost do not care about PHP version from official distribution.

**Comment by derjoachim** [comment]
As per 6.7.33 (released two months ago at the time of this comment), it should be possible to install the community version without ioncube. Therefore, I'll close this ticket
