### ISSUE TITLE
logout when inactive not working on admin account

### ISSUE THREAD

**Issue by johanpeters** [Intermesh/groupoffice#963]
for non admin accounts the timed logout looks like working.
when admin is logged in the account is not logout after the configured time.

**Comment by manjarooo** [comment]
I can confirm that.
When I get the message that I got logged out due to timeout, I press "OK", but I am still in the system, and can navigate/open sites and edit settings etc.

**Comment by mschering** [comment]
Sorry, there's no difference with a normal account. I tested it and it works fine. Maybe you logged in via /caldav or /webdav with a basic auth dialog? That login can't be unset.
