### ISSUE TITLE
Partial search inside notes

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#964]
Friends,

We found out something interesting. Sometimes we have a hard time with certain searches inside NOTES. 

Title of note: Outlook - 0x8004df0b - Sincronizando as pastas, conexão não disponível

If I search for 8004, it won't find the note. 0x8004 however, finds it.

See video.

Thanks.

https://user-images.githubusercontent.com/44004645/219421701-df2c6aa7-f6a6-4a3a-a49c-e9a727ef3646.mp4

**Comment by mschering** [comment]
Yes, this is expected behaviour. This is because of how the index works.

Tech tip: You can find it with: name: %8004%

**Comment by flaviozluca** [comment]
thanks, perhaps add to manua.
