### ISSUE TITLE
Installing 4.7.13 complains about "DROP FOREIGN KEY in core_import_mapping" table

### ISSUE THREAD

**Issue by robshnup** [Intermesh/groupoffice#965]
While updating from 6.7.12 to 6.7.13 I got this error:
> SQL-Error: ALTER TABLE core_import_mapping` DROP FOREIGN KEY `core_import_mapping_core_entity_null_fk` is not possible
(This foreign key was definitively existent but could not be dropped in MariaDB 10.6.11)

Then in "\go\go\core\install\updates.php" I found in row 1356:
`$updates['202302011409'][] = "ALTER TABLE core_import_mapping` DROP FOREIGN KEY `core_import_mapping_core_entity_null_fk`;";`

Since further on in row 1363 this constraint is re-established, I deleted the dropping of the foreign key in 1356 and the update ran as expected!

A littlebit confusing the dropping and reconditioning of this table.
greetz robw

**Comment by derjoachim** [comment]
This was not reproducible on my 6.7 systems. It should not be a problem to drop a foreign key and recreate it, given that the foreign key exists. Assuming that earlier updates were performed without errors, I am a bit stumped on why the FK was not there in the first place.

Unfortunately, a syntax like `DROP FOREIGN KEY IF EXISTS` is not supported.

Which Mysql / MariaDB version are you using?

**Comment by mschering** [comment]
I fixed this issue on Monday. The fix was already released.
