### ISSUE TITLE
mails with bcc not always sent

### ISSUE THREAD

**Issue by johanpeters** [Intermesh/groupoffice#967]
Hello,
we found out that sending mail to internal and external receipents  (bcc) is not always sent.
in this case to: internal mail adress and BBC: internal and external mail adresses.

check mailserver loging. .nothing sent. checking mailbox.
mailbox is sent
mail is recieved in the internal mailbox (to address)
mail is not received in internal and external mailboxes (bcc address)
no mail is offered to the mailserver 

several days later, same mail .. that was sent.. 
so the working of the mail is not consistant.. but of not delevered than also no mail return.

are there limits in the amount of mail adresses?
how does group-office handle mail with multiple receipents.. ?
does group-office split the message and offer every mail to the server to be delevered or is it one mail and does the mailserver need to convert that to several mails (one mail for every receipient)?

also i saw that the mailserver is just sent al the mail on the same time.. 
so the mail that was sent (150+ reciepents) are al sent on the same time.. so spamfilters are triggert..

**Comment by mschering** [comment]
Sorry for the very late reply. 

But GO just hands one message to the mailserver and delivering it is up to the mailserver. So I suspect this is not a Group-Office problem.
