### ISSUE TITLE
Search in Email folders gives no result

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#969]
When searching at the commandline, all emails are found, but the search in GO gives no results.
No matter which pattern, even with small parts of the searched word, no results.
And it does not matter if the searched string is in the header or full email.

GO latest.

**Comment by derjoachim** [comment]
If you try to search in email message bodies, please update your `/etc/groupoffice/config.php` file like this:

```
$config['email_allow_body_search'] = true;
```

By default, searching in email message bodies is disabled for performance reasons.

**Comment by lonesomewalker** [comment]
mmmmh, silly me, i already marked that in my internal documentation to enable everywhere...
No bug.
