### ISSUE TITLE
Importing notes and tasks

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#971]
Friends,

Tried to import a notepad which I had exported in GO in XLSX format, then import in another account, in another noted, it says 5 items imported but nothing appears. Is it a supported format for importation?

Tried to import tasks which I exported in GO in ICS, got this error:

![image](https://user-images.githubusercontent.com/44004645/224308756-1389e834-aedc-46d1-8131-d95ca06237a1.png)

Can you pls contact me so I can send the evidence files, if needed?

Thanks!

**Comment by mschering** [comment]
Please send me the evidence files ;)

**Comment by mschering** [comment]
The export was invalid. This is fixed in the next release.
