### ISSUE TITLE
Feature request: Notes have files

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#973]
It would really be nice to be able to attach Files to notes.

Thanks.

**Comment by mschering** [comment]
Already possible.

**Comment by mschering** [comment]
Since ever! :)

![image](https://github.com/Intermesh/groupoffice/assets/1314447/8fb66222-082e-4ea2-a90d-b75928ba32b3)

**Comment by flaviozluca** [comment]
Im confused.  Where do I click to add a file?? Which icon?

![image](https://github.com/Intermesh/groupoffice/assets/44004645/a7a15a55-685b-4102-8a91-b46f19f9e4bd)

**Comment by mschering** [comment]
The folder icon next to the opened menu. Also check my screenshot with the "Files" section and "Drop files here".

**Comment by flaviozluca** [comment]
I got a bit lost, I didnt realize it was possible. cant you change it to the traditional "clips" icon? or upload symbol?
