### ISSUE TITLE
feature request: remove formatting in a note

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#974]
Friends,

No way to remove formattting? I use remove formatting it doesn't remove the html code.

Its all highlighted. I have to copy to notepad then back.

See video.

Thanks.

https://user-images.githubusercontent.com/44004645/225711847-77c2b410-5ac8-42cf-9d6d-99090d4f0c96.mp4

**Comment by flaviozluca** [comment]
Merijn,

How are you? Pls check this video too. This is a bit annoying, many times when I paste something to a NOTE, it brings the backgroud color.

Even a normal email, look how it put a white background. I know I can type shift control v, however, this behaviour doesn't seem to occur pasting to other places.

Thanks.

https://github.com/Intermesh/groupoffice/assets/44004645/e9a464be-f6ac-43c0-a675-0359a0eaecba

**Comment by mschering** [comment]
The word paste button fixes it.

**Comment by flaviozluca** [comment]
Not sure what u mean, Word paste button? Sent u evidence of this the other day via email.

**Comment by mschering** [comment]
You can find it in the editor menu

**Comment by flaviozluca** [comment]
Ohh, Word paste got it...

![image](https://github.com/Intermesh/groupoffice/assets/44004645/3272254c-8e80-4c3f-ac90-97ae74d7f2c3)

**Comment by flaviozluca** [comment]
Friend,

I do a CONTROL C in Word, then choose Word paste, nothing happens.

Isnt it supposed to paste?

BTW, how can I paste from other places without bringing formatting? Same option, right?

Tks.

**Comment by mschering** [comment]
This button cleans the selected text. Paste without format is ctrl + shift + v
