### ISSUE TITLE
small issue with an event in the calendar

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#975]
Friends,

I added an event on the 3rd of April 8 AM to 9 AM. The text was badly cut off in the calendar view.

I found that it was due to too many events from 9 AM to 10 AM. deleting 1 of them fixed the visualization of the event from 8 to 9.

I think this could be improved. Cells seem to be somehow merged, even in different days.

https://user-images.githubusercontent.com/44004645/229390474-94c12569-5089-4a7c-a982-120bc805e1f4.mp4

See video pls.

Thanks.

**Comment by mschering** [comment]
This one will be fixed by the new calendar module soon.
