### ISSUE TITLE
fault after fresh install

### ISSUE THREAD

**Issue by Protomolekule** [Intermesh/groupoffice#976]
Using Debian 11.6 installing latest GO 6.7.22 and get the following failure when I call https://IP/groupoffice/install
<!DOCTYPE html>
<html lang="de" dir="ltr">
<head>
	Uncaught exception: PDOException in /usr/share/groupoffice/go/base/db/Columns.php at line 78: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.core_module' doesn't exist at 2023-04-16T12:26:55+00:00

I saw that this failure was solved before, but now it's up again

In sixsix it's working fine

**Comment by mschering** [comment]
Did you get another error prior this to this one? The core_module table should always be installed so I'm guessing the installation was interupted for some reason. Can you also post your mysql version and PHP version?

**Comment by Protomolekule** [comment]
It is a totally fresh installation in a VM using debian-11.6-amd64-netinst.iso. There were no prior errors. I took a look inside the groupoffice/log but there is no further information.

Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11
php -v
PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
