### ISSUE TITLE
Error message due to 1 invalid recipient shows BR HTML codes

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#977]
Friends,

1 or 2 invalid emails, the error message GO shows is not friendly, has HTML codes that are not interpreted.

See

![image](https://user-images.githubusercontent.com/44004645/233152944-335d4403-ddbb-4bbf-a147-0d37d0e76b76.png)

Thanks,
Flávio

**Comment by mschering** [comment]
This one has been fixed.
