### ISSUE TITLE
Problem with the address book

### ISSUE THREAD

**Issue by endozip** [Intermesh/groupoffice#978]
After upgrading from version 6.5 to version 6.7.23 there is the following problem with the address book:
If you call up the address book in the e-mail using the +_button, you cannot transfer the selected address to the e-mail, although the address book itself can be edited and organized as normal.
However, after entering a few characters, the existing addresses are automatically added to the e-mail as they appear in the address book.

**Comment by endozip** [comment]
Yes I cannot transfer the selected address to the e-mail by clicking the button labeled 'Add selection'.
When can we expect this release?

**Comment by mschering** [comment]
It has been released today!

**Comment by endozip** [comment]
We installed version 6.7.24 but the problem persists.

**Comment by derjoachim** [comment]
Hmmm... Are there any errors in the Javascript console then?

**Comment by endozip** [comment]
In the Javascript console we get the following error message:

server-side JMAP failure 
Array(3) [ "error", {…}, "clientCallId-16" ]
script.php:1937:34
    success http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1937
    success http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1936
    handleResponse ExtJS
    handleTransactionResponse http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2312
    asyncRequest http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2418
    (Async: EventListener.handleEvent)
    asyncRequest http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2417
    request http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2472
    request ExtJS
    processQueue http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1936
    timeout http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1934
    (Async: setTimeout handler)
    delayedProcessQueue http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1934
    request http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:1930
    fillMultipleRecipients http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:4389
    selectMultiple http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:4395
    addSelection http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:2704
    (Async: promise callback)
    addSelection http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:2704
    handler http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:2705
    ExtJS 2
    (Async: EventListener.handleEvent)
    ret http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:1868
    addListener http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2029
    ExtJS 22
    handler http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:4395
    ExtJS 2
Uncaught (in promise) 
Object { message: "Required property 'go\\modules\\community\\addressbook\\model\\Contact::addressBookId' not fetched", type: "exception" }

**Comment by endozip** [comment]
We can also create new addresses in the address book, but neither delete the new addresses nor the old addresses.
The Java console gives the following error message:

Uncaught TypeError: this.entityStore is undefined
    handler http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:3556
    createDelegate http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:1397
    setTimeout handler*defer http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:1431
    ExtJS 2
    createCallback http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:1350
    ExtJS 2
    ret http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:1868
    addListener http://192.168.200.94/groupoffice/views/Extjs3/javascript/ext-base-debug.js?mtime=1681997762:2029
    ExtJS 24
    handler http://192.168.200.94/groupoffice/views/Extjs3/script.php?v=1682872508:3555
    ExtJS 3
script.php:3556:1

**Comment by endozip** [comment]
However, the address book entries can be edited, changed and saved.

**Comment by derjoachim** [comment]
The first error may have been solved as per 6.7.25, as I cannot reproduce it on my development environment. I did reproduce it though on our production, which is an earlier version. For now, I am considering this problem already fixed.

The second problem, I can neither reproduce in 6.7.25 nor an earlier version. That is, I can delete postal addresses just fine from any contact, both on my development environment and the production environments I administer.

**Comment by endozip** [comment]
We tried to install version 6.7.25 but the installation failed with the following error message:

orbereitung zum Entpacken von .../71-groupoffice_6.7.25-sixseven_all.deb ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
Package apache2 is not configured yet. Will defer actions by package groupoffice.
Entpacken von groupoffice (6.7.25-sixseven) über (6.7.24-sixseven) ...
dpkg: Fehler beim Bearbeiten des Archivs /tmp/apt-dpkg-install-eSdjji/71-groupoffice_6.7.25-sixseven_all.deb (--unpack):
 »/usr/share/groupoffice/views/goui/groupoffice-core/node_modules/@intermesh/goui/.github/ISSUE_TEMPLATE/bug_report.md.dpkg-new« kann nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: flushing administrative password
Package apache2 is not configured yet. Will defer actions by package groupoffice.
Fehler traten auf beim Bearbeiten von:
 /tmp/apt-dpkg-install-eSdjji/71-groupoffice_6.7.25-sixseven_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by endozip** [comment]
After the installation failed, GroupOffice seems to start normally but you don't get any more messages. /var/log/mail shows this error message:

May  2 20:44:02 groupoffice postfix/pickup[76504]: 04C7F1E41B5: uid=33 from=<www-data>
May  2 20:44:02 groupoffice postfix/proxymap[84478]: warning: connect to mysql server localhost: Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
May  2 20:44:02 groupoffice postfix/cleanup[84477]: warning: proxy:mysql:/etc/postfix/mysql_virtual_alias_maps.cf lookup error for "www-data@groupoffice"
May  2 20:44:02 groupoffice postfix/cleanup[84477]: warning: 04C7F1E41B5: virtual_alias_maps map lookup problem for www-data@groupoffice -- message not accepted, try again later
May  2 20:44:16 groupoffice postfix/postfix-script[85239]: stopping the Postfix mail system
May  2 20:44:16 groupoffice postfix/master[1738]: terminating on signal 15
May  2 20:49:57 groupoffice dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp, sieve (core dumps disabled)
May  2 20:50:00 groupoffice postfix/postfix-script[1758]: starting the Postfix mail system
May  2 20:50:00 groupoffice postfix/master[1760]: daemon started -- version 3.5.18, configuration /etc/postfix
May  2 20:50:00 groupoffice postfix/proxymap[1770]: error: unsupported dictionary type: mysql
May  2 20:50:00 groupoffice postfix/pickup[1761]: 19F9E1E03A5: uid=33 from=<www-data>
May  2 20:50:00 groupoffice postfix/proxymap[1770]: error: unsupported dictionary type: mysql
May  2 20:50:00 groupoffice postfix/proxymap[1770]: warning: mysql:/etc/postfix/mysql_virtual_alias_maps.cf is unavailable. unsupported dictionary type: mysql
May  2 20:50:00 groupoffice postfix/cleanup[1769]: warning: proxy:mysql:/etc/postfix/mysql_virtual_alias_maps.cf lookup error for "www-data@groupoffice"
May  2 20:50:00 groupoffice postfix/cleanup[1769]: warning: 19F9E1E03A5: virtual_alias_maps map lookup problem for www-data@groupoffice -- message not accepted, try again later
May  2 20:50:00 groupoffice postfix/pickup[1761]: 1B2FE1E03A5: uid=33 from=<www-data>
May  2 20:50:00 groupoffice postfix/proxymap[1770]: warning: mysql:/etc/postfix/mysql_virtual_alias_maps.cf is unavailable. unsupported dictionary type: mysql
May  2 20:50:00 groupoffice postfix/cleanup[1769]: warning: proxy:mysql:/etc/postfix/mysql_virtual_alias_maps.cf lookup error for "www-data@groupoffice"

**Comment by endozip** [comment]
Luckily we can restore the backup.
It probably wasn't a good idea to upgrade from version 6.5 to version 6.7 unnecessarily.

**Comment by endozip** [comment]
_**"The second problem, I can neither reproduce in 6.7.25 nor an earlier version. That is, I can delete postal addresses just fine from any contact, both on my development environment and the production environments I administer."**_

We can also no longer delete address book entries with admin access.

**Comment by gilbertrobert** [comment]
Since we upgraded to debian 6.7.30-sixseven, the address book window in email composition no longer works.
We have this in the error messages :
script.php?v=1686322838:3555 Uncaught TypeError: this.addButton.setDisabled is not a function

    at sb.<anonymous> (script.php?v=1686322838:3555:210)
    at EXTUTIL.Event.fire (ext-all-debug.js?mtime=1684765014:309:34)
    at constructor.fireEvent (ext-all-debug.js?mtime=1684765014:53:31)
    at constructor.select (ext-all-debug.js?mti…1684765014:34028:18)
    at constructor.onNodeClick (ext-all-debug.js?mti...1684765014:34010:14)
    at EXTUTIL.Event.fire (ext-all-debug.js?mtime=1684765014:309:34)
    at sb.fireEvent (ext-all-debug.js?mtime=1684765014:53:31)
    at sb.proxyNodeEvent (ext-all-debug.js?mti…1684765014:33496:21)
    at constructor.fireEvent (ext-all-debug.js?mti…1684765014:34367:34)
    at sb.fireEvent (ext-all-debug.js?mti...1684765014:35468:36)


Thanks in advance for your help.
