### ISSUE TITLE
Unfriendly SMTP errors

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#981]
Friends,

Can we make the errors friendlier? Example, when you sent to an invalid box.

![image](https://user-images.githubusercontent.com/44004645/233869186-5b1843bd-1db4-48f7-8b5a-2fa5e2601a7b.png)

![image](https://user-images.githubusercontent.com/44004645/233869212-420082db-f500-4703-aadd-a29356e087ed.png)

Thanks.

**Comment by lonesomewalker** [comment]
I think this might be not possible due to the fact that these feedback messages are different from mailserver to mailserver and their configuration itself.

**Comment by flaviozluca** [comment]
Thanks, friend. But I mean the huge error, not the final error itself, which is fine. It shows the entire communication.

Still, you understood that and theres no way to distinguish just the meaningful error, is that it?

Thanks.

**Comment by mschering** [comment]
This has been fixed in 6.8
