### ISSUE TITLE
6.7.25 dpkg error update ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by thomasgg23** [Intermesh/groupoffice#985]
I'm getting the following error when trying to update from 6.7.24 -> 6.7.25 on an ubuntu 22.04 LTS server.

Unpacking groupoffice (6.7.25-sixseven) over (6.7.24-sixseven) ...
dpkg: error processing archive /var/cache/apt/archives/groupoffice_6.7.25-sixseven_all.deb (--unpack):
 unable to open '/usr/share/groupoffice/views/goui/groupoffice-core/node_modules/@intermesh/goui/.github/ISSUE_TEMPLATE/bug_report.md.dpkg-new': No such file or directory
No apport report written because the error message indicates an issue on the local system.

Update crash and 6.7.24 is running fine. But 6.7.25 wont install.

Any hints?

**Comment by creissig** [comment]
Hi there,

had the same issue on upgrading from 6.7.23 to 6.7.25 on Debian. After some trying with the 'apt clean' and 'apt autoremove' which did not solve the problem, i could solve it by

apt remove groupoffice

In the dialog keep the database and then

apt install -f groupoffice

Then jump to yourdomain/groupoffice/install and you should be fine.
