### ISSUE TITLE
Signing emails with smime not working as expected

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#986]
When signing an email with valid smime cert, the password dialog pops up.
Then sending email.
Everyting is fine for THIS email.

But the next email sent also got the "sign with smime" ticked, and you can't remove that -> email does not get signed.
Also, if you explicitly want to sign the following email it is not working.
Only if you log off and on again it proceeds as "enter password" before sending.

Latest version 6.6

**Comment by thomasgg23** [comment]
Strange, I'm using 6.6.159 and have the option "always sign e-mails" activated.
![image](https://user-images.githubusercontent.com/2633051/235883406-1c577de6-642b-4c67-88e0-5dd7fe5e2648.png)

Groupoffice password dialog pops up one time after a new login, after that all emails get signed and sent with the smime certificate.

I tried sending one e-mail without signing and the another one with signing enabled. Works for me.

**Comment by mschering** [comment]
I believe this problem has been fixed some time ago.
