### ISSUE TITLE
disabling cache

### ISSUE THREAD

**Issue by lonesomewalker** [Intermesh/groupoffice#987]
As far as i remember:
```
$config['core'] = [
    'general' => [
        'cache' => 'go\\core\\cache\\None'
    ]
];
```

This should disable the cache, right?

Also, when i look into the install/upgrade.php, i can see:
```go()->setCache(new \go\core\cache\None());```

When i call the install/upgrade.php, cache gets cleared. But disabling does not seem to work?

**Comment by michalcharvat** [comment]
Cache configuration is directly under $config['cache'] option.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/8058273/236583851-6571ee67-67ab-4342-8c5b-e41037404b0a.png">

**Comment by lonesomewalker** [comment]
The thing is, i want to disable cache, by default.

**Comment by mschering** [comment]
Why?

**Comment by lonesomewalker** [comment]
Development :-)

**Comment by mschering** [comment]
We always manually clear the cache with /install/upgrade.php but you can set this:

$config['cache'] = \go\core\cache\None::class;

**Comment by lonesomewalker** [comment]
Yeah, i know how to do this the "correct" way, but in this case it would be a little bit annoying ;-)

Thank you!

**Comment by mschering** [comment]
It should stop things from being cached. I just verfified that the config option works.
