### ISSUE TITLE
error when updating to 6.7.29,

### ISSUE THREAD

**Issue by maquinate2** [Intermesh/groupoffice#992]
error when updating to 6.7.29, when the process ends the following error appears ? how can I solve it ? thank you

Upgrade output will be logged into: log/upgrade/20230520_030540.log

[legacy/zpushadmin] Excuting query: alter table zpa_devices
    modify remote_addr varchar(45) not null;
Error: Exception in /usr/share/groupoffice/go/core/Installer.php at line 783: 42S02: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'groupoffice.zpa_devices' doesn't exist
Query: alter table zpa_devices
    modify remote_addr varchar(45) not null;
Package: legacy
Module: zpushadmin
Module installed version: 7
Module source version: 8
ABORTING: Please contact support

**Comment by mschering** [comment]
Strange, this table should be there. Either remove the module or create the table:

CREATE TABLE IF NOT EXISTS `zpa_devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(50) NOT NULL,
  `device_type` varchar(50) NOT NULL,
  `remote_addr` varchar(45) NOT NULL,
  `can_connect` tinyint(1) NOT NULL DEFAULT '0',
  `ctime` int(11) NOT NULL,
  `mtime` int(11) NOT NULL,
  `new` tinyint(1) NOT NULL DEFAULT '1',
  `username` varchar(190) NOT NULL DEFAULT '',
  `comment` text,
  `as_version` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
	KEY `device_id` (`device_id`,`username`)
) ENGINE=InnoDB ;
