### ISSUE TITLE
FYI, certain HTML in a note can affect color of webmail for viewed emails

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#993]
FYI, certain HTML in a note can affect color of webmail for viewed emails

[font.zip](https://github.com/Intermesh/groupoffice/files/11525632/font.zip)
See video, I added note TEST in GO's demo webmail.

Thanks.

**Comment by mschering** [comment]
Thanks, the input will be checked better in the next release.

**Comment by flaviozluca** [comment]
Thank you, friend.
