### ISSUE TITLE
Strange issue with notes and text being deleted

### ISSUE THREAD

**Issue by flaviozluca** [Intermesh/groupoffice#995]
I have a really strange issue where sometimes I would somehow, inadvertedly delete text in a note.

I'm able to reproduce it, even in more than 1 computer.

It happens when I hit enter in a sentence written in a note in GO, then I select that text with is in the line below which shift and at the same time press arrown down (not the arrow in the alphanumeric pad, but the arrows by themselves in a keyboard).

So I have a text such as "the quick brown fox jumps over the lazy dog".

I hit enter before the word fox

So it reads

the quick brown
fox jumps over the lazy dog

Now I position the cursor before the word fox, press shift and, at the same time, arrow down (but the arrow which is by itself in a keyboard, not the one in the alphanumeric pad). Boom, that text (fox jumps over) gets deleted. If you try this and it doesn't happen, please try again it shall happen. Do a backspace, put fox up there with the initial phrase, press entender again, shift arrown down again... Surely it will delete the text. And what is strange is, control Z does not bring back the text.

It's as if it's some editor issue, which it understand shift arrown down as having an ENTER and deleting the text.

Pls see video I made at GO's demo.

Thanks,
Flavio

https://github.com/Intermesh/groupoffice/assets/44004645/c532434d-4e28-4573-a342-511bb6d21a8f

**Comment by mschering** [comment]
Thanks! Strange one indeed :) Fixed in the next release.

**Comment by flaviozluca** [comment]
Merinj! Sorry for the cross-post, but can you take a brief look in an email I sent you about a quote, etc? Resent it just now to info@

Thanks!
